export const AUDIT_ACTIONS = {
  authLoginSuccess: "auth.login.success",
  authLoginFailed: "auth.login.failed",
  authLogout: "auth.logout",
  authPasswordChanged: "auth.password.changed",
  authSessionsRevoked: "auth.sessions.revoked",
  authEmailChanged: "auth.email.changed",
  adminUserCreated: "admin_user.created",
  adminUserUpdated: "admin_user.updated",
  adminUserActivated: "admin_user.activated",
  adminUserDeactivated: "admin_user.deactivated",
  adminUserPasswordReset: "admin_user.password.reset",
  adminUserDeleted: "admin_user.deleted",
  reportsExport: "reports.export",
  integrationAuthorizationStarted: "integration.authorization.started",
  integrationAuthorizationSucceeded: "integration.authorization.succeeded",
  integrationAuthorizationFailed: "integration.authorization.failed",
  integrationAssetsDiscovered: "integration.assets.discovered",
  integrationAssetsDiscoveryFailed: "integration.assets.discovery_failed",
  integrationAssetsSelected: "integration.assets.selected",
  integrationTestSucceeded: "integration.test.succeeded",
  integrationTestFailed: "integration.test.failed",
  integrationSyncRequested: "integration.sync.requested",
  integrationDiagnosed: "integration.diagnosed",
  integrationDisconnected: "integration.disconnected",
  integrationAppConfigurationCreated: "integration.app_configuration.created",
  integrationAppConfigurationReplaced: "integration.app_configuration.replaced",
  integrationAppConfigurationRemoved: "integration.app_configuration.removed",
  integrationAppConfigurationTestPassed: "integration.app_configuration.test_passed",
  integrationAppConfigurationTestFailed: "integration.app_configuration.test_failed",
  integrationAppConfigurationReadinessChanged: "integration.app_configuration.readiness_changed",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  "auth.login.success": "تسجيل دخول ناجح",
  "auth.login.failed": "فشل تسجيل الدخول",
  "auth.logout": "تسجيل خروج",
  "auth.password.changed": "تغيير كلمة المرور",
  "auth.sessions.revoked": "إبطال الجلسات",
  "auth.email.changed": "تغيير البريد الإلكتروني",
  "admin_user.created": "إنشاء مستخدم",
  "admin_user.updated": "تعديل مستخدم",
  "admin_user.activated": "تفعيل مستخدم",
  "admin_user.deactivated": "تعطيل مستخدم",
  "admin_user.password.reset": "تغيير كلمة مرور مستخدم",
  "admin_user.deleted": "حذف مستخدم",
  "reports.export": "تصدير تقرير",
  "integration.authorization.started": "بدء تفويض تكامل خارجي",
  "integration.authorization.succeeded": "نجاح تفويض تكامل خارجي",
  "integration.authorization.failed": "فشل تفويض تكامل خارجي",
  "integration.assets.discovered": "اكتشاف أصول تكامل خارجي",
  "integration.assets.discovery_failed": "فشل اكتشاف أصول تكامل خارجي",
  "integration.assets.selected": "اختيار أصول تكامل خارجي",
  "integration.test.succeeded": "نجاح اختبار تكامل خارجي",
  "integration.test.failed": "فشل اختبار تكامل خارجي",
  "integration.sync.requested": "طلب مزامنة تكامل خارجي",
  "integration.diagnosed": "تشخيص تكامل خارجي",
  "integration.disconnected": "فصل تكامل خارجي",
  "integration.app_configuration.created": "إنشاء إعداد تطبيق مزوّد",
  "integration.app_configuration.replaced": "استبدال إعداد تطبيق مزوّد",
  "integration.app_configuration.removed": "إزالة إعداد تطبيق مزوّد",
  "integration.app_configuration.test_passed": "نجاح اختبار إعداد تطبيق مزوّد",
  "integration.app_configuration.test_failed": "فشل اختبار إعداد تطبيق مزوّد",
  "integration.app_configuration.readiness_changed": "تغيّر جاهزية إعداد تطبيق مزوّد",
};

export const AUDIT_ACTION_OPTIONS = Object.entries(AUDIT_ACTION_LABELS).map(([value, label]) => ({
  value,
  label,
}));
