-- =============================================================================
-- FOUNDATIONAL SCHEMA BASELINE
-- =============================================================================
--
-- This is a foundational schema baseline for future FRESH-ENVIRONMENT rebuilds
-- only and MUST NOT be blindly run against the existing production Supabase
-- database. The production database already contains these objects; every
-- statement uses IF NOT EXISTS / idempotent guards, but this file is intended
-- for bootstrapping a brand-new project, applied BEFORE the dated migrations in
-- this folder (timestamp 20250618000000 orders it first so later foreign keys
-- such as page_id -> pages resolve).
--
-- Source & accuracy:
--   Generated from LIVE Supabase schema metadata via read-only introspection
--   (pg_catalog / pg_attribute / pg_constraint / pg_indexes / pg_policies /
--   pg_class.relrowsecurity) using a Session Pooler connection. Column types,
--   defaults, nullability, identity, constraints, indexes, RLS status, and
--   policies below reflect the actual database. NO table data / rows were read
--   or included.
--
-- Scope:
--   Only the foundational objects that were missing from the other committed
--   migrations: pages, hero_templates, hero_assignments, topic_categories,
--   topic_series, topics, media_categories, media_items, menus, menu_items,
--   page_sections. All other tables (block templates, projects, feed/media
--   modules, site_settings, admin_*) are created by their own dated migrations.
--
-- RLS:
--   Row Level Security is ENABLED on every table below (verified from
--   pg_class.relrowsecurity). Only three explicit policies exist in the live
--   schema (on topics, menus, menu_items) and are reproduced verbatim. The
--   other tables have RLS enabled with NO policies, meaning anon/public roles
--   cannot access them — server code uses the service-role key, which bypasses
--   RLS. This matches production and is intentional.
--
-- Storage:
--   No storage.buckets or storage.objects policies exist in the live schema
--   metadata (verified: 0 policies). Storage buckets (cms-images, cms-documents)
--   are provisioned outside SQL (see docs/security-media-upload-migration.md)
--   and are therefore not represented here.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- pages
-- ---------------------------------------------------------------------------
create table if not exists public.pages (
  id bigint generated by default as identity not null,
  title text not null,
  slug text not null,
  path text not null,
  page_type text not null default 'static'::text,
  status text not null default 'published'::text,
  seo_title text,
  seo_description text,
  seo_keywords jsonb not null default '[]'::jsonb,
  is_system boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint pages_pkey PRIMARY KEY (id),
  constraint pages_path_key UNIQUE (path),
  constraint pages_slug_key UNIQUE (slug),
  constraint pages_page_type_check CHECK ((page_type = ANY (ARRAY['home'::text, 'static'::text, 'hub'::text, 'contact'::text, 'system'::text]))),
  constraint pages_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text, 'hidden'::text, 'archived'::text])))
);

create index if not exists pages_status_idx ON public.pages USING btree (status);
create index if not exists pages_path_idx ON public.pages USING btree (path);

alter table public.pages enable row level security;

-- ---------------------------------------------------------------------------
-- hero_templates
-- ---------------------------------------------------------------------------
create table if not exists public.hero_templates (
  id bigint generated by default as identity not null,
  name text not null,
  slug text not null,
  description text,
  section_key text not null default 'hero'::text,
  variant text not null default 'internal-page'::text,
  style_preset text not null default 'cinematic-gold'::text,
  source_type text not null default 'manual'::text,
  source_id bigint,
  source_slug text,
  limit_count integer not null default 1,
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  config jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint hero_templates_pkey PRIMARY KEY (id),
  constraint hero_templates_slug_key UNIQUE (slug),
  constraint hero_templates_source_type_check CHECK ((source_type = ANY (ARRAY['manual'::text, 'latest_topics'::text, 'featured_topics'::text, 'topic_category'::text, 'latest_media'::text, 'featured_media'::text, 'media_category'::text])))
);

create index if not exists hero_templates_visible_idx ON public.hero_templates USING btree (is_visible);
create index if not exists hero_templates_variant_idx ON public.hero_templates USING btree (variant);

alter table public.hero_templates enable row level security;

-- ---------------------------------------------------------------------------
-- hero_assignments
-- ---------------------------------------------------------------------------
create table if not exists public.hero_assignments (
  id bigint generated by default as identity not null,
  hero_id bigint not null,
  target_type text not null default 'page'::text,
  target_id bigint,
  target_slug text,
  path text,
  is_active boolean not null default true,
  priority integer not null default 100,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint hero_assignments_pkey PRIMARY KEY (id),
  constraint hero_assignments_hero_id_fkey FOREIGN KEY (hero_id) REFERENCES hero_templates(id) ON DELETE CASCADE,
  constraint hero_assignments_target_type_check CHECK ((target_type = ANY (ARRAY['page'::text, 'route'::text, 'topic'::text, 'topic_category'::text, 'media_item'::text, 'media_category'::text, 'default'::text])))
);

create index if not exists hero_assignments_lookup_idx ON public.hero_assignments USING btree (target_type, target_id, target_slug, path, is_active, priority DESC);
create index if not exists hero_assignments_hero_idx ON public.hero_assignments USING btree (hero_id);

alter table public.hero_assignments enable row level security;

-- ---------------------------------------------------------------------------
-- topic_categories  (self-referencing parent_id)
-- ---------------------------------------------------------------------------
create table if not exists public.topic_categories (
  id bigint generated always as identity not null,
  name text not null,
  slug text not null,
  description text,
  sort_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  parent_id bigint,
  image text,
  image_alt text,
  display_title text,
  display_excerpt text,
  show_in_menu boolean not null default true,
  is_featured boolean not null default false,
  status text not null default 'published'::text,
  constraint topic_categories_pkey PRIMARY KEY (id),
  constraint topic_categories_slug_key UNIQUE (slug),
  constraint topic_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES topic_categories(id)
);

create index if not exists topic_categories_parent_id_idx ON public.topic_categories USING btree (parent_id);
create index if not exists topic_categories_status_idx ON public.topic_categories USING btree (status);
create index if not exists topic_categories_show_in_menu_idx ON public.topic_categories USING btree (show_in_menu);

alter table public.topic_categories enable row level security;

-- ---------------------------------------------------------------------------
-- topic_series  (-> topic_categories)
-- ---------------------------------------------------------------------------
create table if not exists public.topic_series (
  id bigint generated by default as identity not null,
  name text not null,
  slug text not null,
  description text,
  status text not null default 'published'::text,
  sort_order integer not null default 0,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  category_id bigint,
  constraint topic_series_pkey PRIMARY KEY (id),
  constraint topic_series_slug_key UNIQUE (slug),
  constraint topic_series_category_id_fkey FOREIGN KEY (category_id) REFERENCES topic_categories(id) ON DELETE RESTRICT
);

create index if not exists topic_series_slug_idx ON public.topic_series USING btree (slug);
create index if not exists topic_series_status_idx ON public.topic_series USING btree (status);
create index if not exists topic_series_deleted_at_idx ON public.topic_series USING btree (deleted_at);
create index if not exists topic_series_sort_order_idx ON public.topic_series USING btree (sort_order);
create index if not exists topic_series_category_id_idx ON public.topic_series USING btree (category_id);

alter table public.topic_series enable row level security;

-- ---------------------------------------------------------------------------
-- topics  (-> topic_categories, topic_series)
-- ---------------------------------------------------------------------------
create table if not exists public.topics (
  id bigint generated by default as identity not null,
  slug text not null,
  title text not null,
  excerpt text not null,
  content text not null,
  image text not null,
  category text not null,
  category_slug text not null,
  series text,
  series_slug text,
  date_label text,
  published_at timestamp with time zone,
  is_featured boolean not null default false,
  is_popular boolean not null default false,
  seo_title text,
  seo_description text,
  seo_keywords jsonb not null default '[]'::jsonb,
  faq jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  category_id bigint,
  status text default 'published'::text,
  deleted_at timestamp with time zone,
  focus_keyword text,
  image_alt text,
  series_id bigint,
  constraint topics_pkey PRIMARY KEY (id),
  constraint topics_slug_key UNIQUE (slug),
  constraint topics_category_id_fkey FOREIGN KEY (category_id) REFERENCES topic_categories(id),
  constraint topics_series_id_fkey FOREIGN KEY (series_id) REFERENCES topic_series(id)
);

create index if not exists topics_slug_idx ON public.topics USING btree (slug);
create index if not exists topics_category_slug_idx ON public.topics USING btree (category_slug);
create index if not exists topics_series_slug_idx ON public.topics USING btree (series_slug);
create index if not exists topics_status_idx ON public.topics USING btree (status);
create index if not exists topics_deleted_at_idx ON public.topics USING btree (deleted_at);
create index if not exists topics_category_id_idx ON public.topics USING btree (category_id);
create index if not exists topics_published_at_idx ON public.topics USING btree (published_at DESC);
create index if not exists topics_series_id_idx ON public.topics USING btree (series_id);

alter table public.topics enable row level security;
create policy "Allow public read topics" on public.topics as PERMISSIVE for SELECT to anon using (true);

-- ---------------------------------------------------------------------------
-- media_categories
-- ---------------------------------------------------------------------------
create table if not exists public.media_categories (
  id bigint generated always as identity not null,
  name text not null,
  slug text not null,
  description text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint media_categories_pkey PRIMARY KEY (id),
  constraint media_categories_slug_key UNIQUE (slug)
);

alter table public.media_categories enable row level security;

-- ---------------------------------------------------------------------------
-- media_items
-- ---------------------------------------------------------------------------
create table if not exists public.media_items (
  id bigint generated always as identity not null,
  slug text not null,
  title text not null,
  excerpt text not null,
  content text[] not null default ARRAY[]::text[],
  image text not null default '/images/venesia-5.png'::text,
  image_alt text,
  type text not null,
  category text not null,
  category_slug text,
  project text,
  duration text,
  date_label text,
  published_at date not null default CURRENT_DATE,
  status text not null default 'draft'::text,
  is_featured boolean not null default false,
  is_popular boolean not null default false,
  sort_order integer not null default 0,
  seo_title text,
  seo_description text,
  seo_keywords text[] not null default ARRAY[]::text[],
  focus_keyword text,
  og_image text,
  schema_type text not null default 'Article'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  constraint media_items_pkey PRIMARY KEY (id),
  constraint media_items_type_slug_unique UNIQUE (type, slug),
  constraint media_items_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text, 'unpublished'::text, 'archived'::text]))),
  constraint media_items_type_check CHECK ((type = ANY (ARRAY['news'::text, 'video'::text, 'gallery'::text, 'press'::text, 'site-update'::text])))
);

create index if not exists media_items_type_status_idx ON public.media_items USING btree (type, status);
create index if not exists media_items_published_at_idx ON public.media_items USING btree (published_at DESC);
create index if not exists media_items_category_slug_idx ON public.media_items USING btree (category_slug);
create index if not exists media_items_featured_idx ON public.media_items USING btree (is_featured) WHERE (is_featured = true);
create index if not exists media_items_popular_idx ON public.media_items USING btree (is_popular) WHERE (is_popular = true);

alter table public.media_items enable row level security;

-- ---------------------------------------------------------------------------
-- menus
-- ---------------------------------------------------------------------------
create table if not exists public.menus (
  id bigint generated by default as identity not null,
  name text not null,
  slug text not null,
  location text not null default 'main'::text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint menus_pkey PRIMARY KEY (id),
  constraint menus_slug_key UNIQUE (slug)
);

create index if not exists menus_location_active_idx ON public.menus USING btree (location, is_active);

alter table public.menus enable row level security;
create policy "Public can read active menus" on public.menus as PERMISSIVE for SELECT to public using ((is_active = true));

-- ---------------------------------------------------------------------------
-- menu_items  (-> menus, self-referencing parent_id)
-- ---------------------------------------------------------------------------
create table if not exists public.menu_items (
  id bigint generated by default as identity not null,
  menu_id bigint not null,
  parent_id bigint,
  label text not null,
  item_type text not null default 'custom'::text,
  href text,
  linked_type text,
  linked_id bigint,
  anchor text,
  target text not null default '_self'::text,
  css_class text,
  style_preset text not null default 'default'::text,
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint menu_items_pkey PRIMARY KEY (id),
  constraint menu_items_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE,
  constraint menu_items_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES menu_items(id) ON DELETE CASCADE,
  constraint menu_items_item_type_check CHECK ((item_type = ANY (ARRAY['custom'::text, 'page'::text, 'topic'::text, 'topic_category'::text, 'project'::text, 'external'::text, 'anchor'::text, 'parent'::text]))),
  constraint menu_items_target_check CHECK ((target = ANY (ARRAY['_self'::text, '_blank'::text])))
);

create index if not exists menu_items_menu_parent_order_idx ON public.menu_items USING btree (menu_id, parent_id, sort_order);
create index if not exists menu_items_visible_idx ON public.menu_items USING btree (is_visible);

alter table public.menu_items enable row level security;
create policy "Public can read visible menu items" on public.menu_items as PERMISSIVE for SELECT to public using (((is_visible = true) AND (EXISTS ( SELECT 1
   FROM menus
  WHERE ((menus.id = menu_items.menu_id) AND (menus.is_active = true))))));

-- ---------------------------------------------------------------------------
-- page_sections  (legacy; -> pages)
-- ---------------------------------------------------------------------------
create table if not exists public.page_sections (
  id bigint generated by default as identity not null,
  page_id bigint not null,
  section_key text not null,
  section_type text not null default 'hero'::text,
  slot text not null default 'top'::text,
  variant text not null default 'internal-page'::text,
  style_preset text not null default 'cinematic-gold'::text,
  source_type text not null default 'manual'::text,
  source_id bigint,
  source_slug text,
  limit_count integer not null default 1,
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  config jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint page_sections_pkey PRIMARY KEY (id),
  constraint page_sections_page_key_unique UNIQUE (page_id, section_key),
  constraint page_sections_page_id_fkey FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE,
  constraint page_sections_section_type_check CHECK ((section_type = ANY (ARRAY['hero'::text, 'content'::text, 'cta'::text, 'faq'::text, 'gallery'::text, 'latest'::text, 'custom'::text]))),
  constraint page_sections_slot_check CHECK ((slot = ANY (ARRAY['top'::text, 'before_content'::text, 'main'::text, 'sidebar'::text, 'after_content'::text, 'before_footer'::text]))),
  constraint page_sections_source_type_check CHECK ((source_type = ANY (ARRAY['manual'::text, 'latest_topics'::text, 'featured_topics'::text, 'topic_category'::text, 'latest_media'::text, 'featured_media'::text, 'media_category'::text])))
);

create index if not exists page_sections_page_order_idx ON public.page_sections USING btree (page_id, slot, sort_order);
create index if not exists page_sections_type_visible_idx ON public.page_sections USING btree (section_type, is_visible);
create index if not exists page_sections_source_idx ON public.page_sections USING btree (source_type, source_id);

alter table public.page_sections enable row level security;

commit;
