-- Extend the existing Page Composition Position owner with Layout-owned Regions.
-- Current pages adopt one canonical legacy Layout; Assignment.slot remains the
-- Region key. No Template Builder, data owner, or parallel Composition runtime.
begin;

create table if not exists public.page_composition_layouts (
  id bigint generated by default as identity primary key,
  key text not null unique,
  admin_label text not null,
  constraint page_composition_layouts_key_check
    check (key ~ '^[a-z][a-z0-9-]{0,63}$'),
  constraint page_composition_layouts_label_check
    check (length(btrim(admin_label)) > 0)
);

create table if not exists public.page_composition_regions (
  layout_id bigint not null references public.page_composition_layouts(id) on delete cascade,
  key text not null,
  admin_label text not null,
  sort_order integer not null,
  primary key (layout_id, key),
  constraint page_composition_regions_key_check
    check (key ~ '^[a-z][a-z0-9-]{0,63}$'),
  constraint page_composition_regions_label_check
    check (length(btrim(admin_label)) > 0),
  constraint page_composition_regions_order_unique
    unique (layout_id, sort_order)
);

alter table public.page_composition_layouts enable row level security;
alter table public.page_composition_regions enable row level security;
revoke all on public.page_composition_layouts, public.page_composition_regions from public, anon, authenticated;
grant select, insert, update, delete on public.page_composition_layouts, public.page_composition_regions to service_role;
grant usage, select on sequence public.page_composition_layouts_id_seq to service_role;

insert into public.page_composition_layouts(key, admin_label)
values ('venisia-legacy', 'التوزيع الحالي')
on conflict (key) do nothing;

insert into public.page_composition_regions(layout_id, key, admin_label, sort_order)
select layout.id, region.key, region.label, region.ordering
from public.page_composition_layouts layout
cross join (values
  ('main', 'المحتوى الرئيسي', 10),
  ('sidebar', 'الشريط الجانبي', 20),
  ('bottom', 'أسفل الصفحة', 30),
  ('footer', 'قبل الفوتر', 40),
  ('hero', 'الهيرو', 50)
) as region(key, label, ordering)
where layout.key = 'venisia-legacy'
on conflict (layout_id, key) do nothing;

alter table public.pages
  add column if not exists layout_id bigint;

do $legacy_layout$
declare v_legacy_id bigint;
begin
  select id into strict v_legacy_id
  from public.page_composition_layouts where key = 'venisia-legacy';
  update public.pages set layout_id = v_legacy_id where layout_id is null;
  execute format('alter table public.pages alter column layout_id set default %s', v_legacy_id);
end;
$legacy_layout$;

alter table public.pages
  alter column layout_id set not null;
do $layout_fk$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.pages'::regclass and conname = 'pages_layout_id_fkey'
  ) then
    alter table public.pages add constraint pages_layout_id_fkey
      foreign key (layout_id) references public.page_composition_layouts(id);
  end if;
end;
$layout_fk$;
create index if not exists pages_layout_id_idx on public.pages(layout_id);

-- Persist the legacy renderer's existing aliases as their canonical Region
-- identities. This changes no rendered placement and leaves unknown values
-- untouched for the fail-closed preflight below.
do $normalize_legacy_assignments$
declare v_table text;
begin
  perform set_config('app.page_composition_write', 'on', true);
  foreach v_table in array array[
    'page_content_block_assignments', 'page_cta_block_assignments',
    'page_cards_block_assignments', 'page_breadcrumb_block_assignments',
    'page_feed_module_assignments', 'page_featured_module_assignments',
    'page_media_sidebar_module_assignments', 'page_media_hub_module_assignments'
  ] loop
    execute format($query$
      update public.%I set slot = case slot
        when 'top' then 'hero'
        when 'before-content' then 'main'
        when 'after-content' then 'bottom'
        when 'before-footer' then 'bottom'
        else slot end
      where slot in ('top','before-content','after-content','before-footer')
    $query$, v_table);
  end loop;
end;
$normalize_legacy_assignments$;

do $legacy_position_preflight$
begin
  if exists (
    select 1 from public.page_composition_assignments assignment
    join public.pages page on page.id = assignment.page_id
    where not exists (
      select 1 from public.page_composition_regions region
      where region.layout_id = page.layout_id and region.key = assignment.slot
    )
  ) then
    raise exception using errcode = '23514', message = 'legacy_page_assignment_region_missing';
  end if;
end;
$legacy_position_preflight$;

create or replace function public.enforce_page_assignment_region()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  v_page_id bigint;
  v_region text;
begin
  if tg_table_name = 'hero_assignments' then
    if new.target_type is distinct from 'page' then return new; end if;
    v_page_id := new.target_id;
    v_region := 'hero';
  else
    v_page_id := new.page_id;
    v_region := new.slot;
  end if;

  if v_page_id is null or v_region is null or not exists (
    select 1 from public.pages page
    join public.page_composition_regions region
      on region.layout_id = page.layout_id and region.key = v_region
    where page.id = v_page_id
  ) then
    raise exception using errcode = '23514', message = 'page_assignment_region_not_in_layout';
  end if;
  return new;
end;
$function$;

do $assignment_guards$
declare v_table text;
begin
  foreach v_table in array array[
    'page_content_block_assignments', 'page_cta_block_assignments',
    'page_cards_block_assignments', 'page_breadcrumb_block_assignments',
    'page_feed_module_assignments', 'page_featured_module_assignments',
    'page_media_sidebar_module_assignments', 'page_media_hub_module_assignments'
  ] loop
    execute format('drop trigger if exists page_composition_region_guard on public.%I', v_table);
    execute format(
      'create trigger page_composition_region_guard before insert or update of page_id, slot on public.%I for each row execute function public.enforce_page_assignment_region()',
      v_table
    );
  end loop;
end;
$assignment_guards$;

drop trigger if exists page_composition_region_guard on public.hero_assignments;
create trigger page_composition_region_guard
before insert or update of target_type, target_id on public.hero_assignments
for each row execute function public.enforce_page_assignment_region();

create or replace function public.enforce_page_layout_change()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if exists (
    select 1 from public.page_composition_assignments assignment
    where assignment.page_id = new.id
      and not exists (
        select 1 from public.page_composition_regions region
        where region.layout_id = new.layout_id and region.key = assignment.slot
      )
  ) then
    raise exception using errcode = '23514', message = 'page_layout_has_invalid_assignments';
  end if;
  return new;
end;
$function$;

drop trigger if exists page_composition_layout_change_guard on public.pages;
create trigger page_composition_layout_change_guard
before update of layout_id on public.pages
for each row execute function public.enforce_page_layout_change();

create or replace function public.enforce_page_region_identity()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if tg_op = 'UPDATE' then
    if (new.layout_id, new.key) is distinct from (old.layout_id, old.key) then
      raise exception using errcode = '23514', message = 'page_region_identity_immutable';
    end if;
    return new;
  end if;
  if exists (
    select 1 from public.pages page
    join public.page_composition_assignments assignment on assignment.page_id = page.id
    where page.layout_id = old.layout_id and assignment.slot = old.key
  ) then
    raise exception using errcode = '23514', message = 'page_region_in_use';
  end if;
  return old;
end;
$function$;

drop trigger if exists page_composition_region_identity_guard on public.page_composition_regions;
create trigger page_composition_region_identity_guard
before update of layout_id, key or delete on public.page_composition_regions
for each row execute function public.enforce_page_region_identity();

-- The existing atomic owner has one legacy literal in the multi-page template
-- sync branch. Membership is enforced for each inserted Assignment by the
-- region trigger above, including pages with different Layouts.
do $extend_atomic_owner$
declare v_definition text;
begin
  select pg_get_functiondef(oid) into strict v_definition
  from pg_proc
  where oid = 'public.mutate_page_composition(bigint,text,jsonb,bigint,text)'::regprocedure;
  if position('v_slot !~ ''^[a-z][a-z0-9-]{0,63}$''' in v_definition) > 0 then
    return;
  end if;
  if position('v_slot not in (''main'',''hero'',''sidebar'')' in v_definition) = 0 then
    raise exception using errcode = '22023', message = 'page_composition_slot_contract_drift';
  end if;
  v_definition := replace(v_definition,
    'v_slot not in (''main'',''hero'',''sidebar'')',
    'v_slot !~ ''^[a-z][a-z0-9-]{0,63}$''');
  execute v_definition;
end;
$extend_atomic_owner$;

commit;
