begin;

-- Standalone Featured owner. Placement remains in Page Composition assignments;
-- content rows remain owned and read by Public Content Read.
create table if not exists public.featured_module_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  status text not null default 'unpublished'
    constraint featured_module_templates_status_check
    check (status in ('published', 'unpublished')),
  config jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.page_featured_module_assignments (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.pages(id) on delete cascade,
  template_id bigint not null references public.featured_module_templates(id) on delete cascade,
  slot text not null,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (page_id, template_id)
);

create index if not exists page_featured_module_assignments_page_order_idx
  on public.page_featured_module_assignments(page_id, slot, sort_order, id);
create index if not exists page_featured_module_assignments_template_idx
  on public.page_featured_module_assignments(template_id);

comment on table public.featured_module_templates is
  'Featured selection and presentation templates. Does not own Public Content data or placement.';
comment on column public.page_featured_module_assignments.slot is
  'Semantic Page Composition Region selected by this Assignment.';

alter table public.featured_module_templates enable row level security;
alter table public.page_featured_module_assignments enable row level security;
revoke all on table public.featured_module_templates from public, anon, authenticated;
revoke all on table public.page_featured_module_assignments from public, anon, authenticated;
grant select, insert, update, delete on table public.featured_module_templates to service_role;
grant select, insert, update, delete on table public.page_featured_module_assignments to service_role;
grant usage, select on sequence public.featured_module_templates_id_seq to service_role;
grant usage, select on sequence public.page_featured_module_assignments_id_seq to service_role;

create or replace view public.page_composition_assignments
with (security_invoker = true)
as
select 'content'::text as kind, id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_content_block_assignments
union all select 'cta', id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_cta_block_assignments
union all select 'cards', id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_cards_block_assignments
union all select 'breadcrumb', id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_breadcrumb_block_assignments
union all select 'feed', id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_feed_module_assignments
union all select 'featured', id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_featured_module_assignments
union all select 'media_sidebar', id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_media_sidebar_module_assignments
union all select 'media_hub', id, page_id, template_id, slot, sort_order, is_visible, updated_at
from public.page_media_hub_module_assignments
union all
select 'hero', assignment.id, assignment.target_id, assignment.hero_id,
       'hero', greatest(0, 1000 - assignment.priority), assignment.is_active, assignment.updated_at
from public.hero_assignments assignment
where assignment.target_type = 'page' and assignment.target_id is not null;

comment on view public.page_composition_assignments is
  'Read-only aggregate projection for the existing Page Composition assignment owners, including Featured.';
revoke all on public.page_composition_assignments from anon, authenticated;
grant select on public.page_composition_assignments to service_role;

drop trigger if exists page_composition_atomic_guard on public.page_featured_module_assignments;
create trigger page_composition_atomic_guard
before insert or update or delete on public.page_featured_module_assignments
for each row execute function public.enforce_page_composition_atomic_contract();

do $extend_admin_pages_read_owner$
declare
  v_definition text;
  v_previous text;
begin
  select pg_get_functiondef(
    'public.admin_list_pages(integer,integer,text,text,text)'::regprocedure
  ) into v_definition;
  if v_definition is null then
    raise exception 'Featured migration refused: admin_list_pages owner is missing';
  end if;
  v_previous := v_definition;
  v_definition := replace(
    v_definition,
    'union all select page_id from public.page_feed_module_assignments',
    'union all select page_id from public.page_feed_module_assignments
      union all select page_id from public.page_featured_module_assignments'
  );
  if v_definition = v_previous then
    raise exception 'Featured migration refused: Admin Pages read owner marker drifted';
  end if;
  execute v_definition;
end;
$extend_admin_pages_read_owner$;

-- Extend the existing atomic aggregate owner in-place. The assertions make
-- this fail closed if its canonical body has drifted before this migration.
do $extend_page_composition_owner$
declare
  v_definition text;
  v_previous text;
begin
  select pg_get_functiondef(
    'public.mutate_page_composition(bigint,text,jsonb,bigint,text)'::regprocedure
  ) into v_definition;
  if v_definition is null then
    raise exception 'Featured migration refused: mutate_page_composition owner is missing';
  end if;
  if v_definition like '%page_featured_module_assignments%' then
    raise exception 'Featured migration refused: mutate_page_composition already contains Featured';
  end if;

  v_previous := v_definition;
  v_definition := replace(
    v_definition,
    'perform 1 from public.page_feed_module_assignments where page_id = p_page_id order by id for update;',
    'perform 1 from public.page_feed_module_assignments where page_id = p_page_id order by id for update;
  perform 1 from public.page_featured_module_assignments where page_id = p_page_id order by id for update;'
  );
  if v_definition = v_previous then
    raise exception 'Featured migration refused: assignment-lock owner marker drifted';
  end if;

  v_previous := v_definition;
  v_definition := replace(
    v_definition,
    'when ''feed'' then ''page_feed_module_assignments''',
    'when ''feed'' then ''page_feed_module_assignments''
      when ''featured'' then ''page_featured_module_assignments'''
  );
  if v_definition = v_previous then
    raise exception 'Featured migration refused: assignment-table owner marker drifted';
  end if;

  v_previous := v_definition;
  v_definition := replace(
    v_definition,
    'when ''feed'' then ''feed_module_templates''',
    'when ''feed'' then ''feed_module_templates''
      when ''featured'' then ''featured_module_templates'''
  );
  if v_definition = v_previous then
    raise exception 'Featured migration refused: template-table owner marker drifted';
  end if;

  v_previous := v_definition;
  v_definition := replace(
    v_definition,
    '(''page_feed_module_assignments''), (''page_media_sidebar_module_assignments''),',
    '(''page_feed_module_assignments''), (''page_featured_module_assignments''),
      (''page_media_sidebar_module_assignments''),'
  );
  if v_definition = v_previous then
    raise exception 'Featured migration refused: duplicate-page owner marker drifted';
  end if;

  execute v_definition;
end;
$extend_page_composition_owner$;

-- Adopt every non-listing Media Featured template into the new owner. Listing
-- presentation templates stay in Media Hub and never become Featured owners.
insert into public.featured_module_templates (
  name, slug, description, status, config, sort_order, created_at, updated_at
)
select
  template.name,
  template.slug,
  template.description,
  template.status,
  jsonb_build_object(
    'source', jsonb_build_object(
      'kind', 'media-center',
      'contentType', case template.config ->> 'type'
        when 'site-update' then 'site_update'
        when 'site_update' then 'site_update'
        when 'news' then 'news'
        when 'press' then 'press'
        when 'video' then 'video'
        when 'gallery' then 'gallery'
        else 'news' end
    ),
    'selection', jsonb_build_object('mode', 'automatic'),
    'itemLimit', greatest(1, least(12, coalesce(
      nullif(template.config ->> 'itemLimit', '')::integer,
      nullif(template.config ->> 'limit', '')::integer,
      1
    ))),
    'presentation', jsonb_build_object(
      'variant', 'hero',
      'eyebrow', nullif(template.config #>> '{presentation,eyebrow}', ''),
      'title', coalesce(template.config #>> '{presentation,title}', ''),
      'description', coalesce(template.config #>> '{presentation,description}', ''),
      'ctaText', coalesce(template.config #>> '{presentation,ctaText}', ''),
      'showExcerpt', true,
      'showDate', true,
      'showEyebrow', true,
      'eyebrowBold', false,
      'eyebrowAlignment', 'right',
      'showTitle', true,
      'titleBold', true,
      'titleAlignment', 'right'
    )
  ),
  template.sort_order,
  template.created_at,
  template.updated_at
from public.media_hub_module_templates template
where template.section_key = 'featured'
  and coalesce(template.config ->> 'placement', 'hub') <> 'listing'
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  status = excluded.status,
  config = excluded.config,
  sort_order = excluded.sort_order,
  updated_at = excluded.updated_at;

do $adopt_featured_assignments$
begin
  perform set_config('app.page_composition_write', 'on', true);

  insert into public.page_featured_module_assignments (
    page_id, template_id, slot, sort_order, is_visible, created_at, updated_at
  )
  select
    assignment.page_id,
    featured.id,
    assignment.slot,
    assignment.sort_order,
    assignment.is_visible,
    assignment.created_at,
    assignment.updated_at
  from public.page_media_hub_module_assignments assignment
  join public.media_hub_module_templates legacy on legacy.id = assignment.template_id
  join public.featured_module_templates featured on featured.slug = legacy.slug
  where legacy.section_key = 'featured'
    and coalesce(legacy.config ->> 'placement', 'hub') <> 'listing'
  on conflict (page_id, template_id) do update set
    slot = excluded.slot,
    sort_order = excluded.sort_order,
    is_visible = excluded.is_visible,
    updated_at = excluded.updated_at;

  delete from public.page_media_hub_module_assignments assignment
  using public.media_hub_module_templates legacy
  where legacy.id = assignment.template_id
    and legacy.section_key = 'featured'
    and coalesce(legacy.config ->> 'placement', 'hub') <> 'listing';

  delete from public.media_hub_module_templates
  where section_key = 'featured'
    and coalesce(config ->> 'placement', 'hub') <> 'listing';
end;
$adopt_featured_assignments$;

-- Replace the Topics Listing-owned visual with a standalone Featured module.
-- Its initial category is derived from the exact current public Featured item;
-- if no eligible item exists, no empty template is invented.
with current_featured as (
  select topic.category_slug
  from public.topics topic
  where topic.content_type = 'article'
    and topic.status = 'published'
    and topic.deleted_at is null
    and topic.is_featured is true
    and nullif(btrim(topic.category_slug), '') is not null
    and topic.slug not like 'e2e-test%'
  order by topic.published_at desc nulls last, topic.id desc
  limit 1
)
insert into public.featured_module_templates (
  name, slug, description, status, config, sort_order
)
select
  'Topics — Featured',
  'topics-featured',
  'Featured content between Topics Intro and Listing',
  'published',
  jsonb_build_object(
    'source', jsonb_build_object('kind', 'categories', 'categorySlug', category_slug),
    'selection', jsonb_build_object('mode', 'automatic'),
    'itemLimit', 1,
    'presentation', jsonb_build_object(
      'variant', 'hero',
      'eyebrow', 'Featured',
      'title', 'موضوع مميز',
      'description', '',
      'ctaText', 'اقرأ الموضوع',
      'showExcerpt', true,
      'showDate', true,
      'showEyebrow', true,
      'eyebrowBold', false,
      'eyebrowAlignment', 'right',
      'showTitle', true,
      'titleBold', true,
      'titleAlignment', 'right'
    )
  ),
  15
from current_featured
on conflict (slug) do nothing;

do $assign_topics_featured$
declare
  v_page_id bigint;
  v_template_id bigint;
begin
  select page.id, template.id into v_page_id, v_template_id
  from public.pages page
  join public.featured_module_templates template on template.slug = 'topics-featured'
  where page.slug = 'topics';
  if v_page_id is not null and v_template_id is not null then
    perform set_config('app.page_composition_write', 'on', true);
    insert into public.page_featured_module_assignments (
      page_id, template_id, slot, sort_order, is_visible
    ) values (v_page_id, v_template_id, 'main', 15, true)
    on conflict (page_id, template_id) do nothing;
  end if;
end;
$assign_topics_featured$;

-- Normalize cross-owner ordering after the one-time ownership transfer.
do $normalize_featured_adoption_order$
declare
  v_row record;
  v_table text;
begin
  perform set_config('app.page_composition_write', 'on', true);
  for v_row in
    select kind, id,
      row_number() over (partition by page_id, slot order by sort_order, kind, id) * 10 as next_order
    from public.page_composition_assignments
    where kind <> 'hero'
  loop
    v_table := case v_row.kind
      when 'content' then 'page_content_block_assignments'
      when 'cta' then 'page_cta_block_assignments'
      when 'cards' then 'page_cards_block_assignments'
      when 'breadcrumb' then 'page_breadcrumb_block_assignments'
      when 'feed' then 'page_feed_module_assignments'
      when 'featured' then 'page_featured_module_assignments'
      when 'media_sidebar' then 'page_media_sidebar_module_assignments'
      when 'media_hub' then 'page_media_hub_module_assignments' end;
    execute format('update public.%I set sort_order=$1 where id=$2', v_table)
      using v_row.next_order, v_row.id;
  end loop;
end;
$normalize_featured_adoption_order$;

do $extend_closure_health$
declare
  v_definition text;
  v_previous text;
begin
  select pg_get_functiondef('public.global_truth_atomic_closure_health()'::regprocedure)
    into v_definition;
  v_previous := v_definition;
  v_definition := replace(
    v_definition,
    'tgname = ''page_composition_atomic_guard''::name) = 8',
    'tgname = ''page_composition_atomic_guard''::name) = 9'
  );
  if v_definition = v_previous then
    -- PostgreSQL versions may render the comparison without explicit casts.
    v_definition := replace(
      v_definition,
      'tgname=''page_composition_atomic_guard'' and not tgisinternal) = 8',
      'tgname=''page_composition_atomic_guard'' and not tgisinternal) = 9'
    );
  end if;
  if v_definition = v_previous then
    raise exception 'Featured migration refused: closure-health trigger marker drifted';
  end if;
  execute v_definition;
end;
$extend_closure_health$;

insert into public.admin_audit_logs (
  actor_admin_user_id, actor_username, action, entity_type, entity_id, entity_label, metadata
) values (
  null,
  'system:migration',
  'page_composition.featured_owner_adopted',
  'page_composition',
  null,
  'Featured',
  jsonb_build_object(
    'migration', '20260828233733_featured_page_composition_module',
    'selection_owner', 'featured_module_templates',
    'read_owner', 'public_content_read',
    'placement_owner', 'mutate_page_composition',
    'legacy_media_featured_remaining', (
      select count(*) from public.media_hub_module_templates
      where section_key = 'featured'
        and coalesce(config ->> 'placement', 'hub') <> 'listing'
    )
  )
);

do $assert_featured_owner_closure$
begin
  if exists (
    select 1 from public.media_hub_module_templates
    where section_key = 'featured'
      and coalesce(config ->> 'placement', 'hub') <> 'listing'
  ) then
    raise exception 'Featured owner closure refused: Media Hub Featured owner remains';
  end if;
  if exists (
    select 1 from public.featured_module_templates template
    where jsonb_typeof(template.config -> 'source') <> 'object'
       or template.config #>> '{source,kind}' not in ('categories', 'media-center')
       or jsonb_typeof(template.config -> 'selection') <> 'object'
       or template.config #>> '{selection,mode}' not in ('automatic', 'manual')
       or template.config #>> '{presentation,variant}' not in (
         'hero', 'editorial', 'large-card', 'three-cards', 'carousel'
       )
       or template.config ? 'placement'
  ) then
    raise exception 'Featured owner closure refused: canonical contract drift detected';
  end if;
  if to_regprocedure('public.mutate_page_composition(bigint,text,jsonb,bigint,text)') is null
     or position(
       'page_featured_module_assignments' in pg_get_functiondef(
         'public.mutate_page_composition(bigint,text,jsonb,bigint,text)'::regprocedure
       )
     ) = 0 then
    raise exception 'Featured owner closure refused: Page Composition owner adoption missing';
  end if;
  if (
    select count(*) from pg_trigger
    where tgname = 'page_composition_atomic_guard' and not tgisinternal
  ) <> 9 then
    raise exception 'Featured owner closure refused: atomic guard adoption incomplete';
  end if;
end;
$assert_featured_owner_closure$;

commit;
