-- Project Construction Tracking Detail
--
-- Additive Tracking sub-domain. public.projects remains the sole Project
-- identity/publication/location owner. No Production rows are seeded or
-- backfilled by this migration.

begin;

create table public.project_tracking_profiles (
  project_id bigint primary key references public.projects(id) on delete restrict,
  project_receipt_date date,
  license_receipt_date date,
  contractor_name text,
  created_by bigint references public.admin_users(id) on delete set null,
  updated_by bigint references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_tracking_profiles_contractor_check
    check (contractor_name is null or btrim(contractor_name) <> '')
);

create table public.project_tracking_stages (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete restrict,
  name text not null,
  description text,
  sort_order integer not null,
  start_date date,
  planned_duration_value integer,
  planned_duration_unit text,
  is_visible boolean not null default true,
  created_by bigint references public.admin_users(id) on delete set null,
  updated_by bigint references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_tracking_stages_name_check check (btrim(name) <> ''),
  constraint project_tracking_stages_description_check check (description is null or btrim(description) <> ''),
  constraint project_tracking_stages_sort_order_check check (sort_order >= 0),
  constraint project_tracking_stages_duration_check check (
    (planned_duration_value is null and planned_duration_unit is null)
    or (planned_duration_value > 0 and planned_duration_unit in ('day', 'week', 'month'))
  ),
  constraint project_tracking_stages_project_order_key
    unique (project_id, sort_order) deferrable initially immediate
);

create table public.project_tracking_items (
  id bigint generated by default as identity primary key,
  stage_id bigint not null references public.project_tracking_stages(id) on delete restrict,
  name text not null,
  description text,
  sort_order integer not null,
  status text not null default 'not_started',
  start_date date,
  completion_date date,
  is_visible boolean not null default true,
  created_by bigint references public.admin_users(id) on delete set null,
  updated_by bigint references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_tracking_items_name_check check (btrim(name) <> ''),
  constraint project_tracking_items_description_check check (description is null or btrim(description) <> ''),
  constraint project_tracking_items_sort_order_check check (sort_order >= 0),
  constraint project_tracking_items_status_check check (status in ('not_started', 'in_progress', 'completed')),
  constraint project_tracking_items_completion_check check (
    (status = 'completed' and completion_date is not null)
    or (status <> 'completed' and completion_date is null)
  ),
  constraint project_tracking_items_date_order_check check (
    start_date is null or completion_date is null or completion_date >= start_date
  ),
  constraint project_tracking_items_stage_order_key
    unique (stage_id, sort_order) deferrable initially immediate
);

create table public.project_tracking_updates (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.project_tracking_items(id) on delete restrict,
  occurred_at timestamptz not null,
  title text not null,
  body text not null,
  publication_status text not null default 'draft',
  published_at timestamptz,
  published_by bigint references public.admin_users(id) on delete set null,
  created_by bigint references public.admin_users(id) on delete set null,
  updated_by bigint references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_tracking_updates_title_check check (btrim(title) <> ''),
  constraint project_tracking_updates_body_check check (btrim(body) <> ''),
  constraint project_tracking_updates_publication_check
    check (publication_status in ('draft', 'published', 'unpublished', 'archived')),
  constraint project_tracking_updates_published_at_check
    check (publication_status <> 'published' or published_at is not null)
);

create table public.project_tracking_update_media (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  update_id bigint not null references public.project_tracking_updates(id) on delete cascade,
  media_kind text not null,
  public_url text not null,
  poster_url text,
  title text,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_tracking_update_media_kind_check check (media_kind in ('image', 'video')),
  constraint project_tracking_update_media_public_url_check check (btrim(public_url) <> ''),
  constraint project_tracking_update_media_poster_url_check check (poster_url is null or btrim(poster_url) <> ''),
  constraint project_tracking_update_media_title_check check (title is null or btrim(title) <> ''),
  constraint project_tracking_update_media_sort_order_check check (sort_order >= 0),
  constraint project_tracking_update_media_update_client_key unique (update_id, client_key),
  constraint project_tracking_update_media_update_order_key
    unique (update_id, sort_order) deferrable initially immediate
);

create index project_tracking_stages_project_visibility_order_idx
  on public.project_tracking_stages(project_id, is_visible, sort_order, id);
create index project_tracking_items_stage_visibility_order_idx
  on public.project_tracking_items(stage_id, is_visible, sort_order, id);
create index project_tracking_updates_item_publication_date_idx
  on public.project_tracking_updates(item_id, publication_status, occurred_at desc, id desc);
create index project_tracking_update_media_update_kind_order_idx
  on public.project_tracking_update_media(update_id, media_kind, sort_order, id);

create or replace function public.set_project_tracking_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, pg_temp
as $function$
begin
  new.updated_at := pg_catalog.now();
  return new;
end
$function$;

create or replace function public.mutate_project_tracking_stage(
  p_project_id bigint,
  p_actor_id bigint,
  p_action text,
  p_stage_id bigint default null,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_action text := pg_catalog.lower(pg_catalog.btrim(coalesce(p_action, '')));
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_stage public.project_tracking_stages%rowtype;
  v_sort_order integer;
  v_child_count bigint;
begin
  if p_project_id is null or p_project_id <= 0 or p_actor_id is null or p_actor_id <= 0 then
    raise exception using errcode = '22023', message = 'Valid Project and actor ids are required.';
  end if;
  if v_action not in ('create', 'update', 'delete') or pg_catalog.jsonb_typeof(v_payload) <> 'object' then
    raise exception using errcode = '22023', message = 'Tracking Stage command is invalid.';
  end if;
  if not exists (select 1 from public.projects where id = p_project_id) then
    raise exception using errcode = 'P0002', message = 'Project not found.';
  end if;
  if not exists (select 1 from public.admin_users where id = p_actor_id and is_active) then
    raise exception using errcode = '42501', message = 'Active Admin actor not found.';
  end if;

  if v_action = 'create' then
    if p_stage_id is not null or exists (
      select 1 from pg_catalog.jsonb_object_keys(v_payload) key
      where key not in (
        'name', 'description', 'start_date', 'planned_duration_value',
        'planned_duration_unit', 'is_visible'
      )
    ) then
      raise exception using errcode = '22023', message = 'Tracking Stage create payload is invalid.';
    end if;
    select coalesce(max(sort_order) + 1, 0) into v_sort_order
      from public.project_tracking_stages where project_id = p_project_id;
    insert into public.project_tracking_stages (
      project_id, name, description, sort_order, start_date,
      planned_duration_value, planned_duration_unit, is_visible, created_by, updated_by
    ) values (
      p_project_id,
      pg_catalog.btrim(v_payload ->> 'name'),
      nullif(pg_catalog.btrim(v_payload ->> 'description'), ''),
      v_sort_order,
      nullif(v_payload ->> 'start_date', '')::date,
      nullif(v_payload ->> 'planned_duration_value', '')::integer,
      nullif(pg_catalog.lower(pg_catalog.btrim(v_payload ->> 'planned_duration_unit')), ''),
      coalesce(nullif(v_payload ->> 'is_visible', '')::boolean, true),
      p_actor_id,
      p_actor_id
    ) returning * into v_stage;
  else
    if p_stage_id is null or p_stage_id <= 0 then
      raise exception using errcode = '22023', message = 'A valid Tracking Stage id is required.';
    end if;
    select * into v_stage from public.project_tracking_stages
     where id = p_stage_id and project_id = p_project_id for update;
    if not found then
      raise exception using errcode = 'P0002', message = 'Tracking Stage not found in this Project.';
    end if;
    if v_action = 'delete' then
      if v_payload <> '{}'::jsonb then
        raise exception using errcode = '22023', message = 'Tracking Stage delete accepts no payload.';
      end if;
      select count(*) into v_child_count from public.project_tracking_items where stage_id = p_stage_id;
      if v_child_count > 0 then
        raise exception using errcode = '23503', message = 'A Tracking Stage with Items cannot be deleted.';
      end if;
      delete from public.project_tracking_stages where id = p_stage_id returning * into v_stage;
    else
      if exists (
        select 1 from pg_catalog.jsonb_object_keys(v_payload) key
        where key not in (
          'name', 'description', 'start_date', 'planned_duration_value',
          'planned_duration_unit', 'is_visible'
        )
      ) then
        raise exception using errcode = '22023', message = 'Tracking Stage update payload is invalid.';
      end if;
      update public.project_tracking_stages set
        name = pg_catalog.btrim(v_payload ->> 'name'),
        description = nullif(pg_catalog.btrim(v_payload ->> 'description'), ''),
        start_date = nullif(v_payload ->> 'start_date', '')::date,
        planned_duration_value = nullif(v_payload ->> 'planned_duration_value', '')::integer,
        planned_duration_unit = nullif(pg_catalog.lower(pg_catalog.btrim(v_payload ->> 'planned_duration_unit')), ''),
        is_visible = coalesce(nullif(v_payload ->> 'is_visible', '')::boolean, false),
        updated_by = p_actor_id
      where id = p_stage_id returning * into v_stage;
    end if;
  end if;

  select count(*) into v_child_count from public.project_tracking_items where stage_id = v_stage.id;
  return pg_catalog.to_jsonb(v_stage) || pg_catalog.jsonb_build_object('item_count', v_child_count);
end
$function$;

create or replace function public.reorder_project_tracking_stages(
  p_project_id bigint,
  p_actor_id bigint,
  p_stage_ids bigint[]
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_expected integer;
begin
  if p_project_id is null or p_project_id <= 0 or p_actor_id is null or p_actor_id <= 0 or p_stage_ids is null then
    raise exception using errcode = '22023', message = 'Tracking Stage reorder input is invalid.';
  end if;
  if not exists (select 1 from public.admin_users where id = p_actor_id and is_active) then
    raise exception using errcode = '42501', message = 'Active Admin actor not found.';
  end if;
  perform 1 from public.project_tracking_stages where project_id = p_project_id for update;
  select count(*)::integer into v_expected from public.project_tracking_stages where project_id = p_project_id;
  if pg_catalog.cardinality(p_stage_ids) <> v_expected
     or (select count(distinct ordered_id.id) from unnest(p_stage_ids) ordered_id(id)) <> v_expected
     or exists (
       select 1 from unnest(p_stage_ids) ordered_id(id)
       left join public.project_tracking_stages stage
         on stage.id = ordered_id.id and stage.project_id = p_project_id
       where stage.id is null
     ) then
    raise exception using errcode = '23514', message = 'Tracking Stage reorder must contain the exact Project Stage set.';
  end if;
  set constraints public.project_tracking_stages_project_order_key deferred;
  update public.project_tracking_stages stage set
    sort_order = ordered.ordinality - 1,
    updated_by = p_actor_id
  from unnest(p_stage_ids) with ordinality ordered(id, ordinality)
  where stage.id = ordered.id and stage.project_id = p_project_id;
  return v_expected;
end
$function$;

create or replace function public.mutate_project_tracking_item(
  p_project_id bigint,
  p_stage_id bigint,
  p_actor_id bigint,
  p_action text,
  p_item_id bigint default null,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_action text := pg_catalog.lower(pg_catalog.btrim(coalesce(p_action, '')));
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_item public.project_tracking_items%rowtype;
  v_sort_order integer;
  v_update_count bigint;
begin
  if p_project_id is null or p_project_id <= 0 or p_stage_id is null or p_stage_id <= 0
     or p_actor_id is null or p_actor_id <= 0 then
    raise exception using errcode = '22023', message = 'Valid Project, Stage and actor ids are required.';
  end if;
  if v_action not in ('create', 'update', 'delete') or pg_catalog.jsonb_typeof(v_payload) <> 'object' then
    raise exception using errcode = '22023', message = 'Tracking Item command is invalid.';
  end if;
  if not exists (
    select 1 from public.project_tracking_stages where id = p_stage_id and project_id = p_project_id
  ) then
    raise exception using errcode = '23503', message = 'Tracking Stage does not belong to this Project.';
  end if;
  if not exists (select 1 from public.admin_users where id = p_actor_id and is_active) then
    raise exception using errcode = '42501', message = 'Active Admin actor not found.';
  end if;

  if v_action = 'create' then
    if p_item_id is not null or exists (
      select 1 from pg_catalog.jsonb_object_keys(v_payload) key
      where key not in ('name', 'description', 'status', 'start_date', 'completion_date', 'is_visible')
    ) then
      raise exception using errcode = '22023', message = 'Tracking Item create payload is invalid.';
    end if;
    select coalesce(max(sort_order) + 1, 0) into v_sort_order
      from public.project_tracking_items where stage_id = p_stage_id;
    insert into public.project_tracking_items (
      stage_id, name, description, sort_order, status, start_date,
      completion_date, is_visible, created_by, updated_by
    ) values (
      p_stage_id,
      pg_catalog.btrim(v_payload ->> 'name'),
      nullif(pg_catalog.btrim(v_payload ->> 'description'), ''),
      v_sort_order,
      coalesce(nullif(pg_catalog.lower(pg_catalog.btrim(v_payload ->> 'status')), ''), 'not_started'),
      nullif(v_payload ->> 'start_date', '')::date,
      nullif(v_payload ->> 'completion_date', '')::date,
      coalesce(nullif(v_payload ->> 'is_visible', '')::boolean, true),
      p_actor_id,
      p_actor_id
    ) returning * into v_item;
  else
    if p_item_id is null or p_item_id <= 0 then
      raise exception using errcode = '22023', message = 'A valid Tracking Item id is required.';
    end if;
    select item.* into v_item
      from public.project_tracking_items item
      join public.project_tracking_stages stage on stage.id = item.stage_id
     where item.id = p_item_id and item.stage_id = p_stage_id and stage.project_id = p_project_id
     for update of item;
    if not found then
      raise exception using errcode = 'P0002', message = 'Tracking Item not found in this Stage and Project.';
    end if;
    if v_action = 'delete' then
      if v_payload <> '{}'::jsonb then
        raise exception using errcode = '22023', message = 'Tracking Item delete accepts no payload.';
      end if;
      select count(*) into v_update_count from public.project_tracking_updates where item_id = p_item_id;
      if v_update_count > 0 then
        raise exception using errcode = '23503', message = 'A Tracking Item with historical Updates cannot be deleted.';
      end if;
      delete from public.project_tracking_items where id = p_item_id returning * into v_item;
    else
      if exists (
        select 1 from pg_catalog.jsonb_object_keys(v_payload) key
        where key not in ('name', 'description', 'status', 'start_date', 'completion_date', 'is_visible')
      ) then
        raise exception using errcode = '22023', message = 'Tracking Item update payload is invalid.';
      end if;
      update public.project_tracking_items set
        name = pg_catalog.btrim(v_payload ->> 'name'),
        description = nullif(pg_catalog.btrim(v_payload ->> 'description'), ''),
        status = pg_catalog.lower(pg_catalog.btrim(v_payload ->> 'status')),
        start_date = nullif(v_payload ->> 'start_date', '')::date,
        completion_date = nullif(v_payload ->> 'completion_date', '')::date,
        is_visible = coalesce(nullif(v_payload ->> 'is_visible', '')::boolean, false),
        updated_by = p_actor_id
      where id = p_item_id returning * into v_item;
    end if;
  end if;

  select count(*) into v_update_count from public.project_tracking_updates where item_id = v_item.id;
  return pg_catalog.to_jsonb(v_item) || pg_catalog.jsonb_build_object('update_count', v_update_count);
end
$function$;

create or replace function public.reorder_project_tracking_items(
  p_project_id bigint,
  p_stage_id bigint,
  p_actor_id bigint,
  p_item_ids bigint[]
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_expected integer;
begin
  if p_project_id is null or p_project_id <= 0 or p_stage_id is null or p_stage_id <= 0
     or p_actor_id is null or p_actor_id <= 0 or p_item_ids is null then
    raise exception using errcode = '22023', message = 'Tracking Item reorder input is invalid.';
  end if;
  if not exists (
    select 1 from public.project_tracking_stages where id = p_stage_id and project_id = p_project_id
  ) then
    raise exception using errcode = '23503', message = 'Tracking Stage does not belong to this Project.';
  end if;
  if not exists (select 1 from public.admin_users where id = p_actor_id and is_active) then
    raise exception using errcode = '42501', message = 'Active Admin actor not found.';
  end if;
  perform 1 from public.project_tracking_items where stage_id = p_stage_id for update;
  select count(*)::integer into v_expected from public.project_tracking_items where stage_id = p_stage_id;
  if pg_catalog.cardinality(p_item_ids) <> v_expected
     or (select count(distinct ordered_id.id) from unnest(p_item_ids) ordered_id(id)) <> v_expected
     or exists (
       select 1 from unnest(p_item_ids) ordered_id(id)
       left join public.project_tracking_items item on item.id = ordered_id.id and item.stage_id = p_stage_id
       where item.id is null
     ) then
    raise exception using errcode = '23514', message = 'Tracking Item reorder must contain the exact Stage Item set.';
  end if;
  set constraints public.project_tracking_items_stage_order_key deferred;
  update public.project_tracking_items item set
    sort_order = ordered.ordinality - 1,
    updated_by = p_actor_id
  from unnest(p_item_ids) with ordinality ordered(id, ordinality)
  where item.id = ordered.id and item.stage_id = p_stage_id;
  return v_expected;
end
$function$;

create trigger project_tracking_profiles_set_updated_at before update on public.project_tracking_profiles
for each row execute function public.set_project_tracking_updated_at();
create trigger project_tracking_stages_set_updated_at before update on public.project_tracking_stages
for each row execute function public.set_project_tracking_updated_at();
create trigger project_tracking_items_set_updated_at before update on public.project_tracking_items
for each row execute function public.set_project_tracking_updated_at();
create trigger project_tracking_updates_set_updated_at before update on public.project_tracking_updates
for each row execute function public.set_project_tracking_updated_at();
create trigger project_tracking_update_media_set_updated_at before update on public.project_tracking_update_media
for each row execute function public.set_project_tracking_updated_at();

create or replace function public.save_project_tracking_profile(
  p_project_id bigint,
  p_actor_id bigint,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_profile public.project_tracking_profiles%rowtype;
begin
  if p_project_id is null or p_project_id <= 0 or p_actor_id is null or p_actor_id <= 0 then
    raise exception using errcode = '22023', message = 'Valid Project and actor ids are required.';
  end if;
  if pg_catalog.jsonb_typeof(v_payload) <> 'object'
     or exists (
       select 1 from pg_catalog.jsonb_object_keys(v_payload) key
       where key not in ('project_receipt_date', 'license_receipt_date', 'contractor_name')
     ) then
    raise exception using errcode = '22023', message = 'Tracking profile payload is invalid.';
  end if;
  if not exists (select 1 from public.projects where id = p_project_id) then
    raise exception using errcode = 'P0002', message = 'Project not found.';
  end if;
  if not exists (select 1 from public.admin_users where id = p_actor_id and is_active) then
    raise exception using errcode = '42501', message = 'Active Admin actor not found.';
  end if;

  insert into public.project_tracking_profiles (
    project_id, project_receipt_date, license_receipt_date, contractor_name, created_by, updated_by
  ) values (
    p_project_id,
    nullif(v_payload ->> 'project_receipt_date', '')::date,
    nullif(v_payload ->> 'license_receipt_date', '')::date,
    nullif(pg_catalog.btrim(v_payload ->> 'contractor_name'), ''),
    p_actor_id,
    p_actor_id
  )
  on conflict (project_id) do update set
    project_receipt_date = excluded.project_receipt_date,
    license_receipt_date = excluded.license_receipt_date,
    contractor_name = excluded.contractor_name,
    updated_by = excluded.updated_by
  returning * into v_profile;

  return pg_catalog.to_jsonb(v_profile);
end
$function$;

create or replace function public.mutate_project_tracking_update(
  p_project_id bigint,
  p_item_id bigint,
  p_actor_id bigint,
  p_action text,
  p_update_id bigint default null,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_action text := pg_catalog.lower(pg_catalog.btrim(coalesce(p_action, '')));
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_update public.project_tracking_updates%rowtype;
  v_media jsonb;
  v_entry jsonb;
  v_publication_status text;
begin
  if p_project_id is null or p_project_id <= 0 or p_item_id is null or p_item_id <= 0
     or p_actor_id is null or p_actor_id <= 0 then
    raise exception using errcode = '22023', message = 'Valid Project, Item and actor ids are required.';
  end if;
  if v_action not in ('create', 'update', 'delete') or pg_catalog.jsonb_typeof(v_payload) <> 'object' then
    raise exception using errcode = '22023', message = 'Tracking Update command is invalid.';
  end if;
  if not exists (
    select 1
      from public.project_tracking_items item
      join public.project_tracking_stages stage on stage.id = item.stage_id
     where item.id = p_item_id and stage.project_id = p_project_id
  ) then
    raise exception using errcode = '23503', message = 'Tracking Item does not belong to this Project.';
  end if;
  if not exists (select 1 from public.admin_users where id = p_actor_id and is_active) then
    raise exception using errcode = '42501', message = 'Active Admin actor not found.';
  end if;

  if v_action = 'delete' then
    if p_update_id is null or p_update_id <= 0 or v_payload <> '{}'::jsonb then
      raise exception using errcode = '22023', message = 'Tracking Update delete input is invalid.';
    end if;
    select update_row.* into v_update
      from public.project_tracking_updates update_row
     where update_row.id = p_update_id and update_row.item_id = p_item_id for update;
    if not found then
      raise exception using errcode = 'P0002', message = 'Tracking Update not found in this Item.';
    end if;
    delete from public.project_tracking_updates where id = p_update_id returning * into v_update;
    return pg_catalog.to_jsonb(v_update) || pg_catalog.jsonb_build_object('media', '[]'::jsonb);
  end if;

  if exists (
    select 1 from pg_catalog.jsonb_object_keys(v_payload) key
    where key not in ('occurred_at', 'title', 'body', 'publication_status', 'media')
  ) then
    raise exception using errcode = '22023', message = 'Tracking Update payload contains unsupported fields.';
  end if;
  v_media := coalesce(v_payload -> 'media', '[]'::jsonb);
  if pg_catalog.jsonb_typeof(v_media) <> 'array' then
    raise exception using errcode = '22023', message = 'Tracking Update media must be an array.';
  end if;
  v_publication_status := pg_catalog.lower(pg_catalog.btrim(v_payload ->> 'publication_status'));
  if v_publication_status not in ('draft', 'published', 'unpublished', 'archived') then
    raise exception using errcode = '22023', message = 'Tracking Update publication status is invalid.';
  end if;

  if v_action = 'create' then
    if p_update_id is not null then
      raise exception using errcode = '22023', message = 'A new Tracking Update cannot provide an id.';
    end if;
    insert into public.project_tracking_updates (
      item_id, occurred_at, title, body, publication_status,
      published_at, published_by, created_by, updated_by
    ) values (
      p_item_id,
      (v_payload ->> 'occurred_at')::timestamptz,
      pg_catalog.btrim(v_payload ->> 'title'),
      pg_catalog.btrim(v_payload ->> 'body'),
      v_publication_status,
      case when v_publication_status = 'published' then pg_catalog.now() else null end,
      case when v_publication_status = 'published' then p_actor_id else null end,
      p_actor_id,
      p_actor_id
    ) returning * into v_update;
  else
    if p_update_id is null or p_update_id <= 0 then
      raise exception using errcode = '22023', message = 'A valid Tracking Update id is required.';
    end if;
    select update_row.* into v_update
      from public.project_tracking_updates update_row
     where update_row.id = p_update_id and update_row.item_id = p_item_id for update;
    if not found then
      raise exception using errcode = 'P0002', message = 'Tracking Update not found in this Item.';
    end if;
    update public.project_tracking_updates set
      occurred_at = (v_payload ->> 'occurred_at')::timestamptz,
      title = pg_catalog.btrim(v_payload ->> 'title'),
      body = pg_catalog.btrim(v_payload ->> 'body'),
      publication_status = v_publication_status,
      published_at = case
        when v_publication_status = 'published' then coalesce(v_update.published_at, pg_catalog.now())
        else v_update.published_at
      end,
      published_by = case
        when v_publication_status = 'published' then coalesce(v_update.published_by, p_actor_id)
        else v_update.published_by
      end,
      updated_by = p_actor_id
    where id = p_update_id returning * into v_update;
  end if;

  set constraints public.project_tracking_update_media_update_order_key deferred;
  for v_entry in select value from pg_catalog.jsonb_array_elements(v_media)
  loop
    if pg_catalog.jsonb_typeof(v_entry) <> 'object' or exists (
      select 1 from pg_catalog.jsonb_object_keys(v_entry) key
      where key not in ('client_key', 'media_kind', 'public_url', 'poster_url', 'title', 'sort_order')
    ) then
      raise exception using errcode = '22023', message = 'Tracking Update media entry is invalid.';
    end if;
    insert into public.project_tracking_update_media (
      client_key, update_id, media_kind, public_url, poster_url, title, sort_order
    ) values (
      (v_entry ->> 'client_key')::uuid,
      v_update.id,
      pg_catalog.lower(pg_catalog.btrim(v_entry ->> 'media_kind')),
      pg_catalog.btrim(v_entry ->> 'public_url'),
      nullif(pg_catalog.btrim(v_entry ->> 'poster_url'), ''),
      nullif(pg_catalog.btrim(v_entry ->> 'title'), ''),
      (v_entry ->> 'sort_order')::integer
    )
    on conflict (update_id, client_key) do update set
      media_kind = excluded.media_kind,
      public_url = excluded.public_url,
      poster_url = excluded.poster_url,
      title = excluded.title,
      sort_order = excluded.sort_order;
  end loop;

  delete from public.project_tracking_update_media media
   where media.update_id = v_update.id
     and not exists (
       select 1 from pg_catalog.jsonb_array_elements(v_media) entry
       where (entry ->> 'client_key')::uuid = media.client_key
     );

  return pg_catalog.to_jsonb(v_update) || pg_catalog.jsonb_build_object(
    'media',
    coalesce((
      select pg_catalog.jsonb_agg(pg_catalog.to_jsonb(media) order by media.sort_order, media.id)
      from public.project_tracking_update_media media where media.update_id = v_update.id
    ), '[]'::jsonb)
  );
end
$function$;

create or replace function public.project_tracking_public_detail_v1(p_slug text)
returns jsonb
language sql
stable
security invoker
set search_path = pg_catalog, pg_temp
as $function$
with project_row as (
  select
    project.id, project.slug, project.code, project.type,
    project.arabic_name, project.english_name, project.location_label,
    project.hero_image, project.hero_image_alt
  from public.projects project
  where project.slug = pg_catalog.lower(pg_catalog.btrim(p_slug))
    and project.publication_status = 'published'
),
eligible_stages as (
  select stage.*
  from public.project_tracking_stages stage
  join project_row project on project.id = stage.project_id
  where stage.is_visible
),
eligible_items as (
  select item.*
  from public.project_tracking_items item
  join eligible_stages stage on stage.id = item.stage_id
  where item.is_visible
),
eligible_updates as (
  select update_row.*
  from public.project_tracking_updates update_row
  join eligible_items item on item.id = update_row.item_id
  where update_row.publication_status = 'published'
),
media_by_update as (
  select media.update_id,
    pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object(
        'id', media.id, 'kind', media.media_kind, 'url', media.public_url,
        'posterUrl', media.poster_url, 'title', media.title, 'sortOrder', media.sort_order
      ) order by media.sort_order, media.id
    ) as media
  from public.project_tracking_update_media media
  join eligible_updates update_row on update_row.id = media.update_id
  group by media.update_id
),
updates_with_media as (
  select update_row.*, item.stage_id, coalesce(media.media, '[]'::jsonb) as media
  from eligible_updates update_row
  join eligible_items item on item.id = update_row.item_id
  left join media_by_update media on media.update_id = update_row.id
),
updates_by_item as (
  select update_row.item_id,
    pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object(
        'id', update_row.id, 'itemId', update_row.item_id, 'stageId', update_row.stage_id,
        'occurredAt', update_row.occurred_at, 'title', update_row.title,
        'body', update_row.body, 'publishedAt', update_row.published_at, 'media', update_row.media
      ) order by update_row.occurred_at desc, update_row.id desc
    ) as updates
  from updates_with_media update_row
  group by update_row.item_id
),
stage_statuses as (
  select stage.*,
    case
      when count(item.id) = 0 then 'not_started'
      when bool_and(item.status = 'completed') then 'completed'
      when bool_or(item.status <> 'not_started') then 'in_progress'
      else 'not_started'
    end as derived_status
  from eligible_stages stage
  left join eligible_items item on item.stage_id = stage.id
  group by
    stage.id, stage.project_id, stage.name, stage.description, stage.sort_order,
    stage.start_date, stage.planned_duration_value, stage.planned_duration_unit,
    stage.is_visible, stage.created_by, stage.updated_by, stage.created_at, stage.updated_at
),
items_by_stage as (
  select item.stage_id,
    pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object(
        'id', item.id, 'stageId', item.stage_id, 'name', item.name,
        'description', item.description, 'sortOrder', item.sort_order,
        'status', item.status, 'startDate', item.start_date,
        'completionDate', item.completion_date,
        'updates', coalesce(updates.updates, '[]'::jsonb)
      ) order by item.sort_order, item.id
    ) as items
  from eligible_items item
  left join updates_by_item updates on updates.item_id = item.id
  group by item.stage_id
),
stages_payload as (
  select stage.id, stage.sort_order, stage.derived_status,
    pg_catalog.jsonb_build_object(
      'id', stage.id, 'projectId', stage.project_id, 'name', stage.name,
      'description', stage.description, 'sortOrder', stage.sort_order,
      'startDate', stage.start_date,
      'plannedDuration', case
        when stage.planned_duration_value is null then null
        else pg_catalog.jsonb_build_object('value', stage.planned_duration_value, 'unit', stage.planned_duration_unit)
      end,
      'status', stage.derived_status,
      'items', coalesce(items.items, '[]'::jsonb)
    ) as stage
  from stage_statuses stage
  left join items_by_stage items on items.stage_id = stage.id
),
latest_update as (
  select * from updates_with_media order by occurred_at desc, id desc limit 1
),
fallback_stage as (
  select stage.id
  from stage_statuses stage
  order by
    case stage.derived_status when 'in_progress' then 0 when 'not_started' then 1 else 2 end,
    case when stage.derived_status = 'completed' then -stage.sort_order else stage.sort_order end,
    stage.id
  limit 1
),
derived_counts as (
  select
    (select count(*) from eligible_updates)::integer as update_count,
    (select count(*) from public.project_tracking_update_media media
      join eligible_updates update_row on update_row.id = media.update_id
      where media.media_kind = 'image')::integer as image_count,
    (select count(*) from public.project_tracking_update_media media
      join eligible_updates update_row on update_row.id = media.update_id
      where media.media_kind = 'video')::integer as video_count,
    (select count(*) from stage_statuses)::integer as stage_count,
    (select count(*) from stage_statuses where derived_status = 'completed')::integer as completed_stage_count
)
select case
  when not exists (select 1 from project_row) then null
  else pg_catalog.jsonb_build_object(
    'project', (
      select pg_catalog.jsonb_build_object(
        'id', project.id, 'slug', project.slug, 'code', project.code,
        'type', project.type, 'arabicName', project.arabic_name,
        'englishName', project.english_name, 'location', project.location_label,
        'heroImage', project.hero_image, 'heroImageAlt', project.hero_image_alt
      ) from project_row project
    ),
    'profile', (
      select case when profile.project_id is null then null else pg_catalog.jsonb_build_object(
        'projectReceiptDate', profile.project_receipt_date,
        'licenseReceiptDate', profile.license_receipt_date,
        'contractorName', profile.contractor_name
      ) end
      from project_row project
      left join public.project_tracking_profiles profile on profile.project_id = project.id
    ),
    'stages', coalesce((
      select pg_catalog.jsonb_agg(stage.stage order by stage.sort_order, stage.id) from stages_payload stage
    ), '[]'::jsonb),
    'latestUpdate', (
      select pg_catalog.jsonb_build_object(
        'id', update_row.id, 'itemId', update_row.item_id, 'stageId', update_row.stage_id,
        'occurredAt', update_row.occurred_at, 'title', update_row.title,
        'body', update_row.body, 'media', update_row.media
      ) from latest_update update_row
    ),
    'currentStageId', coalesce((select stage_id from latest_update), (select id from fallback_stage)),
    'latestVisual', coalesce(
      (
        select media.value ->> 'url'
        from latest_update update_row,
          lateral pg_catalog.jsonb_array_elements(update_row.media) media(value)
        where media.value ->> 'kind' = 'image'
        order by (media.value ->> 'sortOrder')::integer limit 1
      ),
      (
        select media.value ->> 'posterUrl'
        from latest_update update_row,
          lateral pg_catalog.jsonb_array_elements(update_row.media) media(value)
        where media.value ->> 'kind' = 'video' and coalesce(media.value ->> 'posterUrl', '') <> ''
        order by (media.value ->> 'sortOrder')::integer limit 1
      ),
      (select hero_image from project_row)
    ),
    'counts', (
      select pg_catalog.jsonb_build_object(
        'updates', counts.update_count, 'images', counts.image_count,
        'videos', counts.video_count, 'stages', counts.stage_count,
        'completedStages', counts.completed_stage_count
      ) from derived_counts counts
    )
  )
end;
$function$;

alter table public.project_tracking_profiles enable row level security;
alter table public.project_tracking_stages enable row level security;
alter table public.project_tracking_items enable row level security;
alter table public.project_tracking_updates enable row level security;
alter table public.project_tracking_update_media enable row level security;

revoke all on table
  public.project_tracking_profiles,
  public.project_tracking_stages,
  public.project_tracking_items,
  public.project_tracking_updates,
  public.project_tracking_update_media
from anon, authenticated;
grant select, insert, update, delete on table
  public.project_tracking_profiles,
  public.project_tracking_stages,
  public.project_tracking_items,
  public.project_tracking_updates,
  public.project_tracking_update_media
to service_role;
grant usage, select on sequence
  public.project_tracking_stages_id_seq,
  public.project_tracking_items_id_seq,
  public.project_tracking_updates_id_seq,
  public.project_tracking_update_media_id_seq
to service_role;

revoke all on function public.set_project_tracking_updated_at() from public, anon, authenticated;
revoke all on function public.save_project_tracking_profile(bigint, bigint, jsonb) from public, anon, authenticated;
revoke all on function public.mutate_project_tracking_stage(bigint, bigint, text, bigint, jsonb) from public, anon, authenticated;
revoke all on function public.reorder_project_tracking_stages(bigint, bigint, bigint[]) from public, anon, authenticated;
revoke all on function public.mutate_project_tracking_item(bigint, bigint, bigint, text, bigint, jsonb) from public, anon, authenticated;
revoke all on function public.reorder_project_tracking_items(bigint, bigint, bigint, bigint[]) from public, anon, authenticated;
revoke all on function public.mutate_project_tracking_update(bigint, bigint, bigint, text, bigint, jsonb) from public, anon, authenticated;
revoke all on function public.project_tracking_public_detail_v1(text) from public, anon, authenticated;

grant execute on function public.save_project_tracking_profile(bigint, bigint, jsonb) to service_role;
grant execute on function public.mutate_project_tracking_stage(bigint, bigint, text, bigint, jsonb) to service_role;
grant execute on function public.reorder_project_tracking_stages(bigint, bigint, bigint[]) to service_role;
grant execute on function public.mutate_project_tracking_item(bigint, bigint, bigint, text, bigint, jsonb) to service_role;
grant execute on function public.reorder_project_tracking_items(bigint, bigint, bigint, bigint[]) to service_role;
grant execute on function public.mutate_project_tracking_update(bigint, bigint, bigint, text, bigint, jsonb) to service_role;
grant execute on function public.project_tracking_public_detail_v1(text) to service_role;

comment on table public.project_tracking_profiles is
  'One-to-one Tracking-only Project facts. Project identity and publication remain owned by public.projects.';
comment on table public.project_tracking_stages is
  'Dynamic ordered Construction Stages. Status is derived from child Items and is never persisted here.';
comment on table public.project_tracking_items is
  'Dynamic ordered Stage Items. status is the only persisted operational progress state; percentages are prohibited.';
comment on table public.project_tracking_updates is
  'Historical Update rows under one Item. New Updates never overwrite earlier Update rows.';
comment on table public.project_tracking_update_media is
  'Media associations owned by one Tracking Update. Deleting an Update removes associations, never physical Media assets.';
comment on function public.project_tracking_public_detail_v1(text) is
  'Single-call public Tracking read model. It exposes only published Projects, visible Stages/Items and published Updates, with derived counts/latest/current truth.';

do $project_tracking_acl_assert$
declare
  v_function text;
begin
  foreach v_function in array array[
    'public.save_project_tracking_profile(bigint,bigint,jsonb)',
    'public.mutate_project_tracking_stage(bigint,bigint,text,bigint,jsonb)',
    'public.reorder_project_tracking_stages(bigint,bigint,bigint[])',
    'public.mutate_project_tracking_item(bigint,bigint,bigint,text,bigint,jsonb)',
    'public.reorder_project_tracking_items(bigint,bigint,bigint,bigint[])',
    'public.mutate_project_tracking_update(bigint,bigint,bigint,text,bigint,jsonb)',
    'public.project_tracking_public_detail_v1(text)'
  ] loop
    if pg_catalog.has_function_privilege('anon', v_function, 'execute')
       or pg_catalog.has_function_privilege('authenticated', v_function, 'execute')
       or not pg_catalog.has_function_privilege('service_role', v_function, 'execute') then
      raise exception 'Project Tracking function ACL is invalid for %.', v_function;
    end if;
  end loop;
end
$project_tracking_acl_assert$;

commit;
