-- Project Admin Data Entry clean rebuild (breaking, Project Domain only).
--
-- Purpose:
--   Replace the legacy Project aggregate with the seven-tab Admin data model.
--   The new model deliberately does not backfill or preserve legacy Project rows.
--
-- Data impact when applied later:
--   All rows in the legacy Project tables are deleted because the tables are
--   replaced. No other domain table is targeted. This file MUST NOT be applied
--   to Remote/Production without a separate, explicit approval and a verified
--   backup/forward-fix plan.
--
-- Migration-file state is not Remote schema state and does not prove a row in
-- supabase_migrations.schema_migrations.
--
-- Forward fix:
--   Recreate the clean schema from this migration, then enter Projects through
--   the unified Admin form. There is intentionally no legacy-data backfill.

begin;

-- Harden the legacy destructive function before replacing it. Remote drift has
-- previously exposed this SECURITY DEFINER function to anon/authenticated.
do $acl$
begin
  if to_regprocedure(
    'public.sync_project_children(bigint,jsonb,jsonb,jsonb,jsonb,jsonb)'
  ) is not null then
    execute 'alter function public.sync_project_children(bigint,jsonb,jsonb,jsonb,jsonb,jsonb) set search_path = pg_catalog, pg_temp';
    execute 'revoke all on function public.sync_project_children(bigint,jsonb,jsonb,jsonb,jsonb,jsonb) from public';
    execute 'revoke all on function public.sync_project_children(bigint,jsonb,jsonb,jsonb,jsonb,jsonb) from anon';
    execute 'revoke all on function public.sync_project_children(bigint,jsonb,jsonb,jsonb,jsonb,jsonb) from authenticated';
    execute 'grant execute on function public.sync_project_children(bigint,jsonb,jsonb,jsonb,jsonb,jsonb) to service_role';
  end if;
end
$acl$;

drop function if exists public.sync_project_children(
  bigint, jsonb, jsonb, jsonb, jsonb, jsonb
);
drop function if exists public.admin_list_projects(
  integer, integer, text, text, text, text, text, text, text, text
);

-- Drop only known Project Domain tables. No CASCADE is used: an unexpected
-- external dependency fails the migration instead of silently deleting it.
drop table if exists public.project_media;
drop table if exists public.project_delivery_spec_items;
drop table if exists public.project_floor_plans;
drop table if exists public.projects;

create table public.project_locations (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid() unique,
  level text not null check (level in ('governorate', 'city', 'main_area', 'sub_area')),
  parent_id bigint references public.project_locations (id) on delete restrict,
  name_ar text not null check (btrim(name_ar) <> ''),
  name_en text,
  sort_order integer not null default 0 check (sort_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_locations_parent_name_unique
    unique nulls not distinct (parent_id, level, name_ar),
  constraint project_locations_root_shape_check check (
    (level = 'governorate' and parent_id is null)
    or (level <> 'governorate' and parent_id is not null)
  )
);

create index project_locations_parent_sort_idx
  on public.project_locations (parent_id, level, sort_order, id);

create or replace function public.validate_project_location_parent()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_parent_level text;
  v_parent_active boolean;
  v_expected_parent_level text;
begin
  if new.level = 'governorate' then
    if new.parent_id is not null then
      raise exception using errcode = '23514', message = 'A governorate cannot have a parent.';
    end if;
    return new;
  end if;

  -- The key-share lock serializes hierarchy creation against concurrent parent
  -- reparent/deactivation updates.
  select location.level, location.is_active
    into v_parent_level, v_parent_active
    from public.project_locations as location
   where location.id = new.parent_id
   for key share;

  if v_parent_level is null then
    raise exception using errcode = '23503', message = 'The selected parent location does not exist.';
  end if;

  if not v_parent_active then
    raise exception using errcode = '23514', message = 'A child location cannot be attached to an inactive parent.';
  end if;

  v_expected_parent_level := case new.level
    when 'city' then 'governorate'
    when 'main_area' then 'city'
    when 'sub_area' then 'main_area'
  end;

  if v_parent_level <> v_expected_parent_level then
    raise exception using
      errcode = '23514',
      message = format('Invalid location hierarchy: %s must belong to %s.', new.level, v_expected_parent_level);
  end if;

  return new;
end
$function$;

create trigger project_locations_validate_parent
before insert or update of level, parent_id, is_active
on public.project_locations
for each row execute function public.validate_project_location_parent();

-- A minimal active Cairo chain keeps the first clean Create flow usable after
-- the intentionally destructive rebuild. These are reference locations, not
-- legacy Project data or a backfill.
do $seed$
declare
  v_governorate_id bigint;
  v_city_id bigint;
  v_main_area_id bigint;
begin
  insert into public.project_locations (
    client_key, level, name_ar, name_en, sort_order, is_active
  ) values (
    'ca100000-0000-4000-8000-000000000001',
    'governorate', 'القاهرة', 'Cairo', 0, true
  )
  returning id into v_governorate_id;

  insert into public.project_locations (
    client_key, level, parent_id, name_ar, name_en, sort_order, is_active
  ) values (
    'ca100000-0000-4000-8000-000000000002',
    'city', v_governorate_id, 'القاهرة الجديدة', 'New Cairo', 0, true
  )
  returning id into v_city_id;

  insert into public.project_locations (
    client_key, level, parent_id, name_ar, name_en, sort_order, is_active
  ) values (
    'ca100000-0000-4000-8000-000000000003',
    'main_area', v_city_id, 'التجمع الخامس', 'Fifth Settlement', 0, true
  )
  returning id into v_main_area_id;

  insert into public.project_locations (
    client_key, level, parent_id, name_ar, name_en, sort_order, is_active
  ) values (
    'ca100000-0000-4000-8000-000000000004',
    'sub_area', v_main_area_id, 'الحي الثاني', 'Second District', 0, true
  );
end
$seed$;

create table public.projects (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('residential', 'commercial')),
  arabic_name text not null check (btrim(arabic_name) <> ''),
  english_name text not null check (btrim(english_name) <> ''),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),

  general_description text not null check (
    btrim(general_description) <> '' and char_length(general_description) <= 1000
  ),
  short_description text not null check (
    btrim(short_description) <> '' and char_length(short_description) <= 500
  ),
  image text not null check (btrim(image) <> ''),
  image_alt text not null check (btrim(image_alt) <> ''),
  hero_image text not null check (btrim(hero_image) <> ''),
  hero_image_alt text not null check (btrim(hero_image_alt) <> ''),
  small_box_image text not null check (btrim(small_box_image) <> ''),
  small_box_image_alt text not null check (btrim(small_box_image_alt) <> ''),

  governorate_id bigint not null references public.project_locations (id) on delete restrict,
  city_id bigint not null references public.project_locations (id) on delete restrict,
  main_area_id bigint not null references public.project_locations (id) on delete restrict,
  sub_area_id bigint references public.project_locations (id) on delete restrict,
  location_label text not null check (btrim(location_label) <> ''),
  location_description text not null default '',
  google_maps_url text not null check (
    btrim(google_maps_url) <> '' and google_maps_url ~* '^https?://'
  ),
  latitude numeric(9, 6) not null check (latitude between -90 and 90),
  longitude numeric(9, 6) not null check (longitude between -180 and 180),
  map_zoom smallint not null check (map_zoom between 1 and 22),

  overview_title text not null check (btrim(overview_title) <> ''),
  overview_body text not null check (
    btrim(regexp_replace(replace(overview_body, '&nbsp;', ' '), '<[^>]*>', '', 'g')) <> ''
  ),
  overview_media_type text not null default 'image' check (overview_media_type in ('image', 'video')),
  overview_main_image text,
  overview_main_image_alt text not null default '',

  delivery_title text not null check (btrim(delivery_title) <> ''),
  delivery_body text not null check (
    btrim(regexp_replace(replace(delivery_body, '&nbsp;', ' '), '<[^>]*>', '', 'g')) <> ''
  ),

  seo_title text not null default '' check (char_length(seo_title) <= 60),
  seo_description text not null default '' check (char_length(seo_description) <= 160),
  focus_keyword text not null default '',
  seo_keywords text[] not null default '{}'::text[],
  canonical_url text check (canonical_url is null or canonical_url ~* '^https?://'),
  robots_index boolean,
  robots_follow boolean,
  og_image text,
  og_image_alt text not null default '',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint projects_overview_image_required_check check (
    overview_media_type <> 'image'
    or (
      coalesce(btrim(overview_main_image), '') <> ''
      and btrim(overview_main_image_alt) <> ''
    )
  ),
  constraint projects_overview_image_alt_check check (
    overview_main_image is null or btrim(overview_main_image_alt) <> ''
  ),
  constraint projects_og_image_alt_check check (
    og_image is null or btrim(og_image_alt) <> ''
  )
);

create index projects_type_updated_idx on public.projects (type, updated_at desc, id desc);
create index projects_location_idx
  on public.projects (governorate_id, city_id, main_area_id, sub_area_id);

create table public.project_location_points (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  project_id bigint not null references public.projects (id) on delete cascade,
  kind text not null check (kind in ('transport', 'road', 'landmark')),
  label text not null check (btrim(label) <> ''),
  distance_text text not null default '',
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_location_points_client_unique unique (project_id, client_key),
  constraint project_location_points_client_key_unique unique (client_key),
  constraint project_location_points_sort_unique
    unique (project_id, kind, sort_order) deferrable initially deferred
);

create table public.project_features (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  project_id bigint not null references public.projects (id) on delete cascade,
  body text not null check (btrim(body) <> ''),
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_features_client_unique unique (project_id, client_key),
  constraint project_features_client_key_unique unique (client_key),
  constraint project_features_sort_unique
    unique (project_id, sort_order) deferrable initially deferred
);

create table public.project_floor_plans (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  project_id bigint not null references public.projects (id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  area_text text not null default '',
  featured boolean not null default false,
  architectural_image text,
  architectural_image_alt text not null default '' check (
    architectural_image is null or btrim(architectural_image_alt) <> ''
  ),
  furnishing_image text,
  furnishing_image_alt text not null default '' check (
    furnishing_image is null or btrim(furnishing_image_alt) <> ''
  ),
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_floor_plans_client_unique unique (project_id, client_key),
  constraint project_floor_plans_client_key_unique unique (client_key),
  constraint project_floor_plans_sort_unique
    unique (project_id, sort_order) deferrable initially deferred
);

create table public.project_floor_plan_details (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  floor_plan_id bigint not null references public.project_floor_plans (id) on delete cascade,
  label text not null check (btrim(label) <> ''),
  value text not null check (btrim(value) <> ''),
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_floor_plan_details_client_unique unique (floor_plan_id, client_key),
  constraint project_floor_plan_details_client_key_unique unique (client_key),
  constraint project_floor_plan_details_sort_unique
    unique (floor_plan_id, sort_order) deferrable initially deferred
);

create table public.project_delivery_items (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  project_id bigint not null references public.projects (id) on delete cascade,
  body text not null check (btrim(body) <> ''),
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_delivery_items_client_unique unique (project_id, client_key),
  constraint project_delivery_items_client_key_unique unique (client_key),
  constraint project_delivery_items_sort_unique
    unique (project_id, sort_order) deferrable initially deferred
);

create table public.project_media (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  project_id bigint not null references public.projects (id) on delete cascade,
  section text not null check (section in ('overview', 'delivery', 'gallery')),
  image text not null check (btrim(image) <> ''),
  alt_text text not null check (btrim(alt_text) <> ''),
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_media_client_unique unique (project_id, client_key),
  constraint project_media_client_key_unique unique (client_key),
  constraint project_media_sort_unique
    unique (project_id, section, sort_order) deferrable initially deferred
);

create table public.project_videos (
  id bigint generated by default as identity primary key,
  client_key uuid not null default gen_random_uuid(),
  project_id bigint not null references public.projects (id) on delete cascade,
  section text not null check (section in ('overview', 'gallery')),
  video_url text not null check (
    btrim(video_url) <> '' and video_url ~* '^https?://'
  ),
  poster_image text,
  poster_alt text not null default '' check (
    poster_image is null or btrim(poster_alt) <> ''
  ),
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_videos_client_unique unique (project_id, client_key),
  constraint project_videos_client_key_unique unique (client_key),
  constraint project_videos_sort_unique
    unique (project_id, section, sort_order) deferrable initially deferred
);

create index project_location_points_project_idx
  on public.project_location_points (project_id, kind, sort_order);
create index project_features_project_idx
  on public.project_features (project_id, sort_order);
create index project_floor_plans_project_idx
  on public.project_floor_plans (project_id, sort_order);
create index project_floor_plan_details_plan_idx
  on public.project_floor_plan_details (floor_plan_id, sort_order);
create index project_delivery_items_project_idx
  on public.project_delivery_items (project_id, sort_order);
create index project_media_project_idx
  on public.project_media (project_id, section, sort_order);
create index project_videos_project_idx
  on public.project_videos (project_id, section, sort_order);
create unique index project_videos_single_overview_idx
  on public.project_videos (project_id)
  where section = 'overview';

-- Project type and the selected geographic chain are database invariants, not
-- merely Server Action conventions. These triggers also protect migration-owner
-- maintenance DML from creating an invalid aggregate.
create or replace function public.prevent_project_type_change()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, pg_temp
as $function$
begin
  if new.type is distinct from old.type then
    raise exception using
      errcode = '23514',
      message = 'Project type is immutable after creation.';
  end if;
  return new;
end
$function$;

create trigger projects_type_immutable
before update of type on public.projects
for each row execute function public.prevent_project_type_change();

create or replace function public.validate_project_location_selection()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, pg_temp
as $function$
begin
  if new.governorate_id is null
     or new.city_id is null
     or new.main_area_id is null then
    raise exception using
      errcode = '23514',
      message = 'Governorate, city and main area must be selected together.';
  end if;

  -- Lock the selected chain in deterministic ID order. A concurrent location
  -- update must finish before this validation (or wait for this Project write),
  -- closing the check/reparent and check/deactivate races.
  perform 1
    from public.project_locations location
   where location.id = any (
     array[new.governorate_id, new.city_id, new.main_area_id, new.sub_area_id]
   )
   order by location.id
   for key share;

  if not exists (
    select 1
      from public.project_locations governorate
      join public.project_locations city
        on city.id = new.city_id
       and city.level = 'city'
       and city.parent_id = governorate.id
      join public.project_locations main_area
        on main_area.id = new.main_area_id
       and main_area.level = 'main_area'
       and main_area.parent_id = city.id
      left join public.project_locations sub_area
        on sub_area.id = new.sub_area_id
       and sub_area.level = 'sub_area'
       and sub_area.parent_id = main_area.id
       where governorate.id = new.governorate_id
         and governorate.level = 'governorate'
         and governorate.is_active
         and city.is_active
         and main_area.is_active
         and (new.sub_area_id is null or sub_area.is_active)
         and (new.sub_area_id is null or sub_area.id is not null)
  ) then
    raise exception using
      errcode = '23514',
      message = 'The selected location hierarchy is invalid.';
  end if;

  return new;
end
$function$;

create trigger projects_validate_location_selection
before insert or update of governorate_id, city_id, main_area_id, sub_area_id
on public.projects
for each row execute function public.validate_project_location_selection();

create or replace function public.prevent_project_location_reparent()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, pg_temp
as $function$
begin
  if old.level is distinct from new.level
     and exists (
       select 1
         from public.project_locations child
        where child.parent_id = new.id
     ) then
    raise exception using
      errcode = '23514',
      message = 'A location with children cannot change level.';
  end if;

  if old.is_active
     and not new.is_active
     and exists (
       select 1
         from public.project_locations child
        where child.parent_id = new.id
          and child.is_active
     ) then
    raise exception using
      errcode = '23514',
      message = 'A location with active children cannot be deactivated.';
  end if;

  if old.is_active
     and not new.is_active
     and exists (
       select 1 from public.projects project
       where project.governorate_id = new.id
          or project.city_id = new.id
          or project.main_area_id = new.id
          or project.sub_area_id = new.id
     ) then
    raise exception using
      errcode = '23514',
      message = 'A referenced project location cannot be deactivated.';
  end if;

  if old.level is distinct from new.level
     and exists (
       select 1 from public.projects project
       where project.governorate_id = new.id
          or project.city_id = new.id
          or project.main_area_id = new.id
          or project.sub_area_id = new.id
     ) then
    raise exception using
      errcode = '23514',
      message = 'A referenced project location cannot change level.';
  end if;

  if new.level = 'city'
     and exists (
       select 1 from public.projects project
       where project.city_id = new.id
         and project.governorate_id is distinct from new.parent_id
     ) then
    raise exception using
      errcode = '23514',
      message = 'Reparenting this city would invalidate a project location hierarchy.';
  end if;

  if new.level = 'main_area'
     and exists (
       select 1 from public.projects project
       where project.main_area_id = new.id
         and project.city_id is distinct from new.parent_id
     ) then
    raise exception using
      errcode = '23514',
      message = 'Reparenting this main area would invalidate a project location hierarchy.';
  end if;

  if new.level = 'sub_area'
     and exists (
       select 1 from public.projects project
       where project.sub_area_id = new.id
         and project.main_area_id is distinct from new.parent_id
     ) then
    raise exception using
      errcode = '23514',
      message = 'Reparenting this sub area would invalidate a project location hierarchy.';
  end if;

  return new;
end
$function$;

create trigger project_locations_prevent_reparent
before update of level, parent_id, is_active on public.project_locations
for each row execute function public.prevent_project_location_reparent();

alter table public.project_locations enable row level security;
alter table public.projects enable row level security;
alter table public.project_location_points enable row level security;
alter table public.project_features enable row level security;
alter table public.project_floor_plans enable row level security;
alter table public.project_floor_plan_details enable row level security;
alter table public.project_delivery_items enable row level security;
alter table public.project_media enable row level security;
alter table public.project_videos enable row level security;

-- One transaction-owned aggregate write. JSON is transport only; independently
-- identified ordered records are persisted in relational child tables.
create or replace function public.save_project_admin_entry(
  p_project_id bigint default null,
  p_payload jsonb default '{}'::jsonb
)
returns table (project_id bigint, slug text, updated_at timestamptz)
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_project_id bigint;
  v_existing_type text;
  v_now timestamptz := clock_timestamp();
  v_root jsonb := coalesce(p_payload -> 'project', '{}'::jsonb);
  v_deleted jsonb := coalesce(p_payload -> 'deleted', '{}'::jsonb);
  v_item jsonb;
  v_plan jsonb;
  v_plan_id bigint;
  v_index integer;
  v_client_key uuid;
  v_governorate_id bigint;
  v_city_id bigint;
  v_main_area_id bigint;
  v_sub_area_id bigint;
begin
  if jsonb_typeof(p_payload) is distinct from 'object' then
    raise exception using errcode = '22023', message = 'Project payload must be a JSON object.';
  end if;
  if jsonb_typeof(v_root) is distinct from 'object' then
    raise exception using errcode = '22023', message = 'Project root must be a JSON object.';
  end if;
  if jsonb_typeof(v_deleted) is distinct from 'object' then
    raise exception using errcode = '22023', message = 'Project deleted tombstones must be a JSON object.';
  end if;
  if coalesce(btrim(v_root ->> 'arabic_name'), '') = '' then
    raise exception using errcode = '22023', message = 'Arabic project name is required.';
  end if;
  if coalesce(btrim(v_root ->> 'english_name'), '') = '' then
    raise exception using errcode = '22023', message = 'English project name is required.';
  end if;
  if coalesce(v_root ->> 'type', '') not in ('residential', 'commercial') then
    raise exception using errcode = '22023', message = 'Project type is invalid.';
  end if;
  if coalesce(v_root ->> 'slug', '') !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then
    raise exception using errcode = '22023', message = 'Project slug is invalid.';
  end if;
  if coalesce(btrim(v_root ->> 'general_description'), '') = ''
     or char_length(v_root ->> 'general_description') > 1000 then
    raise exception using errcode = '22023', message = 'General description is required and must not exceed 1000 characters.';
  end if;
  if coalesce(btrim(v_root ->> 'short_description'), '') = ''
     or char_length(v_root ->> 'short_description') > 500 then
    raise exception using errcode = '22023', message = 'Short description is required and must not exceed 500 characters.';
  end if;
  if coalesce(btrim(v_root ->> 'image'), '') = ''
     or coalesce(btrim(v_root ->> 'image_alt'), '') = '' then
    raise exception using errcode = '22023', message = 'Card image and alt text are required.';
  end if;
  if coalesce(btrim(v_root ->> 'hero_image'), '') = ''
     or coalesce(btrim(v_root ->> 'hero_image_alt'), '') = '' then
    raise exception using errcode = '22023', message = 'Hero image and alt text are required.';
  end if;
  if coalesce(btrim(v_root ->> 'small_box_image'), '') = ''
     or coalesce(btrim(v_root ->> 'small_box_image_alt'), '') = '' then
    raise exception using errcode = '22023', message = 'Small-box image and alt text are required.';
  end if;
  if coalesce(btrim(v_root ->> 'location_label'), '') = '' then
    raise exception using errcode = '22023', message = 'Project location label is required.';
  end if;
  if coalesce(btrim(v_root ->> 'google_maps_url'), '') = ''
     or (v_root ->> 'google_maps_url') !~* '^https?://' then
    raise exception using errcode = '22023', message = 'Google Maps URL is required and must use HTTP or HTTPS.';
  end if;
  if nullif(v_root ->> 'latitude', '') is null
     or (v_root ->> 'latitude')::numeric not between -90 and 90 then
    raise exception using errcode = '22023', message = 'Latitude is required and must be between -90 and 90.';
  end if;
  if nullif(v_root ->> 'longitude', '') is null
     or (v_root ->> 'longitude')::numeric not between -180 and 180 then
    raise exception using errcode = '22023', message = 'Longitude is required and must be between -180 and 180.';
  end if;
  if nullif(v_root ->> 'map_zoom', '') is null
     or (v_root ->> 'map_zoom')::numeric <> trunc((v_root ->> 'map_zoom')::numeric)
     or (v_root ->> 'map_zoom')::numeric not between 1 and 22 then
    raise exception using errcode = '22023', message = 'Map zoom is required and must be an integer between 1 and 22.';
  end if;
  if coalesce(btrim(v_root ->> 'overview_title'), '') = '' then
    raise exception using errcode = '22023', message = 'Overview title is required.';
  end if;
  if coalesce(
       btrim(regexp_replace(
         replace(coalesce(v_root ->> 'overview_body', ''), '&nbsp;', ' '),
         '<[^>]*>', '', 'g'
       )),
       ''
     ) = '' then
    raise exception using errcode = '22023', message = 'Overview body is required.';
  end if;
  if coalesce(v_root ->> 'overview_media_type', '') not in ('image', 'video') then
    raise exception using errcode = '22023', message = 'Overview media type is invalid.';
  end if;
  if v_root ->> 'overview_media_type' = 'image'
     and (
       coalesce(btrim(v_root ->> 'overview_main_image'), '') = ''
       or coalesce(btrim(v_root ->> 'overview_main_image_alt'), '') = ''
     ) then
    raise exception using errcode = '22023', message = 'Overview image and alt text are required in image mode.';
  end if;
  if nullif(v_root ->> 'overview_main_image', '') is not null
     and coalesce(btrim(v_root ->> 'overview_main_image_alt'), '') = '' then
    raise exception using errcode = '22023', message = 'Overview image alt text is required when an image is selected.';
  end if;
  if coalesce(btrim(v_root ->> 'delivery_title'), '') = '' then
    raise exception using errcode = '22023', message = 'Delivery title is required.';
  end if;
  if coalesce(
       btrim(regexp_replace(
         replace(coalesce(v_root ->> 'delivery_body', ''), '&nbsp;', ' '),
         '<[^>]*>', '', 'g'
       )),
       ''
     ) = '' then
    raise exception using errcode = '22023', message = 'Delivery body is required.';
  end if;
  if char_length(coalesce(v_root ->> 'seo_title', '')) > 60 then
    raise exception using errcode = '22023', message = 'SEO title must not exceed 60 characters.';
  end if;
  if char_length(coalesce(v_root ->> 'seo_description', '')) > 160 then
    raise exception using errcode = '22023', message = 'SEO description must not exceed 160 characters.';
  end if;
  if nullif(v_root ->> 'canonical_url', '') is not null
     and (v_root ->> 'canonical_url') !~* '^https?://' then
    raise exception using errcode = '22023', message = 'Canonical URL must use HTTP or HTTPS.';
  end if;
  if nullif(v_root ->> 'og_image', '') is not null
     and coalesce(btrim(v_root ->> 'og_image_alt'), '') = '' then
    raise exception using errcode = '22023', message = 'Open Graph image alt text is required when an image is selected.';
  end if;

  v_governorate_id := nullif(v_root ->> 'governorate_id', '')::bigint;
  v_city_id := nullif(v_root ->> 'city_id', '')::bigint;
  v_main_area_id := nullif(v_root ->> 'main_area_id', '')::bigint;
  v_sub_area_id := nullif(v_root ->> 'sub_area_id', '')::bigint;

  if v_governorate_id is null or v_city_id is null or v_main_area_id is null then
    raise exception using errcode = '23514', message = 'Governorate, city and main area must be selected together.';
  end if;

  perform 1
    from public.project_locations location
   where location.id = any (
     array[v_governorate_id, v_city_id, v_main_area_id, v_sub_area_id]
   )
   order by location.id
   for key share;

  if not exists (
    select 1
      from public.project_locations governorate
      join public.project_locations city
        on city.id = v_city_id
       and city.level = 'city'
       and city.parent_id = governorate.id
      join public.project_locations main_area
        on main_area.id = v_main_area_id
       and main_area.level = 'main_area'
       and main_area.parent_id = city.id
      left join public.project_locations sub_area
        on sub_area.id = v_sub_area_id
       and sub_area.level = 'sub_area'
       and sub_area.parent_id = main_area.id
     where governorate.id = v_governorate_id
       and governorate.level = 'governorate'
       and governorate.is_active
       and city.is_active
       and main_area.is_active
       and (v_sub_area_id is null or sub_area.is_active)
       and (v_sub_area_id is null or sub_area.id is not null)
  ) then
    raise exception using errcode = '23514', message = 'The selected location hierarchy is invalid or inactive.';
  end if;

  if p_project_id is null then
    insert into public.projects (
      type, arabic_name, english_name, slug,
      general_description, short_description,
      image, image_alt, hero_image, hero_image_alt,
      small_box_image, small_box_image_alt,
      governorate_id, city_id, main_area_id, sub_area_id,
      location_label, location_description, google_maps_url,
      latitude, longitude, map_zoom,
      overview_title, overview_body, overview_media_type, overview_main_image, overview_main_image_alt,
      delivery_title, delivery_body,
      seo_title, seo_description, focus_keyword, seo_keywords,
      canonical_url, robots_index, robots_follow, og_image, og_image_alt,
      created_at, updated_at
    ) values (
      v_root ->> 'type', btrim(v_root ->> 'arabic_name'), btrim(v_root ->> 'english_name'), btrim(v_root ->> 'slug'),
      coalesce(v_root ->> 'general_description', ''), coalesce(v_root ->> 'short_description', ''),
      nullif(v_root ->> 'image', ''), coalesce(v_root ->> 'image_alt', ''),
      nullif(v_root ->> 'hero_image', ''), coalesce(v_root ->> 'hero_image_alt', ''),
      nullif(v_root ->> 'small_box_image', ''), coalesce(v_root ->> 'small_box_image_alt', ''),
      v_governorate_id, v_city_id, v_main_area_id, v_sub_area_id,
      coalesce(v_root ->> 'location_label', ''), coalesce(v_root ->> 'location_description', ''),
      nullif(v_root ->> 'google_maps_url', ''),
      nullif(v_root ->> 'latitude', '')::numeric,
      nullif(v_root ->> 'longitude', '')::numeric,
      nullif(v_root ->> 'map_zoom', '')::smallint,
      coalesce(v_root ->> 'overview_title', ''), coalesce(v_root ->> 'overview_body', ''),
      v_root ->> 'overview_media_type',
      nullif(v_root ->> 'overview_main_image', ''), coalesce(v_root ->> 'overview_main_image_alt', ''),
      coalesce(v_root ->> 'delivery_title', ''), coalesce(v_root ->> 'delivery_body', ''),
      coalesce(v_root ->> 'seo_title', ''), coalesce(v_root ->> 'seo_description', ''),
      coalesce(v_root ->> 'focus_keyword', ''),
      coalesce(array(select jsonb_array_elements_text(coalesce(v_root -> 'seo_keywords', '[]'::jsonb))), '{}'::text[]),
      nullif(v_root ->> 'canonical_url', ''),
      case when v_root ? 'robots_index' then (v_root ->> 'robots_index')::boolean else null end,
      case when v_root ? 'robots_follow' then (v_root ->> 'robots_follow')::boolean else null end,
      nullif(v_root ->> 'og_image', ''), coalesce(v_root ->> 'og_image_alt', ''),
      v_now, v_now
    )
    returning id into v_project_id;
  else
    select project.type into v_existing_type
      from public.projects project
     where project.id = p_project_id
     for update;
    if v_existing_type is null then
      raise exception using errcode = 'P0002', message = 'Project not found.';
    end if;
    if v_root ->> 'type' <> v_existing_type then
      raise exception using errcode = '23514', message = 'Project type is immutable after creation.';
    end if;

    update public.projects project set
      arabic_name = btrim(v_root ->> 'arabic_name'),
      english_name = btrim(v_root ->> 'english_name'),
      slug = btrim(v_root ->> 'slug'),
      general_description = case when v_root ? 'general_description' then coalesce(v_root ->> 'general_description', '') else project.general_description end,
      short_description = case when v_root ? 'short_description' then coalesce(v_root ->> 'short_description', '') else project.short_description end,
      image = case when v_root ? 'image' then nullif(v_root ->> 'image', '') else project.image end,
      image_alt = case when v_root ? 'image_alt' then coalesce(v_root ->> 'image_alt', '') else project.image_alt end,
      hero_image = case when v_root ? 'hero_image' then nullif(v_root ->> 'hero_image', '') else project.hero_image end,
      hero_image_alt = case when v_root ? 'hero_image_alt' then coalesce(v_root ->> 'hero_image_alt', '') else project.hero_image_alt end,
      small_box_image = case when v_root ? 'small_box_image' then nullif(v_root ->> 'small_box_image', '') else project.small_box_image end,
      small_box_image_alt = case when v_root ? 'small_box_image_alt' then coalesce(v_root ->> 'small_box_image_alt', '') else project.small_box_image_alt end,
      governorate_id = case when v_root ? 'governorate_id' then v_governorate_id else project.governorate_id end,
      city_id = case when v_root ? 'city_id' then v_city_id else project.city_id end,
      main_area_id = case when v_root ? 'main_area_id' then v_main_area_id else project.main_area_id end,
      sub_area_id = case when v_root ? 'sub_area_id' then v_sub_area_id else project.sub_area_id end,
      location_label = case when v_root ? 'location_label' then coalesce(v_root ->> 'location_label', '') else project.location_label end,
      location_description = case when v_root ? 'location_description' then coalesce(v_root ->> 'location_description', '') else project.location_description end,
      google_maps_url = case when v_root ? 'google_maps_url' then nullif(v_root ->> 'google_maps_url', '') else project.google_maps_url end,
      latitude = case when v_root ? 'latitude' then nullif(v_root ->> 'latitude', '')::numeric else project.latitude end,
      longitude = case when v_root ? 'longitude' then nullif(v_root ->> 'longitude', '')::numeric else project.longitude end,
      map_zoom = case when v_root ? 'map_zoom' then nullif(v_root ->> 'map_zoom', '')::smallint else project.map_zoom end,
      overview_title = case when v_root ? 'overview_title' then coalesce(v_root ->> 'overview_title', '') else project.overview_title end,
      overview_body = case when v_root ? 'overview_body' then coalesce(v_root ->> 'overview_body', '') else project.overview_body end,
      overview_media_type = v_root ->> 'overview_media_type',
      overview_main_image = case when v_root ? 'overview_main_image' then nullif(v_root ->> 'overview_main_image', '') else project.overview_main_image end,
      overview_main_image_alt = case when v_root ? 'overview_main_image_alt' then coalesce(v_root ->> 'overview_main_image_alt', '') else project.overview_main_image_alt end,
      delivery_title = case when v_root ? 'delivery_title' then coalesce(v_root ->> 'delivery_title', '') else project.delivery_title end,
      delivery_body = case when v_root ? 'delivery_body' then coalesce(v_root ->> 'delivery_body', '') else project.delivery_body end,
      seo_title = case when v_root ? 'seo_title' then coalesce(v_root ->> 'seo_title', '') else project.seo_title end,
      seo_description = case when v_root ? 'seo_description' then coalesce(v_root ->> 'seo_description', '') else project.seo_description end,
      focus_keyword = case when v_root ? 'focus_keyword' then coalesce(v_root ->> 'focus_keyword', '') else project.focus_keyword end,
      seo_keywords = case when v_root ? 'seo_keywords' then coalesce(array(select jsonb_array_elements_text(coalesce(v_root -> 'seo_keywords', '[]'::jsonb))), '{}'::text[]) else project.seo_keywords end,
      canonical_url = case when v_root ? 'canonical_url' then nullif(v_root ->> 'canonical_url', '') else project.canonical_url end,
      robots_index = case when v_root ? 'robots_index' then nullif(v_root ->> 'robots_index', '')::boolean else project.robots_index end,
      robots_follow = case when v_root ? 'robots_follow' then nullif(v_root ->> 'robots_follow', '')::boolean else project.robots_follow end,
      og_image = case when v_root ? 'og_image' then nullif(v_root ->> 'og_image', '') else project.og_image end,
      og_image_alt = case when v_root ? 'og_image_alt' then coalesce(v_root ->> 'og_image_alt', '') else project.og_image_alt end,
      updated_at = v_now
    where project.id = p_project_id;
    v_project_id := p_project_id;
  end if;

  -- Deletions are explicit tombstones. Omitting an existing child from an
  -- upsert array never deletes it. Ownership is checked before every delete so
  -- a forged ID cannot cross Project boundaries. Tombstones run before upserts
  -- so replacing the single overview video does not hit its partial unique
  -- index before the old row is removed.
  if v_deleted ? 'location_point_ids' then
    if jsonb_typeof(v_deleted -> 'location_point_ids') is distinct from 'array' then
      raise exception using errcode = '22023', message = 'deleted.location_point_ids must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements_text(v_deleted -> 'location_point_ids') requested(id)
      where not exists (
        select 1 from public.project_location_points existing
        where existing.id = requested.id::bigint
          and existing.project_id = v_project_id
      )
    ) then
      raise exception using errcode = '23503', message = 'A deleted location point does not belong to this project.';
    end if;
    delete from public.project_location_points existing
     where existing.project_id = v_project_id
       and existing.id in (
         select requested.id::bigint
         from jsonb_array_elements_text(v_deleted -> 'location_point_ids') requested(id)
       );
  end if;

  if v_deleted ? 'feature_ids' then
    if jsonb_typeof(v_deleted -> 'feature_ids') is distinct from 'array' then
      raise exception using errcode = '22023', message = 'deleted.feature_ids must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements_text(v_deleted -> 'feature_ids') requested(id)
      where not exists (
        select 1 from public.project_features existing
        where existing.id = requested.id::bigint
          and existing.project_id = v_project_id
      )
    ) then
      raise exception using errcode = '23503', message = 'A deleted feature does not belong to this project.';
    end if;
    delete from public.project_features existing
     where existing.project_id = v_project_id
       and existing.id in (
         select requested.id::bigint
         from jsonb_array_elements_text(v_deleted -> 'feature_ids') requested(id)
       );
  end if;

  if v_deleted ? 'floor_plan_detail_ids' then
    if jsonb_typeof(v_deleted -> 'floor_plan_detail_ids') is distinct from 'array' then
      raise exception using errcode = '22023', message = 'deleted.floor_plan_detail_ids must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements_text(v_deleted -> 'floor_plan_detail_ids') requested(id)
      where not exists (
        select 1
        from public.project_floor_plan_details existing
        join public.project_floor_plans plan on plan.id = existing.floor_plan_id
        where existing.id = requested.id::bigint
          and plan.project_id = v_project_id
      )
    ) then
      raise exception using errcode = '23503', message = 'A deleted floor plan detail does not belong to this project.';
    end if;
    delete from public.project_floor_plan_details existing
     using public.project_floor_plans plan
     where plan.id = existing.floor_plan_id
       and plan.project_id = v_project_id
       and existing.id in (
         select requested.id::bigint
         from jsonb_array_elements_text(v_deleted -> 'floor_plan_detail_ids') requested(id)
       );
  end if;

  if v_deleted ? 'floor_plan_ids' then
    if jsonb_typeof(v_deleted -> 'floor_plan_ids') is distinct from 'array' then
      raise exception using errcode = '22023', message = 'deleted.floor_plan_ids must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements_text(v_deleted -> 'floor_plan_ids') requested(id)
      where not exists (
        select 1 from public.project_floor_plans existing
        where existing.id = requested.id::bigint
          and existing.project_id = v_project_id
      )
    ) then
      raise exception using errcode = '23503', message = 'A deleted floor plan does not belong to this project.';
    end if;
    delete from public.project_floor_plans existing
     where existing.project_id = v_project_id
       and existing.id in (
         select requested.id::bigint
         from jsonb_array_elements_text(v_deleted -> 'floor_plan_ids') requested(id)
       );
  end if;

  if v_deleted ? 'delivery_item_ids' then
    if jsonb_typeof(v_deleted -> 'delivery_item_ids') is distinct from 'array' then
      raise exception using errcode = '22023', message = 'deleted.delivery_item_ids must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements_text(v_deleted -> 'delivery_item_ids') requested(id)
      where not exists (
        select 1 from public.project_delivery_items existing
        where existing.id = requested.id::bigint
          and existing.project_id = v_project_id
      )
    ) then
      raise exception using errcode = '23503', message = 'A deleted delivery item does not belong to this project.';
    end if;
    delete from public.project_delivery_items existing
     where existing.project_id = v_project_id
       and existing.id in (
         select requested.id::bigint
         from jsonb_array_elements_text(v_deleted -> 'delivery_item_ids') requested(id)
       );
  end if;

  if v_deleted ? 'media_ids' then
    if jsonb_typeof(v_deleted -> 'media_ids') is distinct from 'array' then
      raise exception using errcode = '22023', message = 'deleted.media_ids must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements_text(v_deleted -> 'media_ids') requested(id)
      where not exists (
        select 1 from public.project_media existing
        where existing.id = requested.id::bigint
          and existing.project_id = v_project_id
      )
    ) then
      raise exception using errcode = '23503', message = 'A deleted media item does not belong to this project.';
    end if;
    delete from public.project_media existing
     where existing.project_id = v_project_id
       and existing.id in (
         select requested.id::bigint
         from jsonb_array_elements_text(v_deleted -> 'media_ids') requested(id)
       );
  end if;

  if v_deleted ? 'video_ids' then
    if jsonb_typeof(v_deleted -> 'video_ids') is distinct from 'array' then
      raise exception using errcode = '22023', message = 'deleted.video_ids must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements_text(v_deleted -> 'video_ids') requested(id)
      where not exists (
        select 1 from public.project_videos existing
        where existing.id = requested.id::bigint
          and existing.project_id = v_project_id
      )
    ) then
      raise exception using errcode = '23503', message = 'A deleted video does not belong to this project.';
    end if;
    delete from public.project_videos existing
     where existing.project_id = v_project_id
       and existing.id in (
         select requested.id::bigint
         from jsonb_array_elements_text(v_deleted -> 'video_ids') requested(id)
       );
  end if;

  -- Location points: stable DB IDs are retained through the client_key upsert.
  if p_payload ? 'location_points' then
    if jsonb_typeof(p_payload -> 'location_points') <> 'array' then
      raise exception using errcode = '22023', message = 'location_points must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'location_points') item
      where (
        nullif(item ->> 'id', '') is not null
        and not exists (
          select 1 from public.project_location_points existing
          where existing.id = (item ->> 'id')::bigint
            and existing.project_id = v_project_id
            and existing.client_key = (item ->> 'client_key')::uuid
        )
      ) or (
        nullif(item ->> 'id', '') is null
        and exists (
          select 1 from public.project_location_points existing
          where existing.client_key = (item ->> 'client_key')::uuid
        )
      )
    ) then
      raise exception using errcode = '23503', message = 'A location point does not belong to this project.';
    end if;
    if exists (
      select 1 from public.project_location_points existing
      where existing.project_id = v_project_id
        and not exists (
          select 1 from jsonb_array_elements(p_payload -> 'location_points') item
          where nullif(item ->> 'id', '')::bigint = existing.id
            and (item ->> 'client_key')::uuid = existing.client_key
        )
    ) then
      raise exception using errcode = '22023', message = 'An existing location point was omitted without an explicit deletion tombstone.';
    end if;

    insert into public.project_location_points (
      client_key, project_id, kind, label, distance_text, sort_order, updated_at
    )
    select
      (item.value ->> 'client_key')::uuid,
      v_project_id,
      item.value ->> 'kind',
      btrim(item.value ->> 'label'),
      coalesce(item.value ->> 'distance_text', ''),
      row_number() over (
        partition by item.value ->> 'kind'
        order by item.ordinality
      ) - 1,
      v_now
    from jsonb_array_elements(p_payload -> 'location_points') with ordinality item(value, ordinality)
    on conflict (project_id, client_key) do update set
      kind = excluded.kind,
      label = excluded.label,
      distance_text = excluded.distance_text,
      sort_order = excluded.sort_order,
      updated_at = excluded.updated_at;

  end if;

  if p_payload ? 'features' then
    if jsonb_typeof(p_payload -> 'features') <> 'array' then
      raise exception using errcode = '22023', message = 'features must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'features') item
      where (
        nullif(item ->> 'id', '') is not null
        and not exists (
          select 1 from public.project_features existing
          where existing.id = (item ->> 'id')::bigint
            and existing.project_id = v_project_id
            and existing.client_key = (item ->> 'client_key')::uuid
        )
      ) or (
        nullif(item ->> 'id', '') is null
        and exists (
          select 1 from public.project_features existing
          where existing.client_key = (item ->> 'client_key')::uuid
        )
      )
    ) then
      raise exception using errcode = '23503', message = 'A feature identity is invalid for this project.';
    end if;
    if exists (
      select 1 from public.project_features existing
      where existing.project_id = v_project_id
        and not exists (
          select 1 from jsonb_array_elements(p_payload -> 'features') item
          where nullif(item ->> 'id', '')::bigint = existing.id
            and (item ->> 'client_key')::uuid = existing.client_key
        )
    ) then
      raise exception using errcode = '22023', message = 'An existing feature was omitted without an explicit deletion tombstone.';
    end if;
    insert into public.project_features (client_key, project_id, body, sort_order, updated_at)
    select
      (item.value ->> 'client_key')::uuid,
      v_project_id,
      btrim(item.value ->> 'body'),
      item.ordinality - 1,
      v_now
    from jsonb_array_elements(p_payload -> 'features') with ordinality item(value, ordinality)
    on conflict (project_id, client_key) do update set
      body = excluded.body,
      sort_order = excluded.sort_order,
      updated_at = excluded.updated_at;
  end if;

  if p_payload ? 'floor_plans' then
    if jsonb_typeof(p_payload -> 'floor_plans') <> 'array' then
      raise exception using errcode = '22023', message = 'floor_plans must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'floor_plans') item
      where (
        nullif(item ->> 'id', '') is not null
        and not exists (
          select 1 from public.project_floor_plans existing
          where existing.id = (item ->> 'id')::bigint
            and existing.project_id = v_project_id
            and existing.client_key = (item ->> 'client_key')::uuid
        )
      ) or (
        nullif(item ->> 'id', '') is null
        and exists (
          select 1 from public.project_floor_plans existing
          where existing.client_key = (item ->> 'client_key')::uuid
        )
      )
    ) then
      raise exception using errcode = '23503', message = 'A floor plan identity is invalid for this project.';
    end if;
    if exists (
      select 1 from public.project_floor_plans existing
      where existing.project_id = v_project_id
        and not exists (
          select 1 from jsonb_array_elements(p_payload -> 'floor_plans') item
          where nullif(item ->> 'id', '')::bigint = existing.id
            and (item ->> 'client_key')::uuid = existing.client_key
        )
    ) then
      raise exception using errcode = '22023', message = 'An existing floor plan was omitted without an explicit deletion tombstone.';
    end if;
    v_index := 0;
    for v_plan in select value from jsonb_array_elements(p_payload -> 'floor_plans') loop
      v_client_key := (v_plan ->> 'client_key')::uuid;

      insert into public.project_floor_plans (
        client_key, project_id, name, area_text, featured,
        architectural_image, architectural_image_alt,
        furnishing_image, furnishing_image_alt,
        sort_order, updated_at
      ) values (
        v_client_key, v_project_id, btrim(v_plan ->> 'name'),
        coalesce(v_plan ->> 'area_text', ''), coalesce((v_plan ->> 'featured')::boolean, false),
        nullif(v_plan ->> 'architectural_image', ''), coalesce(v_plan ->> 'architectural_image_alt', ''),
        nullif(v_plan ->> 'furnishing_image', ''), coalesce(v_plan ->> 'furnishing_image_alt', ''),
        v_index, v_now
      )
      on conflict (project_id, client_key) do update set
        name = excluded.name,
        area_text = excluded.area_text,
        featured = excluded.featured,
        architectural_image = excluded.architectural_image,
        architectural_image_alt = excluded.architectural_image_alt,
        furnishing_image = excluded.furnishing_image,
        furnishing_image_alt = excluded.furnishing_image_alt,
        sort_order = excluded.sort_order,
        updated_at = excluded.updated_at
      returning id into v_plan_id;

      if v_plan ? 'details' then
        if jsonb_typeof(v_plan -> 'details') <> 'array' then
          raise exception using errcode = '22023', message = 'floor plan details must be an array.';
        end if;
        if exists (
          select 1
          from jsonb_array_elements(v_plan -> 'details') detail
          where (
            nullif(detail ->> 'id', '') is not null
            and not exists (
              select 1 from public.project_floor_plan_details existing
              where existing.id = (detail ->> 'id')::bigint
                and existing.floor_plan_id = v_plan_id
                and existing.client_key = (detail ->> 'client_key')::uuid
            )
          ) or (
            nullif(detail ->> 'id', '') is null
            and exists (
              select 1 from public.project_floor_plan_details existing
              where existing.client_key = (detail ->> 'client_key')::uuid
            )
          )
        ) then
          raise exception using errcode = '23503', message = 'A floor plan detail identity is invalid for this plan.';
        end if;
        if exists (
          select 1 from public.project_floor_plan_details existing
          where existing.floor_plan_id = v_plan_id
            and not exists (
              select 1 from jsonb_array_elements(v_plan -> 'details') detail
              where nullif(detail ->> 'id', '')::bigint = existing.id
                and (detail ->> 'client_key')::uuid = existing.client_key
            )
        ) then
          raise exception using errcode = '22023', message = 'An existing floor plan detail was omitted without an explicit deletion tombstone.';
        end if;
        insert into public.project_floor_plan_details (
          client_key, floor_plan_id, label, value, sort_order, updated_at
        )
        select
          (detail.value ->> 'client_key')::uuid,
          v_plan_id,
          btrim(detail.value ->> 'label'),
          btrim(detail.value ->> 'value'),
          detail.ordinality - 1,
          v_now
        from jsonb_array_elements(v_plan -> 'details') with ordinality detail(value, ordinality)
        on conflict (floor_plan_id, client_key) do update set
          label = excluded.label,
          value = excluded.value,
          sort_order = excluded.sort_order,
          updated_at = excluded.updated_at;
      end if;
      v_index := v_index + 1;
    end loop;
  end if;

  if p_payload ? 'delivery_items' then
    if jsonb_typeof(p_payload -> 'delivery_items') <> 'array' then
      raise exception using errcode = '22023', message = 'delivery_items must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'delivery_items') item
      where (
        nullif(item ->> 'id', '') is not null
        and not exists (
          select 1 from public.project_delivery_items existing
          where existing.id = (item ->> 'id')::bigint
            and existing.project_id = v_project_id
            and existing.client_key = (item ->> 'client_key')::uuid
        )
      ) or (
        nullif(item ->> 'id', '') is null
        and exists (
          select 1 from public.project_delivery_items existing
          where existing.client_key = (item ->> 'client_key')::uuid
        )
      )
    ) then
      raise exception using errcode = '23503', message = 'A delivery item identity is invalid for this project.';
    end if;
    if exists (
      select 1 from public.project_delivery_items existing
      where existing.project_id = v_project_id
        and not exists (
          select 1 from jsonb_array_elements(p_payload -> 'delivery_items') item
          where nullif(item ->> 'id', '')::bigint = existing.id
            and (item ->> 'client_key')::uuid = existing.client_key
        )
    ) then
      raise exception using errcode = '22023', message = 'An existing delivery item was omitted without an explicit deletion tombstone.';
    end if;
    insert into public.project_delivery_items (client_key, project_id, body, sort_order, updated_at)
    select
      (item.value ->> 'client_key')::uuid,
      v_project_id,
      btrim(item.value ->> 'body'),
      item.ordinality - 1,
      v_now
    from jsonb_array_elements(p_payload -> 'delivery_items') with ordinality item(value, ordinality)
    on conflict (project_id, client_key) do update set
      body = excluded.body,
      sort_order = excluded.sort_order,
      updated_at = excluded.updated_at;
  end if;

  if p_payload ? 'media' then
    if jsonb_typeof(p_payload -> 'media') <> 'array' then
      raise exception using errcode = '22023', message = 'media must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'media') item
      where (
        nullif(item ->> 'id', '') is not null
        and not exists (
          select 1 from public.project_media existing
          where existing.id = (item ->> 'id')::bigint
            and existing.project_id = v_project_id
            and existing.client_key = (item ->> 'client_key')::uuid
        )
      ) or (
        nullif(item ->> 'id', '') is null
        and exists (
          select 1 from public.project_media existing
          where existing.client_key = (item ->> 'client_key')::uuid
        )
      )
    ) then
      raise exception using errcode = '23503', message = 'A media identity is invalid for this project.';
    end if;
    if exists (
      select 1 from public.project_media existing
      where existing.project_id = v_project_id
        and not exists (
          select 1 from jsonb_array_elements(p_payload -> 'media') item
          where nullif(item ->> 'id', '')::bigint = existing.id
            and (item ->> 'client_key')::uuid = existing.client_key
        )
    ) then
      raise exception using errcode = '22023', message = 'An existing media item was omitted without an explicit deletion tombstone.';
    end if;
    insert into public.project_media (
      client_key, project_id, section, image, alt_text, sort_order, updated_at
    )
    select
      (item.value ->> 'client_key')::uuid,
      v_project_id,
      item.value ->> 'section',
      btrim(item.value ->> 'image'),
      coalesce(item.value ->> 'alt_text', ''),
      row_number() over (
        partition by item.value ->> 'section'
        order by item.ordinality
      ) - 1,
      v_now
    from jsonb_array_elements(p_payload -> 'media') with ordinality item(value, ordinality)
    on conflict (project_id, client_key) do update set
      section = excluded.section,
      image = excluded.image,
      alt_text = excluded.alt_text,
      sort_order = excluded.sort_order,
      updated_at = excluded.updated_at;
  end if;

  if p_payload ? 'videos' then
    if jsonb_typeof(p_payload -> 'videos') <> 'array' then
      raise exception using errcode = '22023', message = 'videos must be an array.';
    end if;
    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'videos') item
      where (
        nullif(item ->> 'id', '') is not null
        and not exists (
          select 1 from public.project_videos existing
          where existing.id = (item ->> 'id')::bigint
            and existing.project_id = v_project_id
            and existing.client_key = (item ->> 'client_key')::uuid
        )
      ) or (
        nullif(item ->> 'id', '') is null
        and exists (
          select 1 from public.project_videos existing
          where existing.client_key = (item ->> 'client_key')::uuid
        )
      )
    ) then
      raise exception using errcode = '23503', message = 'A video identity is invalid for this project.';
    end if;
    if exists (
      select 1 from public.project_videos existing
      where existing.project_id = v_project_id
        and not exists (
          select 1 from jsonb_array_elements(p_payload -> 'videos') item
          where nullif(item ->> 'id', '')::bigint = existing.id
            and (item ->> 'client_key')::uuid = existing.client_key
        )
    ) then
      raise exception using errcode = '22023', message = 'An existing video was omitted without an explicit deletion tombstone.';
    end if;
    insert into public.project_videos (
      client_key, project_id, section, video_url, poster_image, poster_alt, sort_order, updated_at
    )
    select
      (item.value ->> 'client_key')::uuid,
      v_project_id,
      item.value ->> 'section',
      btrim(item.value ->> 'video_url'),
      nullif(item.value ->> 'poster_image', ''),
      coalesce(item.value ->> 'poster_alt', ''),
      row_number() over (
        partition by item.value ->> 'section'
        order by item.ordinality
      ) - 1,
      v_now
    from jsonb_array_elements(p_payload -> 'videos') with ordinality item(value, ordinality)
    on conflict (project_id, client_key) do update set
      section = excluded.section,
      video_url = excluded.video_url,
      poster_image = excluded.poster_image,
      poster_alt = excluded.poster_alt,
      sort_order = excluded.sort_order,
      updated_at = excluded.updated_at;
  end if;

  if (select project.overview_media_type from public.projects project where project.id = v_project_id) = 'video'
     and (
       select count(*)
         from public.project_videos video
        where video.project_id = v_project_id
          and video.section = 'overview'
     ) <> 1 then
    raise exception using
      errcode = '23514',
      message = 'Video overview mode requires exactly one overview video.';
  end if;

  -- Surface reorder collisions inside this RPC, rather than leaving initially
  -- deferred ordering constraints to fail later at an outer transaction commit.
  set constraints
    public.project_location_points_sort_unique,
    public.project_features_sort_unique,
    public.project_floor_plans_sort_unique,
    public.project_floor_plan_details_sort_unique,
    public.project_delivery_items_sort_unique,
    public.project_media_sort_unique,
    public.project_videos_sort_unique
  immediate;

  return query
  select project.id, project.slug, project.updated_at
    from public.projects project
   where project.id = v_project_id;
end
$function$;

-- Root deletion is an explicit aggregate mutation. Child rows are removed by
-- their foreign-key cascades in the same transaction; direct table DELETE stays
-- unavailable to the runtime service role.
create or replace function public.delete_project_admin_entry(
  p_project_id bigint
)
returns table (project_type text, project_slug text)
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_project_type text;
  v_project_slug text;
begin
  delete from public.projects as project
   where project.id = p_project_id
  returning project.type, project.slug
       into v_project_type, v_project_slug;

  if not found then
    raise exception using errcode = 'P0002', message = 'Project not found.';
  end if;

  return query select v_project_type, v_project_slug;
end
$function$;

-- Private Admin-only aggregate. RLS stays enabled and no anon/authenticated
-- policies are created. Supabase projects can carry role-specific default
-- privileges, so remove every direct non-owner grant that materialized while
-- these objects were created. This includes column grants: a table-level REVOKE
-- does not remove privileges granted on individual columns.
do $project_acl_cleanup$
declare
  v_grant record;
begin
  for v_grant in
    select distinct
      acl.grantee,
      grantee.rolname as grantee_name,
      relation.relname
    from pg_catalog.pg_class as relation
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
    cross join lateral pg_catalog.aclexplode(relation.relacl) as acl
    left join pg_catalog.pg_roles as grantee
      on grantee.oid = acl.grantee
    where relation.relacl is not null
      and namespace.nspname = 'public'
      and relation.relname = any (array[
        'project_locations',
        'projects',
        'project_location_points',
        'project_features',
        'project_floor_plans',
        'project_floor_plan_details',
        'project_delivery_items',
        'project_media',
        'project_videos'
      ])
      and relation.relkind in ('r', 'p')
      and acl.grantee <> relation.relowner
  loop
    if v_grant.grantee = 0 then
      execute format(
        'revoke all privileges on table public.%I from public cascade',
        v_grant.relname
      );
    else
      execute format(
        'revoke all privileges on table public.%I from %I cascade',
        v_grant.relname,
        v_grant.grantee_name
      );
    end if;
  end loop;

  for v_grant in
    select distinct
      acl.grantee,
      grantee.rolname as grantee_name,
      relation.relname,
      attribute.attname
    from pg_catalog.pg_class as relation
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = relation.oid
     and attribute.attnum > 0
     and not attribute.attisdropped
    cross join lateral pg_catalog.aclexplode(attribute.attacl) as acl
    left join pg_catalog.pg_roles as grantee
      on grantee.oid = acl.grantee
    where attribute.attacl is not null
      and namespace.nspname = 'public'
      and relation.relname = any (array[
        'project_locations',
        'projects',
        'project_location_points',
        'project_features',
        'project_floor_plans',
        'project_floor_plan_details',
        'project_delivery_items',
        'project_media',
        'project_videos'
      ])
      and relation.relkind in ('r', 'p')
      and acl.grantee <> relation.relowner
  loop
    if v_grant.grantee = 0 then
      execute format(
        'revoke all privileges (%I) on table public.%I from public cascade',
        v_grant.attname,
        v_grant.relname
      );
    else
      execute format(
        'revoke all privileges (%I) on table public.%I from %I cascade',
        v_grant.attname,
        v_grant.relname,
        v_grant.grantee_name
      );
    end if;
  end loop;

  for v_grant in
    select distinct
      acl.grantee,
      grantee.rolname as grantee_name,
      sequence.relname
    from pg_catalog.pg_class as sequence
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = sequence.relnamespace
    cross join lateral pg_catalog.aclexplode(sequence.relacl) as acl
    left join pg_catalog.pg_roles as grantee
      on grantee.oid = acl.grantee
    where sequence.relacl is not null
      and namespace.nspname = 'public'
      and sequence.relname = any (array[
        'project_locations_id_seq',
        'projects_id_seq',
        'project_location_points_id_seq',
        'project_features_id_seq',
        'project_floor_plans_id_seq',
        'project_floor_plan_details_id_seq',
        'project_delivery_items_id_seq',
        'project_media_id_seq',
        'project_videos_id_seq'
      ])
      and sequence.relkind = 'S'
      and acl.grantee <> sequence.relowner
  loop
    if v_grant.grantee = 0 then
      execute format(
        'revoke all privileges on sequence public.%I from public cascade',
        v_grant.relname
      );
    else
      execute format(
        'revoke all privileges on sequence public.%I from %I cascade',
        v_grant.relname,
        v_grant.grantee_name
      );
    end if;
  end loop;

  for v_grant in
    select distinct
      acl.grantee,
      grantee.rolname as grantee_name,
      procedure.proname,
      pg_catalog.pg_get_function_identity_arguments(procedure.oid) as identity_arguments
    from pg_catalog.pg_proc as procedure
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = procedure.pronamespace
    cross join lateral pg_catalog.aclexplode(procedure.proacl) as acl
    left join pg_catalog.pg_roles as grantee
      on grantee.oid = acl.grantee
    where procedure.proacl is not null
      and namespace.nspname = 'public'
      and procedure.oid = any (array[
        'public.save_project_admin_entry(bigint,jsonb)'::regprocedure::oid,
        'public.delete_project_admin_entry(bigint)'::regprocedure::oid,
        'public.validate_project_location_parent()'::regprocedure::oid,
        'public.prevent_project_type_change()'::regprocedure::oid,
        'public.validate_project_location_selection()'::regprocedure::oid,
        'public.prevent_project_location_reparent()'::regprocedure::oid
      ])
      and acl.grantee <> procedure.proowner
  loop
    if v_grant.grantee = 0 then
      execute format(
        'revoke all privileges on function public.%I(%s) from public cascade',
        v_grant.proname,
        v_grant.identity_arguments
      );
    else
      execute format(
        'revoke all privileges on function public.%I(%s) from %I cascade',
        v_grant.proname,
        v_grant.identity_arguments,
        v_grant.grantee_name
      );
    end if;
  end loop;
end
$project_acl_cleanup$;

revoke all on function public.save_project_admin_entry(bigint, jsonb) from public;
revoke all on function public.save_project_admin_entry(bigint, jsonb) from anon;
revoke all on function public.save_project_admin_entry(bigint, jsonb) from authenticated;
revoke all on function public.save_project_admin_entry(bigint, jsonb) from service_role;
revoke all privileges on function public.delete_project_admin_entry(bigint)
  from public, anon, authenticated, service_role;
grant execute on function public.save_project_admin_entry(bigint, jsonb) to service_role;
grant execute on function public.delete_project_admin_entry(bigint) to service_role;

revoke all privileges on table
  public.project_locations,
  public.projects,
  public.project_location_points,
  public.project_features,
  public.project_floor_plans,
  public.project_floor_plan_details,
  public.project_delivery_items,
  public.project_media,
  public.project_videos
from public, anon, authenticated, service_role;

-- The server may load the aggregate and active location options directly. All
-- mutations remain behind the SECURITY DEFINER aggregate RPC.
grant select on table
  public.project_locations,
  public.projects,
  public.project_location_points,
  public.project_features,
  public.project_floor_plans,
  public.project_floor_plan_details,
  public.project_delivery_items,
  public.project_media,
  public.project_videos
to service_role;

revoke all privileges on sequence
  public.project_locations_id_seq,
  public.projects_id_seq,
  public.project_location_points_id_seq,
  public.project_features_id_seq,
  public.project_floor_plans_id_seq,
  public.project_floor_plan_details_id_seq,
  public.project_delivery_items_id_seq,
  public.project_media_id_seq,
  public.project_videos_id_seq
from public, anon, authenticated, service_role;

revoke all privileges on function public.validate_project_location_parent()
  from public, anon, authenticated, service_role;
revoke all privileges on function public.prevent_project_type_change()
  from public, anon, authenticated, service_role;
revoke all privileges on function public.validate_project_location_selection()
  from public, anon, authenticated, service_role;
revoke all privileges on function public.prevent_project_location_reparent()
  from public, anon, authenticated, service_role;

-- Fail closed before COMMIT if either a default privilege or inherited runtime
-- membership still exposes a direct mutation surface.
do $project_acl_assert$
declare
  v_table text;
  v_sequence text;
  v_role text;
begin
  foreach v_table in array array[
    'project_locations',
    'projects',
    'project_location_points',
    'project_features',
    'project_floor_plans',
    'project_floor_plan_details',
    'project_delivery_items',
    'project_media',
    'project_videos'
  ]
  loop
    if not pg_catalog.has_table_privilege(
      'service_role',
      format('public.%I', v_table),
      'SELECT'
    ) or pg_catalog.has_table_privilege(
      'service_role',
      format('public.%I', v_table),
      'INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN'
    ) then
      raise exception using
        errcode = '42501',
        message = format('Unsafe service_role table ACL remains on public.%I.', v_table);
    end if;

    foreach v_role in array array['anon', 'authenticated']
    loop
      if pg_catalog.has_table_privilege(
        v_role,
        format('public.%I', v_table),
        'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN'
      ) then
        raise exception using
          errcode = '42501',
          message = format('Unsafe %I table ACL remains on public.%I.', v_role, v_table);
      end if;
    end loop;
  end loop;

  if exists (
    select 1
    from pg_catalog.pg_class as relation
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
    cross join lateral pg_catalog.aclexplode(relation.relacl) as acl
    where relation.relacl is not null
      and namespace.nspname = 'public'
      and relation.relname = any (array[
        'project_locations',
        'projects',
        'project_location_points',
        'project_features',
        'project_floor_plans',
        'project_floor_plan_details',
        'project_delivery_items',
        'project_media',
        'project_videos'
      ])
      and relation.relkind in ('r', 'p')
      and acl.grantee <> relation.relowner
      and not (
        acl.grantee = 'service_role'::regrole::oid
        and acl.privilege_type = 'SELECT'
        and not acl.is_grantable
      )
  ) then
    raise exception using
      errcode = '42501',
      message = 'A non-owner direct table grant remains on the Project aggregate.';
  end if;

  if exists (
    select 1
    from pg_catalog.pg_class as relation
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = relation.oid
     and attribute.attnum > 0
     and not attribute.attisdropped
    cross join lateral pg_catalog.aclexplode(attribute.attacl) as acl
    where attribute.attacl is not null
      and namespace.nspname = 'public'
      and relation.relname = any (array[
        'project_locations',
        'projects',
        'project_location_points',
        'project_features',
        'project_floor_plans',
        'project_floor_plan_details',
        'project_delivery_items',
        'project_media',
        'project_videos'
      ])
      and relation.relkind in ('r', 'p')
      and acl.grantee <> relation.relowner
  ) then
    raise exception using
      errcode = '42501',
      message = 'A non-owner direct column grant remains on the Project aggregate.';
  end if;

  foreach v_sequence in array array[
    'project_locations_id_seq',
    'projects_id_seq',
    'project_location_points_id_seq',
    'project_features_id_seq',
    'project_floor_plans_id_seq',
    'project_floor_plan_details_id_seq',
    'project_delivery_items_id_seq',
    'project_media_id_seq',
    'project_videos_id_seq'
  ]
  loop
    foreach v_role in array array['anon', 'authenticated', 'service_role']
    loop
      if pg_catalog.has_sequence_privilege(
        v_role,
        format('public.%I', v_sequence),
        'SELECT,USAGE,UPDATE'
      ) then
        raise exception using
          errcode = '42501',
          message = format('Unsafe %I sequence ACL remains on public.%I.', v_role, v_sequence);
      end if;
    end loop;
  end loop;

  if exists (
    select 1
    from pg_catalog.pg_class as sequence
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = sequence.relnamespace
    cross join lateral pg_catalog.aclexplode(sequence.relacl) as acl
    where sequence.relacl is not null
      and namespace.nspname = 'public'
      and sequence.relname = any (array[
        'project_locations_id_seq',
        'projects_id_seq',
        'project_location_points_id_seq',
        'project_features_id_seq',
        'project_floor_plans_id_seq',
        'project_floor_plan_details_id_seq',
        'project_delivery_items_id_seq',
        'project_media_id_seq',
        'project_videos_id_seq'
      ])
      and sequence.relkind = 'S'
      and acl.grantee <> sequence.relowner
  ) then
    raise exception using
      errcode = '42501',
      message = 'A non-owner direct sequence grant remains on the Project aggregate.';
  end if;

  if not pg_catalog.has_function_privilege(
    'service_role',
    'public.save_project_admin_entry(bigint,jsonb)',
    'EXECUTE'
  ) or not pg_catalog.has_function_privilege(
    'service_role',
    'public.delete_project_admin_entry(bigint)',
    'EXECUTE'
  ) then
    raise exception using
      errcode = '42501',
      message = 'service_role cannot execute both Project aggregate RPCs.';
  end if;

  foreach v_role in array array['anon', 'authenticated']
  loop
    if pg_catalog.has_function_privilege(
      v_role,
      'public.save_project_admin_entry(bigint,jsonb)',
      'EXECUTE'
    ) or pg_catalog.has_function_privilege(
      v_role,
      'public.delete_project_admin_entry(bigint)',
      'EXECUTE'
    ) then
      raise exception using
        errcode = '42501',
        message = format('Unsafe %I Project aggregate RPC ACL remains.', v_role);
    end if;
  end loop;

  foreach v_role in array array['anon', 'authenticated', 'service_role']
  loop
    if pg_catalog.has_function_privilege(
      v_role,
      'public.validate_project_location_parent()',
      'EXECUTE'
    ) or pg_catalog.has_function_privilege(
      v_role,
      'public.prevent_project_type_change()',
      'EXECUTE'
    ) or pg_catalog.has_function_privilege(
      v_role,
      'public.validate_project_location_selection()',
      'EXECUTE'
    ) or pg_catalog.has_function_privilege(
      v_role,
      'public.prevent_project_location_reparent()',
      'EXECUTE'
    ) then
      raise exception using
        errcode = '42501',
        message = format('Unsafe %I helper-function ACL remains.', v_role);
    end if;
  end loop;

  if exists (
    select 1
    from pg_catalog.pg_proc as procedure
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = procedure.pronamespace
    cross join lateral pg_catalog.aclexplode(procedure.proacl) as acl
    where procedure.proacl is not null
      and namespace.nspname = 'public'
      and procedure.oid = any (array[
        'public.save_project_admin_entry(bigint,jsonb)'::regprocedure::oid,
        'public.delete_project_admin_entry(bigint)'::regprocedure::oid
      ])
      and acl.grantee <> procedure.proowner
      and not (
        acl.grantee = 'service_role'::regrole::oid
        and acl.privilege_type = 'EXECUTE'
        and not acl.is_grantable
      )
  ) then
    raise exception using
      errcode = '42501',
      message = 'A non-owner direct Project RPC grant remains.';
  end if;

  if exists (
    select 1
    from pg_catalog.pg_proc as procedure
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = procedure.pronamespace
    cross join lateral pg_catalog.aclexplode(procedure.proacl) as acl
    where procedure.proacl is not null
      and namespace.nspname = 'public'
      and procedure.oid = any (array[
        'public.validate_project_location_parent()'::regprocedure::oid,
        'public.prevent_project_type_change()'::regprocedure::oid,
        'public.validate_project_location_selection()'::regprocedure::oid,
        'public.prevent_project_location_reparent()'::regprocedure::oid
      ])
      and acl.grantee <> procedure.proowner
  ) then
    raise exception using
      errcode = '42501',
      message = 'A non-owner direct helper-function grant remains.';
  end if;
end
$project_acl_assert$;

-- Final clean-schema parity gate. This block is assertion-only: it performs no
-- DDL or DML and leaves default privileges untouched. Any catalog or reference
-- seed drift aborts the complete rebuild before COMMIT.
do $project_clean_schema_parity_assert$
declare
  v_tables constant text[] := array[
    'project_locations',
    'projects',
    'project_location_points',
    'project_features',
    'project_floor_plans',
    'project_floor_plan_details',
    'project_delivery_items',
    'project_media',
    'project_videos'
  ];
  v_sequences constant text[] := array[
    'project_locations_id_seq',
    'projects_id_seq',
    'project_location_points_id_seq',
    'project_features_id_seq',
    'project_floor_plans_id_seq',
    'project_floor_plan_details_id_seq',
    'project_delivery_items_id_seq',
    'project_media_id_seq',
    'project_videos_id_seq'
  ];
  v_function_names constant text[] := array[
    'save_project_admin_entry',
    'delete_project_admin_entry',
    'validate_project_location_parent',
    'prevent_project_type_change',
    'validate_project_location_selection',
    'prevent_project_location_reparent'
  ];
  v_owner_oid oid;
  v_actual_count integer;
begin
  select role_record.oid
    into strict v_owner_oid
    from pg_catalog.pg_roles as role_record
   where role_record.rolname = current_user;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_class as relation
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = any (v_tables)
     and relation.relkind = 'r';

  if v_actual_count <> 9 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 9 tables; found %s.',
        v_actual_count
      );
  end if;

  if exists (
    select 1
      from pg_catalog.pg_class as relation
      join pg_catalog.pg_namespace as namespace
        on namespace.oid = relation.relnamespace
     where namespace.nspname = 'public'
       and relation.relname = any (v_tables)
       and relation.relkind = 'r'
       and relation.relowner <> v_owner_oid
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'A Project aggregate table is not owned by the clean migration owner.';
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_class as sequence_relation
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = sequence_relation.relnamespace
   where namespace.nspname = 'public'
     and sequence_relation.relname = any (v_sequences)
     and sequence_relation.relkind = 'S';

  if v_actual_count <> 9 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 9 identity sequences; found %s.',
        v_actual_count
      );
  end if;

  if exists (
    select 1
      from pg_catalog.pg_class as sequence_relation
      join pg_catalog.pg_namespace as namespace
        on namespace.oid = sequence_relation.relnamespace
     where namespace.nspname = 'public'
       and sequence_relation.relname = any (v_sequences)
       and sequence_relation.relkind = 'S'
       and sequence_relation.relowner <> v_owner_oid
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'A Project aggregate identity sequence is not owned by the clean migration owner.';
  end if;

  -- Every expected sequence must be the internal identity dependency of the
  -- matching table's generated-by-default id column.
  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_class as sequence_relation
    join pg_catalog.pg_namespace as sequence_namespace
      on sequence_namespace.oid = sequence_relation.relnamespace
    join pg_catalog.pg_depend as dependency
      on dependency.classid = 'pg_catalog.pg_class'::regclass
     and dependency.objid = sequence_relation.oid
     and dependency.objsubid = 0
     and dependency.refclassid = 'pg_catalog.pg_class'::regclass
     and dependency.deptype = 'i'
    join pg_catalog.pg_class as table_relation
      on table_relation.oid = dependency.refobjid
    join pg_catalog.pg_namespace as table_namespace
      on table_namespace.oid = table_relation.relnamespace
    join pg_catalog.pg_attribute as id_attribute
      on id_attribute.attrelid = table_relation.oid
     and id_attribute.attnum = dependency.refobjsubid
   where sequence_namespace.nspname = 'public'
     and table_namespace.nspname = 'public'
     and sequence_relation.relname = any (v_sequences)
     and table_relation.relname = any (v_tables)
     and sequence_relation.relname = table_relation.relname || '_id_seq'
     and sequence_relation.relowner = table_relation.relowner
     and id_attribute.attname = 'id'
     and id_attribute.attidentity = 'd';

  if v_actual_count <> 9 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 9 owned identity mappings; found %s.',
        v_actual_count
      );
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_attribute as attribute
    join pg_catalog.pg_class as relation on relation.oid = attribute.attrelid
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = any (v_tables)
     and relation.relkind = 'r'
     and attribute.attnum > 0
     and not attribute.attisdropped;

  if v_actual_count <> 114 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 114 columns; found %s.',
        v_actual_count
      );
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_constraint as constraint_record
    join pg_catalog.pg_class as relation
      on relation.oid = constraint_record.conrelid
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = any (v_tables)
     and relation.relkind = 'r';

  if v_actual_count <> 99 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 99 constraints; found %s.',
        v_actual_count
      );
  end if;

  if exists (
    select 1
      from pg_catalog.pg_constraint as constraint_record
      join pg_catalog.pg_class as relation
        on relation.oid = constraint_record.conrelid
      join pg_catalog.pg_namespace as namespace
        on namespace.oid = relation.relnamespace
     where namespace.nspname = 'public'
       and relation.relname = any (v_tables)
       and relation.relkind = 'r'
       and not constraint_record.convalidated
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'A Project clean-schema constraint is not validated.';
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_index as index_record
    join pg_catalog.pg_class as relation
      on relation.oid = index_record.indrelid
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = any (v_tables)
     and relation.relkind = 'r';

  if v_actual_count <> 44 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 44 indexes; found %s.',
        v_actual_count
      );
  end if;

  if exists (
    select 1
      from pg_catalog.pg_index as index_record
      join pg_catalog.pg_class as relation
        on relation.oid = index_record.indrelid
      join pg_catalog.pg_namespace as namespace
        on namespace.oid = relation.relnamespace
     where namespace.nspname = 'public'
       and relation.relname = any (v_tables)
       and relation.relkind = 'r'
       and (
         not index_record.indisvalid
         or not index_record.indisready
         or not index_record.indislive
       )
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'A Project clean-schema index is not valid, ready, and live.';
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_class as relation
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = any (v_tables)
     and relation.relkind = 'r'
     and relation.relrowsecurity
     and not relation.relforcerowsecurity;

  if v_actual_count <> 9 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected RLS enabled without FORCE on 9 tables; found %s.',
        v_actual_count
      );
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_policy as policy
    join pg_catalog.pg_class as relation on relation.oid = policy.polrelid
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = any (v_tables);

  if v_actual_count <> 0 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected no RLS policies; found %s.',
        v_actual_count
      );
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_trigger as trigger_record
    join pg_catalog.pg_class as relation
      on relation.oid = trigger_record.tgrelid
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = any (v_tables)
     and not trigger_record.tgisinternal;

  if v_actual_count <> 4 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 4 user triggers; found %s.',
        v_actual_count
      );
  end if;

  with expected(table_name, trigger_name, function_signature) as (
    values
      (
        'project_locations',
        'project_locations_validate_parent',
        'public.validate_project_location_parent()'
      ),
      (
        'projects',
        'projects_type_immutable',
        'public.prevent_project_type_change()'
      ),
      (
        'projects',
        'projects_validate_location_selection',
        'public.validate_project_location_selection()'
      ),
      (
        'project_locations',
        'project_locations_prevent_reparent',
        'public.prevent_project_location_reparent()'
      )
  )
  select count(*)::integer
    into v_actual_count
    from expected
    join pg_catalog.pg_class as relation
      on relation.relname = expected.table_name
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
     and namespace.nspname = 'public'
    join pg_catalog.pg_trigger as trigger_record
      on trigger_record.tgrelid = relation.oid
     and trigger_record.tgname = expected.trigger_name
     and not trigger_record.tgisinternal
     and trigger_record.tgenabled = 'O'
     and trigger_record.tgfoid = pg_catalog.to_regprocedure(
       expected.function_signature
     );

  if v_actual_count <> 4 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected all 4 named trigger bindings; found %s.',
        v_actual_count
      );
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_trigger as trigger_record
    join pg_catalog.pg_class as relation
      on relation.oid = trigger_record.tgrelid
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = relation.relnamespace
   where namespace.nspname = 'public'
     and relation.relname = 'project_locations'
     and trigger_record.tgname = any (array[
       'project_locations_validate_parent',
       'project_locations_prevent_reparent'
     ])
     and not trigger_record.tgisinternal
     and position(
       'is_active' in pg_catalog.pg_get_triggerdef(trigger_record.oid, true)
     ) > 0;

  if v_actual_count <> 2 then
    raise exception using
      errcode = 'P0001',
      message = 'Both Project location trigger definitions must include is_active.';
  end if;

  select count(*)::integer
    into v_actual_count
    from pg_catalog.pg_proc as procedure
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = procedure.pronamespace
   where namespace.nspname = 'public'
     and procedure.proname = any (v_function_names);

  if v_actual_count <> 6 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected exactly 6 aggregate function signatures; found %s.',
        v_actual_count
      );
  end if;

  with expected(signature, security_definer, returns_trigger) as (
    values
      ('public.save_project_admin_entry(bigint,jsonb)', true, false),
      ('public.delete_project_admin_entry(bigint)', true, false),
      ('public.validate_project_location_parent()', false, true),
      ('public.prevent_project_type_change()', false, true),
      ('public.validate_project_location_selection()', false, true),
      ('public.prevent_project_location_reparent()', false, true)
  )
  select count(*)::integer
    into v_actual_count
    from expected
    join pg_catalog.pg_proc as procedure
      on procedure.oid = pg_catalog.to_regprocedure(expected.signature)
    join pg_catalog.pg_namespace as namespace
      on namespace.oid = procedure.pronamespace
     and namespace.nspname = 'public'
    join pg_catalog.pg_language as language
      on language.oid = procedure.prolang
     and language.lanname = 'plpgsql'
   where procedure.proowner = v_owner_oid
     and procedure.prokind = 'f'
     and procedure.prosecdef = expected.security_definer
     and not procedure.proleakproof
     and procedure.provolatile = 'v'
     and procedure.proconfig = array[
       'search_path=pg_catalog, pg_temp'
     ]::text[]
     and (
       (
         expected.returns_trigger
         and procedure.prorettype = 'pg_catalog.trigger'::regtype
         and not procedure.proretset
       )
       or (
         not expected.returns_trigger
         and procedure.prorettype = 'pg_catalog.record'::regtype
         and procedure.proretset
       )
     );

  if v_actual_count <> 6 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected 6 safe function definitions; found %s.',
        v_actual_count
      );
  end if;

  with expected(
    client_key,
    level,
    parent_client_key,
    name_ar,
    name_en,
    sort_order,
    is_active
  ) as (
    values
      (
        'ca100000-0000-4000-8000-000000000001'::uuid,
        'governorate',
        null::uuid,
        U&'\0627\0644\0642\0627\0647\0631\0629',
        'Cairo',
        0,
        true
      ),
      (
        'ca100000-0000-4000-8000-000000000002'::uuid,
        'city',
        'ca100000-0000-4000-8000-000000000001'::uuid,
        U&'\0627\0644\0642\0627\0647\0631\0629\0020\0627\0644\062c\062f\064a\062f\0629',
        'New Cairo',
        0,
        true
      ),
      (
        'ca100000-0000-4000-8000-000000000003'::uuid,
        'main_area',
        'ca100000-0000-4000-8000-000000000002'::uuid,
        U&'\0627\0644\062a\062c\0645\0639\0020\0627\0644\062e\0627\0645\0633',
        'Fifth Settlement',
        0,
        true
      ),
      (
        'ca100000-0000-4000-8000-000000000004'::uuid,
        'sub_area',
        'ca100000-0000-4000-8000-000000000003'::uuid,
        U&'\0627\0644\062d\064a\0020\0627\0644\062b\0627\0646\064a',
        'Second District',
        0,
        true
      )
  )
  select count(*)::integer
    into v_actual_count
    from expected
    join public.project_locations as location
      on location.client_key = expected.client_key
    left join public.project_locations as parent
      on parent.id = location.parent_id
   where location.level = expected.level
     and parent.client_key is not distinct from expected.parent_client_key
     and location.name_ar = expected.name_ar
     and location.name_en = expected.name_en
     and location.sort_order = expected.sort_order
     and location.is_active = expected.is_active;

  if v_actual_count <> 4 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Project clean-schema parity expected the exact 4-row reference location chain; matched %s.',
        v_actual_count
      );
  end if;
end
$project_clean_schema_parity_assert$;

commit;
