import assert from "node:assert/strict";
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const MARKER = "// Generated by the existing public verification owner: R08 Preview fixture.\n";
const BRANCH = "codex/audit2-root-cause-closure";
const TARGETS = ["src/app/verification-cache-probe", "src/app/api/verification-cache-probe"] as const;

export function prepareVercelCacheProbe(options: { root?: string; env?: NodeJS.ProcessEnv; now?: number } = {}) {
  const root = realpathSync(resolve(options.root ?? ROOT)), env = options.env ?? process.env, now = options.now ?? Date.now();
  const templateRoot = resolve(root, "scripts/fixtures/vercel-cache-probe");
  const manifest = JSON.parse(readFileSync(resolve(templateRoot, "manifest.json"), "utf8")) as { publicKey: string; expiresAt: number; branch: string };
  assert.equal(manifest.branch, BRANCH);
  assert.ok(manifest.publicKey.startsWith("-----BEGIN PUBLIC KEY-----"));
  assert.ok(Number.isSafeInteger(manifest.expiresAt));
  const enabled = env.VERCEL === "1" && env.VERCEL_ENV === "preview" && env.VERCEL_TARGET_ENV === "preview" &&
    env.VERCEL_GIT_COMMIT_REF === BRANCH && /^[a-f0-9]{40}$/u.test(env.VERCEL_GIT_COMMIT_SHA ?? "") && now < manifest.expiresAt;
  const assertOwnedPath = (relative: string) => {
    let checked = root;
    for (const part of relative.split("/")) {
      checked = resolve(checked, part);
      assert.ok(checked.startsWith(root + sep));
      if (existsSync(checked)) assert.ok(!lstatSync(checked).isSymbolicLink(), "Generated paths may not cross symlinks.");
    }
  };
  for (const relative of TARGETS) {
    assertOwnedPath(relative);
    const target = resolve(root, relative);
    assert.ok(target.startsWith(root + sep));
    if (!existsSync(target)) continue;
    assert.ok(lstatSync(target).isDirectory() && !lstatSync(target).isSymbolicLink(), "Generated target must be an owned regular directory.");
    for (const file of readdirSync(target)) {
      const path = resolve(target, file);
      assert.ok(path.startsWith(target + sep) && lstatSync(path).isFile() && !lstatSync(path).isSymbolicLink());
      assert.ok(readFileSync(path, "utf8").startsWith(MARKER), "Refusing to remove a non-owned route.");
    }
    rmSync(target, { recursive: true });
  }
  if (!enabled) return { generated: false, reason: "Only the exact unexpired PR Preview may contain this verification fixture." };
  const inputs = [
    ["page.tsx", "src/app/verification-cache-probe/page.tsx"],
    ["actions.ts", "src/app/verification-cache-probe/actions.ts"],
    ["runtime.ts", "src/app/verification-cache-probe/runtime.ts"],
    ["route.ts", "src/app/api/verification-cache-probe/route.ts"],
  ];
  for (const [input, output] of inputs) {
    const content = readFileSync(resolve(templateRoot, input + ".template"), "utf8")
      .replaceAll("__PROBE_MANIFEST__", JSON.stringify(manifest));
    assertOwnedPath(output);
    const path = resolve(root, output);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, MARKER + content);
  }
  return { generated: true, branch: BRANCH, expiresAt: manifest.expiresAt, sourceHead: env.VERCEL_GIT_COMMIT_SHA, generatedFiles: inputs.map(([, output]) => output) };
}
