import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const MARKER = "// Generated by the existing public verification owner: R08 Preview fixture.\n";
const BRANCH = "codex/audit2-root-cause-closure";
const TARGETS = ["src/app/verification-cache-probe", "src/app/api/verification-cache-probe"] as const;

/** The Preview toolbar script is denied just like every foreign request; only its diagnostic classification differs. */
export function classifyVercelCacheProbeRequest(request: { url: string; method: string; resourceType: string }, deploymentOrigin: string) {
  let url: URL;
  try { url = new URL(request.url); } catch { return "unexpected-denied-foreign" as const; }
  if (url.origin === deploymentOrigin || url.protocol === "data:" || url.protocol === "blob:") return "allowed-owned-or-inline" as const;
  if (request.url === "https://vercel.live/_next-live/feedback/feedback.js" && request.method === "GET" && ["script", "fetch"].includes(request.resourceType)) {
    return "expected-denied-preview-feedback" as const;
  }
  return "unexpected-denied-foreign" as const;
}

/** Absence retains the baseline proof; the explicit flag selects the fixed deployment contract. */
export function parseVercelCacheProbeFenceMode(args: readonly string[]) {
  const matches = args.map((value, index) => ({ value, index })).filter(item => item.value.startsWith("--expect-fenced"));
  assert.ok(matches.length <= 1, "Duplicate fence mode flag.");
  if (matches.length === 0) return false;
  const match = matches[0];
  assert.equal(match.value, "--expect-fenced", "Fence mode is a fixed boolean flag.");
  assert.ok(args[match.index + 1] === undefined || args[match.index + 1].startsWith("--"), "Fence mode does not accept a value.");
  return true;
}

export function prepareVercelCacheProbe(options: { root?: string; env?: NodeJS.ProcessEnv; now?: number } = {}) {
  const root = realpathSync(resolve(options.root ?? ROOT)), env = options.env ?? process.env, now = options.now ?? Date.now();
  const templateRoot = resolve(root, "scripts/fixtures/vercel-cache-probe");
  const manifest = JSON.parse(readFileSync(resolve(templateRoot, "manifest.json"), "utf8")) as { publicKey: string; expiresAt: number; branch: string };
  assert.equal(manifest.branch, BRANCH);
  assert.ok(manifest.publicKey.startsWith("-----BEGIN PUBLIC KEY-----"));
  assert.ok(Number.isSafeInteger(manifest.expiresAt));
  const enabled = env.VERCEL === "1" && env.VERCEL_ENV === "preview" && env.VERCEL_TARGET_ENV === "preview" &&
    env.VERCEL_GIT_COMMIT_REF === BRANCH && /^[a-f0-9]{40}$/u.test(env.VERCEL_GIT_COMMIT_SHA ?? "") && now < manifest.expiresAt;
  const assertOwnedPath = (relative: string) => {
    let checked = root;
    for (const part of relative.split("/")) {
      checked = resolve(checked, part);
      assert.ok(checked.startsWith(root + sep));
      if (existsSync(checked)) assert.ok(!lstatSync(checked).isSymbolicLink(), "Generated paths may not cross symlinks.");
    }
  };
  for (const relative of TARGETS) {
    assertOwnedPath(relative);
    const target = resolve(root, relative);
    assert.ok(target.startsWith(root + sep));
    if (!existsSync(target)) continue;
    assert.ok(lstatSync(target).isDirectory() && !lstatSync(target).isSymbolicLink(), "Generated target must be an owned regular directory.");
    for (const file of readdirSync(target)) {
      const path = resolve(target, file);
      assert.ok(path.startsWith(target + sep) && lstatSync(path).isFile() && !lstatSync(path).isSymbolicLink());
      assert.ok(readFileSync(path, "utf8").startsWith(MARKER), "Refusing to remove a non-owned route.");
    }
    rmSync(target, { recursive: true });
  }
  if (!enabled) return { generated: false, reason: "Only the exact unexpired PR Preview may contain this verification fixture." };
  const readerSourceSha256 = createHash("sha256").update(readFileSync(resolve(templateRoot,"runtime.ts.template"),"utf8").replaceAll("\r\n","\n")).digest("hex");
  const inputs = [
    ["page.tsx", "src/app/verification-cache-probe/page.tsx"],
    ["actions.ts", "src/app/verification-cache-probe/actions.ts"],
    ["runtime.ts", "src/app/verification-cache-probe/runtime.ts"],
    ["route.ts", "src/app/api/verification-cache-probe/route.ts"],
  ];
  for (const [input, output] of inputs) {
    const content = readFileSync(resolve(templateRoot, input + ".template"), "utf8")
      .replaceAll("__PROBE_MANIFEST__", JSON.stringify(manifest))
      .replaceAll("__PROBE_SOURCE_SHA256__", readerSourceSha256);
    assertOwnedPath(output);
    const path = resolve(root, output);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, MARKER + content);
  }
  return { generated: true, branch: BRANCH, expiresAt: manifest.expiresAt, sourceHead: env.VERCEL_GIT_COMMIT_SHA, generatedFiles: inputs.map(([, output]) => output) };
}

/** Explicit independent Action request keeps transient SQL within its owned Vercel function. */
export function parseVercelCacheProbeReadTransport(args: readonly string[]) {
  const matches=args.map((value,index)=>({value,index})).filter(item=>item.value.startsWith("--read-after-action"));
  assert.ok(matches.length<=1,"Duplicate read transport flag.");
  if(matches.length===0)return "get" as const;
  assert.equal(matches[0].value,"--read-after-action","Read transport is a fixed boolean flag.");
  assert.ok(args[matches[0].index+1]===undefined || args[matches[0].index+1].startsWith("--"),"Read transport does not accept a value.");
  return "action" as const;
}
