import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {PGlite} from '@electric-sql/pglite';
import ts from 'typescript';
import {loadCoreQueryPresentationPlan,registeredEntityKeys,coreQueryScenario} from './fixtures/admin-core-query-presentation-plan.mjs';
import {assertCoreQueryProjection,assertCoreQueryLocation} from './fixtures/admin-core-query-presentation-journeys.mjs';
import {parseAdminEntityListRequestQuery} from '../src/lib/admin/entity-list/data-engine/contracts.ts';
import type {OwnedLocalHandle} from './lib/isolated-supabase.mts';
import type {CoreQueryFixtures} from './verify-admin-core-query-presentation-isolated.mts';
const require=createRequire(import.meta.url),db=new PGlite(),plan=await loadCoreQueryPresentationPlan();
const statements:string[]=[];let active=true,scopes=0;
const query=async(sql:string,values?:unknown[])=>{assert.ok(active);statements.push(sql);const result=await db.query<Record<string,unknown>>(sql,values);return {rows:result.rows,rowCount:result.rows.length};};
const handle={identity:{runId:'a'.repeat(32)},withDatabaseConnection:async<T,>(work:(connection:{query:typeof query})=>Promise<T>)=>{assert.ok(active);scopes++;try{return await work({query});}finally{scopes--;}}} as unknown as OwnedLocalHandle;
const isolated={assertOwnedLocalHandle:(candidate:unknown)=>{assert.ok(active);assert.equal(candidate,handle);}};
function compiledOwner(file:string,ports:Record<string,unknown>){const source=readFileSync(resolve(import.meta.dirname,file),'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const target={exports:{}};new Function('require','module','exports',output)((name:string)=>{if(name in ports)return ports[name];assert.equal(name,'node:assert/strict');return require(name);},target,target.exports);return target.exports;}
const actor=compiledOwner('verify-admin-core-domain-readback-isolated.mts',{'./lib/isolated-supabase.mts':isolated});
const makeOwner=()=>compiledOwner('verify-admin-core-query-presentation-isolated.mts',{'./lib/isolated-supabase.mts':isolated,'./verify-admin-core-domain-readback-isolated.mts':actor,'../src/lib/admin/entity-list/data-engine/contracts.ts':{parseAdminEntityListRequestQuery},'./fixtures/admin-core-query-presentation-plan.mjs':{loadCoreQueryPresentationPlan,coreQueryScenario}}) as typeof import('./verify-admin-core-query-presentation-isolated.mts');
const owner=makeOwner();
const fixtures:CoreQueryFixtures={queryClosure:{contexts:{}}};let id=100;
const checks:string[]=[];const test=async(name:string,callback:()=>void|Promise<void>)=>{await callback();checks.push(name);};
const request=(routeKey='topics',scenario='first')=>({id:randomUUID(),kind:'query-presentation-state',routeKey,scenario});
const read=(routeKey='topics',scenario='first')=>owner.readCoreQueryPresentationCheckpoint(handle,request(routeKey,scenario),fixtures);
try{
 const tables=new Map<string,Set<string>>();for(const spec of plan){const names=tables.get(spec.table)??new Set(['id','status','deleted_at','image','content_type','is_active','is_visible','publication_status','entity_type','type','level','project_id','stage_id','item_id','path','slug']);names.add(spec.labelColumn);names.add(spec.sortField);tables.set(spec.table,names);}
 for(const[table,names]of tables){if(table==='admin_users')for(const name of ['username','email','role'])names.add(name);const declaration=[...names].map(name=>'"'+name+'" '+(name==='id'?'bigint primary key':name.endsWith('_id')?'bigint':name==='is_active'||name==='is_visible'?'boolean':name.endsWith('_at')?'timestamptz':'text')).join(',');await db.exec(`create table public.${table}(${declaration});`);}
 await db.exec("insert into public.admin_users(id,username,email,role,is_active) values(7,'qa_admin_interaction','qa-admin-interaction@example.invalid','admin',true);create table public.admin_user_preferences(admin_user_id bigint,view_key text,preferences jsonb);");
 for(const spec of plan){const search='qa-b1-control-'+spec.key.replaceAll('_','-')+'-rows',ids:number[]=[];const f={search,ids,...(spec.kind?{projectId:99}:{}),...(spec.kind==='items'?{stageId:98}:{}),...(spec.kind==='updates'?{itemId:97}:{})};fixtures.queryClosure.contexts[spec.key]=f;
  for(let i=0;i<spec.rowCount;i++){
   const row:Record<string,unknown>={id:++id,[spec.labelColumn]:search+' '+String(Math.floor(i/2)).padStart(3,'0'),status:spec.entity==='redirects'?(i%2===0?'active':'inactive'):(i%2===0?'published':'unpublished'),image:spec.entity==='topics_without_image'?'':'image',content_type:i%2===0?'article':'news',is_active:i%2===0,is_visible:i%2===0,publication_status:spec.kind==='updates'?(i%2===0?'unpublished':'draft'):(i%2===0?'published':'unpublished'),entity_type:i%2===0?'topic':'page',type:spec.type,level:spec.level,project_id:99,stage_id:98,item_id:97,path:'/qa/'+id,slug:'qa-'+id};
   if(spec.sortField.endsWith('_at'))row[spec.sortField]=new Date(Date.UTC(2026,0,3,0,Math.floor(i/2))).toISOString();
   const keys=Object.keys(row);await db.query(`insert into public.${spec.table}(${keys.map(key=>'"'+key+'"').join(',')}) values(${keys.map((_,index)=>'$'+(index+1)).join(',')})`,Object.values(row));ids.push(id);
  }
 }
 await test('Exact current registry and manifest route contexts derive the page-sized fixture bound',()=>{assert.equal(plan.length,17);assert.equal(new Set(plan.map(spec=>spec.consumerId)).size,13);assert.equal(new Set(plan.map(spec=>spec.entity)).size,16);for(const spec of plan)assert.equal(spec.rowCount,2*Math.min(...spec.contract.pageSizeOptions)+3);});
 await test('Current canonical Browser URL contract matches the native requested page',async()=>{const spec=plan.find(r=>r.key==='topics')!,receipt=await read('topics','second');assertCoreQueryLocation(spec,fixtures.queryClosure.contexts.topics,receipt,'http://127.0.0.1:31001'+receipt.route+'?'+receipt.query,'http://127.0.0.1:31001');});
 await test('Wrong URL query, sort, filter, page, size or origin cannot satisfy a matching row projection',async()=>{const spec=plan.find(r=>r.key==='topics')!,receipt=await read('topics','second');for(const[key,value]of [['q','different'],['sort','title_desc'],['status','unpublished'],['page','3'],['limit','20']]){const params=new URLSearchParams(receipt.query);params.set(key,value);assert.throws(()=>assertCoreQueryLocation(spec,fixtures.queryClosure.contexts.topics,receipt,'http://127.0.0.1:31001'+receipt.route+'?'+params,'http://127.0.0.1:31001'));}assert.throws(()=>assertCoreQueryLocation(spec,fixtures.queryClosure.contexts.topics,receipt,'http://127.0.0.1:31002'+receipt.route+'?'+receipt.query,'http://127.0.0.1:31001'));});
 await test('Actual AST registry reader rejects nonobject and unknown spread ownership',()=>{assert.throws(()=>registeredEntityKeys('export const adminEntityListAdapterRegistry = other;'));assert.throws(()=>registeredEntityKeys('export const adminEntityListAdapterRegistry = {...other};'));});
 for(const spec of plan)await test('Native ordered pages, union, filter and clamp: '+spec.key,async()=>{
  const first=await read(spec.key),second=await read(spec.key,'second'),third=await read(spec.key,'third');assert.equal(first.actorId,7);assert.deepEqual([...first.expectedIds,...second.expectedIds,...third.expectedIds],first.completeIds);assert.equal(new Set(first.completeIds).size,spec.rowCount);
  const clamp=await read(spec.key,'clamp');assert.deepEqual(clamp.expectedIds,third.expectedIds);assert.equal(clamp.pagination.page,3);
  const empty=await read(spec.key,'empty');assert.deepEqual(empty.expectedIds,[]);assert.equal(empty.pagination.totalRows,0);
  const wide=await read(spec.key,'wide');assert.ok(wide.expectedIds.length>first.expectedIds.length);
  const descending=await read(spec.key,'descending');assert.notDeepEqual(descending.expectedIds,first.expectedIds);assert.deepEqual([...descending.completeIds].sort((a,b)=>a-b),[...first.completeIds].sort((a,b)=>a-b));
  if(spec.filter){const filtered=await read(spec.key,'filtered');assert.ok(filtered.completeIds.length>0&&filtered.completeIds.length<first.completeIds.length,spec.key+JSON.stringify({filtered:filtered.completeIds.length,total:first.completeIds.length}));}
  assert.equal(statements.at(-1),'commit');assert.equal(scopes,0);
 });
 await test('Browser projection rejects wrong ordering, count, clamp and duplicated API IDs',async()=>{const first=await read();const payload={rows:first.expectedIds.map(id=>({id})),pagination:first.pagination};assertCoreQueryProjection(first,payload);for(const candidate of [{...payload,rows:[...payload.rows].reverse()},{...payload,pagination:{...payload.pagination,totalRows:999}},{...payload,pagination:{...payload.pagination,page:3}},{...payload,rows:[payload.rows[0],...payload.rows.slice(0,-1)]}])assert.throws(()=>assertCoreQueryProjection(first,candidate));});
 await test('Unregistered selector, caller SQL/IDs, actor or scenario rejects before SQL',async()=>{for(const patch of [{sql:'select 1'},{ids:[1]},{actorId:8},{routeKey:'auth.users'},{routeKey:'projects'},{scenario:'execute'},{kind:'query'},{id:'x;delete'}]){const before=statements.length;await assert.rejects(owner.readCoreQueryPresentationCheckpoint(handle,{...request(),...patch},fixtures));assert.equal(statements.length,before);}});
 await test('Fixture object substitution and duplicated fixture identity deny new binding',async()=>{const before=statements.length;await assert.rejects(owner.readCoreQueryPresentationCheckpoint(handle,request(),structuredClone(fixtures)));assert.equal(statements.length,before);});
 await test('Native unexpected matching row invalidates complete-set proof and rolls back',async()=>{await db.query("insert into public.topics(id,title) values(9999,$1)",[fixtures.queryClosure.contexts.topics.search+' foreign']);await assert.rejects(read());assert.equal(statements.at(-1),'rollback');await db.exec('delete from public.topics where id=9999');});
 await test('Native domain mutation invalidates its preserved fingerprint',async()=>{const target=fixtures.queryClosure.contexts.topics.ids[0];await db.query("update public.topics set status='unpublished' where id=$1",[target]);await assert.rejects(read());assert.equal(statements.at(-1),'rollback');await db.query("update public.topics set status='published' where id=$1",[target]);});
 await test('Exact fixed QA identity and inactive/missing actor are rejected',async()=>{await db.exec("update public.admin_users set is_active=false where id=7");await assert.rejects(read());assert.equal(statements.at(-1),'rollback');await db.exec("update public.admin_users set is_active=true where id=7");});
 await test('Preference reads are actor/view bound; unrelated preference cannot satisfy persistence',async()=>{await db.query('insert into public.admin_user_preferences values(8,$1,$2::jsonb)',['content-topics',JSON.stringify({visibleColumns:['wrong']})]);assert.equal((await read('topics','preferences')).preference,null);await db.query('insert into public.admin_user_preferences values(7,$1,$2::jsonb)',['content-topics',JSON.stringify({visibleColumns:['title','status']})]);assert.deepEqual((await read('topics','preferences')).preference,{visibleColumns:['title','status']});});
 await test('Expired owner is rejected before any read or scope',async()=>{active=false;const before=statements.length;await assert.rejects(read());assert.equal(statements.length,before);assert.equal(scopes,0);active=true;});

 const finalOwner=makeOwner();await db.exec('delete from public.admin_user_preferences where admin_user_id=7');
 const outcomes:Record<string,unknown>[]=[],evidence:Record<string,unknown>[]=[];
 for(const spec of plan){
  const sequence=['first','empty','second','third','clamp','wide','descending',...(spec.filter?['filtered']:[]),'preferences','preferences','first'],nativeCheckpointIds:string[]=[];let pref=0;
  for(const scenario of sequence){
   if(scenario==='preferences'){pref++;await db.query('delete from public.admin_user_preferences where admin_user_id=7 and view_key=$1',[spec.viewKey]);await db.query('insert into public.admin_user_preferences values(7,$1,$2::jsonb)',[spec.viewKey,JSON.stringify({visibleColumns:pref===1?['title']:['title','status']})]);}
   const receipt=await finalOwner.readCoreQueryPresentationCheckpoint(handle,request(spec.key,scenario),fixtures);nativeCheckpointIds.push(receipt.id);
  }
  const outcome={routeKey:spec.key,consumerId:spec.consumerId,entity:spec.entity,nativeActorId:7,nativeCheckpointIds,optionalColumn:{key:'status',persistedAndReloaded:true,semanticBaselineRestored:true,physicalInitialAbsenceRestored:false},querySearchEmptyNonempty:true,backAndReload:true,outOfRangeClamped:true,pageSizeChanged:true,domainFingerprintUnchanged:true,pageUnion:spec.rowCount,rowEvidence:[],remaining:['No Browser claim from controlled aggregate'],sortBoundary:'controlled',filterBoundary:'controlled'};
  outcomes.push(outcome);evidence.push({...outcome,id:'core-query-presentation-'+spec.key,status:'pass'});
 }
 const browser={status:'pass',driverCompleted:true,inventoryOnly:false,cohort:'query-presentation',errors:[],queryPresentation:{status:'pass',outcomes},evidence};
 await test('Strict aggregate joins every current route and all186 successful same-handle native checkpoints',()=>{const joined=finalOwner.verifyCoreQueryPresentationCompletion(handle,browser);assert.equal(joined.contexts,plan.length);assert.equal(joined.nativeCheckpoints,186);assert.equal(joined.actorId,7);assert.deepEqual(joined.automaticCoverage,[]);assert.equal(joined.globalClosed,false);});
 for(const [name,change]of [
  ['failed-browser',(v:typeof browser)=>{v.status='fail';}],['unfinished-driver',(v:typeof browser)=>{v.driverCompleted=false;}],['inventory-only',(v:typeof browser)=>{v.inventoryOnly=true;}],['wrong-cohort',(v:typeof browser)=>{v.cohort='other';}],['missing-route',(v:typeof browser)=>{v.queryPresentation.outcomes.pop();}],['duplicate-route',(v:typeof browser)=>{v.queryPresentation.outcomes.push(v.queryPresentation.outcomes[0]);}],['missing-pass-receipt',(v:typeof browser)=>{v.evidence.shift();}],['duplicate-mixed-status-receipt',(v:typeof browser)=>{v.evidence.push({...v.evidence[0],status:'fail'});}],['failed-receipt',(v:typeof browser)=>{v.evidence[0].status='fail';}],
  ['invented-native-id',(v:typeof browser)=>{(v.queryPresentation.outcomes[0].nativeCheckpointIds as string[])[0]=randomUUID();}],['duplicate-native-id',(v:typeof browser)=>{const ids=v.queryPresentation.outcomes[0].nativeCheckpointIds as string[];ids[1]=ids[0];}],['out-of-order-native',(v:typeof browser)=>{const ids=v.queryPresentation.outcomes[0].nativeCheckpointIds as string[];[ids[1],ids[2]]=[ids[2],ids[1]];}],['wrong-positive-actor',(v:typeof browser)=>{v.queryPresentation.outcomes[0].nativeActorId=8;}],['missing-planned-scenario',(v:typeof browser)=>{(v.queryPresentation.outcomes[0].nativeCheckpointIds as string[]).pop();}],
 ]as const)await test('Aggregate rejects '+name,()=>{const changed=structuredClone(browser);change(changed);if(name.includes('native')||name==='wrong-positive-actor'||name==='missing-planned-scenario')Object.assign(changed.evidence[0],changed.queryPresentation.outcomes[0]);assert.throws(()=>finalOwner.verifyCoreQueryPresentationCompletion(handle,changed));});
 await test('Same native request ID cannot be reused to fabricate another scenario',async()=>{const id=(outcomes[0].nativeCheckpointIds as string[])[0],before=statements.length;await assert.rejects(finalOwner.readCoreQueryPresentationCheckpoint(handle,{...request(),id},fixtures));assert.equal(statements.length,before);});
 await test('Unjoined extra native checkpoint denies aggregate completion',async()=>{await finalOwner.readCoreQueryPresentationCheckpoint(handle,request(),fixtures);assert.throws(()=>finalOwner.verifyCoreQueryPresentationCompletion(handle,browser));});
 console.log(JSON.stringify({status:'pass',checks:checks.length,records:checks,scope:'Actual native-reader SQL in PGlite and actual projection/plan functions; controlled lifecycle ports. No Browser/native PostgREST fixture proof claimed.'},null,2));
}finally{await db.close();}
