import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { PGlite } from "@electric-sql/pglite";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MIGRATION =
  "sql/migrations/20260814020742_projects_domain_hardening.sql";
const MIGRATION_NAME = MIGRATION.split("/").at(-1)!;

const read = (path: string) =>
  readFileSync(join(ROOT, path), "utf8").replace(/\r\n?/g, "\n");

let passed = 0;
function check(label: string, condition: unknown) {
  assert.ok(condition, label);
  passed += 1;
  console.log(`PASS ${label}`);
}

check("Projects Domain hardening migration exists", existsSync(join(ROOT, MIGRATION)));
const migration = read(MIGRATION);

check(
  "migration removes only the obsolete Project code uniqueness contract",
  migration.includes("drop index if exists public.projects_code_unique_idx") &&
    !/drop\s+(table|column)|\bcascade\b/i.test(
      migration.replace(/--[^\n]*/g, ""),
    ),
);
check(
  "migration declares project_id as the sole Project identity",
  migration.includes("public.projects.id is not the sole primary key") &&
    migration.includes("All Project Domain relationships use project_id"),
);
check(
  "migration keeps Project code as a formatted presentation label",
  migration.includes("Required user-visible Project label") &&
    !migration.includes("alter column code drop not null") &&
    !migration.includes("drop constraint if exists projects_code_format_check"),
);
check(
  "migration refuses relationship drift instead of cascading it away",
  migration.includes("relationship targets a Project column other than project_id") &&
    migration.includes("a Project Domain relation stores project_code"),
);

const db = await PGlite.create();
try {
  await db.exec(`
    create table public.projects (
      id bigint generated by default as identity primary key,
      code text not null constraint projects_code_format_check
        check (code ~ '^[A-Z0-9]+(?:-[A-Z0-9]+)*$')
    );
    create unique index projects_code_unique_idx
      on public.projects (upper(code));
    create table public.project_media (
      id bigint generated by default as identity primary key,
      project_id bigint not null references public.projects(id) on delete cascade
    );
    create function public.duplicate_project_admin_entry(bigint)
    returns void language sql as 'select';
    insert into public.projects (code) values ('LABEL-A');
  `);

  await db.exec(migration);

  const duplicate = await db.query<{ id: number }>(
    "insert into public.projects (code) values ('LABEL-A') returning id",
  );
  check(
    "duplicate Project labels are accepted and receive different project_id identities",
    duplicate.rows.length === 1 && Number(duplicate.rows[0]?.id) === 2,
  );

  const identity = await db.query<{
    primary_columns: string[];
    non_id_relationships: number;
    code_unique_indexes: number;
    id_comment: string;
    code_comment: string;
  }>(`
    select
      array(
        select attribute.attname
          from pg_constraint primary_key
          cross join lateral unnest(primary_key.conkey) column_number(attnum)
          join pg_attribute attribute
            on attribute.attrelid = primary_key.conrelid
           and attribute.attnum = column_number.attnum
         where primary_key.conrelid = 'public.projects'::regclass
           and primary_key.contype = 'p'
         order by column_number.attnum
      ) as primary_columns,
      (
        select count(*)::integer
          from pg_constraint relationship
          cross join lateral unnest(relationship.confkey) referenced_column(attnum)
          join pg_attribute attribute
            on attribute.attrelid = relationship.confrelid
           and attribute.attnum = referenced_column.attnum
         where relationship.contype = 'f'
           and relationship.confrelid = 'public.projects'::regclass
           and attribute.attname <> 'id'
      ) as non_id_relationships,
      (
        select count(*)::integer
          from pg_index index_record
         where index_record.indrelid = 'public.projects'::regclass
           and index_record.indisunique
           and pg_get_indexdef(index_record.indexrelid) ~* '\\mcode\\M'
      ) as code_unique_indexes,
      col_description('public.projects'::regclass, 1) as id_comment,
      col_description('public.projects'::regclass, 2) as code_comment
  `);
  const proof = identity.rows[0];
  check(
    "database catalog exposes only projects.id as Project identity",
    JSON.stringify(proof?.primary_columns) === JSON.stringify(["id"]) &&
      Number(proof?.non_id_relationships) === 0 &&
      Number(proof?.code_unique_indexes) === 0,
  );
  check(
    "database comments preserve the identity and label contracts",
    proof?.id_comment?.includes("sole Project identity") === true &&
      proof?.code_comment?.includes("not an identity") === true,
  );
} finally {
  await db.close();
}

const invalidDb = await PGlite.create();
try {
  await invalidDb.exec(`
    create table public.projects (
      id bigint generated by default as identity primary key,
      code text not null unique
    );
    create unique index projects_code_unique_idx
      on public.projects (upper(code));
    create table public.project_legacy_relation (
      id bigint generated by default as identity primary key,
      project_code text not null references public.projects(code)
    );
  `);
  await assert.rejects(
    invalidDb.exec(migration),
    /relationship targets a Project column other than project_id/i,
  );
  passed += 1;
  console.log("PASS migration rejects a relationship that targets Project code");
} finally {
  await invalidDb.close();
}

function sourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return sourceFiles(path);
    return /\.(?:ts|tsx)$/i.test(entry.name) ? [path] : [];
  });
}

const activeProjectSources = [
  "src/app/admin/projects",
  "src/lib/admin/projects",
  "src/lib/projects",
].flatMap((directory) => sourceFiles(join(ROOT, directory)));
const identityLookupPattern =
  /(?:\.eq\(\s*["']code["']|\bp_project_code\b|\bwhere\s+(?:public\.)?projects?\.code\s*=)/i;
const activeIdentityDrift = activeProjectSources.filter((path) =>
  identityLookupPattern.test(readFileSync(path, "utf8")),
);
check(
  "active Project runtimes do not resolve Project identity by code",
  activeIdentityDrift.length === 0,
);

const futureSqlDrift = readdirSync(join(ROOT, "sql", "migrations"))
  .filter((name) => name.endsWith(".sql") && name > MIGRATION_NAME)
  .filter((name) => {
    const sql = read(`sql/migrations/${name}`);
    return /\bproject_code\b|references\s+(?:public\.)?projects\s*\(\s*code\s*\)|create\s+unique\s+index[\s\S]{0,240}\bprojects\b[\s\S]{0,240}\bcode\b/i.test(
      sql,
    );
  });
check(
  "later migrations do not reintroduce Project code identity or relationships",
  futureSqlDrift.length === 0,
);

console.log(`Project Domain identity verification passed (${passed} checks).`);
