import{isCoreMediaSelection}from'./fixtures/admin-core-media-journeys.mjs';
import{CORE_MEDIA_RECOVERY_FOLLOWUP_SELECTION}from'./fixtures/admin-core-media-recovery-journeys.mjs';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {assertCoreContentDraftReadReceipt,assertCoreHeroReopenReadReceipt,assertCoreHeroReadActionBinding,assertCoreHeroReadActionRequest} from './fixtures/admin-core-form-draft-restoration.mjs';
import {selectCoreLinkPreviewAction} from './fixtures/admin-core-template-library-presentation-journeys.mjs';
import {CORE_PRESENTATION_HERO_SELECTION,CORE_PRESENTATION_SCROLL_SELECTION,corePresentationSelectedKinds,corePresentationSelectedIds,assertCorePresentationSelectionReceipt} from "./fixtures/admin-core-presentation-controls-contract.mjs";
import {assertCoreHeroPendingRequestSemantics,assertPresentationAcceptedDiscardReceipts,partitionPresentationDiscardNativeRecords} from './fixtures/admin-core-presentation-controls-contract.mjs';
import {assertCoreRenderedAdoptionJoin} from './fixtures/admin-core-rendered-adoption.mjs';
import {join} from 'node:path';
import {partitionContentScrollNativeRecords} from './fixtures/admin-core-presentation-controls-contract.mjs';
import assert from "node:assert/strict";
import {randomUUID,createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {createRequire} from "node:module";
import {createJiti} from "jiti";
import ts from "typescript";
import * as React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {assertContentScrollFingerprints,assertContentScrollReceipt,validateContentScrollFixture,PRESENTATION_CONTROL_KINDS,PRESENTATION_CONTROL_PHASES,PRESENTATION_CONTROL_ASSETS,buildCorePresentationControlsPlan,validatePresentationControlsRequest,presentationControlForm,loadPresentationControlBuilders,assertPresentationControlsConfig,assertPresentationControlsRow} from "./fixtures/admin-core-presentation-controls-contract.mjs";
const root=resolve(import.meta.dirname,".."),jiti=createJiti(import.meta.url,{fsCache:false,moduleCache:false,alias:{"server-only":resolve(root,"node_modules/next/dist/compiled/server-only/empty.js")}});
const{ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST:manifest}=await jiti.import<typeof import("../src/lib/admin/form-system/adoption-manifest.ts")>(resolve(root,"src/lib/admin/form-system/adoption-manifest.ts"));
const fixtures={templates:PRESENTATION_CONTROL_KINDS.map((kind,index)=>({kind,id:index+1,name:"QA "+kind,slug:"qa-admin-page-interaction-"+kind+"-8",editPath:"/admin/pages-blocks/blocks/"+kind+"/"+(index+1)})),assets:PRESENTATION_CONTROL_ASSETS.map(objectKey=>({objectKey,publicUrl:"/"+objectKey}))};
const cases:string[]=[],test=(name:string,run:()=>unknown)=>{run();cases.push(name);};const builders=await loadPresentationControlBuilders();
test("Actual current Form manifest resolves only two concrete edit surfaces without axis promotion",()=>{const plan=buildCorePresentationControlsPlan({manifest,fixtures});assert.equal(plan.recipes.length,2);assert.ok(plan.recipes.every((row:{coverage:unknown[]})=>row.coverage.length===0));assert.deepEqual(plan.automaticAxisCoverage,[]);assert.equal(plan.globalClosed,false);assert.equal(plan.nonCapabilities.length,3);});
test("Missing current Hero adopter rejects",()=>assert.throws(()=>buildCorePresentationControlsPlan({manifest:manifest.filter(row=>!("registryModuleKind" in row)||row.registryModuleKind!=="hero"),fixtures})));
for(const delta of[{templates:fixtures.templates.slice(1)},{templates:[...fixtures.templates,fixtures.templates[0]]},{templates:fixtures.templates.map((row,index)=>index?row:{...row,slug:"real-template"})},{templates:fixtures.templates.map((row,index)=>index?row:{...row,id:0})},{templates:fixtures.templates.map((row,index)=>index?row:{...row,editPath:"/admin"})},{assets:fixtures.assets.map((row,index)=>index?row:{...row,publicUrl:"https://foreign.invalid"})}])test("Reject unowned fixture "+cases.length,()=>assert.throws(()=>buildCorePresentationControlsPlan({manifest,fixtures:{...fixtures,...delta}})));
const request={id:randomUUID(),kind:"presentation-controls-state",recipe:"hero",phase:"baseline"};test("Fixed twelve native phase requests",()=>{for(const recipe of PRESENTATION_CONTROL_KINDS)for(const phase of PRESENTATION_CONTROL_PHASES)validatePresentationControlsRequest({...request,recipe,phase});});
for(const delta of[{sql:"select 1"},{expected:{}},{table:"hero_templates"},{recipe:"__proto__"},{recipe:"constructor"},{phase:"skip"},{id:"bad"}])test("Reject arbitrary checkpoint "+JSON.stringify(delta),()=>assert.throws(()=>validatePresentationControlsRequest({...request,...delta})));
for(const kind of PRESENTATION_CONTROL_KINDS){
 const form=presentationControlForm(kind,fixtures),config=builders.build(kind,form);
 test("Actual private pure config builder round trip: "+kind,()=>assertPresentationControlsConfig(kind,config,fixtures));
 for(const key of["title","showTitle","titleBold","titleAlignment",...(kind==="hero"?["images","mobileImages","primaryCtaLink","secondaryCtaLink","imageComposition"]:["body"])])test("Native projection rejects missing authored "+kind+":"+key,()=>{const broken=structuredClone(config);delete broken[key];assert.throws(()=>assertPresentationControlsConfig(kind,broken,fixtures));});
 const original={id:kind==="hero"?1:2,name:"QA "+kind,slug:"qa-admin-page-interaction-"+kind+"-8",status:"published",variant:kind==="hero"?"internal-page":null,style_preset:null,description:null,created_at:"2026-01-01",updated_at:"2026-01-01",config:{title:"original"},...(kind==="hero"?{source_type:"manual",source_id:null,source_slug:null,limit_count:1,is_visible:true}:{}),other_identity:"retained"};
 const saved={...original,config,updated_at:"2026-01-02",variant:original.variant||"default",style_preset:kind==="hero"?"cinematic-gold":"premium-dark"};
 test("Exact current Action default normalization, identity preserved: "+kind,()=>assertPresentationControlsRow(kind,saved,original,config));
 for(const key of["id","slug","name","status","created_at","other_identity","config"])test("Native full row comparison rejects unrelated drift "+kind+":"+key,()=>assert.throws(()=>assertPresentationControlsRow(kind,{...saved,[key]:"changed"},original,config)));
}
test("Actual Hero builder stores cleared secondary CTA as null rather than a fabricated none object",()=>{const config=builders.build("hero",presentationControlForm("hero",fixtures));assert.equal(config.secondaryCtaLink,null);});
test("Current internal Hero forces canonical order; this journey does not claim editable element order",()=>{const form=presentationControlForm("hero",fixtures);form.set("hero_element_order","cta,title");assert.deepEqual(builders.build("hero",form).heroElementOrder,["eyebrow","title","highlight","subtitle","description","cta"]);});
const utils=await jiti.import<typeof import("../src/lib/page-blocks/admin-utils.ts")>(resolve(root,"src/lib/page-blocks/admin-utils.ts"));
for(const[kind,name]of [["hero","updateHeroTemplateDetails"],["content","updateContentBlock"]]){
 const file=resolve(root,"src/app/admin/pages-blocks/blocks",kind,"actions.ts"),source=readFileSync(file,"utf8"),tree=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true);const fn=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name);assert.ok(fn&&ts.isFunctionDeclaration(fn)&&fn.body);
 const firstGuard=fn.body.statements.findIndex(node=>ts.isIfStatement(node));assert.ok(firstGuard>0);const prefix=fn.body.statements.slice(0,firstGuard+1).map(node=>node.getText(tree)).join("\n");assert.doesNotMatch(prefix,/getSupabaseAdmin|mutatePageComposition|coordinateMedia/u);
 const code=ts.transpileModule("async function guard(formData:FormData){"+prefix+"}",{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 const guard=new Function("requireAdminSession","parseNumber","cleanText","slugify",code+";return guard;")(async()=>({id:99}),utils.parseNumber,utils.cleanText,utils.slugify) as (form:FormData)=>Promise<void>;
 const form=new FormData();form.set("id","1");form.set("slug","qa-valid");form.set("name","");await assert.rejects(guard(form));cases.push("Actual Action prewrite missing-name guard: "+kind);
 form.set("name","QA valid");await guard(form);cases.push("Actual Action prewrite guard permits canonical retry: "+kind);
}
// Render the actual shared formatting owner with actual leaf controls. Only CSS is stubbed.
const ownerFile=resolve(root,"src/components/admin/page-blocks/ModuleEditorPresentation.tsx"),ownerSource=readFileSync(ownerFile,"utf8"),tree=ts.createSourceFile(ownerFile,ownerSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const owner=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="ModuleEditorVisibilityAlignRow");assert.ok(owner);const ownerCode=ts.transpileModule(owner.getText(tree).replace(/^export /,""),{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
const leaf=(name:string)=>{const filename=resolve(root,"src/components/admin/ui",name+".tsx"),compiled=ts.transpileModule(readFileSync(filename,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const loaded={exports:{}};new Function("require","module","exports",compiled)(createRequire(import.meta.url),loaded,loaded.exports);return (loaded.exports as {default:React.ComponentType}).default;};
const Switch=leaf("AdminFormSwitch"),Format=leaf("AdminTextFormatControls");
const Row=new Function("React","useState","Children","AdminFormSwitch","AdminTextFormatControls","MODULE_EDITOR_CONTROL_CARD_CLASS_NAME",ownerCode+";return ModuleEditorVisibilityAlignRow;")(React,React.useState,React.Children,Switch,Format,"") as React.ComponentType<Record<string,unknown>>;
for(const mirrored of[false,true])test("Actual rendered "+(mirrored?"two mirrored CTA":"single text")+" toolbars retain one submitted format tuple",()=>{const html=renderToStaticMarkup(React.createElement(Row,{label:"QA",alignmentName:"cta_alignment",showName:"show_cta",boldName:"cta_bold",alignmentDefault:"center",showDefault:false,boldDefault:true,controlsPlacement:mirrored?"cards":"header"},React.createElement("div",{key:"a"},"A"),...(mirrored?[React.createElement("div",{key:"b"},"B")]:[])));for(const name of["show_cta","cta_alignment","cta_bold"])assert.equal(html.split('name="'+name+'"').length-1,1);assert.equal(html.split('role="switch"').length-1,mirrored?2:1);assert.equal(html.split('data-admin-text-format-bold=""').length-1,mirrored?2:1);assert.match(html,/name="show_cta" value="false"/u);assert.match(html,/name="cta_alignment" value="center"/u);});
const browser=readFileSync(resolve(root,"scripts/fixtures/admin-core-presentation-controls-journeys.mjs"),"utf8");test("No alternate interception, direct HTTP, hidden mutations, forced clicks or capability promotion",()=>{assert.doesNotMatch(browser,/page\.(route|unroute|request)|force:\s*true|\.selectOption\(|dispatchEvent\(/u);assert.match(browser,/nativeFinalityRequired:true/u);assert.match(browser,/fieldset\[data-admin-form-fields\]/u);assert.doesNotMatch(browser,/data-admin-form-pending-fields/u);assert.match(browser,/actualStatementCancelled:cancel/u);});
const scrollFixture={id:11,name:'QA Core Content Scroll Variant',slug:'qa-core-content-scroll-about-intro-single-image',variant:'about-intro-single-image',status:'unpublished',editPath:'/admin/pages-blocks/blocks/content/11',unassigned:true,configSha256:'a'.repeat(64)};
const fingerprint={id:randomUUID(),kind:'form-permission-fingerprint',correlationId:randomUUID(),phase:'before',status:'pass',ownedRunId:'owned-verification-run',adminAuditIncluded:true,adminUsersIncluded:true,publicTableCount:64,publicTableInventorySha256:'b'.repeat(64),publicDataSha256:'c'.repeat(64)};
const afterFingerprint={...fingerprint,id:randomUUID(),phase:'after'},scrollSource='d'.repeat(64),scrollReceipt={fixture:scrollFixture,sourceSha256:scrollSource,routePathname:scrollFixture.editPath,readOnly:true,saveNotInvoked:true,reloadVariantRetained:true,pickerCancelled:true,exactTriggerFocusRestored:true,nativeIds:[fingerprint.id,afterFingerprint.id],ownedRunId:fingerprint.ownedRunId,automaticCoverage:[],globalClosed:false};
const scrollBrowser={status:'pass',driverCompleted:true,inventoryOnly:false,sourceSha256:scrollSource,evidence:[{id:'existing-auth-login',status:'pass',authenticated:true},{id:'core-presentation-content-variant-scroll',status:'pass',contentScroll:scrollReceipt,renderedAdoption:[{id:'presentation-content-single-image-media-scroll'}]}],errors:[],presentationControls:{contentScroll:scrollReceipt}};
const proof={browser:scrollBrowser,nativeRecords:[fingerprint,afterFingerprint],fixture:scrollFixture,ownedRunId:fingerprint.ownedRunId},copy=()=>JSON.parse(JSON.stringify(proof));
test('Separate actual Content fixture + broker fingerprints qualify only readonly partial observation',()=>{validateContentScrollFixture(scrollFixture);assertContentScrollFingerprints(fingerprint,afterFingerprint);const result=assertContentScrollReceipt(proof);assert.equal(result.status,'partial-not-global-pass');assert.equal(result.renderedAdoptionJoinStillRequired,true);assert.deepEqual(result.automaticCoverage,[]);});
const corruptions:Array<[string,(x:ReturnType<typeof copy>)=>void]>=[
 ['fixture variant',x=>x.fixture.variant='default'],['assigned template',x=>x.fixture.unassigned=false],['foreign fixture route',x=>x.fixture.editPath='/admin'],['failed journey',x=>x.browser.evidence[1].status='fail'],['recorded failed journey',x=>x.browser.errors.push({id:'core-presentation-content-variant-scroll'})],['duplicate journey',x=>x.browser.evidence.push({...x.browser.evidence[1]})],['missing authentication',x=>x.browser.evidence.shift()],['foreign source',x=>x.browser.sourceSha256='e'.repeat(64)],['false save promise',x=>{x.browser.presentationControls.contentScroll.saveNotInvoked=false;x.browser.evidence[1].contentScroll.saveNotInvoked=false;}],['missing fingerprint',x=>x.nativeRecords.pop()],['duplicate native record',x=>x.nativeRecords.push({...x.nativeRecords[0]})],['foreign owned run',x=>x.nativeRecords[1].ownedRunId='foreign'],['data mutation',x=>x.nativeRecords[1].publicDataSha256='f'.repeat(64)],['audit excluded',x=>x.nativeRecords[1].adminAuditIncluded=false],['identity excluded',x=>x.nativeRecords[1].adminUsersIncluded=false],['inventory changed',x=>x.nativeRecords[1].publicTableCount++],['foreign correlation',x=>x.nativeRecords[1].correlationId=randomUUID()],['wrong phase order',x=>x.nativeRecords[1].phase='before'],['missing actual rendered observation',x=>x.browser.evidence[1].renderedAdoption=[]],['different collector summary',x=>x.browser.presentationControls.contentScroll.routePathname='/admin/elsewhere'],
];for(const[name,change]of corruptions)test('Content scroll strict native join rejects '+name,()=>{const value=copy();change(value);assert.throws(()=>assertContentScrollReceipt(value));});
const nativeFile=resolve(root,'scripts/verify-admin-core-presentation-controls-isolated.mts'),nativeSource=readFileSync(nativeFile,'utf8'),nativeAst=ts.createSourceFile(nativeFile,nativeSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),seedNode=nativeAst.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='prepareContentScrollFixture');assert.ok(seedNode);const seedCode=ts.transpileModule(seedNode.getText(nativeAst).replaceAll('import.meta.url','moduleUrl'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const realConfig=await jiti.import<typeof import('../src/lib/page-blocks/configs.ts')>(resolve(root,'src/lib/page-blocks/configs.ts')),realRegistry=await jiti.import<typeof import('../src/lib/page-blocks/module-edit-registry.ts')>(resolve(root,'src/lib/page-blocks/module-edit-registry.ts'));
async function seedPort(mode:string){const calls:Array<{sql:string;args?:unknown[]}>=[];const handle={owned:true,withDatabaseConnection:async(callback:(client:{query:(sql:string,args?:unknown[])=>Promise<{rows:Record<string,unknown>[]}>})=>unknown)=>callback({query:async(sql,args)=>{calls.push({sql,args});if(sql==='begin'||sql==='rollback')return{rows:[]};if(sql==='commit'){if(mode==='commit-error')throw Error('COMMIT_FAIL');return{rows:[]};}if(sql.startsWith('select id from public.content_block_templates'))return{rows:mode==='duplicate'?[{id:99}]:[]};if(sql.startsWith('insert into public.content_block_templates')){if(mode==='insert-error')throw Error('INSERT_FAIL');assert.equal(args?.[1],scrollFixture.slug);assert.equal(args?.[2],scrollFixture.variant);assert.equal(typeof args?.[3],'string');const config=JSON.parse(String(args?.[3]));return{rows:[{id:11,name:scrollFixture.name,slug:scrollFixture.slug,variant:scrollFixture.variant,status:'unpublished',config}]};}if(sql.startsWith('select id from public.page_composition_assignments'))return{rows:mode==='assigned'?[{id:2}]:[]};throw Error('UNEXPECTED_SQL');}})};const seed=new Function('moduleUrl','assert','assertOwnedLocalHandle','createJiti','PRESENTATION_CONTROL_ASSETS','hash','validateContentScrollFixture',seedCode+';return prepareContentScrollFixture;')(import.meta.url,assert,(target:typeof handle)=>assert.equal(target.owned,true),()=>({import:(specifier:string)=>Promise.resolve(specifier.includes('module-edit-registry')?realRegistry:realConfig)}),PRESENTATION_CONTROL_ASSETS,()=> 'a'.repeat(64),validateContentScrollFixture) as (handle:unknown)=>Promise<unknown>;return{calls,run:()=>seed(handle)};}
for(const mode of ['okay','duplicate','assigned','insert-error','commit-error']){const port=await seedPort(mode);if(mode==='okay'){const result=await port.run();validateContentScrollFixture(result);assert.equal(port.calls.at(-1)?.sql,'commit');assert.equal(port.calls.filter(row=>row.sql==='rollback').length,0);}else{await assert.rejects(port.run());assert.equal(port.calls.at(-1)?.sql,'rollback');}cases.push('Actual fixed native seed transaction '+mode);}
const primaryLoop=ts.createSourceFile('journey.mjs',browser,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);test('Extra Content observation uses existing fingerprint protocol and no save/POST transport',()=>{assert.match(browser,/kind:'form-permission-fingerprint'/u);assert.match(browser,/assertContentScrollFingerprints\(before,after\)/u);assert.match(browser,/actionRequests,0/u);assert.match(browser,/picker\.getByRole\('button',\{name:'إلغاء'/u);assert.match(browser,/planned:plan\.recipes\.length,completed:outcomes.length/u);assert.ok(primaryLoop.statements.some(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='observeContentScrollVariant'));});


const coreNativeRows=[{id:randomUUID(),kind:'presentation-controls-state',status:'pass'},{id:randomUUID(),kind:'domain-write-fault-arm',status:'pass'},fingerprint,afterFingerprint];const qualifiedScroll=assertContentScrollReceipt(proof);
test('Qualified Content fingerprints partition exactly, preserving every original state and fault',()=>assert.deepEqual(partitionContentScrollNativeRecords(coreNativeRows,qualifiedScroll),coreNativeRows.slice(0,2)));
for(const mode of ['missing','duplicate','foreign','wrong-kind','failed','reordered','forged-qualification'])test('Strict Content partition refuses '+mode,()=>{const records=JSON.parse(JSON.stringify(coreNativeRows)),qualified=JSON.parse(JSON.stringify(qualifiedScroll));if(mode==='missing')records.pop();else if(mode==='duplicate')records.push({...records[2]});else if(mode==='foreign')records.push({...records[2],id:randomUUID()});else if(mode==='wrong-kind')records[2].kind='other';else if(mode==='failed')records[2].status='fail';else if(mode==='reordered')[records[2],records[3]]=[records[3],records[2]];else qualified.unusedVariantUnchanged=false;assert.throws(()=>partitionContentScrollNativeRecords(records,qualified));});

const collectorPath=resolve(root,'scripts/verify-admin-adoption-readback-isolated.mts'),collectorSource=readFileSync(collectorPath,'utf8'),collectorAst=ts.createSourceFile(collectorPath,collectorSource,ts.ScriptTarget.Latest,true),sourceAnchorStatements=new Map<string,string>();
function findContentSourceAnchor(node:ts.Node){if(ts.isVariableStatement(node))for(const declaration of node.declarationList.declarations){if(ts.isIdentifier(declaration.name)&&['contentScrollSource','contentScrollRendered'].includes(declaration.name.text)){assert.equal(sourceAnchorStatements.has(declaration.name.text),false);sourceAnchorStatements.set(declaration.name.text,node.getText(collectorAst));}}ts.forEachChild(node,findContentSourceAnchor);}findContentSourceAnchor(collectorAst);assert.equal(sourceAnchorStatements.size,2);
const runContentSourceAnchor=new Function('readFileSync','join','artifactDir','browser','contentScroll','assertCoreRenderedAdoptionJoin',ts.transpileModule([...sourceAnchorStatements.values()].join('\n')+'\nreturn contentScrollRendered;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText);
function anchorBrowser(sourceSha256:string){const value=JSON.parse(JSON.stringify(scrollBrowser)),binding={boundary:'form',consumer:'block-template-content-editor',surface:'content:template-edit'};value.sourceSha256=sourceSha256;value.presentationControls.contentScroll.sourceSha256=sourceSha256;value.evidence[1].contentScroll.sourceSha256=sourceSha256;value.requiredCases=[{key:'form:block-template-content-editor:capability:scrollbar',boundary:'form',consumer:binding.consumer,axis:'scrollbar',scenario:'complete_applicable_capability_behavior',declaration:'adopted'},{boundary:'form',consumer:binding.consumer,surface:binding.surface}];value.evidence[1].renderedAdoption=[{id:'presentation-content-single-image-media-scroll',receiptId:randomUUID(),status:'rendered-fragments-observed',sourceSha256,axis:'scrollbar',routePathname:scrollFixture.editPath,bindings:[{key:value.requiredCases[0].key,...binding}],containment:'modal-lock',observations:[{viewport:'desktop',width:1280,height:900},{viewport:'narrow',width:390,height:760}].map(view=>({...view,state:'overflow-observed',targetReachable:true,targetHitTestPassed:true,computedCanonicalThin:true,extent:900,client:400,actualWheelMoved:true,farBoundaryReached:true,backgroundPositionRetained:true})),automaticCoverage:[],globalClosed:false}];return value;}
function anchorPort(browser:ReturnType<typeof anchorBrowser>,manifestSource:string|null){const calls:string[]=[];const value=()=>runContentSourceAnchor((path:string,encoding:string)=>{calls.push(path);assert.equal(path,join(root,'owned-review-artifacts','public-source-manifest.json'));assert.equal(encoding,'utf8');if(manifestSource===null)throw Error('MISSING_OWNED_SOURCE_MANIFEST');return JSON.stringify({sourceSha256:manifestSource});},join,join(root,'owned-review-artifacts'),browser,{fixtureId:scrollFixture.id},assertCoreRenderedAdoptionJoin);return{calls,value};}
test('Actual collector anchors Content rendered join to independent frozen source manifest',()=>{const port=anchorPort(anchorBrowser(scrollSource),scrollSource);assert.equal(port.value().sourceSha256,scrollSource);assert.equal(port.calls.length,1);});
test('Actual collector rejects coherently foreign source across Browser summary and Content rendered receipt',()=>{const browser=anchorBrowser('e'.repeat(64));assert.equal(assertContentScrollReceipt({...proof,browser}).status,'partial-not-global-pass');const port=anchorPort(browser,scrollSource);assert.throws(port.value);assert.equal(port.calls.length,1);});
test('Actual collector rejects missing frozen source manifest',()=>assert.throws(anchorPort(anchorBrowser(scrollSource),null).value));
test('Actual collector rejects malformed independent frozen source hash',()=>assert.throws(anchorPort(anchorBrowser(scrollSource),'not-a-source-hash').value));


// Controlled compiled metadata exercises the real counter and canonical selector; no Product Browser or DB credit.
function controlledHeroReadReceipt(pathname:string){const worker='app/admin/pages-blocks/blocks/hero/[id]/page',owner='src/lib/admin/links/actions.ts';return{contract:'admin-links',sourceSha256:scrollSource,manifestSha256:'a'.repeat(64),buildMetadataSha256:'b'.repeat(64),ownerSourceSha256:createHash('sha256').update(readFileSync(resolve(root,owner))).digest('hex'),worker,pathname,actions:['browseAdminLinksAjax','resolveAdminLinkAjax'].map((exportedName,index)=>({actionIdSha256:String(index+1).repeat(64),exportedName,owner,worker,filename:owner,allowedFilenames:[owner]})),totalPosts:2,readPosts:2,forbiddenPosts:0,readActionIds:['1'.repeat(64),'2'.repeat(64)],mutationCapableRequests:0,claimsZeroNetworkActions:false};}

const discardPlan=buildCorePresentationControlsPlan({manifest,fixtures});
function discardFrame(){const nativeRecords:Record<string,unknown>[]=[],outcomes=discardPlan.recipes.map((recipe:{kind:string;consumer:string;surface:string;editPath:string})=>{const correlation=randomUUID(),reopenCorrelation=randomUUID(),pair=[{...fingerprint,id:randomUUID(),correlationId:correlation,phase:'before'},{...fingerprint,id:randomUUID(),correlationId:correlation,phase:'after'}],reopened=[{...fingerprint,id:randomUUID(),correlationId:reopenCorrelation,phase:'before'},{...fingerprint,id:randomUUID(),correlationId:reopenCorrelation,phase:'after'}];for(const phase of PRESENTATION_CONTROL_PHASES){nativeRecords.push({id:randomUUID(),kind:'presentation-controls-state',status:'pass',actorBound:true,assignmentGraphUnchanged:true,catalogUnchanged:true,recipe:recipe.kind,phase});if(phase==='serverRejected')nativeRecords.push(...pair,...reopened);}return{kind:recipe.kind,consumer:recipe.consumer,surface:recipe.surface,postRejectionDirtyNavigationCancelled:true,acceptedDiscard:{status:'discard-accepted-before-reauthor',kind:'navigated',fromPathname:recipe.editPath,toPathname:'/admin/pages-blocks/blocks/'+recipe.kind,nativeBefore:pair[0].id,nativeAfter:pair[1].id,nativeCorrelationId:correlation,actionRequests:0,nativePublicStateUnchanged:true,adminAuditIncluded:true,guardAccepted:true,observedDestination:true,acceptedBeforeReauthor:true,reopen:{nativeBefore:reopened[0].id,nativeAfter:reopened[1].id,nativeCorrelationId:reopenCorrelation,actionRequests:0,nativePublicStateUnchanged:true,draftReauthored:true,originalRouteRestored:true,...(recipe.kind==='hero'?{readPosts:controlledHeroReadReceipt(recipe.editPath)}:{})}}};});return JSON.parse(JSON.stringify({browser:{status:'pass',cohort:'presentation-controls',driverCompleted:true,sourceSha256:scrollSource,errors:[],presentationControls:{planned:2,completed:2,outcomes},evidence:outcomes.map((r:{kind:string})=>({...r,id:'core-presentation-controls-'+r.kind,status:'pass'}))},nativeRecords,ownedRunId:fingerprint.ownedRunId,sourceSha256:scrollSource,plan:discardPlan}));}
test('Exact Hero/Content accepted discard and reopen pair join preserves original twelve state receipts',()=>{const value=discardFrame(),joined=assertPresentationAcceptedDiscardReceipts(value);assert.equal(joined.qualified.length,2);assert.equal(joined.nativeCheckpointIds.length,8);const remaining=partitionPresentationDiscardNativeRecords(value.nativeRecords,joined);assert.equal(remaining.length,12);assert.ok(remaining.every((r:{kind:string})=>r.kind==='presentation-controls-state'));});
const discardMutants:Record<string,(x:ReturnType<typeof discardFrame>)=>void>={foreignActorBinding:x=>x.nativeRecords[3].actorBound=false,missingActorBinding:x=>delete x.nativeRecords[3].actorBound,missingEditor:x=>x.browser.presentationControls.outcomes.pop(),missingEvidence:x=>x.browser.evidence.pop(),foreignSource:x=>x.sourceSha256='f'.repeat(64),wrongFixtureId:x=>{x.browser.evidence[0].acceptedDiscard.fromPathname='/admin/pages-blocks/blocks/hero/999';x.browser.presentationControls.outcomes[0].acceptedDiscard.fromPathname='/admin/pages-blocks/blocks/hero/999';},foreignConsumer:x=>x.browser.presentationControls.outcomes[0].consumer='block-template-cards-editor',wrongSurface:x=>x.browser.presentationControls.outcomes[0].surface='hero:template-command',missingCancel:x=>x.browser.evidence[0].postRejectionDirtyNavigationCancelled=false,missingAcceptance:x=>{x.browser.evidence[0].acceptedDiscard.guardAccepted=false;x.browser.presentationControls.outcomes[0].acceptedDiscard.guardAccepted=false;},missingPair:x=>x.nativeRecords.splice(5,1),duplicateNative:x=>x.nativeRecords.push({...x.nativeRecords[4]}),foreignRun:x=>x.nativeRecords[4].ownedRunId='foreign',changedData:x=>x.nativeRecords[5].publicDataSha256='e'.repeat(64),auditOmitted:x=>x.nativeRecords[4].adminAuditIncluded=false,usersOmitted:x=>x.nativeRecords[4].adminUsersIncluded=false,missingReopen:x=>{delete x.browser.evidence[0].acceptedDiscard.reopen;delete x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen;},reopenWrites:x=>{x.browser.evidence[0].acceptedDiscard.reopen.actionRequests=1;x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen.actionRequests=1;},changedReopen:x=>x.nativeRecords[7].publicDataSha256='e'.repeat(64),borrowedReopen:x=>{x.browser.evidence[0].acceptedDiscard.reopen.nativeCorrelationId=x.browser.evidence[0].acceptedDiscard.nativeCorrelationId;x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen.nativeCorrelationId=x.browser.evidence[0].acceptedDiscard.nativeCorrelationId;},reordered:x=>[x.nativeRecords[4],x.nativeRecords[5]]=[x.nativeRecords[5],x.nativeRecords[4]],failedBrowser:x=>x.browser.status='failed',recordedError:x=>x.browser.errors.push({id:x.browser.evidence[0].id}),nativeAfterSave:x=>{const pairs=x.nativeRecords.splice(4,4);x.nativeRecords.push(...pairs);}};
for(const[name,change]of Object.entries(discardMutants))test('Accepted discard exact scheduled join rejects '+name,()=>{const value=discardFrame();change(value);assert.throws(()=>assertPresentationAcceptedDiscardReceipts(value));});
test('A foreign fingerprint survives discard partition and fails existing strict Content partition',()=>{const value=discardFrame(),joined=assertPresentationAcceptedDiscardReceipts(value);value.nativeRecords.push({...fingerprint,id:randomUUID()});const rest=partitionPresentationDiscardNativeRecords(value.nativeRecords,joined);assert.throws(()=>partitionContentScrollNativeRecords([...rest,fingerprint,afterFingerprint],qualifiedScroll));});

const scopedIds=corePresentationSelectedIds(CORE_PRESENTATION_SCROLL_SELECTION);
test('Finite Hero Scroll selector retains original order and omits only qualified generic Content',()=>{assert.deepEqual(corePresentationSelectedKinds(),['hero','content']);assert.deepEqual(scopedIds,['core-presentation-controls-hero','core-presentation-content-variant-scroll']);assert.throws(()=>corePresentationSelectedKinds('all'));assert.throws(()=>corePresentationSelectedIds(null));});
function selectedPresentationFrame(){const canonical=[{key:'original-open-case',boundary:'form',consumer:'controlled-consumer',surface:'edit',scenario:'rollback'}],browser={scope:'core-closure',cohort:'presentation-controls',journeySelection:CORE_PRESENTATION_SCROLL_SELECTION,status:'pass',driverCompleted:true,inventoryOnly:false,wholeCohortExecuted:false,globalClosed:false,errors:[],requiredCases:canonical.map(row=>({...row,status:'open',evidence:null})),selectedJourneyIds:[...scopedIds],executedJourneyIds:[...scopedIds],evidence:[{id:'existing-auth-login',status:'pass',authenticated:true,coverage:[]},...scopedIds.map(id=>({id,status:'pass',authenticated:false,coverage:[]}))]};return {canonical,browser};}
test('Selected Hero Scroll receipt retains unchanged canonical identities with zero automatic coverage',()=>{const x=selectedPresentationFrame(),result=assertCorePresentationSelectionReceipt(x.browser,x.canonical);assert.equal(result.retainedContentReplayed,false);assert.equal(result.globalClosed,false);assert.deepEqual(result.automaticCoverage,[]);});
const selectedMutators:Record<string,(x:ReturnType<typeof selectedPresentationFrame>)=>void>={unknown:x=>{x.browser.journeySelection='unknown';},cohort:x=>{x.browser.cohort='template-controls';},scope:x=>{x.browser.scope='audit2-selected';},missing:x=>{x.browser.executedJourneyIds.pop();},reorder:x=>{x.browser.executedJourneyIds.reverse();},replay:x=>{x.browser.evidence.push({id:'core-presentation-controls-content',status:'pass',coverage:[],authenticated:false});},extra:x=>{x.browser.selectedJourneyIds.push('new');},failed:x=>{x.browser.evidence[1].status='fail';},login:x=>{x.browser.evidence[0].authenticated=false;},unfinished:x=>{x.browser.driverCompleted=false;},whole:x=>{x.browser.wholeCohortExecuted=true;},global:x=>{x.browser.globalClosed=true;},lostIdentity:x=>{x.browser.requiredCases=[];},inventory:x=>{x.browser.inventoryOnly=true;}};
for(const[label,change]of Object.entries(selectedMutators))test('Scoped presentation rejects '+label,()=>{const x=selectedPresentationFrame();change(x);assert.throws(()=>assertCorePresentationSelectionReceipt(x.browser,x.canonical));});
function scopedDiscardFrame(selection:string=CORE_PRESENTATION_SCROLL_SELECTION){const x=discardFrame(),hero=x.browser.presentationControls.outcomes[0],keep=new Set([hero.acceptedDiscard.nativeBefore,hero.acceptedDiscard.nativeAfter,hero.acceptedDiscard.reopen.nativeBefore,hero.acceptedDiscard.reopen.nativeAfter]);x.nativeRecords=x.nativeRecords.filter((r:{id:string;recipe?:string})=>r.recipe==='hero'||keep.has(r.id));x.browser.journeySelection=selection;x.browser.presentationControls.planned=1;x.browser.presentationControls.completed=1;x.browser.presentationControls.outcomes=[hero];x.browser.evidence=x.browser.evidence.filter((r:{id:string})=>r.id==='core-presentation-controls-hero');x.plan=buildCorePresentationControlsPlan({manifest,fixtures:{...fixtures,selection},selection});return x;}
test('Hero-only discard joins all four unchanged fingerprint requirements and six physical phases',()=>{const x=scopedDiscardFrame(),q=assertPresentationAcceptedDiscardReceipts(x);assert.equal(q.qualified.length,1);assert.equal(q.nativeCheckpointIds.length,4);assert.equal(partitionPresentationDiscardNativeRecords(x.nativeRecords,q).length,6);});
for(const label of ['lost-phase','lost-reopen','lost-audit','full-plan','changed-native','wrong-source'])test('Hero-only discard cannot weaken '+label,()=>{const x=scopedDiscardFrame();if(label==='lost-phase')x.nativeRecords.pop();if(label==='lost-reopen')delete x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen;if(label==='lost-audit')x.nativeRecords.find((r:{kind:string})=>r.kind==='form-permission-fingerprint').adminAuditIncluded=false;if(label==='full-plan')x.plan=discardPlan;if(label==='changed-native')x.nativeRecords.find((r:{phase:string;kind:string})=>r.kind==='form-permission-fingerprint'&&r.phase==='after').publicDataSha256='f'.repeat(64);if(label==='wrong-source')x.browser.sourceSha256='f'.repeat(64);assert.throws(()=>assertPresentationAcceptedDiscardReceipts(x));});
const completionNode=nativeAst.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='assertCorePresentationControlsCompleted');assert.ok(completionNode);
const completePrivate=new Function('assert','assertOwnedLocalHandle','states','corePresentationSelectedKinds','PRESENTATION_CONTROL_KINDS','PRESENTATION_CONTROL_PHASES',ts.transpileModule(completionNode.getText(nativeAst).replace(/^export /u,''),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText+';return assertCorePresentationControlsCompleted;');
function privateCompletion(selection:string|null,patch:Record<string,unknown>={}){const handle={},state={fixtures:{selection},phases:{hero:6,content:selection===null?6:0},writes:selection===null?2:1,nativeReads:selection===null?12:6,...patch};return completePrivate(assert,(x:object)=>assert.equal(x,handle),new WeakMap([[handle,state]]),corePresentationSelectedKinds,PRESENTATION_CONTROL_KINDS,PRESENTATION_CONTROL_PHASES)(handle);}
test('Private native completion binds exact registered selection for full and remaining recipes',()=>{assert.equal(privateCompletion(null).recipes,2);assert.equal(privateCompletion(CORE_PRESENTATION_SCROLL_SELECTION).recipes,1);});
for(const [label,changed]of Object.entries({retainedReplay:{phases:{hero:6,content:1}},missingHero:{phases:{hero:5,content:0}},extraWrite:{writes:2},missingRead:{nativeReads:5},unregisteredSelection:{fixtures:{selection:'foreign'}}}))test('Private selected completion rejects '+label,()=>assert.throws(()=>privateCompletion(CORE_PRESENTATION_SCROLL_SELECTION,changed)));


function selectedCollectorDraftRoute(selection:string|null,draft:unknown,sourceText=collectorSource){const ast=ts.createSourceFile('collector.mts',sourceText,ts.ScriptTarget.Latest,true),matches:ts.IfStatement[]=[];function visit(n:ts.Node){if(ts.isIfStatement(n)&&n.expression.getText(ast).startsWith('selectedJourneys &&'))matches.push(n);ts.forEachChild(n,visit);}visit(ast);assert.equal(matches.length,1);const condition=matches[0].expression.getText(ast),flags=Object.fromEntries([...new Set(condition.match(/\bis[A-Z]\w*/gu)??[])].filter(name=>name!=='isCoreMediaSelection').map(name=>[name,false]));const check=new Function('browser','selectedJourneys','isCoreMediaSelection','CORE_MEDIA_RECOVERY_FOLLOWUP_SELECTION','CORE_PRESENTATION_SCROLL_SELECTION','CORE_PRESENTATION_HERO_SELECTION',...Object.keys(flags),'return ('+condition+');');const generalRequired=check({journeySelection:selection},{status:'pass'},isCoreMediaSelection,CORE_MEDIA_RECOVERY_FOLLOWUP_SELECTION,CORE_PRESENTATION_SCROLL_SELECTION,CORE_PRESENTATION_HERO_SELECTION,...Object.values(flags));if(generalRequired)assert.ok(draft);return generalRequired;}
function selectedCollectorActualDiscard(x:ReturnType<typeof scopedDiscardFrame>){const nodes:ts.VariableDeclaration[]=[];function visit(n:ts.Node){if(ts.isVariableDeclaration(n)&&n.name.getText(collectorAst)==='acceptedDiscard'&&n.initializer&&ts.isCallExpression(n.initializer)&&n.initializer.expression.getText(collectorAst)==='assertPresentationAcceptedDiscardReceipts')nodes.push(n);ts.forEachChild(n,visit);}visit(collectorAst);assert.equal(nodes.length,1);const js=ts.transpileModule('const '+nodes[0].getText(collectorAst)+';', {compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const fn=new Function('assertPresentationAcceptedDiscardReceipts','browser','native','handle','presentationSource','buildCorePresentationControlsPlan','ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST','readFileSync','join','artifactDir',js+';return acceptedDiscard;');return fn(assertPresentationAcceptedDiscardReceipts,x.browser,{records:x.nativeRecords},{identity:{runId:x.ownedRunId}},{sourceSha256:x.sourceSha256},buildCorePresentationControlsPlan,manifest,(file:string,encoding:string)=>{assert.equal(file,join('controlled-only','admin-adoption-fixtures.json'));assert.equal(encoding,'utf8');return JSON.stringify({presentationControls:{...fixtures,selection:x.browser.journeySelection}});},join,'controlled-only');}
test('Selected collector route: exact Presentation bypasses only general Form draft and executes actual dedicated discard join',()=>{assert.equal(selectedCollectorDraftRoute(CORE_PRESENTATION_SCROLL_SELECTION,null),false);assert.equal(selectedCollectorActualDiscard(scopedDiscardFrame()).qualified.length,1);});
test('Selected collector route: previous general draft assertion reproduces the rejection',()=>{const old=collectorSource.replace(' && browser.journeySelection!==CORE_PRESENTATION_SCROLL_SELECTION','');assert.notEqual(old,collectorSource);assert.throws(()=>selectedCollectorDraftRoute(CORE_PRESENTATION_SCROLL_SELECTION,null,old));});
test('Selected collector route: unrelated Form selection still requires general restoration',()=>{assert.throws(()=>selectedCollectorDraftRoute('text-topic-forms',null));assert.equal(selectedCollectorDraftRoute('text-topic-forms',{status:'pass'}),true);});
for(const [name,mutate]of Object.entries({missingAcceptedDiscard:(x:ReturnType<typeof scopedDiscardFrame>)=>{delete x.browser.presentationControls.outcomes[0].acceptedDiscard;},missingReopen:(x:ReturnType<typeof scopedDiscardFrame>)=>{delete x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen;},missingFingerprint:(x:ReturnType<typeof scopedDiscardFrame>)=>{x.nativeRecords.splice(x.nativeRecords.findIndex((r:{kind:string})=>r.kind==='form-permission-fingerprint'),1);},foreignSource:(x:ReturnType<typeof scopedDiscardFrame>)=>{x.sourceSha256='f'.repeat(64);}}))test('Selected collector route: actual dedicated discard still rejects '+name,()=>{assert.equal(selectedCollectorDraftRoute(CORE_PRESENTATION_SCROLL_SELECTION,null),false);const x=scopedDiscardFrame();mutate(x);assert.throws(()=>selectedCollectorActualDiscard(x));});


const heroOnlyIds=corePresentationSelectedIds(CORE_PRESENTATION_HERO_SELECTION);
function heroOnlyFrame(){const x=selectedPresentationFrame();x.browser.journeySelection=CORE_PRESENTATION_HERO_SELECTION;x.browser.selectedJourneyIds=[...heroOnlyIds];x.browser.executedJourneyIds=[...heroOnlyIds];x.browser.evidence=x.browser.evidence.filter(row=>row.id==='existing-auth-login'||heroOnlyIds.includes(row.id));return x;}
test('Hero-only selection executes exactly original Hero without retained Content or Scroll',()=>{assert.deepEqual(heroOnlyIds,['core-presentation-controls-hero']);assert.deepEqual(corePresentationSelectedKinds(CORE_PRESENTATION_HERO_SELECTION),['hero']);const x=heroOnlyFrame();assert.deepEqual(assertCorePresentationSelectionReceipt(x.browser,x.canonical).executedJourneyIds,heroOnlyIds);assert.equal(privateCompletion(CORE_PRESENTATION_HERO_SELECTION).recipes,1);assert.equal(selectedCollectorDraftRoute(CORE_PRESENTATION_HERO_SELECTION,null),false);assert.equal(selectedCollectorActualDiscard(scopedDiscardFrame(CORE_PRESENTATION_HERO_SELECTION)).qualified.length,1);});
for(const id of ['core-presentation-controls-content','core-presentation-content-variant-scroll'])test('Hero-only selection rejects replay of '+id,()=>{const x=heroOnlyFrame();x.browser.evidence.push({id,status:'pass',authenticated:false,coverage:[]});assert.throws(()=>assertCorePresentationSelectionReceipt(x.browser,x.canonical));});
for(const [label,mutate]of Object.entries(selectedMutators).filter(([label])=>label!=='reorder'))test('Hero-only exact receipt rejects '+label,()=>{const x=heroOnlyFrame();mutate(x);assert.throws(()=>assertCorePresentationSelectionReceipt(x.browser,x.canonical));});
for(const [label,changed]of Object.entries({retainedReplay:{phases:{hero:6,content:1}},missingHero:{phases:{hero:5,content:0}},extraWrite:{writes:2},missingRead:{nativeReads:5}}))test('Hero-only native completion rejects '+label,()=>assert.throws(()=>privateCompletion(CORE_PRESENTATION_HERO_SELECTION,changed)));
const diagnosticPath=resolve(root,'scripts/fixtures/admin-core-form-draft-restoration.mjs'),diagnosticSource=readFileSync(diagnosticPath,'utf8'),diagnosticTree=ts.createSourceFile(diagnosticPath,diagnosticSource,ts.ScriptTarget.Latest,true),diagnosticNode=diagnosticTree.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='describeDiscardReopenRequests');assert.ok(diagnosticNode);
const projectDiagnostic=new Function('readFileSync','createHash',diagnosticNode.getText(diagnosticTree).replace('import.meta.url',JSON.stringify(new URL('./fixtures/admin-core-form-draft-restoration.mjs',import.meta.url).href))+';return describeDiscardReopenRequests;');
const actionId='a'.repeat(40),requestLabel={method:'POST',actionId};
function diagnosticPort(manifest:unknown){return projectDiagnostic((url:URL)=>{assert.ok(url.pathname.endsWith('/.next/server/server-reference-manifest.json'));return Buffer.from(JSON.stringify(manifest));},createHash)([requestLabel]);}
test('Failure diagnostic projects only exact public export/source labels and manifest digest',()=>{const value=diagnosticPort({node:{[actionId]:{exportedName:'resolveAdminLinkAjax',filename:'.tmp-qa/owned/public-build-source/src/lib/admin/links/actions.ts',workers:{secret:'PRIVATE_VALUE'}}},encryptionKey:'PRIVATE_VALUE'});assert.equal(value.manifestStatus,'read');assert.match(value.manifestSha256,/^[a-f0-9]{64}$/u);assert.deepEqual(value.requests,[{...requestLabel,exportedName:'resolveAdminLinkAjax',filename:'src/lib/admin/links/actions.ts'}]);assert.equal(JSON.stringify(value).includes('PRIVATE_VALUE'),false);});
test('Failure diagnostic unknown Action remains unresolved',()=>assert.deepEqual(diagnosticPort({node:{}}).requests,[{...requestLabel,exportedName:null,filename:null}]));
test('Failure diagnostic rejects unsafe metadata without printing raw values',()=>{const value=diagnosticPort({node:{[actionId]:{exportedName:'PRIVATE VALUE',filename:'src/../.env.local'}}});assert.deepEqual(value.requests,[{...requestLabel,exportedName:null,filename:null}]);});
test('Missing diagnostic manifest preserves unresolved failure without claiming an Action label',()=>{const value=projectDiagnostic(()=>{throw Error('PRIVATE_VALUE');},createHash)([requestLabel]);assert.deepEqual(value,{manifestStatus:'unavailable',requests:[requestLabel]});});


// Extract the maintained private counter with only its read-file boundary substituted.
const readCounterFile=resolve(root,'scripts/fixtures/admin-core-form-draft-restoration.mjs'),readCounterSource=readFileSync(readCounterFile,'utf8'),readCounterTree=ts.createSourceFile(readCounterFile,readCounterSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
const counterNames=['HERO_REOPEN_READ_WORKER','CONTENT_DRAFT_READ_WORKER','HERO_REOPEN_READ_EXPORTS','createCoreLinkReadCounter','createHeroReopenReadCounter','createCoreContentDraftReadCounter'];const counterNodes=counterNames.map(name=>{const rows=readCounterTree.statements.filter(n=>(ts.isFunctionDeclaration(n)&&n.name?.text===name)||(ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>d.name.getText(readCounterTree)===name)));assert.equal(rows.length,1);return rows[0].getText(readCounterTree).replace(/^export\s+/u,'');});
const counterCode=ts.transpileModule(counterNodes.join('\n').replaceAll('import.meta.url','moduleUrl'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const heroWorker='app/admin/pages-blocks/blocks/hero/[id]/page',heroPath='/admin/pages-blocks/blocks/hero/1',counterOrigin='http://127.0.0.1:57602',readIds=['c'.repeat(40),'d'.repeat(40)],readOwner='src/lib/admin/links/actions.ts';
const counterManifest:{node:Record<string,{exportedName:string;filename:string;workers:Record<string,object>}>}={node:Object.fromEntries(['browseAdminLinksAjax','resolveAdminLinkAjax'].map((exportedName,index)=>[readIds[index],{exportedName,filename:readOwner,workers:{[heroWorker]:{}}}]))};
const counterMetadata={appDir:root,relativeAppDir:'',config:{turbopack:{root},outputFileTracingRoot:root}};
function counterPort(manifestValue:unknown=counterManifest,metadataValue:unknown=counterMetadata,content=false){const reader=(url:URL)=>{if(url.pathname.endsWith('/.next/server/server-reference-manifest.json'))return Buffer.from(JSON.stringify(manifestValue));assert.ok(url.pathname.endsWith('/.next/required-server-files.json'));return Buffer.from(JSON.stringify(metadataValue));};return new Function('assert','readFileSync','fileURLToPath','selectCoreLinkPreviewAction','createHash','assertCoreHeroReopenReadReceipt','assertCoreContentDraftReadReceipt','moduleUrl','hash',counterCode+';return '+(content?'createCoreContentDraftReadCounter':'createHeroReopenReadCounter')+';')(assert,reader,fileURLToPath,selectCoreLinkPreviewAction,createHash,assertCoreHeroReopenReadReceipt,assertCoreContentDraftReadReceipt,pathToFileURL(readCounterFile).href,/^[a-f0-9]{64}$/u)({origin:counterOrigin,pathname:content?'/admin/pages-blocks/blocks/content/11':heroPath,sourceSha256:scrollSource});}
const readRequest=(id:string|undefined=readIds[0],path=heroPath)=>({url:()=>counterOrigin+path,method:()=>'POST',headers:()=>id===undefined?{}:{'next-action':id}});
test('Actual Hero counter admits both exact read exports, conserves all POSTs, and claims zero mutations only',()=>{const counter=counterPort();assert.equal(counter.track(readRequest()),true);assert.equal(counter.track(readRequest(readIds[1])),true);assert.equal(counter.track(readRequest()),true);const receipt=counter.receipt();assert.equal(receipt.totalPosts,3);assert.equal(receipt.readPosts,3);assert.equal(receipt.forbiddenPosts,0);assert.equal(receipt.claimsZeroNetworkActions,false);assert.equal(receipt.actions.length,2);assert.equal(receipt.manifestSha256,createHash('sha256').update(JSON.stringify(counterManifest)).digest('hex'));assertCoreHeroReopenReadReceipt(receipt,scrollSource);});
const contentReadPath='/admin/pages-blocks/blocks/content/11',contentReadWorker='app/admin/pages-blocks/blocks/content/[id]/page';
function contentReadCounter(){const manifest=structuredClone(counterManifest);for(const row of Object.values(manifest.node))row.workers={[contentReadWorker]:{}};return counterPort(manifest,counterMetadata,true);}
test('Content draft read counter conserves all four scoped read POSTs without claiming zero network',()=>{const counter=contentReadCounter();for(const id of[readIds[0],readIds[0],readIds[1],readIds[1]])assert.equal(counter.track(readRequest(id,contentReadPath)),true);const receipt=counter.receipt();assert.equal(receipt.totalPosts,4);assert.equal(receipt.readPosts,4);assert.equal(receipt.requests.length,4);assert.equal(receipt.claimsZeroNetworkActions,false);assertCoreContentDraftReadReceipt(receipt,scrollSource,contentReadPath);assert.throws(()=>assertCoreHeroReopenReadReceipt(receipt,scrollSource));});
for(const label of['unknown','no-header','mutation','foreign-origin','wrong-route','query'])test('Content draft read counter rejects every noncanonical POST '+label,()=>{const counter=contentReadCounter(),request=label==='no-header'?{...readRequest(readIds[0],contentReadPath),headers:()=>({})}:label==='foreign-origin'?{...readRequest(readIds[0],contentReadPath),url:()=>'https://example.invalid'+contentReadPath}:readRequest(label==='unknown'||label==='mutation'?'e'.repeat(40):readIds[0],label==='wrong-route'?heroPath:label==='query'?contentReadPath+'?saved=1':contentReadPath);assert.equal(counter.track(request),false);assert.equal(counter.snapshot().totalPosts,1);assert.equal(counter.snapshot().forbiddenPosts,1);assert.equal(counter.snapshot().requests.length,1);assert.throws(()=>counter.receipt());});
for(const label of['count','sequence','source','owner','worker','identity','export','payload','request-list'])test('Content scoped read receipt rejects '+label,()=>{const counter=contentReadCounter();counter.track(readRequest(readIds[0],contentReadPath));const receipt=counter.receipt();if(label==='count')receipt.totalPosts=0;if(label==='sequence')receipt.requests[0].index=1;if(label==='source')receipt.sourceSha256='f'.repeat(64);if(label==='owner')receipt.ownerSourceSha256='f'.repeat(64);if(label==='worker')receipt.worker=heroWorker;if(label==='identity')receipt.requests[0].actionIdSha256='f'.repeat(64);if(label==='export')receipt.requests[0].exportedName='updateAction';if(label==='payload')receipt.requests[0].payloadSha256='raw';if(label==='request-list')receipt.requests=[];assert.throws(()=>assertCoreContentDraftReadReceipt(receipt,scrollSource,contentReadPath));});
test('Actual Hero counter admits zero reads without fabricating a fixed request count',()=>assert.equal(counterPort().receipt().totalPosts,0));
for(const label of ['unknown','no-header','wrong-route','query'])test('Actual Hero counter fails closed for '+label,()=>{const counter=counterPort(),request=label==='no-header'?{...readRequest(),headers:()=>({})}:readRequest(label==='unknown'?'e'.repeat(40):readIds[0],label==='wrong-route'?'/admin/pages-blocks/blocks/content/1':label==='query'?heroPath+'?foreign=1':heroPath);assert.equal(counter.track(request),false);assert.throws(()=>counter.receipt());});
for(const exportIndex of [0,1])for(const label of ['absent','duplicate','foreign-owner','foreign-worker','foreign-export'])test('Actual exact read selector rejects '+exportIndex+':'+label,()=>{const m=structuredClone(counterManifest),id=readIds[exportIndex];if(label==='absent')delete m.node[id];if(label==='duplicate')m.node['e'.repeat(40)]=structuredClone(m.node[id]);if(label==='foreign-owner')m.node[id].filename='foreign/'+readOwner;if(label==='foreign-worker')m.node[id].workers={'app/admin/foreign/page':{}};if(label==='foreign-export')m.node[id].exportedName='saveAdminLinkAjax';assert.throws(()=>counterPort(m));});
for(const label of ['app-dir','root','relative'])test('Read counter rejects mismatched build coordinates '+label,()=>{const m=structuredClone(counterMetadata);if(label==='app-dir')m.appDir=resolve(root,'foreign');if(label==='root')m.config.turbopack.root=resolve(root,'foreign');if(label==='relative')m.relativeAppDir='foreign';assert.throws(()=>counterPort(counterManifest,m));});
for(const label of ['missing','total','reads','forbidden','ids','source','owner','worker','zero-network','mutation','path'])test('Current Hero join requires conserved source-bound read receipt '+label,()=>{const x=scopedDiscardFrame(CORE_PRESENTATION_HERO_SELECTION);for(const outcome of [x.browser.evidence[0],x.browser.presentationControls.outcomes[0]]){const v=outcome.acceptedDiscard.reopen.readPosts;if(label==='missing')delete outcome.acceptedDiscard.reopen.readPosts;if(label==='total')v.totalPosts++;if(label==='reads')v.readPosts++;if(label==='forbidden')v.forbiddenPosts++;if(label==='ids')v.readActionIds.push('e'.repeat(64));if(label==='source')v.sourceSha256='f'.repeat(64);if(label==='owner')v.ownerSourceSha256='f'.repeat(64);if(label==='worker')v.worker='app/admin/foreign/page';if(label==='zero-network')v.claimsZeroNetworkActions=true;if(label==='mutation')v.mutationCapableRequests++;if(label==='path')v.pathname='/admin/pages-blocks/blocks/hero/999';}assert.throws(()=>assertPresentationAcceptedDiscardReceipts(x));});
for(const label of ['missing-native-after','changed-native-after','omitted-audit','omitted-users'])test('Read classification cannot replace mandatory reopen DB/Audit '+label,()=>{const x=scopedDiscardFrame(CORE_PRESENTATION_HERO_SELECTION),id=x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen.nativeAfter,index=x.nativeRecords.findIndex((r:{id:string})=>r.id===id);if(label==='missing-native-after')x.nativeRecords.splice(index,1);if(label==='changed-native-after')x.nativeRecords[index].publicDataSha256='f'.repeat(64);if(label==='omitted-audit')x.nativeRecords[index].adminAuditIncluded=false;if(label==='omitted-users')x.nativeRecords[index].adminUsersIncluded=false;assert.throws(()=>assertPresentationAcceptedDiscardReceipts(x));});
test('Default Content does not opt into the Hero read exception',()=>{const x=discardFrame();for(const outcome of [x.browser.evidence[1],x.browser.presentationControls.outcomes[1]])outcome.acceptedDiscard.reopen.readPosts=controlledHeroReadReceipt(heroPath);assert.throws(()=>assertPresentationAcceptedDiscardReceipts(x));});


// The actual driver passes raw definitions; its receipt adds open status and null evidence.
for(const selection of [CORE_PRESENTATION_SCROLL_SELECTION,CORE_PRESENTATION_HERO_SELECTION])test('Raw canonical definitions join decorated current driver receipt '+selection,()=>{const x=selectedPresentationFrame(),ids=corePresentationSelectedIds(selection);x.browser.journeySelection=selection;x.browser.selectedJourneyIds=ids;x.browser.executedJourneyIds=[...ids];x.browser.evidence=x.browser.evidence.filter(row=>row.id==='existing-auth-login'||ids.includes(row.id));assertCorePresentationSelectionReceipt(x.browser,x.canonical);assertCorePresentationSelectionReceipt(x.browser,x.browser.requiredCases);});
for(const label of ['promoted','evidence','identity','missing-status','missing-evidence','duplicate','extra-field','canonical-promoted','canonical-evidence'])test('Presentation receipt shape correction rejects '+label,()=>{const x=selectedPresentationFrame();if(label==='promoted')x.browser.requiredCases[0].status='behavior_verified';if(label==='evidence')Object.assign(x.browser.requiredCases[0],{evidence:'fake'});if(label==='identity')x.browser.requiredCases[0].consumer='foreign';if(label==='missing-status')Reflect.deleteProperty(x.browser.requiredCases[0],'status');if(label==='missing-evidence')Reflect.deleteProperty(x.browser.requiredCases[0],'evidence');if(label==='duplicate'){x.canonical.push({...x.canonical[0]});x.browser.requiredCases.push({...x.browser.requiredCases[0]});}if(label==='extra-field')Object.assign(x.browser.requiredCases[0],{unregistered:true});if(label==='canonical-promoted')Object.assign(x.canonical[0],{status:'behavior_verified',evidence:null});if(label==='canonical-evidence')Object.assign(x.canonical[0],{status:'open',evidence:'fake'});assert.throws(()=>assertCorePresentationSelectionReceipt(x.browser,x.canonical));});


// Execute the current private pending diagnostic with controlled metadata; no network or Product credit.
const pendingTree=ts.createSourceFile('pending-diagnostic.mjs',browser,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),pendingFn=pendingTree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='describeCorePresentationPendingRequests');assert.ok(pendingFn);
const pendingCode=ts.transpileModule(pendingFn.getText(pendingTree),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},transformers:{before:[context=>{const visit=(node:ts.Node):ts.VisitResult<ts.Node>=>ts.isMetaProperty(node)&&node.keywordToken===ts.SyntaxKind.ImportKeyword?context.factory.createIdentifier('__controlledImportMeta'):ts.visitEachChild(node,visit,context);return node=>ts.visitNode(node,visit) as ts.SourceFile;}]}}).outputText;
const pendingDiagnostic=(raw:Buffer|Error)=>new Function('readFileSync','createHash','__controlledImportMeta','exports',pendingCode+';return describeCorePresentationPendingRequests;')((url:URL)=>{assert.equal(url.href,new URL('../../.next/server/server-reference-manifest.json',pathToFileURL(resolve(root,'scripts/fixtures/admin-core-presentation-controls-journeys.mjs'))).href);if(raw instanceof Error)throw raw;return raw;},createHash,{url:pathToFileURL(resolve(root,'scripts/fixtures/admin-core-presentation-controls-journeys.mjs')).href},{});
const pendingRequest=(id:string,path='/admin/pages-blocks/blocks/hero/1?saved=1')=>({headers:()=>({'next-action':id,'cookie':'PRIVATE_COOKIE_NOT_PERSISTED'}),method:()=> 'POST',url:()=> 'http://127.0.0.1:65123'+path});
test('Pending request diagnostic preserves two distinct wire identities and stages without reclassifying them',()=>{const saveId='a'.repeat(40),readId='b'.repeat(40),raw=Buffer.from(JSON.stringify({node:{[saveId]:{exportedName:'updateHeroTemplateDetails',filename:root+'/src/app/admin/pages-blocks/blocks/hero/actions.ts'},[readId]:{exportedName:'resolveAdminLinkAjax',filename:root+'/src/lib/admin/links/actions.ts'}},encryptionKey:'PRIVATE_BUILD_SECRET'})),requests=[pendingRequest(saveId),pendingRequest(readId)],out=pendingDiagnostic(raw)({requests,phases:['held','releasing'],response:{request:()=>requests[0]},sourceSha256:'c'.repeat(64)});assert.equal(out.manifestSha256,createHash('sha256').update(raw).digest('hex'));assert.equal(out.responseRequestIndex,0);assert.equal(out.requests.length,2);assert.deepEqual(out.requests.map((r:{actionId:string;phase:string;exportedName:string;filename:string})=>[r.actionId,r.phase,r.exportedName,r.filename]),[[saveId,'held','updateHeroTemplateDetails','src/app/admin/pages-blocks/blocks/hero/actions.ts'],[readId,'releasing','resolveAdminLinkAjax','src/lib/admin/links/actions.ts']]);assert.deepEqual(out.requests[0].searchKeys,['saved']);assert.doesNotMatch(JSON.stringify(out),/PRIVATE_|encryptionKey|cookie|postData/u);assert.equal(Object.hasOwn(out,'qualified'),false);});
test('Pending request diagnostic records the actual acknowledged request, not the first request by assumption',()=>{const requests=[pendingRequest('a'.repeat(40)),pendingRequest('b'.repeat(40))],out=pendingDiagnostic(Buffer.from('{}'))({requests,phases:['held','released'],response:{request:()=>requests[1]},sourceSha256:'c'.repeat(64)});assert.equal(out.responseRequestIndex,1);assert.equal(out.requests[1].exportedName,null);assert.equal(out.requests[1].filename,null);});
test('Unavailable pending manifest keeps raw counts and refuses inferred labels',()=>{const requests=[pendingRequest('a'.repeat(40))],out=pendingDiagnostic(Error('PRIVATE_ENV'))({requests,phases:['held'],response:{request:()=>requests[0]},sourceSha256:'c'.repeat(64)});assert.equal(out.manifestStatus,'unavailable');assert.equal(out.manifestSha256,null);assert.equal(out.requests.length,1);assert.equal(out.requests[0].exportedName,null);assert.doesNotMatch(JSON.stringify(out),/PRIVATE_ENV/u);});
test('Pending diagnostic omits unsafe manifest labels and malformed action identifiers',()=>{const id='d'.repeat(40),requests=[pendingRequest(id),pendingRequest('private malformed value')],out=pendingDiagnostic(Buffer.from(JSON.stringify({node:{[id]:{exportedName:'bad name with secret',filename:'src/../private.env'}}})))({requests,phases:['held','acknowledged'],response:{request:()=>requests[0]},sourceSha256:'c'.repeat(64)});assert.equal(out.requests[0].exportedName,null);assert.equal(out.requests[0].filename,null);assert.equal(out.requests[1].actionId,null);});
// Execute the current pending contract and collector with controlled same-build metadata only.
function semanticPendingFrame(phase:'rejection'|'save'='save'){
 const counter=counterPort();counter.track(readRequest(readIds[0]));counter.track(readRequest(readIds[1]));
 const readReceipt=counter.receipt(),save={index:0,phase:'held',method:'POST',actionId:'a'.repeat(40),pathname:heroPath,searchKeys:[] as string[],exportedName:'updateHeroTemplateDetails',filename:'src/app/admin/pages-blocks/blocks/hero/actions.ts'},read={index:1,phase:'acknowledged',method:'POST',actionId:readIds[1],pathname:heroPath,searchKeys:['saved','tab'],exportedName:'resolveAdminLinkAjax',filename:readOwner};
 return{sourceSha256:scrollSource,pathname:heroPath,phase,readReceipt,proof:{actualStatementCancelled:phase==='rejection',actionRequests:phase==='save'?2:1,nativeStatementObservedTwice:true,sameStatementIdentity:true,normalKeyboardDedup:true,fieldsDisabled:true,ownedLockReleased:true,closeControl:'not_declared',requestDiagnostic:{sourceSha256:scrollSource,manifestStatus:'read',manifestSha256:readReceipt.manifestSha256,responseRequestIndex:0,requests:phase==='save'?[save,read]:[save]}}};
}
for(const phase of ['rejection','save'] as const)test('Hero pending exact same-build identity preserves raw '+phase+' evidence',()=>{
 const value=semanticPendingFrame(phase),before=structuredClone(value),result=assertCoreHeroPendingRequestSemantics(value);
 assert.equal(result.rawActionPosts,phase==='save'?2:1);assert.equal(result.mutationCapableRequests,1);assert.equal(result.readOnlyActionPosts,phase==='save'?1:0);assert.equal(result.unknownActionPosts,0);assert.equal(result.responseRequestIndex,0);assert.equal(result.rawEvidenceUnchanged,true);assert.deepEqual(value,before);
});
test('Hero pending save without a follow-up read conserves one raw mutation',()=>{const value=semanticPendingFrame();value.proof.actionRequests=1;value.proof.requestDiagnostic.requests.pop();const result=assertCoreHeroPendingRequestSemantics(value);assert.equal(result.rawActionPosts,1);assert.equal(result.readOnlyActionPosts,0);});
test('Hero read identity factors no counters and does not grant reopen success',()=>{const value=semanticPendingFrame(),binding=value.readReceipt;binding.totalPosts=99;assert.equal(assertCoreHeroReadActionBinding(binding,scrollSource),binding);assert.throws(()=>assertCoreHeroReopenReadReceipt(binding,scrollSource));const row=value.proof.requestDiagnostic.requests[1];assert.equal(assertCoreHeroReadActionRequest(row,binding),binding.actions[1]);assert.equal(assertCoreHeroReadActionRequest({...row,filename:readOwner.replaceAll('/','\\')},binding),binding.actions[1]);});
const pendingSemanticMutants:Record<string,(value:ReturnType<typeof semanticPendingFrame>)=>void>={
 'missing diagnostic':x=>Reflect.deleteProperty(x.proof,'requestDiagnostic'),
 'raw count reduced':x=>{x.proof.actionRequests=1;},
 'raw count inflated':x=>{x.proof.actionRequests=3;},
 'zero actions':x=>{x.proof.actionRequests=0;x.proof.requestDiagnostic.requests=[];},
 'extra raw action':x=>{x.proof.requestDiagnostic.requests.push({...x.proof.requestDiagnostic.requests[1],index:2});x.proof.actionRequests=3;},
 'missing index':x=>Reflect.deleteProperty(x.proof.requestDiagnostic.requests[1],'index'),
 'duplicate index':x=>{x.proof.requestDiagnostic.requests[1].index=0;},
 'response joins resolver':x=>{x.proof.requestDiagnostic.responseRequestIndex=1;},
 'response absent':x=>Reflect.deleteProperty(x.proof.requestDiagnostic,'responseRequestIndex'),
 'unavailable manifest':x=>{x.proof.requestDiagnostic.manifestStatus='unavailable';},
 'foreign manifest':x=>{x.proof.requestDiagnostic.manifestSha256='f'.repeat(64);},
 'foreign diagnostic source':x=>{x.proof.requestDiagnostic.sourceSha256='f'.repeat(64);},
 'foreign binding source':x=>{x.readReceipt.sourceSha256='f'.repeat(64);},
 'foreign expected source':x=>{x.sourceSha256='f'.repeat(64);},
 'foreign binding owner hash':x=>{x.readReceipt.ownerSourceSha256='f'.repeat(64);},
 'foreign binding worker':x=>{x.readReceipt.worker='app/admin/foreign/page';},
 'foreign action worker':x=>{x.readReceipt.actions[1].worker='app/admin/foreign/page';},
 'foreign action owner':x=>{x.readReceipt.actions[1].owner='src/lib/admin/foreign/actions.ts';},
 'duplicate bound identity':x=>{x.readReceipt.actions[1].actionIdSha256=x.readReceipt.actions[0].actionIdSha256;},
 'foreign path':x=>{x.pathname='/admin/pages-blocks/blocks/hero/2';},
 'foreign resolver path':x=>{x.proof.requestDiagnostic.requests[1].pathname='/admin/pages-blocks/blocks/hero/2';},
 'resolver GET':x=>{x.proof.requestDiagnostic.requests[1].method='GET';},
 'save not held':x=>{x.proof.requestDiagnostic.requests[0].phase='acknowledged';},
 'save query':x=>{x.proof.requestDiagnostic.requests[0].searchKeys=['saved'];},
 'save wrong export':x=>{x.proof.requestDiagnostic.requests[0].exportedName='updateContentBlock';},
 'save wrong owner':x=>{x.proof.requestDiagnostic.requests[0].filename=readOwner;},
 'save is bound read':x=>{x.proof.requestDiagnostic.requests[0].actionId=readIds[1];},
 'resolver before acknowledgment':x=>{x.proof.requestDiagnostic.requests[1].phase='releasing';},
 'resolver without saved query':x=>{x.proof.requestDiagnostic.requests[1].searchKeys=['tab'];},
 'resolver foreign query':x=>{x.proof.requestDiagnostic.requests[1].searchKeys=['saved','foreign'];},
 'duplicate query key':x=>{x.proof.requestDiagnostic.requests[1].searchKeys=['saved','saved'];},
 'browse is not post-save resolver':x=>{Object.assign(x.proof.requestDiagnostic.requests[1],{actionId:readIds[0],exportedName:'browseAdminLinksAjax'});},
 'unknown raw action':x=>{x.proof.requestDiagnostic.requests[1].actionId='e'.repeat(40);},
 'malformed raw action':x=>{x.proof.requestDiagnostic.requests[1].actionId='not-an-action';},
 'wrong resolver export':x=>{x.proof.requestDiagnostic.requests[1].exportedName='browseAdminLinksAjax';},
 'wrong resolver owner':x=>{x.proof.requestDiagnostic.requests[1].filename='src/app/admin/foreign/actions.ts';},
 'resolver claimed as second save':x=>{Object.assign(x.proof.requestDiagnostic.requests[1],{exportedName:'updateHeroTemplateDetails',filename:'src/app/admin/pages-blocks/blocks/hero/actions.ts'});},
 'rejection cannot exempt resolver':x=>{x.phase='rejection';x.proof.actualStatementCancelled=true;},
 'cancel flag drift':x=>{x.proof.actualStatementCancelled=true;},
};
for(const [name,change]of Object.entries(pendingSemanticMutants))test('Hero pending classification fails closed: '+name,()=>{const value=semanticPendingFrame();change(value);assert.throws(()=>assertCoreHeroPendingRequestSemantics(value));});

// Extract the whole maintained cleanup/native-fault/pending segment; none of its guards are copied.
const pendingBlocks:ts.Block[]=[];function findPendingCollector(node:ts.Node){if(ts.isBlock(node)&&node.statements.some(statement=>ts.isVariableStatement(statement)&&statement.declarationList.declarations.some(declaration=>declaration.name.getText(collectorAst)==='pendingRequestSemantics')))pendingBlocks.push(node);ts.forEachChild(node,findPendingCollector);}findPendingCollector(collectorAst);assert.equal(pendingBlocks.length,1);
const pendingStatements=pendingBlocks[0].statements,cleanupStart=pendingStatements.findIndex(statement=>ts.isVariableStatement(statement)&&statement.declarationList.declarations.some(declaration=>declaration.name.getText(collectorAst)==='cleanup')),outcomeLoop=pendingStatements.findIndex(statement=>ts.isForOfStatement(statement)&&statement.expression.getText(collectorAst)==='result.outcomes');assert.ok(cleanupStart>=0&&outcomeLoop>cleanupStart);
const pendingCollectorCode=ts.transpileModule(pendingStatements.slice(cleanupStart,outcomeLoop+1).map(statement=>statement.getText(collectorAst)).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const executePendingCollector=new Function('assert','readFileSync','join','artifactDir','contentNative','completion','result','browser','presentationSource','PRESENTATION_CONTROL_PHASES','assertCoreHeroPendingRequestSemantics',pendingCollectorCode+';return pendingRequestSemantics;');
function pendingCollectorFrame(kind='hero'){
 const rejection=semanticPendingFrame('rejection'),saved=semanticPendingFrame(),faults=[true,false].flatMap((cancel,index)=>['arm','observe-blocked','observe-blocked',...(cancel?['cancel']:[]),'release'].map(step=>({kind:'domain-write-fault-'+step,entity:'presentation_control_'+kind,token:'controlled-'+index,ownedLockRolledBack:step==='release',cancellationObserved:step==='release'&&cancel}))),states=PRESENTATION_CONTROL_PHASES.map(phase=>({kind:'presentation-controls-state',recipe:kind,phase,status:'pass'}));
 if(kind!=='hero'){saved.proof.actionRequests=1;saved.proof.requestDiagnostic.requests.pop();}
 return{sourceSha256:scrollSource,result:{outcomes:[{kind,postRejectionDirtyNavigationCancelled:true,exactWrites:1,nativeCheckpoints:6,nativePhases:[...PRESENTATION_CONTROL_PHASES],pendingRejection:rejection.proof,pendingSave:saved.proof,acceptedDiscard:{reopen:{readPosts:saved.readReceipt}}}]},native:{states,faults},cleanup:{status:'closed',activeLocks:0,records:structuredClone(faults)},browser:{evidence:[{id:'core-presentation-controls-'+kind,status:'pass'}]}};
}
function pendingCollectorPort(value:ReturnType<typeof pendingCollectorFrame>){return executePendingCollector(assert,(file:string,encoding:string)=>{assert.equal(file,join('controlled-pending','core-native-write-faults.json'));assert.equal(encoding,'utf8');return JSON.stringify(value.cleanup);},join,'controlled-pending',[...value.native.states,...value.native.faults],{nativeCheckpoints:6},value.result,value.browser,{sourceSha256:value.sourceSha256},PRESENTATION_CONTROL_PHASES,assertCoreHeroPendingRequestSemantics) as Array<ReturnType<typeof assertCoreHeroPendingRequestSemantics>>;}
test('Actual Hero collector accepts raw two with one acknowledged save and exact resolver',()=>{const value=pendingCollectorFrame(),before=structuredClone(value),results=pendingCollectorPort(value);assert.deepEqual(results.map(row=>[row.phase,row.rawActionPosts,row.mutationCapableRequests,row.readOnlyActionPosts]),[['rejection',1,1,0],['save',2,1,1]]);assert.deepEqual(value,before);});
test('Actual Content collector retains raw one and never borrows Hero exemption',()=>{const value=pendingCollectorFrame('content');assert.deepEqual(pendingCollectorPort(value),[]);value.result.outcomes[0].pendingSave.actionRequests=2;assert.throws(()=>pendingCollectorPort(value));});
const pendingCollectorMutants:Record<string,(value:ReturnType<typeof pendingCollectorFrame>)=>void>={
 'save identity differs across intervals':x=>{x.result.outcomes[0].pendingSave.requestDiagnostic.requests[0].actionId='b'.repeat(40);},
 'missing canonical binding':x=>Reflect.deleteProperty(x.result.outcomes[0].acceptedDiscard.reopen,'readPosts'),
 'native statement observed once':x=>{x.result.outcomes[0].pendingSave.nativeStatementObservedTwice=false;},
 'different native statement':x=>{x.result.outcomes[0].pendingSave.sameStatementIdentity=false;},
 'keyboard dedup absent':x=>{x.result.outcomes[0].pendingSave.normalKeyboardDedup=false;},
 'fields enabled':x=>{x.result.outcomes[0].pendingSave.fieldsDisabled=false;},
 'lock release missing':x=>{x.result.outcomes[0].pendingSave.ownedLockReleased=false;},
 'unknown close control':x=>{x.result.outcomes[0].pendingSave.closeControl='enabled';},
 'extra accepted save':x=>{x.result.outcomes[0].exactWrites=2;},
 'dirty cancellation absent':x=>{x.result.outcomes[0].postRejectionDirtyNavigationCancelled=false;},
 'missing native phase':x=>{x.native.states.pop();},
 'failed native phase':x=>{x.native.states[3].status='fail';},
 'reordered native phases':x=>{x.native.states.reverse();},
 'missing browser outcome':x=>{x.browser.evidence=[];},
 'failed browser outcome':x=>{x.browser.evidence[0].status='fail';},
 'cleanup open':x=>{x.cleanup.status='open';},
 'active native lock':x=>{x.cleanup.activeLocks=1;},
 'cleanup records mismatch':x=>{x.cleanup.records.pop();},
 'cancel fault missing':x=>{x.native.faults=x.native.faults.filter(row=>row.kind!=='domain-write-fault-cancel');x.cleanup.records=structuredClone(x.native.faults);},
 'release rollback absent':x=>{x.native.faults.at(-1)!.ownedLockRolledBack=false;x.cleanup.records=structuredClone(x.native.faults);},
 'successful save claimed cancelled':x=>{x.native.faults.at(-1)!.cancellationObserved=true;x.cleanup.records=structuredClone(x.native.faults);},
};
for(const [name,change]of Object.entries(pendingCollectorMutants))test('Actual Hero collector preserves mandatory guard: '+name,()=>{const value=pendingCollectorFrame();change(value);assert.throws(()=>pendingCollectorPort(value));});
for(const [name,change]of Object.entries(pendingSemanticMutants))test('Actual Hero collector invokes maintained semantic rejection: '+name,()=>{const value=pendingCollectorFrame(),semantic={...semanticPendingFrame(),proof:value.result.outcomes[0].pendingSave,readReceipt:value.result.outcomes[0].acceptedDiscard.reopen.readPosts,sourceSha256:value.sourceSha256};change(semantic);value.sourceSha256=semantic.sourceSha256;value.result.outcomes[0].pendingSave=semantic.proof;value.result.outcomes[0].acceptedDiscard.reopen.readPosts=semantic.readReceipt;if(name==='foreign path')semantic.readReceipt.pathname=semantic.pathname;assert.throws(()=>pendingCollectorPort(value));});
test('Pending producer retains one held request; collector scopes semantic exception to Hero',()=>{assert.match(browser,/assert\.equal\(posts\.length,1\)/u);const branch=pendingCollectorCode;assert.match(branch,/row\.kind\s*===\s*['"]hero['"]/u);assert.match(branch,/assertCoreHeroPendingRequestSemantics\(/u);assert.match(branch,/else\s+assert\.equal\(proof\.actionRequests,\s*1\)/u);});

console.log(JSON.stringify({status:"pass",controls:cases.length,cases,runtimeExecuted:false,globalClosed:false}));
