import { CORE_DIRECT_IMAGE_VALUES } from "./fixtures/admin-core-direct-image-adoption.mjs";
import { PRESENTATION_CONTROL_ASSETS } from "./fixtures/admin-core-presentation-controls-contract.mjs";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { resolve } from "node:path";
import { createJiti } from "jiti";
import ts from "typescript";
import { PAGE_SEO_RECIPE, PAGE_SEO_PHASES, PAGE_SEO_INVALID_CANONICAL, assertPageSeoScope, summarizePageSeoRejection, assertPageSeoEvidence, assertPageSeoReceiptJoin, assertPageSeoMediaAdoption } from "./fixtures/admin-core-page-seo-contract.mjs";
import { loadEntitySeoPersistenceOwner } from "./backfill-entity-seo-scores.mts";
const root=resolve(import.meta.dirname,".."),jiti=createJiti(import.meta.url,{fsCache:false,moduleCache:false,alias:{"server-only":resolve(root,"node_modules/next/dist/compiled/server-only/empty.js")}});
const seo=await jiti.import<typeof import("../src/lib/seo/entity-seo-types.ts")>(resolve(root,"src/lib/seo/entity-seo-types.ts"));
const {ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST:manifest}=await jiti.import<typeof import("../src/lib/admin/form-system/adoption-manifest.ts")>(resolve(root,"src/lib/admin/form-system/adoption-manifest.ts"));
const cases:string[]=[],test=(name:string,fn:()=>unknown)=>{fn();cases.push(name);};
test("Current specialized SEO surface does not promote generic rollback or axes",()=>{const scope=assertPageSeoScope(manifest);assert.equal(scope.genericDraftPreservationClaim,false);assert.deepEqual(scope.automaticCoverage,[]);});
for(const id of["missing","shared","no-seo"])test("Manifest boundary rejects "+id,()=>assert.throws(()=>assertPageSeoScope(id==="missing"?[]:manifest.map(row=>row.id==="page-composition-and-seo"?{...row,...(id==="shared"?{classification:"shared_adopter"}:{surfaces:["composition"]})}:row))));
const form=new FormData();for(const[key,value]of Object.entries(PAGE_SEO_RECIPE))form.set(key,value===null?"":Array.isArray(value)?value.join(", "):String(value));
const parsed=seo.readEntitySeoFormData(form),values=seo.toEntitySeoPersistence(parsed);
test("Fixed recipe uses actual SEO parser and nullable robots semantics",()=>{for(const[key,value]of Object.entries(PAGE_SEO_RECIPE))assert.deepEqual(values[key as keyof typeof values],value);assert.deepEqual(seo.validateEntitySeoValues(parsed),[]);});
test("Optional empty SEO remains valid; no fabricated required-field negative",()=>assert.deepEqual(seo.validateEntitySeoValues(seo.readEntitySeoFormData(new FormData())),[]));
test("Actual canonical negative rejects only ftp field before persistence",()=>{const issues=seo.validateEntitySeoValues({...parsed,canonicalUrl:PAGE_SEO_INVALID_CANONICAL});assert.equal(issues.length,1);assert.equal(issues[0].field,"canonical_url");assert.equal(issues[0].message,"الرابط الأساسي يجب أن يبدأ بـ http أو https.");});
const scoreOwner=loadEntitySeoPersistenceOwner(),semantic=scoreOwner.buildPageSeoSemanticContent([{content:"Body",slot:"main",sortOrder:10,moduleKind:"content",assignmentId:2},{content:"Hero",slot:"hero",sortOrder:0,moduleKind:"hero",assignmentId:1}],["hero","main"]);
test("Actual Page semantic owner includes ordered composition copy",()=>assert.equal(semantic,"Hero\nBody"));
const basePage={id:41,title:"QA Page",slug:"qa-admin-page-interaction",path:"/qa-admin-page-interaction",status:"published",layout_id:1,seo_title:"original",seo_description:"original",focus_keyword:"QA",seo_keywords:[],canonical_url:null,robots_index:null,robots_follow:null,og_image:null,og_image_alt:null,seo_score:0,seo_score_version:1,seo_score_input_hash:"old",updated_at:"before",created_at:"retained"};
const savedPage={...basePage,...values,...scoreOwner.deriveEntitySeoScore(scoreOwner.toPageSeoScoreInput({...basePage,...values,semanticContent:semantic})),updated_at:"after"};
const base={ownedRunId:"owned-unit",pageId:41,actorId:51,page:basePage,audit:[],otherPagesHash:"other",compositionHash:"composition",assignedTemplatesHash:"templates",semanticContentHash:"semantic",expectedScore:{}};
const saved={...base,page:savedPage,expectedScore:scoreOwner.deriveEntitySeoScore(scoreOwner.toPageSeoScoreInput({...savedPage,semanticContent:semantic})),audit:[{id:1,action:"page.update",entity_type:"page",entity_id:41,actor_admin_user_id:51,metadata:{scope:"page_seo",score:savedPage.seo_score,scoreVersion:savedPage.seo_score_version}}]};
test("Rejected unchanged and actual scored save include authored OG image and alt values",()=>{assertPageSeoEvidence(base,structuredClone(base),"rejected");assertPageSeoEvidence(base,saved,"saved");});
for(const key of["ownedRunId","pageId","actorId","otherPagesHash","compositionHash","assignedTemplatesHash","semanticContentHash"])test("Reject cross-owner or related data drift: "+key,()=>assert.throws(()=>assertPageSeoEvidence(base,{...saved,[key]:"bad"},"saved")));
for(const key of[...Object.keys(PAGE_SEO_RECIPE),"id","status","layout_id","created_at","seo_score","seo_score_version","seo_score_input_hash"])test("Reject native field mismatch: "+key,()=>assert.throws(()=>assertPageSeoEvidence(base,{...saved,page:{...saved.page,[key]:"bad"}},"saved")));
for(const delta of[{audit:[]},{audit:[...saved.audit,...saved.audit]},{audit:[{...saved.audit[0],actor_admin_user_id:52}]},{audit:[{...saved.audit[0],metadata:{...saved.audit[0].metadata,scope:"page_status"}}]}])test("Reject missing, duplicate, foreign actor or wrong-scope audit "+cases.length,()=>assert.throws(()=>assertPageSeoEvidence(base,{...saved,...delta},"saved")));
test("Rejected write cannot hide behind a later retry",()=>assert.throws(()=>assertPageSeoEvidence(base,saved,"rejected")));
for(const choice of["authored","persisted","mixed"])test("Post-rejection observation never claims generic retention: "+choice,()=>{const before={...PAGE_SEO_RECIPE,seo_title:"before"},authored={...PAGE_SEO_RECIPE,canonical_url:PAGE_SEO_INVALID_CANONICAL};const after=choice==="authored"?authored:choice==="persisted"?before:{...authored,seo_title:"before"};const result=summarizePageSeoRejection(before,authored,after);assert.equal(result.classification,choice==="authored"?"authored-draft-retained":choice==="persisted"?"persisted-values-reloaded":"mixed-field-lifecycle");assert.equal(result.genericDraftPreservationClaim,false);});
const nativeSource=readFileSync(resolve(root,"scripts/verify-admin-core-page-seo-isolated.mts"),"utf8"),compiled=ts.transpileModule(nativeSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
// Execute actual phase owner with only handle authentication stubbed; this is an offline guard, not native proof.
const loaded={exports:{} as Record<string,(...args:unknown[])=>unknown>};new Function("require","module","exports",compiled)((id:string)=>{
 if(id==="node:assert/strict")return assert;if(id==="node:crypto")return{createHash:()=>({update:()=>({digest:()=>"hash"})})};
 if(id.includes("isolated-supabase"))return{assertOwnedLocalHandle:(handle:unknown)=>assert.ok(handle)};
 if(id.includes("backfill-entity"))return{loadEntitySeoPersistenceOwner};if(id.includes("page-seo-contract"))return{PAGE_SEO_PHASES,assertPageSeoEvidence};throw new Error(id);
},loaded,loaded.exports);
const accept=loaded.exports.acceptCorePageSeoCheckpoint,complete=loaded.exports.assertCorePageSeoCompleted;
test("Actual phase owner rejects saved-first and incomplete completion",()=>{assert.throws(()=>accept({},"saved","time",saved));assert.throws(()=>complete({}));});
test("Actual phase owner requires four distinct ordered observations and exact reload",()=>{const handle={};accept(handle,"before","time",base);assert.throws(()=>accept(handle,"before","time",base));assert.throws(()=>accept(handle,"saved","time",saved));accept(handle,"rejected","time",base);assert.throws(()=>accept(handle,"saved","other-time",saved));accept(handle,"saved","time",saved);assert.throws(()=>accept(handle,"reloaded","time",{...saved,page:{...saved.page,updated_at:"new"}}));accept(handle,"reloaded","time",saved);assert.deepEqual((complete(handle) as {phases:string[]}).phases,PAGE_SEO_PHASES);});
const composition=readFileSync(resolve(root,"scripts/verify-admin-core-page-composition-isolated.mts"),"utf8");
test("Native SEO capture occurs inside canonical read-only snapshot, state accepted after commit",()=>{assert.match(composition,/begin isolation level repeatable read read only/u);assert.ok(composition.indexOf("await captureCorePageSeoState")<composition.indexOf('await connection.query("commit")'));assert.ok(composition.indexOf("seo:acceptCorePageSeoCheckpoint")>composition.indexOf('await connection.query("commit")'));});
const browser=readFileSync(resolve(root,"scripts/fixtures/admin-core-page-composition-journeys.mjs"),"utf8");
test("Page SEO uses specialized pending fieldset and fixed native two-observation hold",()=>{assert.match(browser,/fieldset\[data-admin-form-pending-fields\]/u);assert.match(browser,/entity:"pages"/u);assert.equal(browser.split('await fault("observe-blocked")').length-1,2);assert.match(browser,/cancellationObserved,false/u);assert.doesNotMatch(browser,/page\.request|force:\s*true|dispatchEvent\(/u);});
// Validate actual fixed request parser, not a duplicated allowlist.
const parserModule={exports:{} as {validateCorePageCompositionRequest:(request:unknown)=>unknown}};
new Function("require","module","exports",ts.transpileModule(composition,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText)((id:string)=>id==="node:assert/strict"?assert:id.includes("page-seo-contract")?{PAGE_SEO_PHASES}:{},parserModule,parserModule.exports);
const request={id:randomUUID(),kind:"page-composition-state",pageId:41,startedAt:new Date().toISOString(),layoutKeys:[],templateRefs:[{kind:"hero",id:1}]};
test("Existing composition request remains exact; SEO only adds a finite optional phase",()=>{parserModule.exports.validateCorePageCompositionRequest(request);for(const seoPhase of PAGE_SEO_PHASES)parserModule.exports.validateCorePageCompositionRequest({...request,seoPhase});});
for(const delta of[{seoPhase:"unknown"},{seoPhase:undefined},{expected:values},{sql:"select 1"},{actorId:51}])test("Reject arbitrary SEO request "+Object.keys(delta)[0],()=>assert.throws(()=>parserModule.exports.validateCorePageCompositionRequest({...request,...delta})));
const phaseRows=PAGE_SEO_PHASES.map((phase,index)=>({id:randomUUID(),kind:"page-composition-state",status:"pass",pageId:41,qaActorId:51,ownedRunId:"owned-unit",seo:{phase,status:"pass",exactWrites:index<2?0:1,canonicalScoreVerified:index>=2,auditIds:index<2?[]:[1]}}));
const token=randomUUID(),faults=["arm","observe-blocked","observe-blocked","release"].map(kind=>({id:randomUUID(),kind:"domain-write-fault-"+kind,entity:"pages",token,status:"pass",...(kind==="observe-blocked"?{backendPid:2,backendStartedAt:"start",queryStartedAt:"query",queryFingerprint:"fingerprint",holderPid:1,observedOneStatement:true}:kind==="release"?{ownedLockRolledBack:true,cancellationObserved:false}:{})}));
const imageControlReceipt=(field:string)=>({receiptId:randomUUID(),sourceSha256:'d'.repeat(64),field,altField:field==='og_image'?'og_image_alt':null,routePathname:field==='og_image'?'/admin/pages-blocks/pages/41':'/admin/settings/general',expected:CORE_DIRECT_IMAGE_VALUES[field as keyof typeof CORE_DIRECT_IMAGE_VALUES],expectedAlt:field==='og_image'?CORE_DIRECT_IMAGE_VALUES.og_image_alt:null,operations:['cancel-original','select','replace','cancel-replace','remove',...(field==='compactLogoUrl'?[]:['select-final'])],catalogAssets:[0,0,1,2,...(field==='compactLogoUrl'?[]:[2])].map(index=>({id:'11111111-1111-4111-8111-111111111111',objectKey:PRESENTATION_CONTROL_ASSETS[index],publicUrl:'/'+PRESENTATION_CONTROL_ASSETS[index],displayName:'Owned image '+index})),actualCatalogApi:true,exactTriggerReturn:true,unrelatedFieldsPreserved:true,removeClearedAlt:field==='og_image'?false:null,removePreservedAlt:field==='og_image'?true:null,automaticCoverage:[],globalClosed:false,requiresNativeSaveAndReload:true});
const joinedCase={id:"core-page-composition-seo-reject-retry-reload",status:"pass",imageAdoption:[imageControlReceipt("og_image"),imageControlReceipt("og_image")],consumer:"page-composition-and-seo",surface:"seo",automaticCoverage:[],coverage:[],genericDraftPreservationClaim:false,rejectionUi:{genericDraftPreservationClaim:false},nativeCheckpoints:4,exactWrites:1,nativePhases:[...PAGE_SEO_PHASES],checkpoints:phaseRows.map(row=>row.id),faultReceipts:faults.map(row=>row.id),faultToken:token,pending:{nativeStatementObservedTwice:true,sameStatementIdentity:true,normalKeyboardDedup:true,fieldsDisabledAndInert:true,ownedLockReleased:true,actionRequests:1}};
const browserJoin={sourceSha256:"d".repeat(64),status:"pass",driverCompleted:true,errors:[],cohort:"page-composition",evidence:[joinedCase]},nativeJoin={status:"pass",ownedRunId:"owned-unit",records:[...phaseRows,...faults]},cleanupJoin={status:"closed",activeLocks:0,records:faults},completionJoin={status:"pass",pageId:41,actorId:51,phases:PAGE_SEO_PHASES,nativeCheckpoints:4,exactWrites:1};
test("Named Browser/native/cleanup joins exactly four snapshots and one held save",()=>assert.equal(assertPageSeoReceiptJoin(browserJoin,nativeJoin,cleanupJoin,completionJoin).exactWrites,1));
for(const mutate of[(v:typeof nativeJoin)=>{v.records.pop();},(v:typeof nativeJoin)=>{v.records[2].status="fail";},(v:typeof nativeJoin)=>{v.records[3]={...v.records[2]};},(v:typeof nativeJoin)=>{Object.assign(v.records[1],{ownedRunId:"foreign"});},(v:typeof nativeJoin)=>{Object.assign(v.records[5],{entity:"projects"});}])test("Strict joined native corruption rejected "+cases.length,()=>{const changed=structuredClone(nativeJoin);mutate(changed);assert.throws(()=>assertPageSeoReceiptJoin(browserJoin,changed,cleanupJoin,completionJoin));});
test("Unclosed lock cannot promote Browser success",()=>assert.throws(()=>assertPageSeoReceiptJoin(browserJoin,nativeJoin,{...cleanupJoin,activeLocks:1},completionJoin)));
test("Source-only or incomplete Browser receipt cannot join",()=>assert.throws(()=>assertPageSeoReceiptJoin({...browserJoin,driverCompleted:false},nativeJoin,cleanupJoin,completionJoin)));


const {ADMIN_COLLECTION_SURFACE_ADOPTION:collectionManifest}=await jiti.import<typeof import('../src/lib/admin/interaction-system/adoption-manifest.ts')>(resolve(root,'src/lib/admin/interaction-system/adoption-manifest.ts'));
const aliasContext={formManifest:manifest,collectionManifest,sourceSha256:browserJoin.sourceSha256},aliasBrowser={...browserJoin,scope:'core-closure',inventoryOnly:false,requiredCases:['form:page-composition-and-seo:capability:media','collection:page-composition-shell:capability:media','collection:page-block-assignments:capability:media'].map(key=>({key,axis:'media'}))};
test('Page SEO media aliases qualify only the exact current aggregate child after unchanged native save join',()=>{const result=assertPageSeoReceiptJoin(aliasBrowser,nativeJoin,cleanupJoin,completionJoin,aliasContext);assert.ok(result.mediaAdoption);assert.equal(result.mediaAdoption.candidateRequiredCases.length,3);assert.equal(result.mediaAdoption.bindings.every((row:{nativePageId:number})=>row.nativePageId===41),true);assert.deepEqual(result.mediaAdoption.automaticCoverage,[]);assert.equal(result.mediaAdoption.globalClosed,false);});
for(const mode of['wrong-scope','inventory-only','missing-cell','duplicate-cell','wrong-axis','wrong-route','wrong-source','foreign-form','missing-seo-child','foreign-collection','foreign-owner-route','missing-owner-child'])test('Page media alias rejects '+mode,()=>{
 const b=structuredClone(aliasBrowser);const c:{formManifest:Array<{id:string;sourceFiles:string[];surfaces:string[]}>;collectionManifest:{surfaces:Array<{id:string;routes:string[];pageSourceFiles:string[];presentationSourceFiles:string[]}>};sourceSha256:string}=JSON.parse(JSON.stringify(aliasContext));
 if(mode==='wrong-scope')b.scope='foreign';else if(mode==='inventory-only')b.inventoryOnly=true;else if(mode==='missing-cell')b.requiredCases.pop();else if(mode==='duplicate-cell')b.requiredCases.push({...b.requiredCases[0]});else if(mode==='wrong-axis')b.requiredCases[0].axis='date_picker';else if(mode==='wrong-route')b.evidence[0].imageAdoption[0].routePathname='/admin/pages-blocks/pages/42';else if(mode==='wrong-source')c.sourceSha256='f'.repeat(64);else if(mode==='foreign-form')c.formManifest=c.formManifest.filter(row=>row.id!=='page-composition-and-seo');else if(mode==='missing-seo-child')c.formManifest=c.formManifest.map(row=>row.id==='page-composition-and-seo'?{...row,sourceFiles:row.sourceFiles.filter(file=>!file.endsWith('/PageSeoPanel.tsx'))}:row);else if(mode==='foreign-collection')c.collectionManifest.surfaces=c.collectionManifest.surfaces.filter(row=>row.id!=='page-block-assignments');else c.collectionManifest.surfaces=c.collectionManifest.surfaces.map(row=>row.id==='page-block-assignments'?{...row,...(mode==='foreign-owner-route'?{pageSourceFiles:['src/app/admin/other/page.tsx']}:{presentationSourceFiles:[]})}:row);
 assert.throws(()=>assertPageSeoMediaAdoption(b,completionJoin,c));
});
const actionFile=resolve(root,"src/app/admin/pages-blocks/pages/page-seo-actions.ts"),actionSource=readFileSync(actionFile,"utf8"),actionTree=ts.createSourceFile(actionFile,actionSource,ts.ScriptTarget.Latest,true);
const actionFn=actionTree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="savePageSeoAction");assert.ok(actionFn&&ts.isFunctionDeclaration(actionFn)&&actionFn.body);
const persistenceIndex=actionFn.body.statements.findIndex(node=>node.getText(actionTree).includes("getSupabaseAdmin()"));assert.ok(persistenceIndex>0);
const helpers=actionTree.statements.filter(node=>ts.isFunctionDeclaration(node)&&["readString","appendSeoQuery"].includes(node.name?.text??"")).map(node=>node.getText(actionTree)).join("\n");
const prefix=actionFn.body.statements.slice(0,persistenceIndex).map(node=>node.getText(actionTree)).join("\n");assert.match(prefix,/validateEntitySeoValues/u);assert.doesNotMatch(prefix,/getSupabaseAdmin|recordCmsAdminAudit/u);
const actionGuard=new Function("requireAdminSession","readEntitySeoFormData","validateEntitySeoValues","redirect",ts.transpileModule(helpers+"\nasync function guard(formData:FormData){"+prefix+"}\n",{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText+";return guard;")(async()=>({id:51}),seo.readEntitySeoFormData,seo.validateEntitySeoValues,(url:string)=>{throw new Error("REDIRECT:"+url);}) as (form:FormData)=>Promise<void>;
form.set("page_id","41");form.set("redirect_to","/admin/pages-blocks/pages/41?tab=seo");form.set("canonical_url",PAGE_SEO_INVALID_CANONICAL);
await assert.rejects(actionGuard(form),error=>{assert.ok(error instanceof Error);const target=new URL(error.message.slice("REDIRECT:".length),"http://localhost");assert.equal(target.pathname,"/admin/pages-blocks/pages/41");assert.equal(target.searchParams.get("seo_error"),"الرابط الأساسي يجب أن يبدأ بـ http أو https.");return true;});cases.push("Actual Action rejects canonical URL through specialized redirect before its first DB access");
form.set("canonical_url",PAGE_SEO_RECIPE.canonical_url);await actionGuard(form);cases.push("Same actual Action prefix accepts valid reauthoring for subsequent persistence");

const {REGISTERED_SLOT_MODULE_KINDS:assignmentKinds}=await jiti.import<typeof import('../src/lib/page-composition/slot-module-registry.ts')>(resolve(root,'src/lib/page-composition/slot-module-registry.ts'));
const assignmentPositions=await jiti.import<typeof import('../src/lib/page-composition/page-assignment-contract.ts')>(resolve(root,'src/lib/page-composition/page-assignment-contract.ts'));
const assignmentHelpers=await import('./fixtures/admin-core-page-composition-journeys.mjs');

// Derive the identity from the current assignment producer; do not mirror its spelling only in a fixture.
function actualAssignmentJourneyId(kind:string):string {
 const source=readFileSync(resolve(root,'scripts/fixtures/admin-core-page-composition-journeys.mjs'),'utf8');
 const tree=ts.createSourceFile('assignment-producer.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
 const owner=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='runCorePageCompositionJourneys');assert.ok(owner);
 const expressions:ts.Expression[]=[];
 const visit=(node:ts.Node)=>{
  if(ts.isForOfStatement(node)){
   let iterable=node.expression;
   if(ts.isCallExpression(iterable)&&ts.isPropertyAccessExpression(iterable.expression)&&iterable.expression.name.text==='filter'&&iterable.expression.expression.getText(tree)==='plan.assignments'){
    assert.equal(iterable.arguments.length,1);assert.equal(iterable.arguments[0].getText(tree).replace(/\s+/gu,''),'row=>!contentSeoOnly||row.kind==="content"','Only the fixed Content followup filter is accepted.');iterable=iterable.expression.expression;
   }
   if(ts.isPropertyAccessExpression(iterable)&&ts.isIdentifier(iterable.expression)&&iterable.expression.text==='plan'&&iterable.name.text==='assignments'){
   const statement=node.statement;assert.ok(ts.isExpressionStatement(statement)&&ts.isAwaitExpression(statement.expression)&&ts.isCallExpression(statement.expression.expression));
   const call=statement.expression.expression;assert.ok(ts.isIdentifier(call.expression)&&call.expression.text==='run');assert.ok(call.arguments[0]);expressions.push(call.arguments[0]);
   }
  }
  ts.forEachChild(node,visit);
 };visit(owner);assert.equal(expressions.length,1,'One actual ordinary-assignment journey producer is required.');
 const value=new Function('template','return ('+expressions[0].getText(tree)+');')({kind}) as unknown;assert.equal(typeof value,'string');return value as string;
}

function assignmentFixture(){
 const epoch='2026-09-27T00:00:00.000Z',actor=51,pageId=41,run='owned-assignment',slug='qa-admin-page-interaction';
 const templateFixtures=assignmentKinds.map((kind,index)=>({kind,id:100+index,name:'QA '+kind+' Unused 3',slug:slug+'-'+kind+'-3',assigned:false}));
 const sourceTemplate=templateFixtures.find(row=>assignmentPositions.MODULE_POSITION_CAPABILITIES[row.kind].mode!=='fixed')!;
 const templates=templateFixtures.map(row=>({...row,status:'published',config_hash:'config',source_row:{id:row.id,name:row.name,slug:row.slug,status:'published',config:{body:'Authored retained content'},variant:'current',created_at:epoch,updated_at:epoch}}));
 type Audit={id:number;action:string;entity_type:string;entity_id:number;actor_admin_user_id:number;operation:string;persistence_owner:string;atomic:boolean};
 type Copy={kind:string;sourceTemplateId:number;row:Record<string,unknown>};
 const before={id:randomUUID(),kind:'page-composition-state',status:'pass',ownedRunId:run,pageId,qaActorId:actor,startedAt:epoch,page:{id:pageId,slug,path:'/'+slug,layout_id:1,row_hash:'fixed-page'},layouts:[{id:1,key:'fixed',admin_label:'Fixed'}],regions:['hero','main','sidebar'].map((key,index)=>({layout_id:1,key,admin_label:key,sort_order:index*10})),
  assignments:[{kind:'hero',id:2,page_id:pageId,template_id:100,slot:'hero',sort_order:0,is_visible:true,updated_at:epoch},{kind:sourceTemplate.kind,id:11,page_id:pageId,template_id:sourceTemplate.id,slot:'main',sort_order:10,is_visible:true,updated_at:epoch},{kind:'cta',id:12,page_id:pageId,template_id:102,slot:'main',sort_order:20,is_visible:true,updated_at:epoch},{kind:'cards',id:13,page_id:pageId,template_id:103,slot:'sidebar',sort_order:20,is_visible:true,updated_at:epoch}],templates,templateCopies:[] as Copy[],audit:[] as Audit[]};
 const normalize=(state:typeof before,time:string)=>{for(const slot of new Set(state.assignments.filter(row=>row.kind!=='hero').map(row=>row.slot)))state.assignments.filter(row=>row.kind!=='hero'&&row.slot===slot).sort((a,b)=>a.sort_order-b.sort_order).forEach((row,index)=>{row.sort_order=(index+1)*10;row.updated_at=new Date(Date.parse(time)+row.id).toISOString();});};
 const append=(state:typeof before,operation:string)=>state.audit.push({id:state.audit.length+1,action:'page_composition.'+operation,entity_type:'page_composition',entity_id:pageId,actor_admin_user_id:actor,operation,persistence_owner:'mutate_page_composition',atomic:true});
 const readonly=structuredClone(before);readonly.id=randomUUID();
 const hidden=structuredClone(readonly);hidden.id=randomUUID();hidden.assignments.find(row=>row.id===11)!.is_visible=false;normalize(hidden,'2026-09-27T00:00:01.000Z');append(hidden,'bulk');
 const shown=structuredClone(hidden);shown.id=randomUUID();shown.assignments.find(row=>row.id===11)!.is_visible=true;normalize(shown,'2026-09-27T00:00:02.000Z');append(shown,'bulk');
 const duplicate=structuredClone(shown);duplicate.id=randomUUID();const original=duplicate.assignments.find(row=>row.id===11)!,source=duplicate.templates.find(row=>row.id===sourceTemplate.id)!.source_row;
 duplicate.assignments.push({...original,id:21,template_id:999,is_visible:false,sort_order:original.sort_order+1});normalize(duplicate,'2026-09-27T00:00:03.000Z');append(duplicate,'duplicate_assignment');duplicate.templateCopies.push({kind:sourceTemplate.kind,sourceTemplateId:sourceTemplate.id,row:{...source,id:999,name:source.name+' — نسخة',slug:source.slug+'-copy-999',status:'unpublished',created_at:'2026-09-27T00:00:03.000Z',updated_at:'2026-09-27T00:00:03.000Z'}});
 const reloaded=structuredClone(duplicate);reloaded.id=randomUUID();const states=[before,readonly,hidden,shown,duplicate,reloaded];
 const observations=['actual_information_back_and_focus','actual_edit_navigation_and_return','actual_current_public_link_opened','actual_visibility_cycle_reload_native','actual_duplicate_template_assignment_audit_handoff','unpublished_copy_visibility_disabled'];
 const rowActionsEvidence={kind:sourceTemplate.kind,sourceAssignmentId:11,sourceTemplateId:sourceTemplate.id,copyAssignmentId:21,copyTemplateId:999,observations,nativeIds:states.map(row=>row.id),automaticCoverage:[],globalClosed:false};
 const browser={scope:'core-closure',cohort:'page-composition',status:'pass',driverCompleted:true,inventoryOnly:false,errors:[],globalClosed:false,sourceSha256:'e'.repeat(64),requiredCases:[{key:'form:page-composition-and-seo:capability:modal',boundary:'form',consumer:'page-composition-and-seo'}],
  evidence:[{id:'existing-auth-login',status:'pass',coverage:[],authenticated:true,sessionArtifactWritten:false,dashboardState:'Dashboard جاهزة'},{id:'core-page-composition-'+sourceTemplate.kind+'-assignment',status:'pass',consumer:'page-composition-and-seo',coverage:[],automaticCoverage:[],templateId:sourceTemplate.id,assignmentId:11,rowActionsEvidence}]};
 const context={fixtures:{pages:{pageId,slug,editorPath:'/admin/pages-blocks/pages/'+pageId,templates:templateFixtures}},formManifest:manifest,collectionManifest,kinds:assignmentKinds,positionCapabilities:assignmentPositions.MODULE_POSITION_CAPABILITIES,getAssignablePositions:assignmentPositions.getAssignablePositions,ownedRunId:run,actorId:actor,sourceSha256:browser.sourceSha256};
 return{browser,native:{status:'pass',ownedRunId:run,records:states},context,states};
}
function assignmentJoin(value:ReturnType<typeof assignmentFixture>){return assignmentHelpers.assertCorePageAssignmentRowActionsJoin(value.browser,value.native,value.context);}
test('Actual assignment producer ID joins the existing private row proof',()=>{const value=assignmentFixture();value.browser.evidence[1].id=actualAssignmentJourneyId(value.browser.evidence[1].rowActionsEvidence!.kind);assignmentJoin(value);});
test('Page assignment join rejects the formerly mirrored identity',()=>{const value=assignmentFixture();value.browser.evidence[1].id='core-page-composition-assignment-'+value.browser.evidence[1].rowActionsEvidence!.kind;assert.throws(()=>assignmentJoin(value));});
test('Actual Page assignment row proof joins exactly six states and three atomic intents',()=>{const result=assignmentJoin(assignmentFixture());assert.equal(result.visibilityWrites,2);assert.equal(result.duplicateWrites,1);assert.equal(result.nativeIds.length,6);assert.equal(result.atomicAuditIds.length,3);assert.equal(result.globalClosed,false);assert.deepEqual(result.automaticCoverage,[]);});
for(const mode of ['failed-browser','source-drift','foreign-run','foreign-actor','missing-login','false-login','duplicate-login','missing-proof','duplicate-proof','wrong-kind','wrong-template','wrong-assignment','missing-observation','missing-native','duplicate-native','reordered-native','skipped-native','failed-native','phase-run-drift','phase-actor-drift','different-start','readonly-write','hidden-still-visible','other-row-visibility','wrong-normalization','hero-timestamp','show-still-hidden','copy-published','copy-field-drift','copy-wrong-parent','extra-copy','missing-audit','foreign-audit','nonatomic-audit','audit-history-drift','reload-write','wrong-copy-id','coverage-promotion','global-promotion'])test('Page assignment joined evidence rejects '+mode,()=>{
 const value=assignmentFixture(),{browser,native,context,states}=value,proof=browser.evidence[1].rowActionsEvidence!;
 if(mode==='failed-browser')browser.status='fail';else if(mode==='source-drift')context.sourceSha256='f'.repeat(64);else if(mode==='foreign-run')context.ownedRunId='foreign';else if(mode==='foreign-actor')context.actorId=52;
 else if(mode==='missing-login')browser.evidence.shift();else if(mode==='false-login')browser.evidence[0].authenticated=false;else if(mode==='duplicate-login')browser.evidence.push(browser.evidence[0]);else if(mode==='missing-proof')browser.evidence.pop();else if(mode==='duplicate-proof')browser.evidence.push({...browser.evidence[1],id:'other'});
 else if(mode==='wrong-kind')proof.kind='hero';else if(mode==='wrong-template')proof.sourceTemplateId=999;else if(mode==='wrong-assignment')proof.sourceAssignmentId=12;else if(mode==='missing-observation')proof.observations.pop();else if(mode==='missing-native')proof.nativeIds.pop();else if(mode==='duplicate-native')proof.nativeIds[1]=proof.nativeIds[0];else if(mode==='reordered-native')native.records.reverse();else if(mode==='skipped-native')native.records.splice(1,0,{...structuredClone(states[0]),id:randomUUID()});else if(mode==='failed-native')states[2].status='fail';else if(mode==='phase-run-drift')states[2].ownedRunId='foreign';else if(mode==='phase-actor-drift')states[2].qaActorId=52;else if(mode==='different-start')states[2].startedAt='2026-09-28T00:00:00Z';
 else if(mode==='readonly-write')states[1].page.row_hash='changed';else if(mode==='hidden-still-visible')states[2].assignments.find(row=>row.id===11)!.is_visible=true;else if(mode==='other-row-visibility')states[2].assignments.find(row=>row.id===12)!.is_visible=false;else if(mode==='wrong-normalization')states[2].assignments.find(row=>row.id===13)!.sort_order=20;else if(mode==='hero-timestamp')states[2].assignments.find(row=>row.kind==='hero')!.updated_at='changed';else if(mode==='show-still-hidden')states[3].assignments.find(row=>row.id===11)!.is_visible=false;
 else if(mode==='copy-published')states[4].templateCopies[0].row.status='published';else if(mode==='copy-field-drift')states[4].templateCopies[0].row.config={body:'foreign'};else if(mode==='copy-wrong-parent')states[4].templateCopies[0].sourceTemplateId=999;else if(mode==='extra-copy')states[4].templateCopies.push(structuredClone(states[4].templateCopies[0]));else if(mode==='missing-audit')states[2].audit=[];else if(mode==='foreign-audit')states[2].audit[0].actor_admin_user_id=52;else if(mode==='nonatomic-audit')states[2].audit[0].atomic=false;else if(mode==='audit-history-drift')states[3].audit[0].id=88;else if(mode==='reload-write')states[5].page.row_hash='changed';else if(mode==='wrong-copy-id')proof.copyTemplateId=998;else if(mode==='coverage-promotion')Object.assign(browser.evidence[1],{coverage:['foreign']});else browser.globalClosed=true;
 assert.throws(()=>assignmentJoin(value));
});
// The new native copy read is exercised through its actual scoped reader with fixed read-only ports.
const compositionModule={exports:{} as {readCorePageCompositionCheckpoint:(handle:unknown,request:unknown)=>Promise<unknown>}};
new Function('require','module','exports',ts.transpileModule(composition,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText)((id:string)=>id==='node:assert/strict'?assert:id.includes('isolated-supabase')?{assertOwnedLocalHandle:(handle:unknown)=>assert.ok(handle)}:id.includes('page-seo-contract')?{PAGE_SEO_PHASES}:{},compositionModule,compositionModule.exports);
async function controlledAssignmentNative(extraCopies=false){
 const value=assignmentFixture(),snapshot=value.states[4],calls:string[]=[],source=snapshot.templates.find(row=>row.kind===value.browser.evidence[1].rowActionsEvidence!.kind)!;
 const connection={async query(sql:string,params:unknown[]=[]){calls.push(sql);if(/^(begin|set local|commit|rollback)/u.test(sql))return{rows:[]};if(sql.includes('from public.admin_users'))return{rows:[{id:51}]};if(sql.includes('from public.pages'))return{rows:[snapshot.page]};if(sql.includes('from public.page_composition_assignments'))return{rows:snapshot.assignments};if(sql.includes('from public.page_composition_layouts'))return{rows:snapshot.layouts};if(sql.includes('from public.page_composition_regions'))return{rows:snapshot.regions};if(sql.includes('from public.admin_audit_logs'))return{rows:snapshot.audit};if(sql.includes('select id,name,slug,status')){assert.deepEqual(params,[source.id,'qa-admin-page-interaction-'+source.kind+'-%']);return{rows:[source]};}if(sql.includes('select to_jsonb(t) source_row')){assert.deepEqual(params,[source.slug+'-copy-%']);assert.match(sql,/order by id limit 2$/u);const row={source_row:snapshot.templateCopies[0].row};return{rows:extraCopies?[row,row]:[row]};}throw Error('Unexpected native query: '+sql);}};
 const handle={identity:{runId:'owned-assignment'},withDatabaseConnection:async(work:(scope:typeof connection)=>Promise<unknown>)=>work(connection)};
 try{const result=await compositionModule.exports.readCorePageCompositionCheckpoint(handle,{id:randomUUID(),kind:'page-composition-state',pageId:41,startedAt:snapshot.startedAt,layoutKeys:[],templateRefs:[{kind:source.kind,id:source.id}]}) as {templateCopies:unknown[]};assert.equal(result.templateCopies.length,1);assert.equal(calls.at(-1),'commit');return calls;}
 catch(error){assert.equal(calls.at(-1),'rollback');throw error;}
}
await controlledAssignmentNative();cases.push('Actual native copy projection uses bound namespace, finite result and read-only commit');
await assert.rejects(controlledAssignmentNative(true));cases.push('Actual native copy read rejects second copy and rolls back its scope');
test('Current SQL clone contract preserves authored fields and applies the unpublished successor',()=>{const sql=readFileSync(resolve(root,'sql/migrations/20260805180000_global_truth_atomic_operations_closure.sql'),'utf8');for(const marker of ["v_clone := v_source || jsonb_build_object(","'-copy-' || v_new_template_id::text","'{status}', '\"draft\"'::jsonb","'{is_visible}', 'false'::jsonb","jsonb_populate_record(null::public.%I, $1)","v_sort_order + 1, v_now"])assert.ok(sql.includes(marker),marker);const successor=readFileSync(resolve(root,"sql/migrations/20260807120000_system_publication_summary_cards_closure.sql"),"utf8");assert.ok(successor.includes('"unpublished"'));assert.ok(successor.includes("mutate_page_composition(bigint,text,jsonb,bigint,text)"));assert.ok(successor.includes("v_next := replace(v_definition, $old$"));});

function closureFixture(){
 const value=assignmentFixture(),initial=structuredClone(value.states[0]);initial.assignments=initial.assignments.filter(row=>row.kind==='hero');const template=value.context.fixtures.pages.templates.find(row=>row.kind==='content')!;const next=(state:typeof initial)=>({...structuredClone(state),id:randomUUID()}),audit=(state:typeof initial,operation:string)=>state.audit.push({id:state.audit.length+1,action:'page_composition.'+operation,entity_type:'page_composition',entity_id:41,actor_admin_user_id:51,operation,persistence_owner:'mutate_page_composition',atomic:true});const cancelled=next(initial),assigned=next(cancelled);assigned.assignments.push({kind:'content',id:70,page_id:41,template_id:template.id,slot:'main',sort_order:10,is_visible:false,updated_at:'2026-09-27T00:00:01Z'});audit(assigned,'save_assignment');const shown=next(assigned);shown.assignments[1].is_visible=true;shown.assignments[1].updated_at='2026-09-27T00:00:02Z';audit(shown,'bulk');const hidden=next(shown);hidden.assignments[1].is_visible=false;hidden.assignments[1].updated_at='2026-09-27T00:00:03Z';audit(hidden,'bulk');const layoutCancelled=next(hidden),saved=next(layoutCancelled),intent={templateId:template.id,slot:'main',sortOrder:10,layoutKey:'qa-core-layout-test',layoutName:'QA Layout'};saved.layouts.push({id:2,key:intent.layoutKey,admin_label:intent.layoutName});saved.regions.push({layout_id:2,key:'main',admin_label:'QA Main',sort_order:10});audit(saved,'save_layout');const states=[initial,cancelled,assigned,shown,hidden,layoutCancelled,saved],proof=assignmentHelpers.assertCorePageCompositionClosureStates(states,intent),namedCellBindings=[{boundary:'form',consumer:'page-composition-and-seo'},...['page-block-assignments','page-composition-shell'].map(consumer=>({boundary:'collection',consumer}))].flatMap(row=>['switch','busy_state'].map(axis=>({...row,axis,key:row.boundary+':'+row.consumer+':capability:'+axis}))),outcome={id:'core-page-composition-boolean-pending',status:'pass',coverage:[],pageId:41,...intent,...proof,nativeIds:states.map(row=>row.id),pending:['row','bulk'].map(mode=>({mode,requests:1,disabledDuringPending:true,busyVisible:true,duplicateBlocked:true,acknowledged:true})),assignVisible:false,assignAfterSave:false,pageLayoutUnchanged:true,namedCellBindings,automaticCoverage:[],globalClosed:false};return{states,intent,sourceSha256:value.context.sourceSha256,ownedRunId:value.context.ownedRunId,actorId:51,fixtures:value.context.fixtures,browser:{sourceSha256:value.context.sourceSha256,status:'pass',driverCompleted:true,cohort:'page-composition',journeySelection:'page-composition-closure-followup',wholeCohortExecuted:false,errors:[],evidence:[outcome],requiredCases:namedCellBindings.map(row=>({...row,scenario:'complete_applicable_capability_behavior'}))},native:{status:'pass',ownedRunId:value.context.ownedRunId,records:states}};
}
test('Closure Boolean and Instant Mutation guards join seven actual states and four unique native intents',()=>{const value=closureFixture();const joined=assignmentHelpers.assertCorePageCompositionClosureJoin(value);assert.equal(joined.joined.length,6);assert.equal(joined.auditIds.length,4);});
for(const mode of ['source','owner','actor','selector','whole','failed','missing','duplicate','order','cancel-write','assign-visible','template','other-assignment','row-not-shown','bulk-not-hidden','layout-cancel-write','page-assigned','layout-wrong-key','layout-regions','audit-missing','audit-actor','audit-atomic','pending-request','pending-busy','pending-duplicate','pending-ack','axis-missing','promote'])test('Closure exact joined intent rejects '+mode,()=>{const value=closureFixture(),row=value.browser.evidence[0],states=value.states;if(mode==='source')value.sourceSha256='f'.repeat(64);else if(mode==='owner')value.ownedRunId='foreign';else if(mode==='actor')value.actorId=99;else if(mode==='selector')value.browser.journeySelection='page-composition-followup';else if(mode==='whole')value.browser.wholeCohortExecuted=true;else if(mode==='failed')value.browser.status='fail';else if(mode==='missing')value.native.records.pop();else if(mode==='duplicate')row.nativeIds[1]=row.nativeIds[0];else if(mode==='order')value.native.records.reverse();else if(mode==='cancel-write')states[1].page.row_hash='changed';else if(mode==='assign-visible')states[2].assignments[1].is_visible=true;else if(mode==='template')states[2].assignments[1].template_id=999;else if(mode==='other-assignment')states[2].assignments[0].slot='main';else if(mode==='row-not-shown')states[3].assignments[1].is_visible=false;else if(mode==='bulk-not-hidden')states[4].assignments[1].is_visible=true;else if(mode==='layout-cancel-write')states[5].page.row_hash='changed';else if(mode==='page-assigned')states[6].page.layout_id=2;else if(mode==='layout-wrong-key')states[6].layouts[1].key='wrong';else if(mode==='layout-regions')states[6].regions.pop();else if(mode==='audit-missing')states[6].audit.pop();else if(mode==='audit-actor')states[6].audit.at(-1)!.actor_admin_user_id=99;else if(mode==='audit-atomic')states[6].audit.at(-1)!.atomic=false;else if(mode==='pending-request')row.pending[0].requests=2;else if(mode==='pending-busy')row.pending[0].busyVisible=false;else if(mode==='pending-duplicate')row.pending[0].duplicateBlocked=false;else if(mode==='pending-ack')row.pending[0].acknowledged=false;else if(mode==='axis-missing')value.browser.requiredCases.pop();else row.globalClosed=true;assert.throws(()=>assignmentHelpers.assertCorePageCompositionClosureJoin(value));});


// Exercise the actual client handlers after React's event dispatch lifetime, without a Browser or database.
function verifyPageLayoutRegionEventLifetime() {
 type Region = Readonly<{ draftId: string; key: string; adminLabel: string; sortOrder: number }>;
 type Update = (current: readonly Region[]) => readonly Region[];
 type Change = (event: { currentTarget: { value: string } | null }) => void;
 const source=readFileSync(resolve(root,'src/app/admin/pages-blocks/pages/[id]/PageLayoutManager.tsx'),'utf8');
 const file=ts.createSourceFile('PageLayoutManager.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
 const handlers=new Map<string,ts.Expression>();
 function visit(node:ts.Node) {
  if(ts.isJsxSelfClosingElement(node)&&node.tagName.getText(file)==='input') {
   const attributes=node.attributes.properties;
   const attribute=(name:string)=>attributes.find((value):value is ts.JsxAttribute=>ts.isJsxAttribute(value)&&value.name.getText(file)===name);
   const value=attribute('value')?.initializer;
   const field=value&&ts.isJsxExpression(value)?value.expression?.getText(file):undefined;
   if(field==='region.key'||field==='region.adminLabel') {
    const change=attribute('onChange')?.initializer;
    assert.ok(change&&ts.isJsxExpression(change)&&change.expression);
    assert.ok(!handlers.has(field),'one actual handler per region field');
    handlers.set(field,change.expression);
   }
  }
  ts.forEachChild(node,visit);
 }
 visit(file);
 assert.deepEqual([...handlers.keys()],['region.key','region.adminLabel']);
 function handler(field:'key'|'adminLabel',setRegions:(update:Update)=>void,index:number):Change {
  const expression=handlers.get('region.'+field);assert.ok(expression);
  const compiled=ts.transpileModule('const change = '+expression.getText(file)+';',{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
  return new Function('setRegions','index',compiled+';return change;')(setRegions,index) as Change;
 }
 const state=()=>Object.freeze([
  Object.freeze({draftId:'region-1',key:'main',adminLabel:'Main',sortOrder:10}),
  Object.freeze({draftId:'region-2',key:'sidebar',adminLabel:'Sidebar',sortOrder:20}),
  Object.freeze({draftId:'region-3',key:'footer',adminLabel:'Footer',sortOrder:30}),
 ]);
 for(const field of ['key','adminLabel'] as const)for(const value of ['QA Main','','المنطقة الثانية'])test('Layout actual '+field+' handler survives deferred event clearing: '+JSON.stringify(value),()=>{
  const queued:Update[]=[],current=state(),element={value},event:{currentTarget:{value:string}|null}={currentTarget:element};
  handler(field,update=>queued.push(update),1)(event);
  assert.equal(queued.length,1);element.value='later DOM value';event.currentTarget=null;
  // A preceding update may have changed a different row before this callback is reduced.
  const newer=Object.freeze([Object.freeze({...current[0],adminLabel:'Concurrent label'}),current[1],current[2]]);
  const before=structuredClone(newer),actual=queued[0](newer);
  assert.deepEqual(actual,[newer[0],{...newer[1],[field]:value},newer[2]]);
  assert.notEqual(actual,newer);assert.equal(actual[0],newer[0]);assert.equal(actual[2],newer[2]);assert.notEqual(actual[1],newer[1]);
  assert.deepEqual(newer,before);assert.deepEqual(queued[0](newer),actual);
 });
 for(const field of ['key','adminLabel'] as const)test('Layout actual '+field+' handler preserves synchronous update and last-row index',()=>{
  const current=state(),event:{currentTarget:{value:string}|null}={currentTarget:{value:'Last region'}};let actual:readonly Region[]=current;
  handler(field,update=>{actual=update(current);},2)(event);event.currentTarget=null;
  assert.deepEqual(actual,[current[0],current[1],{...current[2],[field]:'Last region'}]);
  assert.equal(actual[0],current[0]);assert.equal(actual[1],current[1]);
 });
 test('Layout actual queued key and label handlers compose on the latest region state',()=>{
  const queued:Update[]=[],current=state();
  for(const [field,value] of [['key','content'],['adminLabel','Content area']] as const){const event:{currentTarget:{value:string}|null}={currentTarget:{value}};handler(field,update=>queued.push(update),0)(event);event.currentTarget=null;}
  assert.equal(queued.length,2);const actual=queued.reduce((value,update)=>update(value),current as readonly Region[]);
  assert.deepEqual(actual,[{...current[0],key:'content',adminLabel:'Content area'},current[1],current[2]]);
 });
}
verifyPageLayoutRegionEventLifetime();

console.log(JSON.stringify({status:"pass",controls:cases.length,cases,runtimeExecuted:false,globalClosed:false}));
