import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {createRequire} from "node:module";
import {createJiti} from "jiti";
import ts from "typescript";
import * as React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {PRESENTATION_CONTROL_KINDS,PRESENTATION_CONTROL_PHASES,PRESENTATION_CONTROL_ASSETS,buildCorePresentationControlsPlan,validatePresentationControlsRequest,presentationControlForm,loadPresentationControlBuilders,assertPresentationControlsConfig,assertPresentationControlsRow} from "./fixtures/admin-core-presentation-controls-contract.mjs";
const root=resolve(import.meta.dirname,".."),jiti=createJiti(import.meta.url,{fsCache:false,moduleCache:false,alias:{"server-only":resolve(root,"node_modules/next/dist/compiled/server-only/empty.js")}});
const{ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST:manifest}=await jiti.import<typeof import("../src/lib/admin/form-system/adoption-manifest.ts")>(resolve(root,"src/lib/admin/form-system/adoption-manifest.ts"));
const fixtures={templates:PRESENTATION_CONTROL_KINDS.map((kind,index)=>({kind,id:index+1,name:"QA "+kind,slug:"qa-admin-page-interaction-"+kind+"-8",editPath:"/admin/pages-blocks/blocks/"+kind+"/"+(index+1)})),assets:PRESENTATION_CONTROL_ASSETS.map(objectKey=>({objectKey,publicUrl:"/"+objectKey}))};
const cases:string[]=[],test=(name:string,run:()=>unknown)=>{run();cases.push(name);};const builders=await loadPresentationControlBuilders();
test("Actual current Form manifest resolves only two concrete edit surfaces without axis promotion",()=>{const plan=buildCorePresentationControlsPlan({manifest,fixtures});assert.equal(plan.recipes.length,2);assert.ok(plan.recipes.every((row:{coverage:unknown[]})=>row.coverage.length===0));assert.deepEqual(plan.automaticAxisCoverage,[]);assert.equal(plan.globalClosed,false);assert.equal(plan.nonCapabilities.length,3);});
test("Missing current Hero adopter rejects",()=>assert.throws(()=>buildCorePresentationControlsPlan({manifest:manifest.filter(row=>!("registryModuleKind" in row)||row.registryModuleKind!=="hero"),fixtures})));
for(const delta of[{templates:fixtures.templates.slice(1)},{templates:[...fixtures.templates,fixtures.templates[0]]},{templates:fixtures.templates.map((row,index)=>index?row:{...row,slug:"real-template"})},{templates:fixtures.templates.map((row,index)=>index?row:{...row,id:0})},{templates:fixtures.templates.map((row,index)=>index?row:{...row,editPath:"/admin"})},{assets:fixtures.assets.map((row,index)=>index?row:{...row,publicUrl:"https://foreign.invalid"})}])test("Reject unowned fixture "+cases.length,()=>assert.throws(()=>buildCorePresentationControlsPlan({manifest,fixtures:{...fixtures,...delta}})));
const request={id:randomUUID(),kind:"presentation-controls-state",recipe:"hero",phase:"baseline"};test("Fixed twelve native phase requests",()=>{for(const recipe of PRESENTATION_CONTROL_KINDS)for(const phase of PRESENTATION_CONTROL_PHASES)validatePresentationControlsRequest({...request,recipe,phase});});
for(const delta of[{sql:"select 1"},{expected:{}},{table:"hero_templates"},{recipe:"__proto__"},{recipe:"constructor"},{phase:"skip"},{id:"bad"}])test("Reject arbitrary checkpoint "+JSON.stringify(delta),()=>assert.throws(()=>validatePresentationControlsRequest({...request,...delta})));
for(const kind of PRESENTATION_CONTROL_KINDS){
 const form=presentationControlForm(kind,fixtures),config=builders.build(kind,form);
 test("Actual private pure config builder round trip: "+kind,()=>assertPresentationControlsConfig(kind,config,fixtures));
 for(const key of["title","showTitle","titleBold","titleAlignment",...(kind==="hero"?["images","mobileImages","primaryCtaLink","secondaryCtaLink","imageComposition"]:["body"])])test("Native projection rejects missing authored "+kind+":"+key,()=>{const broken=structuredClone(config);delete broken[key];assert.throws(()=>assertPresentationControlsConfig(kind,broken,fixtures));});
 const original={id:kind==="hero"?1:2,name:"QA "+kind,slug:"qa-admin-page-interaction-"+kind+"-8",status:"published",variant:kind==="hero"?"internal-page":null,style_preset:null,description:null,created_at:"2026-01-01",updated_at:"2026-01-01",config:{title:"original"},...(kind==="hero"?{source_type:"manual",source_id:null,source_slug:null,limit_count:1,is_visible:true}:{}),other_identity:"retained"};
 const saved={...original,config,updated_at:"2026-01-02",variant:original.variant||"default",style_preset:kind==="hero"?"cinematic-gold":"premium-dark"};
 test("Exact current Action default normalization, identity preserved: "+kind,()=>assertPresentationControlsRow(kind,saved,original,config));
 for(const key of["id","slug","name","status","created_at","other_identity","config"])test("Native full row comparison rejects unrelated drift "+kind+":"+key,()=>assert.throws(()=>assertPresentationControlsRow(kind,{...saved,[key]:"changed"},original,config)));
}
test("Actual Hero builder stores cleared secondary CTA as null rather than a fabricated none object",()=>{const config=builders.build("hero",presentationControlForm("hero",fixtures));assert.equal(config.secondaryCtaLink,null);});
test("Current internal Hero forces canonical order; this journey does not claim editable element order",()=>{const form=presentationControlForm("hero",fixtures);form.set("hero_element_order","cta,title");assert.deepEqual(builders.build("hero",form).heroElementOrder,["eyebrow","title","highlight","subtitle","description","cta"]);});
const utils=await jiti.import<typeof import("../src/lib/page-blocks/admin-utils.ts")>(resolve(root,"src/lib/page-blocks/admin-utils.ts"));
for(const[kind,name]of [["hero","updateHeroTemplateDetails"],["content","updateContentBlock"]]){
 const file=resolve(root,"src/app/admin/pages-blocks/blocks",kind,"actions.ts"),source=readFileSync(file,"utf8"),tree=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true);const fn=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name);assert.ok(fn&&ts.isFunctionDeclaration(fn)&&fn.body);
 const firstGuard=fn.body.statements.findIndex(node=>ts.isIfStatement(node));assert.ok(firstGuard>0);const prefix=fn.body.statements.slice(0,firstGuard+1).map(node=>node.getText(tree)).join("\n");assert.doesNotMatch(prefix,/getSupabaseAdmin|mutatePageComposition|coordinateMedia/u);
 const code=ts.transpileModule("async function guard(formData:FormData){"+prefix+"}",{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 const guard=new Function("requireAdminSession","parseNumber","cleanText","slugify",code+";return guard;")(async()=>({id:99}),utils.parseNumber,utils.cleanText,utils.slugify) as (form:FormData)=>Promise<void>;
 const form=new FormData();form.set("id","1");form.set("slug","qa-valid");form.set("name","");await assert.rejects(guard(form));cases.push("Actual Action prewrite missing-name guard: "+kind);
 form.set("name","QA valid");await guard(form);cases.push("Actual Action prewrite guard permits canonical retry: "+kind);
}
// Render the actual shared formatting owner with actual leaf controls. Only CSS is stubbed.
const ownerFile=resolve(root,"src/components/admin/page-blocks/ModuleEditorPresentation.tsx"),ownerSource=readFileSync(ownerFile,"utf8"),tree=ts.createSourceFile(ownerFile,ownerSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const owner=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="ModuleEditorVisibilityAlignRow");assert.ok(owner);const ownerCode=ts.transpileModule(owner.getText(tree).replace(/^export /,""),{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
const leaf=(name:string)=>{const filename=resolve(root,"src/components/admin/ui",name+".tsx"),compiled=ts.transpileModule(readFileSync(filename,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const loaded={exports:{}};new Function("require","module","exports",compiled)(createRequire(import.meta.url),loaded,loaded.exports);return (loaded.exports as {default:React.ComponentType}).default;};
const Switch=leaf("AdminFormSwitch"),Format=leaf("AdminTextFormatControls");
const Row=new Function("React","useState","Children","AdminFormSwitch","AdminTextFormatControls","MODULE_EDITOR_CONTROL_CARD_CLASS_NAME",ownerCode+";return ModuleEditorVisibilityAlignRow;")(React,React.useState,React.Children,Switch,Format,"") as React.ComponentType<Record<string,unknown>>;
for(const mirrored of[false,true])test("Actual rendered "+(mirrored?"two mirrored CTA":"single text")+" toolbars retain one submitted format tuple",()=>{const html=renderToStaticMarkup(React.createElement(Row,{label:"QA",alignmentName:"cta_alignment",showName:"show_cta",boldName:"cta_bold",alignmentDefault:"center",showDefault:false,boldDefault:true,controlsPlacement:mirrored?"cards":"header"},React.createElement("div",{key:"a"},"A"),...(mirrored?[React.createElement("div",{key:"b"},"B")]:[])));for(const name of["show_cta","cta_alignment","cta_bold"])assert.equal(html.split('name="'+name+'"').length-1,1);assert.equal(html.split('role="switch"').length-1,mirrored?2:1);assert.equal(html.split('data-admin-text-format-bold=""').length-1,mirrored?2:1);assert.match(html,/name="show_cta" value="false"/u);assert.match(html,/name="cta_alignment" value="center"/u);});
const browser=readFileSync(resolve(root,"scripts/fixtures/admin-core-presentation-controls-journeys.mjs"),"utf8");test("No alternate interception, direct HTTP, hidden mutations, forced clicks or capability promotion",()=>{assert.doesNotMatch(browser,/page\.(route|unroute|request)|force:\s*true|\.selectOption\(|dispatchEvent\(/u);assert.match(browser,/nativeFinalityRequired:true/u);assert.match(browser,/fieldset\[data-admin-form-fields\]/u);assert.doesNotMatch(browser,/data-admin-form-pending-fields/u);assert.match(browser,/actualStatementCancelled:cancel/u);});
console.log(JSON.stringify({status:"pass",controls:cases.length,cases,runtimeExecuted:false,globalClosed:false}));
