import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { PGlite } from "@electric-sql/pglite";

const migration = readFileSync(
  new URL(
    "../sql/migrations/20260831202338_search_platform_autocomplete_regression.sql",
    import.meta.url,
  ),
  "utf8",
);

const db = new PGlite();

await db.exec(`
  create table public.content_block_templates (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    variant text not null,
    config jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
  );

  insert into public.content_block_templates (
    name,
    slug,
    variant,
    config,
    updated_at
  ) values (
    'Search Platform — Results',
    'search-platform',
    'search-platform',
    '{
      "scope": "all",
      "title": "ابحث في محتوى فينيسيا",
      "filters": ["content-type", "category", "series"],
      "helpText": "ابحث بالعنوان أو الملخص أو الرابط أو التصنيف أو السلسلة.",
      "resultLimit": 12
    }'::jsonb,
    '2026-08-31T00:00:00Z'::timestamptz
  ), (
    'Search — Topics',
    'topics-search',
    'search-platform',
    '{
      "scope": "selected",
      "filters": ["category", "series"],
      "helpText": "البحث في المقالات والعناوين والتصنيفات والسلاسل."
    }'::jsonb,
    '2026-08-31T00:00:00Z'::timestamptz
  );
`);

const untouchedBefore = await db.query<{
  config: Record<string, unknown>;
  updated_at: string;
}>(`
  select config, updated_at::text as updated_at
  from public.content_block_templates
  where slug = 'topics-search'
`);

await db.exec(migration);

const result = await db.query<{
  filters: string[];
  help_text: string;
  scope: string;
  title: string;
  result_limit: number;
  updated: boolean;
  updated_at: string;
}>(`
  select
    array(select jsonb_array_elements_text(config -> 'filters')) as filters,
    config ->> 'helpText' as help_text,
    config ->> 'scope' as scope,
    config ->> 'title' as title,
    (config ->> 'resultLimit')::integer as result_limit,
    updated_at > '2026-08-31T00:00:00Z'::timestamptz as updated,
    updated_at::text as updated_at
  from public.content_block_templates
  where slug = 'search-platform'
    and variant = 'search-platform'
`);

assert.equal(result.rows.length, 1);
assert.deepEqual(
  {
    filters: result.rows[0]?.filters,
    help_text: result.rows[0]?.help_text,
    scope: result.rows[0]?.scope,
    title: result.rows[0]?.title,
    result_limit: result.rows[0]?.result_limit,
    updated: result.rows[0]?.updated,
  },
  {
    filters: ["content-type"],
    help_text: "ابحث بالعنوان أو الملخص أو الرابط.",
    scope: "all",
    title: "ابحث في محتوى فينيسيا",
    result_limit: 12,
    updated: true,
  },
);

const firstUpdatedAt = result.rows[0]?.updated_at;
assert.ok(firstUpdatedAt);

await new Promise((resolve) => setTimeout(resolve, 10));
await db.exec(migration);

const rerun = await db.query<{
  config: Record<string, unknown>;
  updated_at: string;
}>(`
  select config, updated_at::text as updated_at
  from public.content_block_templates
  where slug = 'search-platform'
    and variant = 'search-platform'
`);
assert.equal(rerun.rows[0]?.updated_at, firstUpdatedAt);

const untouched = await db.query<{
  config: Record<string, unknown>;
  updated_at: string;
}>(`
  select config, updated_at::text as updated_at
  from public.content_block_templates
  where slug = 'topics-search'
`);
assert.deepEqual(untouched.rows, untouchedBefore.rows);

await db.close();

console.log(
  "PASS Search Platform regression migration: the canonical results template keeps general-search content-type filtering, preserves unrelated config, leaves other Search templates untouched, and is strictly idempotent on rerun.",
);
