import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { PGlite } from "@electric-sql/pglite";

const migration = readFileSync(
  new URL(
    "../sql/migrations/20260828233733_featured_page_composition_module.sql",
    import.meta.url,
  ),
  "utf8",
);

const db = new PGlite();

await db.exec(`
  create role anon;
  create role authenticated;
  create role service_role;

  create table public.pages (
    id bigint primary key,
    slug text not null unique
  );

  create table public.topics (
    id bigint primary key,
    slug text not null,
    category_slug text,
    content_type text not null,
    status text not null,
    deleted_at timestamptz,
    is_featured boolean not null default false,
    published_at timestamptz
  );

  create table public.media_hub_module_templates (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    description text,
    status text not null default 'unpublished',
    section_key text not null,
    config jsonb not null default '{}'::jsonb,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );

  create table public.admin_audit_logs (
    id bigint generated by default as identity primary key,
    actor_admin_user_id bigint,
    actor_username text,
    action text,
    entity_type text,
    entity_id bigint,
    entity_label text,
    metadata jsonb
  );

  create function public.enforce_page_composition_atomic_contract()
  returns trigger language plpgsql as $$
  begin
    if current_setting('app.page_composition_write', true) is distinct from 'on' then
      raise exception 'atomic owner required';
    end if;
    return coalesce(new, old);
  end;
  $$;

  create table public.page_content_block_assignments (
    id bigint primary key, page_id bigint not null, template_id bigint not null,
    slot text not null, sort_order integer not null, is_visible boolean not null,
    updated_at timestamptz not null default now()
  );
  create table public.page_cta_block_assignments
    (like public.page_content_block_assignments including all);
  create table public.page_cards_block_assignments
    (like public.page_content_block_assignments including all);
  create table public.page_breadcrumb_block_assignments
    (like public.page_content_block_assignments including all);
  create table public.page_feed_module_assignments
    (like public.page_content_block_assignments including all);
  create table public.page_media_sidebar_module_assignments
    (like public.page_content_block_assignments including all);
  create table public.page_media_hub_module_assignments (
    id bigint primary key,
    page_id bigint not null references public.pages(id) on delete cascade,
    template_id bigint not null references public.media_hub_module_templates(id) on delete cascade,
    slot text not null,
    sort_order integer not null,
    is_visible boolean not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );
  create table public.hero_assignments (
    id bigint primary key,
    target_id bigint,
    hero_id bigint not null,
    target_type text not null,
    priority integer not null,
    is_active boolean not null,
    updated_at timestamptz not null default now()
  );

  create trigger page_composition_atomic_guard before insert or update or delete
    on public.page_content_block_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();
  create trigger page_composition_atomic_guard before insert or update or delete
    on public.page_cta_block_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();
  create trigger page_composition_atomic_guard before insert or update or delete
    on public.page_cards_block_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();
  create trigger page_composition_atomic_guard before insert or update or delete
    on public.page_breadcrumb_block_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();
  create trigger page_composition_atomic_guard before insert or update or delete
    on public.page_feed_module_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();
  create trigger page_composition_atomic_guard before insert or update or delete
    on public.page_media_sidebar_module_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();
  create trigger page_composition_atomic_guard before insert or update or delete
    on public.page_media_hub_module_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();
  create trigger page_composition_atomic_guard before insert or update or delete
    on public.hero_assignments for each row
    execute function public.enforce_page_composition_atomic_contract();

  create function public.admin_list_pages(
    p_page integer, p_page_size integer, p_search text, p_status text, p_sort text
  ) returns setof bigint language sql stable as $$
    with assignment_pages as (
      select page_id from public.page_content_block_assignments
      union all select page_id from public.page_feed_module_assignments
    )
    select id from public.pages
    where id in (select page_id from assignment_pages) or p_search is null
    order by id
  $$;

  create function public.mutate_page_composition(
    p_page_id bigint,
    p_operation text,
    p_payload jsonb,
    p_actor_admin_user_id bigint,
    p_request_identity text
  ) returns jsonb language plpgsql security definer as $$
  declare
    v_assignment_table text;
    v_template_table text;
    v_table record;
  begin
    perform 1 from public.page_feed_module_assignments where page_id = p_page_id order by id for update;
    v_assignment_table := case p_payload ->> 'module_kind'
      when 'feed' then 'page_feed_module_assignments'
      when 'media-sidebar' then 'page_media_sidebar_module_assignments'
      when 'media-hub' then 'page_media_hub_module_assignments'
      else null end;
    v_template_table := case p_payload ->> 'module_kind'
      when 'feed' then 'feed_module_templates'
      when 'media-sidebar' then 'media_sidebar_module_templates'
      when 'media-hub' then 'media_hub_module_templates'
      else null end;
    for v_table in
      select table_name from (values
        ('page_feed_module_assignments'), ('page_media_sidebar_module_assignments'),
        ('page_media_hub_module_assignments')
      ) as assignment_tables(table_name)
    loop
      null;
    end loop;
    return jsonb_build_object(
      'page_id', p_page_id,
      'assignment_table', v_assignment_table,
      'template_table', v_template_table
    );
  end;
  $$;

  create function public.global_truth_atomic_closure_health()
  returns jsonb language sql stable as $$
    select jsonb_build_object(
      'page_composition_atomic_operations_closed',
      (select count(*) from pg_trigger where tgname='page_composition_atomic_guard' and not tgisinternal) = 8
    )
  $$;

  select set_config('app.page_composition_write', 'on', false);
  insert into public.pages (id, slug) values (1, 'topics'), (2, 'media-center');
  insert into public.topics (
    id, slug, category_slug, content_type, status, is_featured, published_at
  ) values (
    101, 'featured-topic', 'architecture', 'article', 'published', true, now()
  );
  insert into public.media_hub_module_templates (
    id, name, slug, description, status, section_key, config, sort_order
  ) values
    (10, 'Legacy Featured', 'media-featured', null, 'published', 'featured',
      '{"placement":"hub","type":"site_update","itemLimit":4,"presentation":{"title":"Updates"}}', 20),
    (11, 'Media Listing', 'media-listing', null, 'published', 'featured',
      '{"placement":"listing","type":"news"}', 30);
  insert into public.page_media_hub_module_assignments (
    id, page_id, template_id, slot, sort_order, is_visible
  ) values (20, 2, 10, 'main', 20, true);
`);

await db.exec(migration);

const templates = await db.query<{
  slug: string;
  source_kind: string;
  content_type: string | null;
  category_slug: string | null;
}>(`
  select
    slug,
    config #>> '{source,kind}' as source_kind,
    config #>> '{source,contentType}' as content_type,
    config #>> '{source,categorySlug}' as category_slug
  from public.featured_module_templates
  order by slug
`);
assert.deepEqual(templates.rows, [
  {
    slug: "media-featured",
    source_kind: "media-center",
    content_type: "site_update",
    category_slug: null,
  },
  {
    slug: "topics-featured",
    source_kind: "categories",
    content_type: null,
    category_slug: "architecture",
  },
]);

const assignments = await db.query<{ page_id: bigint; slug: string; slot: string }>(`
  select assignment.page_id, template.slug, assignment.slot
  from public.page_featured_module_assignments assignment
  join public.featured_module_templates template on template.id = assignment.template_id
  order by assignment.page_id
`);
assert.deepEqual(
  assignments.rows.map((row) => ({ ...row, page_id: Number(row.page_id) })),
  [
    { page_id: 1, slug: "topics-featured", slot: "main" },
    { page_id: 2, slug: "media-featured", slot: "main" },
  ],
);

const remainingLegacy = await db.query<{ slug: string }>(`
  select slug from public.media_hub_module_templates order by slug
`);
assert.deepEqual(remainingLegacy.rows, [{ slug: "media-listing" }]);

const ownership = await db.query<{
  assignment_owner: boolean;
  read_owner: boolean;
  trigger_count: number;
  rls_templates: boolean;
  rls_assignments: boolean;
}>(`
  select
    position(
      'page_featured_module_assignments' in pg_get_functiondef(
        'public.mutate_page_composition(bigint,text,jsonb,bigint,text)'::regprocedure
      )
    ) > 0 as assignment_owner,
    position(
      'page_featured_module_assignments' in pg_get_functiondef(
        'public.admin_list_pages(integer,integer,text,text,text)'::regprocedure
      )
    ) > 0 as read_owner,
    (select count(*)::integer from pg_trigger
      where tgname = 'page_composition_atomic_guard' and not tgisinternal) as trigger_count,
    (select relrowsecurity from pg_class
      where oid = 'public.featured_module_templates'::regclass) as rls_templates,
    (select relrowsecurity from pg_class
      where oid = 'public.page_featured_module_assignments'::regclass) as rls_assignments
`);
assert.deepEqual(ownership.rows[0], {
  assignment_owner: true,
  read_owner: true,
  trigger_count: 9,
  rls_templates: true,
  rls_assignments: true,
});

await assert.rejects(
  db.exec(`insert into public.featured_module_templates (
    name, slug, status, config
  ) values ('Invalid', 'invalid-draft', 'draft', '{}')`),
  /featured_module_templates_status_check/u,
);

const health = await db.query<{ closed: boolean }>(`
  select (public.global_truth_atomic_closure_health()
    ->> 'page_composition_atomic_operations_closed')::boolean as closed
`);
assert.equal(health.rows[0]?.closed, true);

await db.close();
console.log(
  "Featured Module PostgreSQL verification passed: migration, ownership transfer, binary publication, RLS, atomic owner adoption, and generic Topics/Media assignments are executable.",
);
