import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {PGlite} from '@electric-sql/pglite';
import ts from 'typescript';
import * as queryPresentationPlan from './fixtures/admin-core-query-presentation-plan.mjs';
const {loadCoreQueryPresentationPlan,registeredEntityKeys,coreQueryScenario,CORE_ACTIVITY_DATE_SCENARIOS,assertCoreActivityDateReceipts,CORE_QUERY_SEARCH_SCENARIOS,CORE_QUERY_STALE_SCENARIOS,coreQueryStaleOwner,coreQueryViewScenarios,coreQuerySearchColumns,coreQueryExtraFilterCases}=queryPresentationPlan;
import {assertCoreQueryProjection,assertCoreQueryLocation} from './fixtures/admin-core-query-presentation-journeys.mjs';
import {parseAdminEntityListRequestQuery} from '../src/lib/admin/entity-list/data-engine/contracts.ts';
import type {OwnedLocalHandle} from './lib/isolated-supabase.mts';
import type {CoreQueryFixtures} from './verify-admin-core-query-presentation-isolated.mts';
const require=createRequire(import.meta.url),db=new PGlite(),plan=await loadCoreQueryPresentationPlan();
const statements:string[]=[];let active=true,scopes=0;
const query=async(sql:string,values?:unknown[])=>{assert.ok(active);statements.push(sql);const result=await db.query<Record<string,unknown>>(sql,values);return {rows:result.rows,rowCount:result.rows.length};};
const handle={identity:{runId:'a'.repeat(32)},withDatabaseConnection:async<T,>(work:(connection:{query:typeof query})=>Promise<T>)=>{assert.ok(active);scopes++;try{return await work({query});}finally{scopes--;}}} as unknown as OwnedLocalHandle;
const isolated={assertOwnedLocalHandle:(candidate:unknown)=>{assert.ok(active);assert.equal(candidate,handle);}};
function compiledOwner(file:string,ports:Record<string,unknown>){const source=readFileSync(resolve(import.meta.dirname,file),'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const target={exports:{}};new Function('require','module','exports',output)((name:string)=>{if(name in ports)return ports[name];assert.equal(name,'node:assert/strict');return require(name);},target,target.exports);return target.exports;}
const actor=compiledOwner('verify-admin-core-domain-readback-isolated.mts',{'./lib/isolated-supabase.mts':isolated});
const makeOwner=()=>compiledOwner('verify-admin-core-query-presentation-isolated.mts',{'./lib/isolated-supabase.mts':isolated,'./verify-admin-core-domain-readback-isolated.mts':actor,'../src/lib/admin/entity-list/data-engine/contracts.ts':{parseAdminEntityListRequestQuery},'./fixtures/admin-core-query-presentation-plan.mjs':queryPresentationPlan}) as typeof import('./verify-admin-core-query-presentation-isolated.mts');
const owner=makeOwner();
const fixtures:CoreQueryFixtures={queryClosure:{contexts:{}}};let id=100;
const checks:string[]=[];const test=async(name:string,callback:()=>void|Promise<void>)=>{await callback();checks.push(name);};
const request=(routeKey='topics',scenario='first')=>({id:randomUUID(),kind:'query-presentation-state',routeKey,scenario});
const read=(routeKey='topics',scenario='first')=>owner.readCoreQueryPresentationCheckpoint(handle,request(routeKey,scenario),fixtures);
try{
 const tables=new Map<string,Set<string>>();for(const spec of plan){const names=tables.get(spec.table)??new Set(['id','status','deleted_at','image','content_type','is_active','is_visible','publication_status','entity_type','type','level','project_id','stage_id','item_id','path','slug']);names.add(spec.labelColumn);names.add(spec.sortField);for(const column of coreQuerySearchColumns(spec))names.add(column);for(const column of ['category_id','parent_id','series_id','featured','is_featured','redirect_type','actor_username','action','role'])names.add(column);tables.set(spec.table,names);}
 for(const[table,names]of tables){if(table==='admin_users')for(const name of ['username','email','role'])names.add(name);if(table==='topic_categories')for(const key of['description','color_token','sort_order','published_at','created_at','updated_at'])names.add(key);const declaration=[...names].map(name=>'"'+name+'" '+(name==='id'?'bigint primary key':name==='sort_order'?'integer':name.endsWith('_id')?'bigint':name==='is_active'||name==='is_visible'||name==='featured'||name==='is_featured'?'boolean':name.endsWith('_at')?'timestamptz':'text')).join(',');await db.exec(`create table public.${table}(${declaration});`);}
 const contentFoundation=readFileSync(resolve(import.meta.dirname,'../sql/migrations/20260717070000_unified_content_engine_foundation.sql'),'utf8');
 const viewStatements=[...contentFoundation.replace(/^\s*--.*$/gmu,'').matchAll(/alter table public\.topics\b[\s\S]*?;/giu)].map(match=>match[0]).filter(statement=>/\bviews_count\b/u.test(statement));assert.ok(viewStatements.length>0);for(const statement of viewStatements)await db.exec(statement);
 await test('Canonical migration owns Topics views_count bigint rather than a fabricated verifier column',async()=>{const columns=(await db.query<{column_name:string;data_type:string;is_nullable:string}>("select column_name,data_type,is_nullable from information_schema.columns where table_schema='public' and table_name='topics' and column_name in ('views_count','view_count') order by column_name")).rows;assert.deepEqual(columns,[{column_name:'views_count',data_type:'bigint',is_nullable:'NO'}]);});
 await test('The old native information projection rejects the misspelled column with SQLSTATE42703',async()=>{await assert.rejects(db.query('select id,view_count from public.topics'),(error:unknown)=>Boolean(error&&typeof error==='object'&&'code' in error&&error.code==='42703'));});
 await test('Canonical view-count default and nonnegative constraint remain enforced in controlled SQL',async()=>{await db.query('insert into public.topics(id) values($1)',[899990]);const rows=(await db.query<{views_count:number}>('select views_count from public.topics where id=$1',[899990])).rows;assert.equal(Number(rows[0].views_count),0);await assert.rejects(db.query('update public.topics set views_count=-1 where id=$1',[899990]),(error:unknown)=>Boolean(error&&typeof error==='object'&&'code' in error&&error.code==='23514'));await db.query('delete from public.topics where id=$1',[899990]);});
 await db.exec("insert into public.admin_users(id,username,email,role,is_active) values(7,'qa_admin_interaction','qa-admin-interaction@example.invalid','admin',true);create table public.admin_user_preferences(admin_user_id bigint,view_key text,preferences jsonb);");
 const taxonomySql=readFileSync(resolve(import.meta.dirname,'../sql/migrations/20260808120000_taxonomy_lifecycle_contract.sql'),'utf8'),categoryFunction=taxonomySql.match(/create function public\.admin_list_categories\([\s\S]*?\$\$;/u)?.[0];assert.ok(categoryFunction&&categoryFunction.includes('stable')&&categoryFunction.includes('security invoker'));await db.exec(categoryFunction);
 await db.exec("insert into public.topic_categories(id,name) values(90,'Controlled category'); insert into public.topic_categories(id,name,slug,status,parent_id,sort_order,deleted_at) values(900003,'Zulu','controlled-trash-parent','unpublished',null,1,'2026-01-02'),(900004,'Alpha','controlled-trash-child','unpublished',900003,0,'2026-01-02'); insert into public.topics(id,title,status,deleted_at) values(900001,'Controlled Topic trash','unpublished','2026-01-02');insert into public.topic_series(id,name,status,deleted_at) values(900002,'Controlled Series trash','unpublished','2026-01-02');");
 for(const spec of plan){const search='qa-b1-control-'+spec.key.replaceAll('_','-')+'-rows',ids:number[]=[];const f={search,ids,...(['topics','series'].includes(spec.entity)?{filterOptions:{category:{id:90,name:'Controlled category'},...(spec.entity==='topics'?{series:{id:91,name:'Controlled series'}}:{})}}:{}),...(spec.kind?{projectId:99}:{}),...(spec.kind==='items'?{stageId:98}:{}),...(spec.kind==='updates'?{itemId:97}:{})};fixtures.queryClosure.contexts[spec.key]=f;
  for(let i=0;i<spec.rowCount;i++){
   const row:Record<string,unknown>={id:++id,[spec.labelColumn]:search+' '+String(Math.floor(i/2)).padStart(3,'0'),status:spec.entity==='redirects'?(i%2===0?'active':'inactive'):(i%2===0?'published':'unpublished'),image:spec.entity==='topics_without_image'?'':'image',content_type:i%2===0?'article':'news',is_active:i%2===0,is_visible:i%2===0,publication_status:spec.kind==='updates'?(i%2===0?'unpublished':'draft'):(i%2===0?'published':'unpublished'),entity_type:i%2===0?'topic':'page',type:spec.type,level:spec.level,project_id:99,stage_id:98,item_id:97,path:'/qa/'+id,slug:'qa-'+id,category_id:90,parent_id:null,series_id:spec.entity==='topics'&&i%3===0?91:null,featured:i%2===0,is_featured:i%2===0,redirect_type:'302',actor_username:'qa_admin_interaction',action:i%2===0?'topic.update':'page.update',role:'admin'};
   if(spec.table==='topics')row.views_count=1234+i;
   if(spec.sortField.endsWith('_at'))row[spec.sortField]=new Date(Date.UTC(2026,0,3,0,Math.floor(i/2))).toISOString();
   const keys=Object.keys(row);await db.query(`insert into public.${spec.table}(${keys.map(key=>'"'+key+'"').join(',')}) values(${keys.map((_,index)=>'$'+(index+1)).join(',')})`,Object.values(row));ids.push(id);
  }
 }
 const projectReadSql=readFileSync(resolve(import.meta.dirname,'../sql/migrations/20260803120000_project_publishing_visibility_capability.sql'),'utf8'),projectFunction=projectReadSql.match(/create or replace function public\.admin_list_projects\([\s\S]*?\$function\$;/u)?.[0];assert.ok(projectFunction);
 await db.exec('alter table public.projects add column if not exists city_id bigint, add column if not exists main_area_id bigint, add column if not exists sub_area_id bigint, add column if not exists published_at timestamptz, add column if not exists updated_at timestamptz');await db.exec(projectFunction);
 const publicationSql=readFileSync(resolve(import.meta.dirname,'../sql/migrations/20260807120000_system_publication_summary_cards_closure.sql'),'utf8'),projectReadRewrites=[...publicationSql.matchAll(/do \$\$[\s\S]*?\$\$;/giu)].map(match=>match[0]).filter(sql=>sql.includes("pg_get_functiondef('public.admin_list_projects("));assert.equal(projectReadRewrites.length,1);await db.exec(projectReadRewrites[0]);
 for(const spec of plan.filter(row=>row.entity==='projects'))for(const scenario of ['first','descending']){
  await test('Native Project '+spec.key+' '+scenario+' order equals actual canonical RPC including duplicate-name ties',async()=>{const native=await read(spec.key,scenario),params=coreQueryScenario(spec,fixtures.queryClosure.contexts[spec.key],scenario),parsed=parseAdminEntityListRequestQuery(spec.contract,params),actual=(await db.query<{value:{rows:Array<{id:number;arabic_name:string}>;total_count:number}}>("select public.admin_list_projects($1,$2,$3,$4,$5,$6,'all','all') value",[1,parsed.pageSize,parsed.sort.field,parsed.sort.direction,spec.type,parsed.search])).rows[0].value;assert.equal(Number(actual.total_count),spec.rowCount);assert.deepEqual(actual.rows.map(row=>Number(row.id)),native.expectedIds);const tied=actual.rows.filter((row,index,rows)=>index>0&&row.arabic_name===rows[index-1].arabic_name);assert.ok(tied.length>0);for(const row of tied){const index=actual.rows.indexOf(row);assert.ok(Number(actual.rows[index-1].id)>Number(row.id));}});
  await test('Old IDASC Project tie cannot satisfy canonical '+spec.key+' '+scenario+' order',async()=>{const native=await read(spec.key,scenario),params=coreQueryScenario(spec,fixtures.queryClosure.contexts[spec.key],scenario),parsed=parseAdminEntityListRequestQuery(spec.contract,params),old=(await db.query<{id:number}>("select id from public.projects where type=$1 and arabic_name like $2 order by arabic_name "+(parsed.sort.direction==='asc'?'asc':'desc')+",id asc",[spec.type,'%'+fixtures.queryClosure.contexts[spec.key].search+'%'])).rows.map(row=>Number(row.id));assert.deepEqual([...old].sort((a,b)=>a-b),[...native.completeIds].sort((a,b)=>a-b));assert.throws(()=>assert.deepEqual(old,native.completeIds));});
 }
 await test('Actual canonical taxonomy tree SQL preserves parent-first trash order over raw membership',async()=>{const result=(await db.query<{value:{rows:Array<{id:number;deleted_at:string}>;total_count:number}}>("select public.admin_list_categories(1,10,'tree','asc','','all','trash') value")).rows[0].value;assert.deepEqual(result.rows.map(row=>Number(row.id)),[900003,900004]);assert.equal(Number(result.total_count),2);assert.ok(result.rows.every(row=>row.deleted_at!==null));const raw=(await db.query<{id:number}>('select id from public.topic_categories where deleted_at is not null order by id')).rows.map(row=>Number(row.id));assert.deepEqual([...result.rows.map(row=>Number(row.id))].sort((a,b)=>a-b),raw);});
 await test('Exact current registry and manifest route contexts derive the page-sized fixture bound',()=>{assert.equal(plan.length,17);assert.equal(new Set(plan.map(spec=>spec.consumerId)).size,13);assert.equal(new Set(plan.map(spec=>spec.entity)).size,16);for(const spec of plan)assert.equal(spec.rowCount,2*Math.min(...spec.contract.pageSizeOptions)+3);});
 await test('Current canonical Browser URL contract matches the native requested page',async()=>{const spec=plan.find(r=>r.key==='topics')!,receipt=await read('topics','second');assertCoreQueryLocation(spec,fixtures.queryClosure.contexts.topics,receipt,'http://127.0.0.1:31001'+receipt.route+'?'+receipt.query,'http://127.0.0.1:31001');});
 await test('Wrong URL query, sort, filter, page, size or origin cannot satisfy a matching row projection',async()=>{const spec=plan.find(r=>r.key==='topics')!,receipt=await read('topics','second');for(const[key,value]of [['q','different'],['sort','title_desc'],['status','unpublished'],['page','3'],['limit','20']]){const params=new URLSearchParams(receipt.query);params.set(key,value);assert.throws(()=>assertCoreQueryLocation(spec,fixtures.queryClosure.contexts.topics,receipt,'http://127.0.0.1:31001'+receipt.route+'?'+params,'http://127.0.0.1:31001'));}assert.throws(()=>assertCoreQueryLocation(spec,fixtures.queryClosure.contexts.topics,receipt,'http://127.0.0.1:31002'+receipt.route+'?'+receipt.query,'http://127.0.0.1:31001'));});
 await test('Actual AST registry reader rejects nonobject and unknown spread ownership',()=>{assert.throws(()=>registeredEntityKeys('export const adminEntityListAdapterRegistry = other;'));assert.throws(()=>registeredEntityKeys('export const adminEntityListAdapterRegistry = {...other};'));});
 for(const spec of plan)await test('Native ordered pages, union, filter and clamp: '+spec.key,async()=>{
  const first=await read(spec.key),second=await read(spec.key,'second'),third=await read(spec.key,'third');assert.equal(first.actorId,7);if(spec.entity==='topics')assert.equal(first.rows[0].information?.viewCount,1234);else assert.equal(first.rows[0].information,undefined);assert.deepEqual([...first.expectedIds,...second.expectedIds,...third.expectedIds],first.completeIds);assert.equal(new Set(first.completeIds).size,spec.rowCount);
  const clamp=await read(spec.key,'clamp');assert.deepEqual(clamp.expectedIds,third.expectedIds);assert.equal(clamp.pagination.page,3);
  const empty=await read(spec.key,'empty');assert.deepEqual(empty.expectedIds,[]);assert.equal(empty.pagination.totalRows,0);
  const wide=await read(spec.key,'wide');assert.ok(wide.expectedIds.length>first.expectedIds.length);
  const descending=await read(spec.key,'descending');assert.notDeepEqual(descending.expectedIds,first.expectedIds);assert.deepEqual([...descending.completeIds].sort((a,b)=>a-b),[...first.completeIds].sort((a,b)=>a-b));
  if(spec.filter){const filtered=await read(spec.key,'filtered');assert.ok(filtered.completeIds.length>0&&filtered.completeIds.length<first.completeIds.length,spec.key+JSON.stringify({filtered:filtered.completeIds.length,total:first.completeIds.length}));}
  assert.equal(statements.at(-1),'commit');assert.equal(scopes,0);
 });
 for(const spec of plan)await test('Actual current native literal, short, cleared and remaining filter SQL: '+spec.key,async()=>{
  const first=await read(spec.key);
  for(const scenario of CORE_QUERY_SEARCH_SCENARIOS){const receipt=await read(spec.key,scenario);assert.ok(receipt.searchProjection);assert.equal(receipt.searchProjection.scope,'full-registered-route');if(scenario.startsWith('search-literal-'))assert.deepEqual(receipt.completeIds,[]);if(scenario==='search-restored')assert.deepEqual(receipt.completeIds,first.completeIds);}
  for(const recipe of coreQueryExtraFilterCases(spec,fixtures.queryClosure.contexts[spec.key])){const receipt=await read(spec.key,recipe.scenario);assert.ok(receipt.extraFilterProjection);assert.ok(receipt.completeIds.every(id=>first.completeIds.includes(id)));if(recipe.phase==='cleared')assert.deepEqual(receipt.completeIds,first.completeIds);if(spec.entity==='topics'&&recipe.key==='series'&&recipe.phase==='applied')assert.deepEqual(receipt.completeIds,first.completeIds.filter((_,index)=>index%3===0));if(spec.entity==='projects'&&recipe.key==='featured'&&recipe.phase==='applied')assert.equal(receipt.completeIds.length,recipe.value==='yes'?Math.ceil(spec.rowCount/2):Math.floor(spec.rowCount/2));}
 });
 await test('Actual Activity native SQL evaluates all six current inclusive, empty and cleared UTC date boundaries',async()=>{
  const spec=plan.find(row=>row.entity==='activity_log')!,baseline=await read(spec.key,'filtered');
  for(const scenario of Object.keys(CORE_ACTIVITY_DATE_SCENARIOS)){
   const receipt=await read(spec.key,scenario);assert.deepEqual(receipt.completeIds,scenario.endsWith('-empty')?[]:baseline.completeIds);
   const params=coreQueryScenario(spec,fixtures.queryClosure.contexts[spec.key],scenario),projection=receipt.dateFilterProjection!;
   assert.equal(projection.dateFrom,params.get('dateFrom')??'');assert.equal(projection.dateTo,params.get('dateTo')??'');
   assert.equal(projection.lower,projection.dateFrom?projection.dateFrom+'T00:00:00.000Z':null);assert.equal(projection.upper,projection.dateTo?projection.dateTo+'T23:59:59.999Z':null);
   assert.deepEqual(projection.timestamps.map(row=>row.id),receipt.completeIds);assert.equal(receipt.actorId,7);assert.equal(receipt.fixtureFingerprint,baseline.fixtureFingerprint);
   for(const row of projection.timestamps){const stamp=Date.parse(row.createdAt);assert.ok(Number.isFinite(stamp));if(projection.lower)assert.ok(stamp>=Date.parse(projection.lower));if(projection.upper)assert.ok(stamp<=Date.parse(projection.upper));}
  }
 });
 await test('Date scenarios cannot escape Activity or accept caller dates before SQL',async()=>{
  for(const value of [request('topics','date-from-included'),request('activity_log','date-from-unknown'),{...request('activity_log','date-to-included'),dateTo:'2026-01-04'}]){const count=statements.length;await assert.rejects(owner.readCoreQueryPresentationCheckpoint(handle,value,fixtures));assert.equal(statements.length,count);}
 });
 await test('Missing original date port reproduces the baseline stale controlled-fixture fault',async()=>{
  const incomplete={...queryPresentationPlan,CORE_ACTIVITY_DATE_SCENARIOS:undefined};
  const old=compiledOwner('verify-admin-core-query-presentation-isolated.mts',{'./lib/isolated-supabase.mts':isolated,'./verify-admin-core-domain-readback-isolated.mts':actor,'../src/lib/admin/entity-list/data-engine/contracts.ts':{parseAdminEntityListRequestQuery},'./fixtures/admin-core-query-presentation-plan.mjs':incomplete}) as typeof import('./verify-admin-core-query-presentation-isolated.mts');
  const count=statements.length;await assert.rejects(old.readCoreQueryPresentationCheckpoint(handle,request(),fixtures),{name:'TypeError',message:'Cannot convert undefined or null to object'});assert.equal(statements.length,count);
 });
 await test('Browser projection rejects wrong ordering, count, clamp and duplicated API IDs',async()=>{const first=await read();const payload={rows:first.expectedIds.map(id=>({id})),pagination:first.pagination};assertCoreQueryProjection(first,payload);for(const candidate of [{...payload,rows:[...payload.rows].reverse()},{...payload,pagination:{...payload.pagination,totalRows:999}},{...payload,pagination:{...payload.pagination,page:3}},{...payload,rows:[payload.rows[0],...payload.rows.slice(0,-1)]}])assert.throws(()=>assertCoreQueryProjection(first,candidate));});
 await test('Unregistered selector, caller SQL/IDs, actor or scenario rejects before SQL',async()=>{for(const patch of [{sql:'select 1'},{ids:[1]},{actorId:8},{routeKey:'auth.users'},{routeKey:'projects'},{scenario:'execute'},{kind:'query'},{id:'x;delete'}]){const before=statements.length;await assert.rejects(owner.readCoreQueryPresentationCheckpoint(handle,{...request(),...patch},fixtures));assert.equal(statements.length,before);}});
 await test('Fixture object substitution and duplicated fixture identity deny new binding',async()=>{const before=statements.length;await assert.rejects(owner.readCoreQueryPresentationCheckpoint(handle,request(),structuredClone(fixtures)));assert.equal(statements.length,before);});
 await test('Native unexpected matching row invalidates complete-set proof and rolls back',async()=>{await db.query("insert into public.topics(id,title) values(9999,$1)",[fixtures.queryClosure.contexts.topics.search+' foreign']);await assert.rejects(read());assert.equal(statements.at(-1),'rollback');await db.exec('delete from public.topics where id=9999');});
 await test('Native domain mutation invalidates its preserved fingerprint',async()=>{const target=fixtures.queryClosure.contexts.topics.ids[0];await db.query("update public.topics set status='unpublished' where id=$1",[target]);await assert.rejects(read());assert.equal(statements.at(-1),'rollback');await db.query("update public.topics set status='published' where id=$1",[target]);});
 await test('Exact fixed QA identity and inactive/missing actor are rejected',async()=>{await db.exec("update public.admin_users set is_active=false where id=7");await assert.rejects(read());assert.equal(statements.at(-1),'rollback');await db.exec("update public.admin_users set is_active=true where id=7");});
 await test('Preference reads are actor/view bound; unrelated preference cannot satisfy persistence',async()=>{await db.query('insert into public.admin_user_preferences values(8,$1,$2::jsonb)',['content-topics',JSON.stringify({visibleColumns:['wrong']})]);assert.equal((await read('topics','preferences')).preference,null);await db.query('insert into public.admin_user_preferences values(7,$1,$2::jsonb)',['content-topics',JSON.stringify({visibleColumns:['title','status']})]);assert.deepEqual((await read('topics','preferences')).preference,{visibleColumns:['title','status']});});
 await test('Expired owner is rejected before any read or scope',async()=>{active=false;const before=statements.length;await assert.rejects(read());assert.equal(statements.length,before);assert.equal(scopes,0);active=true;});

 const finalOwner=makeOwner();await db.exec('delete from public.admin_user_preferences where admin_user_id=7');
 const outcomes:Record<string,unknown>[]=[],evidence:Record<string,unknown>[]=[];
 for(const spec of plan){
  const sequence=['first','empty',...CORE_QUERY_SEARCH_SCENARIOS,...CORE_QUERY_STALE_SCENARIOS,'second','third','clamp','wide','descending',...(spec.filter?['filtered']:[]),...(spec.entity==='activity_log'?Object.keys(CORE_ACTIVITY_DATE_SCENARIOS):[]),...coreQueryExtraFilterCases(spec,fixtures.queryClosure.contexts[spec.key]).map(row=>row.scenario),...coreQueryViewScenarios(spec),'preferences','preferences','first'],nativeCheckpointIds:string[]=[],actualReceipts:Awaited<ReturnType<typeof finalOwner.readCoreQueryPresentationCheckpoint>>[]=[];let pref=0;
  for(const scenario of sequence){
   if(scenario==='preferences'){pref++;await db.query('delete from public.admin_user_preferences where admin_user_id=7 and view_key=$1',[spec.viewKey]);await db.query('insert into public.admin_user_preferences values(7,$1,$2::jsonb)',[spec.viewKey,JSON.stringify({visibleColumns:pref===1?['title']:['title','status']})]);}
   const receipt=await finalOwner.readCoreQueryPresentationCheckpoint(handle,request(spec.key,scenario),fixtures);nativeCheckpointIds.push(receipt.id);actualReceipts.push(receipt);
  }
  const dateFilterEvidence=spec.entity==='activity_log'?{observations:['dateFrom','dateTo'].map(field=>{
   const prefix=field==='dateFrom'?'date-from':'date-to';return{field,sourceControlId:field==='dateFrom'?'activity-date-from':'activity-date-to',type:'date',focused:true,seed:'2026-01-03',keyboardChanged:'2026-01-04',keyboardRestored:'2026-01-03',clearedValue:'',emptyValue:field==='dateFrom'?'2026-01-04':'2026-01-02',appliedValues:['2026-01-03',field==='dateFrom'?'2026-01-04':'2026-01-02',''],nativeCheckpointIds:['included','empty','cleared'].map(suffix=>{const matches=actualReceipts.filter(row=>row.scenario===prefix+'-'+suffix);assert.equal(matches.length,1);return matches[0].id;}),unrelatedQuerySortEntityTypePreserved:true,appliedClearRemovedParam:true};
  }),automaticCoverage:[],globalClosed:false,boundary:'Controlled Browser observations; actual native-reader SQL in PGlite only.'}:null;
  const searchBoundary={observations:CORE_QUERY_SEARCH_SCENARIOS.map(scenario=>{
   const receipt=actualReceipts.find(row=>row.scenario===scenario)!;assert.ok(receipt?.searchProjection);return{scenario,requested:new URLSearchParams(receipt.query).get('q')??'',normalizedSearch:receipt.searchProjection.normalizedSearch,nativeId:receipt.id,actualInputInteraction:true,actualClearButton:scenario==='search-cleared',registeredRouteScopeVerified:true};
  }),automaticCoverage:[],globalClosed:false,boundary:'Controlled Browser observations; actual search SQL in PGlite.'};
  const staleHeld=actualReceipts.find(row=>row.scenario==='stale-held')!,staleCurrent=actualReceipts.find(row=>row.scenario==='stale-restored')!;assert.deepEqual(staleHeld.expectedIds,[]);assert.deepEqual(staleCurrent.expectedIds,actualReceipts[0].expectedIds);
  const staleReadEvidence={sourceOwner:coreQueryStaleOwner(),heldNativeId:staleHeld.id,currentNativeId:staleCurrent.id,beforeReleaseIds:actualReceipts[0].expectedIds,afterReleaseIds:actualReceipts[0].expectedIds,heldResponseIds:[],heldResponseStatus:200,strictRequestCount:1,posts:0,actualSearchInteraction:true,currentQueryRetained:true,method:'GET',pathname:'/api/admin/entity-lists/'+spec.entity,events:{held:1,currentSettled:2,released:3,terminal:4},terminal:'completed',failure:null,responseDelivered:true,automaticCoverage:[],globalClosed:false};
  const extraFilterEvidence={observations:coreQueryExtraFilterCases(spec,fixtures.queryClosure.contexts[spec.key]).map(recipe=>{
   const receipt=actualReceipts.find(row=>row.scenario===recipe.scenario)!;assert.ok(receipt?.extraFilterProjection);return{...recipe,nativeId:receipt.id,actualOptionInteraction:true,cancelPreservedQuery:true,cancelRestoredTriggerFocus:true,reloadPreservedAppliedQuery:true,querySortSizePreserved:true,actualChipClear:recipe.phase==='cleared'};
  }),automaticCoverage:[],globalClosed:false,boundary:'Controlled Browser observations; actual fixed filter SQL in PGlite.'};
  const viewReceipts=actualReceipts.filter(row=>row.scenario.startsWith('view-'));const viewLinkEvidence=spec.viewLink?{sourceLink:spec.viewLink,nativeIds:viewReceipts.map(row=>row.id),trashCompleteIds:viewReceipts[0].completeIds,activeCompleteIds:viewReceipts[2].completeIds,clickedHref:spec.viewLink.href,actualLinkClicked:true,actualTrashHeader:true,reloadPreserved:true,backRestoredPriorQuery:true,priorRowsRestored:true,canonicalDefaultsObserved:true,posts:0,activeControl:'browser-history-back',automaticCoverage:[],globalClosed:false}:null;if(spec.entity==='categories')assert.deepEqual(viewReceipts[0].completeIds,[900003,900004]);
  const rowEvidence:Record<string,unknown>[]=[];
  if(spec.entity==='projects'){
   const rows=actualReceipts[0].rows,unpublished=rows.find(row=>row.publicationStatus==='unpublished'),published=rows.find(row=>row.publicationStatus==='published');assert.ok(unpublished&&published);
   rowEvidence.push({kind:'copyPublicLink',nativeEntityId:unpublished.id,publicationStatus:'unpublished',mode:'disabled-current-publication-state',disabledReason:'انشر المشروع أولًا قبل نسخ الرابط العام.'},{kind:'copyPublicLink',nativeEntityId:published.id,publicationStatus:'published',mode:'actual-clipboard-only-no-navigation',copiedPath:published.publicPath,origin:'http://127.0.0.1:57603'});
   await test('Actual native SQL projects canonical publication states with each first-page ID: '+spec.key,async()=>{const expected=(await db.query<{id:number;publication_status:string}>('select id,publication_status from public.projects where id=any($1::bigint[])',[rows.map(row=>row.id)])).rows;for(const row of rows)assert.equal(row.publicationStatus,expected.find(native=>Number(native.id)===row.id)?.publication_status);});
  }
  const outcome={viewLinkEvidence,searchBoundary,staleReadEvidence,extraFilterEvidence,dateFilterEvidence,routeKey:spec.key,consumerId:spec.consumerId,entity:spec.entity,nativeActorId:7,nativeCheckpointIds,optionalColumn:{key:'status',persistedAndReloaded:true,semanticBaselineRestored:true,physicalInitialAbsenceRestored:false},querySearchEmptyNonempty:true,backAndReload:true,outOfRangeClamped:true,pageSizeChanged:true,domainFingerprintUnchanged:true,pageUnion:spec.rowCount,rowEvidence,remaining:['No Browser claim from controlled aggregate'],sortBoundary:'controlled',filterBoundary:'controlled'};
  outcomes.push(outcome);evidence.push({...outcome,id:'core-query-presentation-'+spec.key,status:'pass'});
 }
 const browser={status:'pass',driverCompleted:true,inventoryOnly:false,cohort:'query-presentation',errors:[],queryPresentation:{status:'pass',outcomes},evidence};
 await test('Strict aggregate joins every current route and every original plus current Activity date checkpoint',()=>{const joined=finalOwner.verifyCoreQueryPresentationCompletion(handle,browser);assert.equal(joined.contexts,plan.length);assert.equal(joined.nativeCheckpoints,outcomes.reduce((count,row)=>count+(row.nativeCheckpointIds as string[]).length,0));assert.equal(joined.summaries.filter(row=>row.datePicker!==null).length,1);assert.equal(joined.actorId,7);assert.deepEqual(joined.automaticCoverage,[]);assert.equal(joined.globalClosed,false);});
 for(const [name,change]of [
  ['failed-browser',(v:typeof browser)=>{v.status='fail';}],['unfinished-driver',(v:typeof browser)=>{v.driverCompleted=false;}],['inventory-only',(v:typeof browser)=>{v.inventoryOnly=true;}],['wrong-cohort',(v:typeof browser)=>{v.cohort='other';}],['missing-route',(v:typeof browser)=>{v.queryPresentation.outcomes.pop();}],['duplicate-route',(v:typeof browser)=>{v.queryPresentation.outcomes.push(v.queryPresentation.outcomes[0]);}],['missing-pass-receipt',(v:typeof browser)=>{v.evidence.shift();}],['duplicate-mixed-status-receipt',(v:typeof browser)=>{v.evidence.push({...v.evidence[0],status:'fail'});}],['failed-receipt',(v:typeof browser)=>{v.evidence[0].status='fail';}],
  ['invented-native-id',(v:typeof browser)=>{(v.queryPresentation.outcomes[0].nativeCheckpointIds as string[])[0]=randomUUID();}],['duplicate-native-id',(v:typeof browser)=>{const ids=v.queryPresentation.outcomes[0].nativeCheckpointIds as string[];ids[1]=ids[0];}],['out-of-order-native',(v:typeof browser)=>{const ids=v.queryPresentation.outcomes[0].nativeCheckpointIds as string[];[ids[1],ids[2]]=[ids[2],ids[1]];}],['wrong-positive-actor',(v:typeof browser)=>{v.queryPresentation.outcomes[0].nativeActorId=8;}],['missing-planned-scenario',(v:typeof browser)=>{(v.queryPresentation.outcomes[0].nativeCheckpointIds as string[]).pop();}],
 ]as const)await test('Aggregate rejects '+name,()=>{const changed=structuredClone(browser);change(changed);if(name.includes('native')||name==='wrong-positive-actor'||name==='missing-planned-scenario')Object.assign(changed.evidence[0],changed.queryPresentation.outcomes[0]);assert.throws(()=>finalOwner.verifyCoreQueryPresentationCompletion(handle,changed));});
 for(const [name,change]of [
  ['missing-date-observation',(row:Record<string,unknown>)=>{((row.dateFilterEvidence as {observations:unknown[]}).observations).pop();}],
  ['duplicate-date-observation',(row:Record<string,unknown>)=>{const values=(row.dateFilterEvidence as {observations:unknown[]}).observations;values.push(values[0]);}],
  ['wrong-date-control',(row:Record<string,unknown>)=>{((row.dateFilterEvidence as {observations:Record<string,unknown>[]}).observations)[0].sourceControlId='foreign-date';}],
  ['invented-date-checkpoint',(row:Record<string,unknown>)=>{(((row.dateFilterEvidence as {observations:{nativeCheckpointIds:string[]}[]}).observations)[0].nativeCheckpointIds)[0]=randomUUID();}],
  ['false-clear-removal',(row:Record<string,unknown>)=>{((row.dateFilterEvidence as {observations:Record<string,unknown>[]}).observations)[0].appliedClearRemovedParam=false;}],
  ['wrong-empty-date',(row:Record<string,unknown>)=>{((row.dateFilterEvidence as {observations:Record<string,unknown>[]}).observations)[1].emptyValue='2026-01-03';}],
 ]as const)await test('Same-source date aggregate rejects '+name,()=>{
  const changed=structuredClone(browser),row=changed.queryPresentation.outcomes.find(row=>row.entity==='activity_log')!;change(row);Object.assign(changed.evidence.find(row=>row.id==='core-query-presentation-activity_log')!,row);assert.throws(()=>finalOwner.verifyCoreQueryPresentationCompletion(handle,changed));
 });
 await test('Direct date join rejects forged native scope, timestamp and broadened result',async()=>{
  const spec=plan.find(row=>row.entity==='activity_log')!,raw:Awaited<ReturnType<typeof read>>[]=[];
  raw.push(await read(spec.key,'filtered'));for(const scenario of Object.keys(CORE_ACTIVITY_DATE_SCENARIOS))raw.push(await read(spec.key,scenario));
  const outcome=structuredClone(outcomes.find(row=>row.entity==='activity_log')!);const observations=(outcome.dateFilterEvidence as {observations:{nativeCheckpointIds:string[]}[]}).observations;
  for(const[index,prefix]of ['date-from','date-to'].entries())observations[index].nativeCheckpointIds=['included','empty','cleared'].map(suffix=>raw.find(row=>row.scenario===prefix+'-'+suffix)!.id);
  assertCoreActivityDateReceipts(outcome,raw,spec,fixtures.queryClosure.contexts[spec.key]);
  for(const change of [(rows:typeof raw)=>{rows[1].ownedRunId='foreign';},(rows:typeof raw)=>{rows[1].actorId=8;},(rows:typeof raw)=>{rows[1].fixtureFingerprint='changed';},(rows:typeof raw)=>{rows[1].dateFilterProjection!.timestamps[0].createdAt='2026-01-02T23:59:59.999Z';},(rows:typeof raw)=>{rows[4].dateFilterProjection!.timestamps[0].createdAt='2026-01-04T00:00:00.000Z';},(rows:typeof raw)=>{rows[2].completeIds=[...rows[0].completeIds];},(rows:typeof raw)=>{rows[1].dateFilterProjection!.lower='2026-01-02T00:00:00.000Z';}]){const changed=structuredClone(raw);change(changed);assert.throws(()=>assertCoreActivityDateReceipts(outcome,changed,spec,fixtures.queryClosure.contexts[spec.key]));}
 });
 for(const [name,change]of [
  ['missing-copy',(rows:Record<string,unknown>[])=>{rows.pop();}],
  ['extra-copy',(rows:Record<string,unknown>[])=>{rows.push({...rows[1]});}],
  ['wrong-copy-status',(rows:Record<string,unknown>[])=>{rows[1].publicationStatus='unpublished';}],
  ['wrong-copy-path',(rows:Record<string,unknown>[])=>{rows[1].copiedPath='/projects/foreign';}],
  ['wrong-copy-identity',(rows:Record<string,unknown>[])=>{rows[1].nativeEntityId=rows[0].nativeEntityId;}],
  ['invented-domain-action-result',(rows:Record<string,unknown>[])=>{rows[1].actionResult='success';}],
 ]as const)await test('Whole native aggregate rejects Project '+name,()=>{const changed=structuredClone(browser),outcome=changed.queryPresentation.outcomes.find(row=>row.entity==='projects')!;change(outcome.rowEvidence as Record<string,unknown>[]);Object.assign(changed.evidence.find(row=>row.id==='core-query-presentation-'+outcome.routeKey)!,outcome);assert.throws(()=>finalOwner.verifyCoreQueryPresentationCompletion(handle,changed));});
 await test('Same native request ID cannot be reused to fabricate another scenario',async()=>{const id=(outcomes[0].nativeCheckpointIds as string[])[0],before=statements.length;await assert.rejects(finalOwner.readCoreQueryPresentationCheckpoint(handle,{...request(),id},fixtures));assert.equal(statements.length,before);});
 await test('Unjoined extra native checkpoint denies aggregate completion',async()=>{await finalOwner.readCoreQueryPresentationCheckpoint(handle,request(),fixtures);assert.throws(()=>finalOwner.verifyCoreQueryPresentationCompletion(handle,browser));});
 console.log(JSON.stringify({status:'pass',checks:checks.length,records:checks,scope:'Actual native-reader SQL in PGlite and actual projection/plan functions; controlled lifecycle ports. No Browser/native PostgREST fixture proof claimed.'},null,2));
}finally{await db.close();}
