import ts from "typescript";
import {assertCoreFormFeedbackPublicationSource,assertCoreAcceptedFormFeedback,assertCoreVisibleAcceptedFeedback} from "./fixtures/admin-core-domain-form-journeys.mjs";
import {CORE_DOWNLOAD_MEDIA_HREF} from './fixtures/admin-core-download-media-adoption.mjs';
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { createJiti } from "jiti";
import { assertCoreNavigationBusyReceipt, buildCoreNavigationSettingsPlan, CORE_NAVIGATION_FOLLOWUP_SELECTION, CORE_NAVIGATION_FOLLOWUP_IDS,CORE_NAVIGATION_EXISTING_SELECTION,CORE_NAVIGATION_MENU_FOOTER_SELECTION,CORE_NAVIGATION_GRAPH_FOOTER_SELECTION,CORE_NAVIGATION_FOOTER_SELECTION,coreNavigationSelectedIds, assertCoreNavigationFollowupReceipt } from "./fixtures/admin-core-navigation-settings-journeys.mjs";
const root = resolve(import.meta.dirname, "..");
const jiti = createJiti(import.meta.url, { fsCache: false, moduleCache: false, alias: { "server-only": resolve(root, "node_modules/next/dist/compiled/server-only/empty.js") } });
import * as owner from './verify-admin-core-navigation-settings-isolated.mts';
const { ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST: manifest } = await jiti.import<typeof import("../src/lib/admin/form-system/adoption-manifest.ts")>(resolve(root, "src/lib/admin/form-system/adoption-manifest.ts"));
const { ADMIN_COLLECTION_SURFACE_ADOPTION: collections } = await jiti.import<typeof import("../src/lib/admin/interaction-system/adoption-manifest.ts")>(resolve(root, "src/lib/admin/interaction-system/adoption-manifest.ts"));
const requiredCases = manifest.filter(row => ["pages-quick-create", "menu-quick-create"].includes(row.id)).flatMap(row => row.surfaces.flatMap(surface => ["save_reload", "failure_preserves_input", "retry"].map(scenario => ({ key: ["form", row.id, surface, scenario].join(":"), boundary: "form", consumer: row.id, surface, scenario }))));
const args = { manifest, collections: collections.surfaces, requiredCases, fixtures: { recipe: owner.CORE_NAVIGATION_RECIPE, duplicatePagePath: "/about", duplicateMenuSlug: "existing-menu", originalFooterHash: "a".repeat(64) } };
const cases: string[] = [];
const test = async (name: string, callback: () => unknown | Promise<unknown>) => { await callback(); cases.push(name); };
await test("Canonical five Form and four Collection boundaries derive only six generic lifecycle cells", () => { const plan = buildCoreNavigationSettingsPlan(args); assert.equal(plan.consumers.length, 5); assert.equal(plan.pageCoverage.length + plan.menuCoverage.length, 6); assert.deepEqual(plan.specializedAutomaticCoverage, []); assert.equal(plan.globalClosed, false); assert.deepEqual(plan.consumers[4].surfaces, ["seo"]); });
for (const id of ["pages-quick-create", "menu-quick-create", "menu-builder", "footer-builder", "page-composition-and-seo"]) await test("Missing canonical boundary rejects: " + id, () => assert.throws(() => buildCoreNavigationSettingsPlan({ ...args, manifest: manifest.filter(row => row.id !== id) })));
await test("Duplicate boundary cannot double-count observations", () => assert.throws(() => buildCoreNavigationSettingsPlan({ ...args, manifest: [...manifest, manifest.find(row => row.id === "menu-builder")] })));
await test("Specialized closure cannot be promoted through generic classification", () => assert.throws(() => buildCoreNavigationSettingsPlan({ ...args, manifest: manifest.map(row => row.id === "footer-builder" ? { ...row, classification: "shared_adopter" } : row) })));
await test("Missing Footer manual-link collection rejects", () => assert.throws(() => buildCoreNavigationSettingsPlan({ ...args, collections: collections.surfaces.filter(row => row.id !== "footer-manual-links") })));
await test("Missing generic lifecycle cell rejects", () => assert.throws(() => buildCoreNavigationSettingsPlan({ ...args, requiredCases: requiredCases.slice(1) })));
await test("Repeated generic lifecycle cell rejects", () => assert.throws(() => buildCoreNavigationSettingsPlan({ ...args, requiredCases: [...requiredCases, requiredCases[0]] })));
const request = { id: randomUUID(), kind: "navigation-settings-state", entity: "menu", phase: "baseline" };
await test("Fixed checkpoint accepts no Browser expectation or SQL", () => assert.deepEqual(owner.validateCoreNavigationSettingsRequest(request), request));
for (const changed of [{ sql: "select secret" }, { expected: [] }, { menuId: 1 }, { actorId: 1 }, { phase: "commit-anything" }, { kind: "run-sql" }, { entity: "__proto__" }, { entity: "constructor" }, { id: "invalid-uuid" }, { phase: "seo-saved" }]) await test("Reject unknown checkpoint contract: " + Object.keys(changed)[0] + "/" + String(Object.values(changed)[0]), () => assert.throws(() => owner.validateCoreNavigationSettingsRequest({ ...request, ...changed })));
await test("Every declared finite phase is independently addressable", () => { for (const [entity, phases] of Object.entries(owner.NAVIGATION_SETTINGS_PHASES)) for (const phase of phases) owner.validateCoreNavigationSettingsRequest({ ...request, entity, phase }); assert.equal(Object.values(owner.NAVIGATION_SETTINGS_PHASES).reduce((sum, phases) => sum + phases.length, 0), 37); });
const r = owner.CORE_NAVIGATION_RECIPE.menu, ids = { a: 101, b: 102, c: 103 };
const base = { menu_id: 41, parent_id: null, href: "#", linked_type: null, linked_id: null, anchor: null, target: "_self", css_class: null, style_preset: "default", is_visible: true, item_type: "parent" };
const graph = [{ ...base, id: 101, label: r.a, sort_order: 20 }, { ...base, id: 102, label: r.b, sort_order: 10 }, { ...base, id: 103, parent_id: 102, label: r.editedC, sort_order: 10, href: CORE_DOWNLOAD_MEDIA_HREF, item_type: "custom", target: "_blank", css_class: r.css, style_preset: "gold-card", is_visible: false }];
await test("Complete hidden/reparented/reordered graph accepted with exact authored identity", () => owner.assertCoreNavigationGraph(graph, 41, "hidden", ids));
for (const [name, mutate] of [
  ["orphan", (rows: typeof graph) => { rows[2].parent_id = 999; }],
  ["cycle", (rows: typeof graph) => { rows[1].parent_id = 103; }],
  ["foreign menu", (rows: typeof graph) => { rows[2].menu_id = 99; }],
  ["duplicate ID", (rows: typeof graph) => { rows[2].id = 101; }],
  ["wrong order", (rows: typeof graph) => { rows[0].sort_order = 10; }],
  ["wrong destination", (rows: typeof graph) => { rows[2].href = "https://example.invalid/other"; }],
  ["wrong visibility", (rows: typeof graph) => { rows[2].is_visible = true; }],
  ["missing child", (rows: typeof graph) => { rows.pop(); }],
] as const) await test("Graph corruption rejects: " + name, () => { const changed = structuredClone(graph); mutate(changed); assert.throws(() => owner.assertCoreNavigationGraph(changed, 41, "hidden", ids)); });
await test("Subtree delete preserves only the original first root and renormalizes order", () => owner.assertCoreNavigationGraph([{ ...graph[0], sort_order: 10 }], 41, "subtree-deleted", ids));
const footer = await owner.buildExpectedCoreNavigationFooter([{ key: "footer.contact_items", value: [{ label: " preserved ", value: " original ", visible: true }] }], 41);
const { validateFooterSlots } = await jiti.import<typeof import("../src/lib/footer/validate-footer-slots.ts")>(resolve(root, "src/lib/footer/validate-footer-slots.ts"));
const slots = footer.find(row => row.key === "footer.slots")!.value as import("../src/lib/footer/footer-slot-types.ts").FooterSlotsConfig;
await test("Authored Footer uses canonical four-slot schema and real Menu identity", () => { assert.equal(validateFooterSlots(slots).ok, true); assert.deepEqual(slots.slots.map(slot => [slot.index, slot.type]), [[1, "custom_links"], [2, "text"], [3, "menu"], [4, "contact"]]); assert.equal((slots.slots[2].config as { menuId: number }).menuId, 41); });
await test("Footer manual draft owner preserves only edited/reordered and surviving links", () => { const links = (slots.slots[0].config as { links: { label: string; sortOrder: number; link: { href: string } }[] }).links; assert.deepEqual(links.map(row => [row.label, row.sortOrder]), [[owner.CORE_NAVIGATION_RECIPE.footer.editedLink, 0], [owner.CORE_NAVIGATION_RECIPE.footer.links[0], 1]]); assert.equal(links[0].link.href, CORE_DOWNLOAD_MEDIA_HREF); });
await test("Nonempty original global contacts normalize through the current owner", () => assert.deepEqual(footer.find(row => row.key === "footer.contact_items")!.value, [{ label: "preserved", value: "original" }]));
await test("Disabled slot is still schema validated", () => { const changed = structuredClone(slots); changed.slots[0].enabled = false; (changed.slots[0].config as Record<string, unknown>).links = "invalid"; assert.equal(validateFooterSlots(changed).ok, false); });
await test("Footer unsafe href rejects using the actual owner", () => { const changed = structuredClone(slots); (changed.slots[0].config as { links: { href: string }[] }).links[0].href = "javascript:alert(1)"; assert.equal(validateFooterSlots(changed).ok, false); });

const seo = await jiti.import<typeof import("../src/lib/seo/entity-seo-types.ts")>(resolve(root, "src/lib/seo/entity-seo-types.ts"));
const seoValues = { seoTitle: owner.CORE_NAVIGATION_RECIPE.page.seoTitle, seoDescription: owner.CORE_NAVIGATION_RECIPE.page.seoDescription, focusKeyword: owner.CORE_NAVIGATION_RECIPE.page.focusKeyword, seoKeywords: [...owner.CORE_NAVIGATION_RECIPE.page.seoKeywords], canonicalUrl: owner.CORE_NAVIGATION_RECIPE.page.canonicalUrl, robotsIndex: false, robotsFollow: false, ogImage: "", ogImageAlt: "" };
await test("Authored valid SEO passes real limits; negative control rejects only canonical URL", () => { assert.deepEqual(seo.validateEntitySeoValues(seoValues), []); const issues = seo.validateEntitySeoValues({ ...seoValues, canonicalUrl: "ftp://example.invalid/rejected" }); assert.equal(issues.length, 1); assert.equal(issues[0].field, "canonical_url"); });
const nativeSource = readFileSync(resolve(root, "scripts/verify-admin-core-navigation-settings-isolated.mts"), "utf8"), browserSource = readFileSync(resolve(root, "scripts/fixtures/admin-core-navigation-settings-journeys.mjs"), "utf8");
await test("Browser has no SQL/credential transport and requires owned cleanup", () => { assert.ok(!browserSource.includes("service_role") && !browserSource.includes("handle.query") && !browserSource.includes("page.request")); assert.match(browserSource, /requiresOwnedCleanupBeforePromotion: true/u); assert.match(nativeSource, /state\.cleanup, true/u); });
await test("Cleanup uses captured exact key set and assertion before commit", () => { const cleanup = nativeSource.slice(nativeSource.indexOf("export async function cleanupCoreNavigationSettingsFixtures")); const proof = cleanup.indexOf("assert.deepEqual(await footerRows(handle), state.originalFooter)"); const commit = cleanup.indexOf('await handle.query("commit")'); assert.ok(proof >= 0 && commit > proof); assert.match(cleanup, /FOOTER_SETTING_KEYS.*filter/u); assert.match(cleanup, /rollback/u); });

const feedbackSource=readFileSync(resolve(root,'src/components/admin/ui/AdminFormRuntime.tsx'),'utf8'),feedbackBinding=assertCoreFormFeedbackPublicationSource(feedbackSource),feedbackSourceSha='a'.repeat(64);
function acceptedFeedbackFixture(){return{consumer:'pages-quick-create',surface:'create',entityId:41,entityKey:'page-quick-create',mode:'create',channel:'form:page-quick-create',routePathname:'/admin/pages-blocks/pages/41',events:[{type:'admin-form-saved',entityId:41,targetIsForm:true,formConnected:true}],sourceSha256:feedbackSourceSha,sourceBinding:feedbackBinding,publicationOrderObserved:true,renderedRegionObserved:true,postUnmountPersistenceRequired:true,visibleFeedback:{...visibleFeedbackFixture(),channel:'form:page-quick-create',routePathname:'/admin/pages-blocks/pages/41',createFormDetached:true,placement:'global',lifecycle:'manual',dismissed:true},automaticCoverage:[] as string[],globalClosed:false};}
const acceptedFeedbackArgs={consumer:'pages-quick-create',surface:'create',entityId:41,entityKey:'page-quick-create',routePrefix:'/admin/pages-blocks/pages',requiredCases,sourceSha256:feedbackSourceSha,sourceBinding:feedbackBinding};
await test('Feedback current publication precedes saved event and create handoff',()=>assert.equal(feedbackBinding.publicationBeforeSavedEvent,true));
await test('Feedback requires distinct publication and visible dismissed result after actual create handoff',()=>assertCoreAcceptedFormFeedback(acceptedFeedbackFixture(),acceptedFeedbackArgs));
for(const[name,mutate]of Object.entries({
 'missing-event':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.events=[],
 'duplicate-event':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.events.push(p.events[0]),
 'foreign-entity':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.events[0].entityId=42,
 'foreign-form':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.entityKey='foreign',
 'foreign-route':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.routePathname='/admin/pages-blocks/menus/41',
 'foreign-consumer':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.consumer='menu-quick-create',
 'event-after-unmount':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.events[0].formConnected=false,
 'bubbled-other-form':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.events[0].targetIsForm=false,
 'foreign-source':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.sourceSha256='b'.repeat(64),
 'source-binding-drift':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.sourceBinding={...p.sourceBinding,sha256:'b'.repeat(64)},
 'event-only':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>Reflect.deleteProperty(p,'visibleFeedback'),
 'render-not-observed':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.renderedRegionObserved=false,
 'handoff-persistence-skipped':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.postUnmountPersistenceRequired=false,
 'visible-wrong-channel':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.channel='form:menu-quick-create',
 'visible-wrong-source':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.sourceSha256='b'.repeat(64),
 'visible-stale':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.priorEntryDetached=false,
 'visible-wrong-route':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.routePathname='/admin/pages-blocks/pages/42',
 'create-still-mounted':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.createFormDetached=false,
 'visible-only-in-closed-modal':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.placement='modal',
 'manual-lifecycle-missing':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.lifecycle='auto',
 'dismiss-not-observed':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.dismissed=false,
 'visible-after-reload':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.observedBeforeReload=false,
 'visible-missing':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.visibleCount=0,
 'visible-duplicate':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.visibleCount=2,
 'visible-error':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.visibleFeedback.variant='danger',
 'auto-credit':(p:ReturnType<typeof acceptedFeedbackFixture>):unknown=>p.automaticCoverage=['foreign'],
})){await test('Feedback accepted event rejects '+name,()=>{const p=acceptedFeedbackFixture();mutate(p);assert.throws(()=>assertCoreAcceptedFormFeedback(p,acceptedFeedbackArgs));});}
await test('Feedback saved event cannot move before actual publisher',()=>assert.throws(()=>assertCoreFormFeedbackPublicationSource(feedbackSource.replace('publishFeedback(nextFeedback, {','deferredPublication(nextFeedback, {'))));
await test('Feedback missing canonical save identity cannot qualify',()=>assert.throws(()=>assertCoreAcceptedFormFeedback(acceptedFeedbackFixture(),{...acceptedFeedbackArgs,requiredCases:[]})));

const feedbackHookSource=readFileSync(resolve(root,'scripts/fixtures/admin-core-domain-form-journeys.mjs'),'utf8');
function capturedFormObserverFactory(source:string){
 const ast=ts.createSourceFile('feedback-hook.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),fn=ast.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='observeCoreAcceptedFormFeedback');assert.ok(fn);
 const callbacks:ts.Expression[]=[];function visit(node:ts.Node){if(ts.isCallExpression(node)&&ts.isPropertyAccessExpression(node.expression)&&node.expression.name.text==='evaluateHandle')callbacks.push(node.arguments[0]);ts.forEachChild(node,visit);}visit(fn);assert.equal(callbacks.length,1);
 const body=fn.getText(ast);assert.ok(body.includes('await expect.poll(()=>observer.evaluate(value=>value.isConnected())).toBe(false)'));assert.ok(!body.includes('expect(form).toHaveCount(0)'));
 return new Function('node','return ('+callbacks[0].getText(ast)+')(node);');
}
await test('Feedback original create node detaches while same locator can match new edit node',()=>{
 const make=capturedFormObserverFactory(feedbackHookSource),oldForm=Object.assign(new EventTarget(),{isConnected:true,getAttribute:(name:string)=>name==='data-admin-form-mode'?'create':'page-quick-create'}),observed=make(oldForm);
 oldForm.dispatchEvent(new CustomEvent('admin-form-saved',{detail:{entityId:41}}));assert.deepEqual(observed.events,[{type:'admin-form-saved',entityId:41,targetIsForm:true,formConnected:true}]);
 oldForm.isConnected=false;const newEditForm={isConnected:true};const liveLocatorMatches=[newEditForm];assert.equal(liveLocatorMatches.length,1);assert.equal(observed.isConnected(),false);assert.equal(newEditForm.isConnected,true);
 observed.dispose();oldForm.dispatchEvent(new CustomEvent('admin-form-saved',{detail:{entityId:42}}));assert.equal(observed.events.length,1);
});
await test('Feedback observer rejects replacement with re-resolved form count',()=>assert.throws(()=>capturedFormObserverFactory(feedbackHookSource.replace('await expect.poll(()=>observer.evaluate(value=>value.isConnected())).toBe(false)','await expect(form).toHaveCount(0)'))));
await test('Feedback original-node capture cannot be removed',()=>assert.throws(()=>capturedFormObserverFactory(feedbackHookSource.replace('form.evaluateHandle(node=>','form.fakeCapture(node=>'))));
function visibleFeedbackFixture(){return{channel:'menu-builder:list',sourceSha256:feedbackSourceSha,variant:'success',visibleCount:1,nonemptyMessage:true,priorEntryDetached:true,renderedRegionObserved:true,observedBeforeReload:true,automaticCoverage:[] as string[],globalClosed:false};}
await test('Feedback accepted visible region remains a distinct proof boundary',()=>assertCoreVisibleAcceptedFeedback(visibleFeedbackFixture(),'menu-builder:list',feedbackSourceSha));
for(const[name,mutate]of Object.entries({
 'wrong-channel':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.channel='foreign',
 'danger-as-success':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.variant='danger',
 'missing-region':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.visibleCount=0,
 'duplicate-region':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.visibleCount=2,
 'empty-message':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.nonemptyMessage=false,
 'stale-result':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.priorEntryDetached=false,
 'after-reload':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.observedBeforeReload=false,
 'wrong-source':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.sourceSha256='b'.repeat(64),
 'auto-credit':(p:ReturnType<typeof visibleFeedbackFixture>):unknown=>p.automaticCoverage=['foreign'],
})){await test('Feedback visible region rejects '+name,()=>{const p=visibleFeedbackFixture();mutate(p);assert.throws(()=>assertCoreVisibleAcceptedFeedback(p,'menu-builder:list',feedbackSourceSha));});}
type RowFragment=Record<string,unknown>;
function navigationRowJoinFixture(){
 const source='a'.repeat(64),menuId=41,itemIds={a:101,b:102,c:103},hash=(letter:string)=>letter.repeat(64);
 const records:RowFragment[]=Object.entries(owner.NAVIGATION_SETTINGS_PHASES).flatMap(([entity,phases])=>phases.map(phase=>({id:randomUUID(),kind:'navigation-settings-state',entity,phase,status:'pass',menuId,itemIds,actorBoundAuditCount:entity==='footer'&&['saved','shown-saved'].includes(phase)?1:0,snapshotHash:hash(entity==='footer'?['saved','reloaded','visibility-shown-draft'].includes(phase)?'c':['shown-saved','shown-reloaded'].includes(phase)?'d':'a':phase==='item-c'||phase==='items-inspected'?'b':'a')})));
 const state=(entity:string,phase:string)=>records.find(row=>row.entity===entity&&row.phase===phase)!;
 const m=owner.CORE_NAVIGATION_RECIPE.menu,f=owner.CORE_NAVIGATION_RECIPE.footer;
 const flags={copyHidden:true,informationReturnedFocus:true,actionRequests:0,externalDestinationFollowed:false};
 const graph:RowFragment[]=[
 {type:'menu',id:'41',label:m.name,routePathname:'/admin/pages-blocks/menus',information:{Slug:m.slug,'الموقع':'Custom','عدد العناصر':'0','الحالة':'ظاهرة'},preview:{access:'disabled',reason:'القائمة لا تملك مسار معاينة عامًا خاصًا بها.'},edit:{mode:'navigation',pathname:'/admin/pages-blocks/menus/41',opened:true},nativeCheckpointId:state('menu','created-row-inspected').id,...flags},
 {type:'menu_item',id:'101',label:m.a,routePathname:'/admin/pages-blocks/menus/41',information:{'الرابط':'#','الحالة':'ظاهر'},preview:{access:'disabled',reason:'لا يملك العنصر مسارًا عامًا مستقلاً يمكن معاينته من هنا.'},nativeCheckpointId:state('menu','items-inspected').id,...flags},
 {type:'menu_item',id:'103',label:m.c,routePathname:'/admin/pages-blocks/menus/41',information:{'الرابط':m.href,'الحالة':'ظاهر'},preview:{access:'allowed',href:m.href},edit:{mode:'dialog',opened:true},nativeCheckpointId:state('menu','items-inspected').id,...flags}];
 const footer:RowFragment[]=[{type:'footer_manual_link',id:'0:'+f.editedLink,label:f.editedLink,routePathname:'/admin/pages-blocks/footer',information:{'الرابط':CORE_DOWNLOAD_MEDIA_HREF,'الهدف':'نفس النافذة','الحالة':'مخفي'},preview:{access:'allowed',href:CORE_DOWNLOAD_MEDIA_HREF},edit:{mode:'dialog-reloaded',opened:true},nativeCheckpointId:state('footer','reloaded').id,...flags}];
 const evidence:RowFragment[]=[{id:'core-navigation-menu-metadata-item-graph-commands',status:'pass',rowActionObservations:graph,automaticCoverage:[]},{id:'core-navigation-footer-aggregate-slots-manual-links-rejection-retry',status:'pass',rowActionObservations:footer,automaticCoverage:[],manualVisibility:{hiddenSavedReloaded:true,shownSavedReloaded:true,extraAcceptedSaves:1,nativePhases:['visibility-draft','saved','reloaded','visibility-shown-draft','shown-saved','shown-reloaded']}}];
 return{source,browser:{sourceSha256:source,status:'pass',driverCompleted:true,errors:[],cohort:'navigation-settings',evidence},native:{status:'pass',ownedRunId:'owned',records},state,graph,footer,evidence};
}
await test('Four exact Native-bound information/preview/edit fragments retain explicit external-destination limit',()=>{const x=navigationRowJoinFixture(),result=owner.assertCoreNavigationRowActionsCompletion(x.browser,x.native,'owned',x.source);assert.equal(result.rowObservations,4);assert.equal(result.additionalFooterWrites,1);assert.deepEqual(result.automaticCoverage,[]);assert.equal(result.globalClosed,false);});
const rowMutators:Record<string,(x:ReturnType<typeof navigationRowJoinFixture>)=>void>={
 foreignSource:x=>{x.browser.sourceSha256='b'.repeat(64);},coherentSelfSource:x=>{x.browser.sourceSha256='b'.repeat(64);Object.assign(x.native,{sourceSha256:'b'.repeat(64)});},foreignRun:x=>{x.native.ownedRunId='other';},unfinished:x=>{x.browser.driverCompleted=false;},wrongCohort:x=>{x.browser.cohort='domain-forms';},missingObservation:x=>{x.graph.pop();},duplicateIdentity:x=>{x.graph[2].id=x.graph[1].id;},foreignRow:x=>{x.footer[0].id='1:'+owner.CORE_NAVIGATION_RECIPE.footer.editedLink;},foreignCheckpoint:x=>{x.graph[0].nativeCheckpointId=x.state('menu','metadata-saved').id;},changedNativeInspection:x=>{x.state('menu','items-inspected').snapshotHash='f'.repeat(64);},inspectionWrite:x=>{x.state('menu','created-row-inspected').actorBoundAuditCount=1;},unsafeParentPreview:x=>{x.graph[1].preview={access:'allowed',href:'#'};},wrongInformation:x=>{(x.graph[0].information as RowFragment).Slug='foreign';},wrongStoredFooterTarget:x=>{(x.footer[0].information as RowFragment)['الهدف']='تبويب جديد';},wrongPersistedFooterState:x=>{(x.footer[0].information as RowFragment)['الحالة']='ظاهر';},notOpenedEdit:x=>{(x.graph[2].edit as RowFragment).opened=false;},readOnlyPost:x=>{x.graph[0].actionRequests=1;},externalFollowed:x=>{x.graph[2].externalDestinationFollowed=true;},copyInvented:x=>{x.footer[0].copyHidden=false;},extraWrite:x=>{x.state('footer','shown-saved').actorBoundAuditCount=2;},lostShownCommit:x=>{x.state('footer','shown-saved').actorBoundAuditCount=0;},changedDraft:x=>{x.state('footer','visibility-shown-draft').snapshotHash='f'.repeat(64);},reloadMismatch:x=>{x.state('footer','shown-reloaded').snapshotHash='f'.repeat(64);},noopVisibility:x=>{x.state('footer','shown-saved').snapshotHash='c'.repeat(64);x.state('footer','shown-reloaded').snapshotHash='c'.repeat(64);},missingPhase:x=>{x.native.records.splice(x.native.records.indexOf(x.state('footer','shown-saved')),1);},duplicatedPhase:x=>{x.native.records.push({...x.state('footer','shown-reloaded'),id:randomUUID()});},duplicateJourney:x=>{x.evidence.push(structuredClone(x.evidence[0]));},inventedCoverage:x=>{x.evidence[0].automaticCoverage=['all-row-actions'];},skippedShow:x=>{(x.evidence[1].manualVisibility as RowFragment).shownSavedReloaded=false;},orphanObservation:x=>{(x.evidence[1].rowActionObservations as RowFragment[]).push(structuredClone(x.graph[0]));}
};
for(const[name,mutate]of Object.entries(rowMutators))await test('Navigation row fragment join rejects '+name,()=>{const x=navigationRowJoinFixture();mutate(x);assert.throws(()=>owner.assertCoreNavigationRowActionsCompletion(x.browser,x.native,'owned',x.source));});
await test('Actual Footer persistence shape differs only at the selected manual visibility field',async()=>{const a=await owner.buildExpectedCoreNavigationFooter([],41,false),b=await owner.buildExpectedCoreNavigationFooter([],41,true);const links=(rows:RowFragment[])=>(((rows.find(row=>row.key==='footer.slots')!.value as {slots:FooterSlotLike[]}).slots[0].config).links);type FooterSlotLike={config:{links:{visible:boolean}[]}};assert.equal(links(a)[0].visible,false);assert.equal(links(b)[0].visible,true);links(a)[0].visible=true;assert.deepEqual(a,b);});
const previewOwner=await jiti.import<typeof import('../src/lib/admin/links/validate.ts')>(resolve(root,'src/lib/admin/links/validate.ts'));
await test('Current preview owner disables parent anchors while retaining exact authored HTTP and PDF destinations',()=>{for(const value of ['#','','javascript:alert(1)','//foreign.invalid'])assert.equal(previewOwner.resolvePublicPreviewHref(value),null);assert.equal(previewOwner.resolvePublicPreviewHref(owner.CORE_NAVIGATION_RECIPE.menu.href),owner.CORE_NAVIGATION_RECIPE.menu.href);assert.equal(previewOwner.resolvePublicPreviewHref(CORE_DOWNLOAD_MEDIA_HREF),CORE_DOWNLOAD_MEDIA_HREF);});
await test('Browser row observation is real owner DOM with native phase after edit and no external click',()=>{assert.match(browserSource,/data-admin-row-actions-information/u);assert.match(browserSource,/data-admin-entity-id/u);assert.match(browserSource,/toHaveAttribute\('target','_blank'\)/u);assert.match(browserSource,/posts\.length,0/u);assert.match(browserSource,/await menuEdit\.click\(\)/u);assert.match(browserSource,/created-row-inspected/u);assert.match(browserSource,/items-inspected/u);assert.match(browserSource,/shown-reloaded/u);assert.doesNotMatch(browserSource,/previewOwner.*\.click\(/u);});

await test('Row completion admits only the existing typed Page native-save intermediate receipt',()=>{
 const b=navigationRowJoinFixture();b.native.records.unshift({id:randomUUID(),kind:'form-save-native',status:'partial-not-global-pass'});owner.assertCoreNavigationRowActionsCompletion(b.browser,b.native,'owned',b.source);
});
for(const [kind,status]of [['unknown-kind','partial-not-global-pass'],['form-save-native','pass'],['form-save-native','fail'],['navigation-settings-state','partial-not-global-pass']])await test('Typed producer status rejects '+kind+'/'+status,()=>{
 const b=navigationRowJoinFixture();b.native.records.unshift({id:randomUUID(),kind,status});assert.throws(()=>owner.assertCoreNavigationRowActionsCompletion(b.browser,b.native,'owned',b.source));
});

const selectedReceipt = {scope:'core-closure',cohort:'navigation-settings',journeySelection:CORE_NAVIGATION_FOLLOWUP_SELECTION,status:'pass',driverCompleted:true,inventoryOnly:false,wholeCohortExecuted:false,errors:[],globalClosed:false,requiredCases,selectedJourneyIds:[...CORE_NAVIGATION_FOLLOWUP_IDS],executedJourneyIds:[...CORE_NAVIGATION_FOLLOWUP_IDS],evidence:CORE_NAVIGATION_FOLLOWUP_IDS.map(id=>({id,status:'pass'}))};
await test('Followup retains exactly seven original navigation operations without descendant replay',()=>{const receipt=assertCoreNavigationFollowupReceipt(selectedReceipt,requiredCases);assert.deepEqual(receipt,{status:'pass',selection:CORE_NAVIGATION_FOLLOWUP_SELECTION,automaticCoverage:[],selectedJourneyIds:[...CORE_NAVIGATION_FOLLOWUP_IDS],executedJourneyIds:[...CORE_NAVIGATION_FOLLOWUP_IDS],retainedDescendantsReplayed:false,wholeCohortExecuted:false,globalClosed:false});});
for(const [label,edit] of Object.entries({missing:(r:typeof selectedReceipt)=>{r.executedJourneyIds.pop();},replay:(r:typeof selectedReceipt)=>{r.evidence.push({id:'core-descendant-presentation-menus',status:'pass'});},failed:(r:typeof selectedReceipt)=>{r.evidence[0].status='fail';},whole:(r:typeof selectedReceipt)=>{r.wholeCohortExecuted=true;},unfinished:(r:typeof selectedReceipt)=>{r.driverCompleted=false;},inventory:(r:typeof selectedReceipt)=>{r.requiredCases=[];},foreign:(r:typeof selectedReceipt)=>{r.cohort='page-composition';}})) await test('Followup rejects '+label,()=>{const r=structuredClone(selectedReceipt);edit(r);assert.throws(()=>assertCoreNavigationFollowupReceipt(r,requiredCases));});
const remainingIds=coreNavigationSelectedIds(CORE_NAVIGATION_EXISTING_SELECTION);
await test('Fixed existing selection derives exactly current6 minus retained2 creates',()=>{assert.deepEqual(remainingIds,CORE_NAVIGATION_FOLLOWUP_IDS.filter(id=>!id.includes('create-rejection-retry-reload')));assert.equal(remainingIds.length,4);assert.deepEqual(owner.coreNavigationPhases(null),owner.NAVIGATION_SETTINGS_PHASES);assert.deepEqual(owner.coreNavigationPhases(CORE_NAVIGATION_FOLLOWUP_SELECTION),owner.NAVIGATION_SETTINGS_PHASES);assert.deepEqual(Object.fromEntries(Object.entries(owner.coreNavigationPhases(CORE_NAVIGATION_EXISTING_SELECTION)).map(([key,phases])=>[key,phases.length])),{page:2,menu:18,footer:11});});
await test('Menu Footer finite selection omits qualified SEO and native Page work while preserving original three applicable identities',()=>{const ids=coreNavigationSelectedIds(CORE_NAVIGATION_MENU_FOOTER_SELECTION);assert.deepEqual(ids,remainingIds.filter(id=>id!=='core-navigation-page-seo-validation-save-reload'));assert.equal(ids.length,3);assert.deepEqual(owner.coreNavigationPhases(CORE_NAVIGATION_MENU_FOOTER_SELECTION),{page:[],menu:owner.coreNavigationPhases(CORE_NAVIGATION_EXISTING_SELECTION).menu,footer:owner.coreNavigationPhases(CORE_NAVIGATION_EXISTING_SELECTION).footer});const receipt={...structuredClone(selectedReceipt),journeySelection:CORE_NAVIGATION_MENU_FOOTER_SELECTION,selectedJourneyIds:[...ids],executedJourneyIds:[...ids],evidence:ids.map(id=>({id,status:'pass'}))};assertCoreNavigationFollowupReceipt(receipt,requiredCases);for(const id of ['core-navigation-page-seo-validation-save-reload','core-navigation-page-create-rejection-retry-reload']){const bad=structuredClone(receipt);bad.evidence.push({id,status:'pass'});assert.throws(()=>assertCoreNavigationFollowupReceipt(bad,requiredCases));}});
const remainingReceipt={...structuredClone(selectedReceipt),journeySelection:CORE_NAVIGATION_EXISTING_SELECTION,selectedJourneyIds:[...remainingIds],executedJourneyIds:[...remainingIds],evidence:remainingIds.map(id=>({id,status:'pass'}))};
await test('Existing4 retain original canonical cells without create or descendant credit',()=>{const r=assertCoreNavigationFollowupReceipt(remainingReceipt,requiredCases);assert.deepEqual(r.selectedJourneyIds,remainingIds);assert.equal(r.globalClosed,false);assert.deepEqual(r.automaticCoverage,[]);});
for(const[label,edit]of Object.entries({missing:(r:typeof remainingReceipt):unknown=>r.executedJourneyIds.pop(),createReplay:(r:typeof remainingReceipt):unknown=>r.executedJourneyIds.push('core-navigation-page-create-rejection-retry-reload'),descendantReplay:(r:typeof remainingReceipt):unknown=>r.evidence.push({id:'core-descendant-presentation-footer',status:'pass'}),lostCase:(r:typeof remainingReceipt):unknown=>r.requiredCases.pop(),failed:(r:typeof remainingReceipt):unknown=>r.evidence[0].status='fail',duplicate:(r:typeof remainingReceipt):unknown=>r.executedJourneyIds[1]=r.executedJourneyIds[0]}))await test('Existing4 rejects '+label,()=>{const r=structuredClone(remainingReceipt);edit(r);assert.throws(()=>assertCoreNavigationFollowupReceipt(r,requiredCases));});
// Execute the existing command adapters and the shared viewport selector together.
// This controlled projection proves placement, not authenticated Browser rendering.
function navigationFeedbackDeclaration(source: string, name: string) {
 const ast=ts.createSourceFile('feedback.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),found:ts.FunctionDeclaration[]=[];
 const visit=(node:ts.Node)=>{if(ts.isFunctionDeclaration(node)&&node.name?.text===name)found.push(node);ts.forEachChild(node,visit);};visit(ast);assert.equal(found.length,1);
 return ts.transpileModule(found[0].getText(ast).replace(/^export /u,''),{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
}
type NavigationFeedbackEntry={channel:string;placement:string;feedback:{variant:string;message:string;[key:string]:unknown}};
type NavigationFeedbackTree={type:unknown;props:Record<string,unknown>;children:unknown[]};
const feedbackOwnerSource=readFileSync(resolve(root,'src/components/admin/AdminFeedbackProvider.tsx'),'utf8');
function navigationGlobalProjection(entries:NavigationFeedbackEntry[]){
 const token=Symbol('actual-viewport-entry'),react={createElement:(type:unknown,props:Record<string,unknown>,...children:unknown[]):NavigationFeedbackTree=>({type,props,children})};
 const render=new Function('useAdminFeedback','React','AdminFeedbackViewportEntry','createPortal',navigationFeedbackDeclaration(feedbackOwnerSource,'AdminFeedbackViewport')+';return AdminFeedbackViewport;')(()=>({entries,dismissFeedback:()=>{},modalHost:null}),react,token,()=>{throw Error('No modal host declared in this control.');});
 const result:NavigationFeedbackEntry[]=[];const visit=(node:unknown)=>{if(Array.isArray(node)){node.forEach(visit);return;}if(!node||typeof node!=='object')return;const n=node as NavigationFeedbackTree;if(n.type===token)result.push(n.props.entry as NavigationFeedbackEntry);n.children?.forEach(visit);};visit(render());return result;
}
for(const[file,callback,channel,host]of[
 ['MenusTableClient.tsx','runMenuMutation','menu-builder:list','MenusTableClient.tsx'],
 ['MenuItemsTableClient.tsx','runMenuItemMutation','menu-builder:41','MenuBuilderClient.tsx'],
]){
 const source=readFileSync(resolve(root,'src/app/admin/pages-blocks/menus',file),'utf8');
 const region=readFileSync(resolve(root,'src/app/admin/pages-blocks/menus',host),'utf8');assert.match(region,/placement="global"/u);assert.doesNotMatch(region,/AdminFeedbackChannelViewport/u);
 for(const outcome of ['success','warning','error']){
  const execute=async(code:string)=>{
   let entries:NavigationFeedbackEntry[]=[{channel,placement:'global',feedback:{variant:'success',message:'previous'}}],mutations=0,refreshes=0;
   const request={id:'controlled-request'},clearFeedback=(target:string)=>{assert.equal(target,channel);entries=entries.filter(e=>e.channel!==target);};
   const instant={mutateAsync:async(actual:unknown)=>{mutations++;assert.equal(actual,request);if(outcome==='error')throw Error('controlled rejection');return{feedbackStatus:outcome,message:'controlled '+outcome};}};
   const publishFeedback=(feedback:NavigationFeedbackEntry['feedback'],options:{channel:string;placement:string})=>{entries.push({...options,feedback});};
   const router={refresh:()=>{refreshes++;}},run=new Function('clearFeedback','feedbackChannel','instant','publishFeedback','router',navigationFeedbackDeclaration(code,callback)+';return '+callback+';')(clearFeedback,channel,instant,publishFeedback,router);
   await run(request);assert.equal(mutations,1);assert.equal(refreshes,outcome==='error'?0:1);assert.equal(entries.length,1);assert.equal(entries[0].feedback.variant,outcome==='error'?'danger':outcome);assert.equal(entries[0].feedback.message,outcome==='error'?'controlled rejection':'controlled '+outcome);return entries;
  };
  await test('Menu actual command '+callback+' '+outcome+' reaches declared shared global viewport',async()=>{const entries=await execute(source);assert.deepEqual(navigationGlobalProjection(entries),entries);});
  await test('Menu placement regression '+callback+' '+outcome+' reproduces undisplayed result',async()=>{const old=source.replaceAll('placement: "global"','placement: "inline"');assert.notEqual(old,source);const entries=await execute(old);assert.deepEqual(navigationGlobalProjection(entries),[]);});
 }
}


// Execute rejected item commands through the actual redirect serializer and canonical Feedback mapper.
const menuShared = await jiti.import<typeof import('../src/app/admin/pages-blocks/menus/menu-builder-shared.ts')>(resolve(root,'src/app/admin/pages-blocks/menus/menu-builder-shared.ts'));
const noticeOwner = await jiti.import<typeof import('../src/lib/admin/entity-list/feedback-codes.ts')>(resolve(root,'src/lib/admin/entity-list/feedback-codes.ts'));
const noticeSource = readFileSync(resolve(root,'src/app/admin/pages-blocks/menus/menu-actions/helpers.ts'),'utf8');
const itemSaveSource = readFileSync(resolve(root,'src/app/admin/pages-blocks/menus/menu-actions/items-save.ts'),'utf8');
function navigationNoticeFunctions(redirect:(url:string)=>never){
 const declarations=['navigationQuery','navigationFailureMessage','menuPath','backToMenu','navigationMutationMessage'].map(name=>navigationFeedbackDeclaration(noticeSource,name)).join('\n');
 return new Function('redirect','backToMenus',declarations+';return {navigationQuery,navigationFailureMessage,menuPath,backToMenu,navigationMutationMessage};')(redirect,()=>{throw Error('Unexpected list fallback.');}) as {navigationQuery:(m:unknown)=>string;navigationFailureMessage:(m:string)=>unknown;menuPath:(id:number,m:unknown)=>string;backToMenu:(id:number,m:unknown)=>never;navigationMutationMessage:(s:unknown,m:string,c?:boolean)=>unknown};
}
const noticeFns=navigationNoticeFunctions(()=>{throw Error('No redirect expected.');});
const mapped=(url:string)=>{const q=new URL(url,'https://example.invalid').searchParams;return noticeOwner.resolveAdminNoticeFeedback(menuShared.MENU_BUILDER_NOTICE_CODES,q.get('notice')??'saved',q.get('message'));};
for(const command of ['createMenuItem','updateMenuItem'])for(const outcome of ['rejected','saved','media-warning'])await test('Actual '+command+' redirect preserves '+outcome+' semantics in shared notice owner',async()=>{
 let calls=0,revalidations=0,url='';const stop=Symbol('redirect');const fns=navigationNoticeFunctions(target=>{url=target;throw stop;});
 const form=new FormData();form.set('id','52');form.set('menu_id','41');form.set('label','controlled item');
 const run=new Function('requireAdminSession','getNumber','getString','getBoolean','resolveMenuItemLink','coordinateMediaReferenceEntityMutation','mutateMenuTree','mediaWriteMutationErrorMessage','navigationFailureMessage','navigationMutationMessage','backToMenu','revalidateNavigation',navigationFeedbackDeclaration(itemSaveSource,command)+';return '+command+';')(
 async()=>({id:7,username:'controlled'}),(f:FormData,k:string)=>Number(f.get(k))||null,(f:FormData,k:string)=>String(f.get(k)??''),()=>false,async()=>({itemType:'parent',href:'#',linkedType:null,linkedId:null,anchor:null,target:'_self'}),async()=>{calls++;if(outcome==='rejected')throw Error('controlled cycle rejection');return{value:{id:52},mediaSynchronization:outcome==='media-warning'?{status:'saved_with_media_sync_warning'}:undefined};},()=>{throw Error('Persistence is not executed in this controlled transport test.');},(error:Error)=>error.message,fns.navigationFailureMessage,fns.navigationMutationMessage,fns.backToMenu,async()=>{revalidations++;});
 await assert.rejects(run(form),error=>error===stop);assert.equal(calls,1);assert.equal(revalidations,outcome==='rejected'?0:1);assert.equal(new URL(url,'https://example.invalid').pathname,'/admin/pages-blocks/menus/41');const feedback=mapped(url);assert.ok(feedback);assert.equal(feedback.variant,outcome==='rejected'?'danger':outcome==='media-warning'?'warning':'success');assert.equal(feedback.title,outcome==='rejected'?'تعذر الحفظ':outcome==='media-warning'?'تم الحفظ مع تنبيه':'تم الحفظ');assert.equal(feedback.dismissible,true);assert.equal(feedback.lifecycle,'manual');assert.ok(feedback.dismissSearchParams?.includes('notice'));if(outcome==='rejected'){assert.equal(feedback.message,'controlled cycle rejection');const q=new URL(url,'https://example.invalid');q.searchParams.delete('notice');assert.equal(mapped(q.href)?.variant,'success','Old missing discriminator reproduces false success.');}
});
for(const [label,message,variant]of [
 ['plain saved','تم الحفظ','success'],['media warning',{message:'saved media warning',mediaWarning:true},'warning'],['cache warning',{message:'saved cache warning',cacheWarning:true},'warning'],['rejected with success-like wording',{message:'تم الحفظ is part of rejected input',error:true},'danger'],['accepted with error-like wording','error is part of accepted label','success'],
] as const)await test('Notice serialization keeps explicit outcome: '+label,()=>{const result=mapped(noticeFns.menuPath(41,message));assert.equal(result?.variant,variant);assert.equal(result?.message,typeof message==='string'?message:message.message);});
await test('Menu detail consumer passes complete notice to canonical mapper and retains read error priority',()=>{const page=readFileSync(resolve(root,'src/app/admin/pages-blocks/menus/[id]/page.tsx'),'utf8'),client=readFileSync(resolve(root,'src/app/admin/pages-blocks/menus/MenuBuilderClient.tsx'),'utf8');assert.match(page,/messageNotice=\{query\?\.notice\}/u);assert.match(client,/resolveAdminNoticeFeedback\(MENU_BUILDER_NOTICE_CODES, messageNotice \?\? "saved", message\)/u);assert.match(client,/loadError\s*\?\s*\{\s*variant: "danger"/u);assert.doesNotMatch(client,/messageWarning/u);});
const graphFooterIds=coreNavigationSelectedIds(CORE_NAVIGATION_GRAPH_FOOTER_SELECTION);
await test('Remaining graph and Footer keep exact two applicable original identities and thirteen Menu checkpoints',()=>{assert.deepEqual(graphFooterIds,CORE_NAVIGATION_FOLLOWUP_IDS.filter(id=>['core-navigation-menu-metadata-item-graph-commands','core-navigation-footer-aggregate-slots-manual-links-rejection-retry'].includes(id)));assert.deepEqual(owner.coreNavigationPhases(CORE_NAVIGATION_GRAPH_FOOTER_SELECTION),{page:[],menu:owner.NAVIGATION_SETTINGS_PHASES.menu.slice(3,16),footer:owner.NAVIGATION_SETTINGS_PHASES.footer});});
const graphFooterReceipt={...structuredClone(remainingReceipt),journeySelection:CORE_NAVIGATION_GRAPH_FOOTER_SELECTION,selectedJourneyIds:[...graphFooterIds],executedJourneyIds:[...graphFooterIds],evidence:graphFooterIds.map(id=>({id,status:'pass'}))};
await test('Remaining two receipt grants no automatic or whole-cohort credit',()=>{const r=assertCoreNavigationFollowupReceipt(graphFooterReceipt,requiredCases);assert.deepEqual(r.selectedJourneyIds,graphFooterIds);assert.deepEqual(r.automaticCoverage,[]);assert.equal(r.globalClosed,false);});
for(const[label,edit]of Object.entries({listReplay:(r:typeof graphFooterReceipt):unknown=>r.executedJourneyIds.push('core-navigation-menu-visibility-duplicate-delete'),lostGraph:(r:typeof graphFooterReceipt):unknown=>r.executedJourneyIds.shift(),lostFooter:(r:typeof graphFooterReceipt):unknown=>r.evidence.pop(),reordered:(r:typeof graphFooterReceipt):unknown=>r.executedJourneyIds.reverse(),duplicate:(r:typeof graphFooterReceipt):unknown=>r.evidence.push(r.evidence[0]),failure:(r:typeof graphFooterReceipt):unknown=>r.evidence[0].status='fail',caseLost:(r:typeof graphFooterReceipt):unknown=>r.requiredCases.pop(),falseWhole:(r:typeof graphFooterReceipt):unknown=>r.wholeCohortExecuted=true}))await test('Remaining two rejects '+label,()=>{const r=structuredClone(graphFooterReceipt);edit(r);assert.throws(()=>assertCoreNavigationFollowupReceipt(r,requiredCases));});
await test('Footer corrected exact textbox keeps fill, disabled disappearance, preserved draft and saved reload checks',()=>{const target='getByRole("textbox", { name: "النص / Tagline", exact: true })';assert.equal(browserSource.split(target).length,5);for(const suffix of['.fill(r.footer.body)',').toHaveCount(0)',').toHaveValue(r.footer.body)'])assert.ok(browserSource.includes(target+suffix));assert.ok(!browserSource.includes('getByLabel("النص / Tagline"'));});


const footerOnlyIds=coreNavigationSelectedIds(CORE_NAVIGATION_FOOTER_SELECTION);
await test('Footer-only keeps exactly the original aggregate identity and eleven native phases without graph replay',()=>{assert.deepEqual(footerOnlyIds,CORE_NAVIGATION_FOLLOWUP_IDS.slice(-1));assert.deepEqual(owner.coreNavigationPhases(CORE_NAVIGATION_FOOTER_SELECTION),{page:[],menu:[],footer:owner.NAVIGATION_SETTINGS_PHASES.footer});});
const footerOnlyReceipt={...structuredClone(graphFooterReceipt),journeySelection:CORE_NAVIGATION_FOOTER_SELECTION,selectedJourneyIds:[...footerOnlyIds],executedJourneyIds:[...footerOnlyIds],evidence:footerOnlyIds.map(id=>({id,status:'pass'}))};
await test('Footer-only complete receipt retains all original cells with no automatic credit',()=>{const result=assertCoreNavigationFollowupReceipt(footerOnlyReceipt,requiredCases);assert.deepEqual(result.executedJourneyIds,footerOnlyIds);assert.deepEqual(result.automaticCoverage,[]);assert.equal(result.globalClosed,false);});
for(const[label,edit]of Object.entries({graphReplay:(r:typeof footerOnlyReceipt):unknown=>r.executedJourneyIds.unshift('core-navigation-menu-metadata-item-graph-commands'),listReplay:(r:typeof footerOnlyReceipt):unknown=>r.evidence.push({id:'core-navigation-menu-visibility-duplicate-delete',status:'pass'}),missingAggregate:(r:typeof footerOnlyReceipt):unknown=>r.evidence.pop(),duplicate:(r:typeof footerOnlyReceipt):unknown=>r.evidence.push(r.evidence[0]),failed:(r:typeof footerOnlyReceipt):unknown=>r.evidence[0].status='fail',lostCase:(r:typeof footerOnlyReceipt):unknown=>r.requiredCases.pop(),falseWhole:(r:typeof footerOnlyReceipt):unknown=>r.wholeCohortExecuted=true}))await test('Footer-only rejects '+label,()=>{const changed=structuredClone(footerOnlyReceipt);edit(changed);assert.throws(()=>assertCoreNavigationFollowupReceipt(changed,requiredCases));});
function footerOnlyRowFixture(){const x=navigationRowJoinFixture();x.native.records=x.native.records.filter(row=>row.entity==='footer');x.evidence.splice(0,1);return{...x,browser:{...x.browser,journeySelection:CORE_NAVIGATION_FOOTER_SELECTION},prepared:{kind:'owned-fixture-preparation',ownedRunId:'owned',pageId:31,menuId:41,pageSnapshotHash:'a'.repeat(64),menuSnapshotHash:'b'.repeat(64),uiCreateClaim:false,automaticCoverage:[],globalClosed:false}};}
await test('Footer-only row join requires actual persisted visibility and exact row without fake Menu observations',()=>{const x=footerOnlyRowFixture(),result=owner.assertCoreNavigationRowActionsCompletion(x.browser,x.native,'owned',x.source,x.prepared);assert.equal(result.rowObservations,1);assert.equal(result.readOnlyMenuCheckpoints,0);assert.equal(result.additionalFooterWrites,1);assert.equal(result.manualVisibilityPersistedBothDirections,true);assert.deepEqual(result.automaticCoverage,[]);});
for(const[label,edit]of Object.entries({foreignRun:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.prepared.ownedRunId='other',falseUiCredit:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.prepared.uiCreateClaim=true,missingNativePhase:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.native.records.pop(),menuNativeReplay:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.native.records.push({id:randomUUID(),kind:'navigation-settings-state',entity:'menu',phase:'created-row-inspected',status:'pass'}),extraObservation:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.footer.push(structuredClone(x.graph[0])),wrongDestination:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>(x.footer[0].preview as RowFragment).href='https://example.invalid/wrong',wrongNativeJoin:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.footer[0].nativeCheckpointId=x.state('footer','baseline').id,extraWrite:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.state('footer','shown-saved').actorBoundAuditCount=2,changedReload:(x:ReturnType<typeof footerOnlyRowFixture>):unknown=>x.state('footer','shown-reloaded').snapshotHash='f'.repeat(64),noVisibleCommit:(x:ReturnType<typeof footerOnlyRowFixture>):void=>{x.state('footer','shown-saved').snapshotHash='c'.repeat(64);x.state('footer','shown-reloaded').snapshotHash='c'.repeat(64);}}))await test('Footer-only exact row join rejects '+label,()=>{const x=footerOnlyRowFixture();edit(x);assert.throws(()=>owner.assertCoreNavigationRowActionsCompletion(x.browser,x.native,'owned',x.source,x.prepared));});
await test('Footer destination callback and reopen use exact unique direction-marked destination without first fallback',()=>{assert.equal(browserSource.split('await assertCoreNavigationFooterLinkDestination(').length,3);const helper=browserSource.slice(browserSource.indexOf('export async function assertCoreNavigationFooterLinkDestination'));assert.match(helper,/locator\('p\[dir="ltr"\]'\)/u);for(const check of ['toHaveCount(1)','toHaveText(href)','toBeVisible()','toHaveCount(0)'])assert.ok(helper.includes(check));assert.ok(helper.includes("getByText('لم يتم اختيار رابط بعد.',{exact:true})"));assert.ok(!helper.includes('.first('));});


// Footer expected validation is data; private/unknown failures keep exception semantics.
const footerValidationDefaults=await jiti.import<typeof import('../src/lib/footer/defaults.ts')>(resolve(root,'src/lib/footer/defaults.ts'));
const footerValidationParsing=await jiti.import<typeof import('../src/lib/footer/parse-footer-settings.ts')>(resolve(root,'src/lib/footer/parse-footer-settings.ts'));
const footerValidationOwner=await jiti.import<typeof import('../src/lib/footer/validate-footer-slots.ts')>(resolve(root,'src/lib/footer/validate-footer-slots.ts'));
function footerValidationFunction(file:string,name:string,ports:Record<string,unknown>){return new Function(...Object.keys(ports),navigationFeedbackDeclaration(readFileSync(resolve(root,file),'utf8'),name)+';return '+name)(...Object.values(ports));}
function footerValidationInput(){const input=footerValidationDefaults.createFreshFooterSettings();input.socialLinks=[{platform:'facebook',label:'QA social',href:'https://example.invalid/footer'}];return input;}
function footerValidationAction(overrides:Record<string,unknown>={}){
 const calls:string[]=[];const helper='src/app/admin/pages-blocks/footer/footer-actions/helpers.ts';
 const ports={requireAdminSession:async()=>{calls.push('auth');return{id:7,username:'qa'};},validateFooterSlots:footerValidationOwner.validateFooterSlots,
 sanitizeSocialLinks:footerValidationFunction(helper,'sanitizeSocialLinks',{isSocialPlatform:footerValidationDefaults.isSocialPlatform}),
 sanitizeContactItems:footerValidationFunction(helper,'sanitizeContactItems',{normalizeFooterContactItem:footerValidationParsing.normalizeFooterContactItem}),
 usesGlobalContactPool:footerValidationFunction(helper,'usesGlobalContactPool',{}),isFooterContactItemPublic:footerValidationParsing.isFooterContactItemPublic,
 FOOTER_SLOTS_SETTING_KEY:'footer.slots',coordinateMediaReferenceDomainMutation:async(input:{mutate:()=>Promise<unknown>;synchronize:(p:{leaseToken:string})=>Promise<unknown>})=>{calls.push('coordinate');await input.mutate();await input.synchronize({leaseToken:'qa-lease'});return{mediaSynchronization:{status:'synchronized'}};},
 buildMediaReferenceWriteScope:(domainKey:string,entityIdentity:string,row:unknown)=>({domainKey,entityIdentity,row}),saveFooterSettingsWithAudit:async()=>{calls.push('persist');},synchronizeMediaReferenceWriteScopesAfterDomainMutation:async()=>{calls.push('synchronize');},
 completeFooterSettingsMutationResult:async(_s:unknown,message:string)=>{calls.push('complete');return{ok:true,status:'success',message};},MediaReferenceWriteLeaseError:class extends Error{},getMediaReferenceWriteLeaseUserMessage:()=>{throw new Error('unexpected lease fixture');},...overrides};
 return{calls,action:footerValidationFunction('src/app/admin/pages-blocks/footer/footer-actions/save.ts','saveFooterBuilderAction',ports)};
}
await test('Footer validation empty-social returns actionable rejection before writes',async()=>{const f=footerValidationAction(),input=footerValidationInput();input.socialLinks=[];const r=await f.action(input);assert.deepEqual(r,{ok:false,status:'error',message:'أضف رابط سوشيال واحدًا على الأقل.'});assert.deepEqual(f.calls,['auth']);});
await test('Footer validation sanitized-empty social remains rejected',async()=>{const f=footerValidationAction(),input=footerValidationInput();input.socialLinks[0].href=' ';assert.equal((await f.action(input)).ok,false);assert.deepEqual(f.calls,['auth']);});
await test('Footer validation malformed slots preserve canonical error and no writes',async()=>{const f=footerValidationAction(),input=footerValidationInput();input.slots.slots=[];const expected=footerValidationOwner.validateFooterSlots(input.slots);assert.equal(expected.ok,false);const r=await f.action(input);assert.equal(r.ok,false);if(!expected.ok)assert.equal(r.message,expected.errors.join(' '));assert.deepEqual(f.calls,['auth']);});
await test('Footer validation missing global contact remains rejected before writes',async()=>{const f=footerValidationAction(),input=footerValidationInput();const contact=input.slots.slots.find(row=>row.type==='contact');assert.ok(contact);contact.enabled=true;contact.config={source:'global',items:[]};input.contactItems=[];assert.deepEqual(await f.action(input),{ok:false,status:'error',message:'أضف عنصر تواصل ظاهرًا واحدًا على الأقل للمجموعة العامة.'});assert.deepEqual(f.calls,['auth']);});
await test('Footer validation repaired input reaches one canonical coordinated mutation',async()=>{const f=footerValidationAction(),r=await f.action(footerValidationInput());assert.equal(r.ok,true);assert.equal(r.status,'success');assert.deepEqual(f.calls,['auth','coordinate','persist','synchronize','complete']);});
await test('Footer validation unauthenticated and unexpected persistence failures still throw',async()=>{const unauth=footerValidationAction({requireAdminSession:async()=>{throw new Error('auth-sentinel');}});await assert.rejects(()=>unauth.action(footerValidationInput()),/auth-sentinel/u);assert.deepEqual(unauth.calls,[]);const broken=footerValidationAction({saveFooterSettingsWithAudit:async()=>{throw new Error('database-sentinel');}});await assert.rejects(()=>broken.action(footerValidationInput()),/database-sentinel/u);assert.deepEqual(broken.calls,['auth','coordinate']);});
async function footerValidationClient(result:unknown){const calls:unknown[][]=[],tasks:Promise<void>[]=[];const capture=(name:string)=>(value:unknown)=>{calls.push([name,value]);};const handle=footerValidationFunction('src/app/admin/pages-blocks/footer/FooterBuilderClient.tsx','handleSave',{isPending:false,resetAlerts:()=>calls.push(['reset']),startTransition:(cb:()=>Promise<void>)=>{tasks.push(cb());},saveFooterBuilderAction:async()=>result,normalizeSlotsForSave:()=>({}),slots:[],contactItems:[],socialLinks:[],legal:{},draftKey:'current-draft',setError:capture('error'),setSavedDraftKey:capture('saved'),setMessageWarning:capture('warning'),setMessage:capture('message'),router:{refresh:()=>calls.push(['refresh'])}});handle();await Promise.all(tasks);return calls;}
await test('Footer validation client displays rejection without saved draft or refresh',async()=>{assert.deepEqual(await footerValidationClient({ok:false,status:'error',message:'أضف رابط سوشيال واحدًا على الأقل.'}),[['reset'],['error','أضف رابط سوشيال واحدًا على الأقل.']]);});
for(const status of ['success','warning'])await test('Footer validation client preserves committed '+status,async()=>{assert.deepEqual(await footerValidationClient({ok:true,status,message:'committed'}),[['reset'],['saved','current-draft'],['warning',status==='warning'],['message','committed'],['refresh']]);});



// Footer Restore is absent by explicit Product contract; it is never an empty passing selection.
await test('Removed Footer Restore selector and phases reject; Save aggregate remains exact',()=>{
 const retired='navigation-settings-footer-restore-followup';
 assert.throws(()=>coreNavigationSelectedIds(retired));assert.throws(()=>owner.coreNavigationPhases(retired));
 for(const phase of ['restore-cancelled','restore-rejected','restored','restore-reloaded'])assert.throws(()=>owner.validateCoreNavigationSettingsRequest({id:randomUUID(),kind:'navigation-settings-state',entity:'footer',phase}));
 assert.deepEqual(footerOnlyIds,['core-navigation-footer-aggregate-slots-manual-links-rejection-retry']);
 assert.deepEqual(owner.NAVIGATION_SETTINGS_PHASES.footer,['baseline','draft','delete-cancelled','draft-final','visibility-draft','rejected','saved','reloaded','visibility-shown-draft','shown-saved','shown-reloaded']);
});
await test('Footer exposes Save only; defaults and manual-link confirmation keep their owners',()=>{
 const client=readFileSync(resolve(root,'src/app/admin/pages-blocks/footer/FooterBuilderClient.tsx'),'utf8');
 assert.doesNotMatch(client,/restoreDefaultFooterAction|handleRestore|restoreOpen|استعادة الافتراضي|استعادة الفوتر الافتراضي/u);
 for(const file of ['src/app/admin/pages-blocks/footer/actions.ts','src/app/admin/pages-blocks/footer/footer-actions/index.ts']){const source=readFileSync(resolve(root,file),'utf8');assert.doesNotMatch(source,/restoreDefaultFooterAction|restore-default/u);assert.match(source,/saveFooterBuilderAction/u);}
 assert.throws(()=>readFileSync(resolve(root,'src/app/admin/pages-blocks/footer/footer-actions/restore-default.ts')),error=>(error as NodeJS.ErrnoException).code==='ENOENT');
 assert.match(readFileSync(resolve(root,'src/app/admin/pages-blocks/footer/footer-builder-utils.ts'),'utf8'),/DEFAULT_FOOTER_SLOTS/u);
 const links=readFileSync(resolve(root,'src/app/admin/pages-blocks/footer/FooterLinksDataGrid.tsx'),'utf8');assert.match(links,/AdminDataGridRowActions/u);assert.match(links,/confirmation:\s*\{\s*mode: "shared"/u);assert.match(links,/تأكيد حذف الرابط/u);
 assert.ok(client.includes('onClick={handleSave}'));assert.match(client,/حفظ الفوتر/u);
});

/** Pure guards distinguish pre-delivery rejection, accepted native write and exact restore. */
export function verifyCoreNavigationBusyControls(){
 const checks:string[]=[],source='a'.repeat(64),actor=2,owned='controlled-navigation-busy';
 const patch=(target:unknown,dotted:string,value:unknown)=>{const parts=dotted.split('.');let node=target as Record<string,unknown>;for(const key of parts.slice(0,-1))node=node[key] as Record<string,unknown>;assert.ok(Object.hasOwn(node,parts.at(-1)!));node[parts.at(-1)!]=value;};
 for(const key of ['menus','items'])for(const visible of [false,true]){
  const menus=key==='menus',route=menus?'/admin/pages-blocks/menus':'/admin/pages-blocks/menus/41',phases=menus?['busy-before','busy-held-rejected','busy-rejected','busy-held-accepted','busy-committed','busy-restored']:['busy-before','busy-held-accepted','busy-committed','busy-restored'];
  const proofs=phases.map(phase=>({id:randomUUID(),kind:'descendant-presentation-state',status:'pass',key,phase,route,actorId:actor,ownedRunId:owned,busy:{targetId:31,visible:phase==='busy-committed'?!visible:visible,unrelatedRowsUnchanged:true,preferencesUnchanged:true,actorBoundAuditCount:['busy-committed','busy-restored'].includes(phase)?1:0,auditActions:['busy-committed','busy-restored'].includes(phase)?[menus?'menu.update':'menu_item.update']:[],attributedEntityId:31,domainUnchanged:true}}));
  const attempts=(menus?['rejected-before-dispatch','accepted','restore']:['accepted','restore']).map(disposition=>({disposition,method:'POST',pathname:route,actionIdSha256:'b'.repeat(64),requestCount:1,unknownActionRequests:0,routeHandlerDrained:true,held:true,pendingDisabled:true,pendingAriaBusy:true,duplicateActivationBlocked:true,released:true,settledEnabled:true,events:['held','pending-observed','released','settled'],responseStatus:disposition==='rejected-before-dispatch'?null:200,transportFailure:disposition==='rejected-before-dispatch'?'net::ERR_FAILED':null}));
  const rejected=proofs.find(row=>row.phase==='busy-rejected'),committed=proofs.find(row=>row.phase==='busy-committed')!;
  const outcome={key,route,targetId:31,sourceSha256:source,nativeActorId:actor,ownedRunId:owned,nativeCheckpointIds:proofs.map(row=>row.id),attempts,visibleRestored:true,totalActionRequests:attempts.length,acceptedFeedback:{channel:menus?'menu-builder:list':'menu-builder:41',sourceSha256:source,variant:'success',visibleCount:1,nonemptyMessage:true,priorEntryDetached:true,renderedRegionObserved:true,observedBeforeReload:true,nativeCheckpointId:committed.id,automaticCoverage:[],globalClosed:false},rejectedFeedback:rejected?{channel:'menu-builder:list',variant:'danger',visible:true,nonemptyMessage:true,priorEntryDetached:true,observedBeforeReload:true,nativeCheckpointId:rejected.id,authenticatedNativeRejection:false,boundary:'owned-pre-delivery-abort'}:null,automaticCoverage:[],globalClosed:false};
  const valid={outcome,proofs},run=(value=valid)=>assertCoreNavigationBusyReceipt(value.outcome,value.proofs,source);run();checks.push('native-busy-positive-'+key+'-'+visible);
  const acceptedIndex=menus?1:0,committedIndex=proofs.findIndex(row=>row.phase==='busy-committed');
  const mutations:Array<[string,unknown]>=[['outcome.key','foreign'],['outcome.sourceSha256','f'.repeat(64)],['outcome.route','/admin/foreign'],['outcome.nativeActorId',0],['outcome.targetId',99],['proofs.1.id',proofs[0].id],['proofs.1.route','/admin/foreign'],['proofs.1.actorId',9],['proofs.1.ownedRunId','foreign'],['proofs.1.busy.domainUnchanged',false],['proofs.1.busy.actorBoundAuditCount',1],['proofs.1.busy.unrelatedRowsUnchanged',false],['proofs.1.busy.preferencesUnchanged',false],['proofs.'+committedIndex+'.busy.visible',visible],['proofs.'+committedIndex+'.busy.actorBoundAuditCount',0],['proofs.'+committedIndex+'.busy.attributedEntityId',99],['proofs.'+committedIndex+'.busy.auditActions',['foreign']],['proofs.'+(proofs.length-1)+'.busy.visible',!visible],['outcome.nativeCheckpointIds',[proofs[0].id]],['outcome.attempts.0.actionIdSha256','foreign'],['outcome.attempts.1.actionIdSha256','c'.repeat(64)],['outcome.attempts.0.requestCount',2],['outcome.attempts.0.unknownActionRequests',1],['outcome.attempts.0.pendingDisabled',false],['outcome.attempts.0.pendingAriaBusy',false],['outcome.attempts.0.duplicateActivationBlocked',false],['outcome.attempts.0.routeHandlerDrained',false],['outcome.attempts.'+acceptedIndex+'.responseStatus',500],['outcome.totalActionRequests',99],['outcome.visibleRestored',false],['outcome.acceptedFeedback.channel','foreign'],['outcome.acceptedFeedback.variant','danger'],['outcome.acceptedFeedback.observedBeforeReload',false],['outcome.acceptedFeedback.nativeCheckpointId',proofs[0].id],['outcome.automaticCoverage',['invented']],['outcome.globalClosed',true]];
  if(menus)mutations.push(['outcome.rejectedFeedback.channel','menu-builder:41'],['outcome.rejectedFeedback.variant','success'],['outcome.rejectedFeedback.observedBeforeReload',false],['outcome.rejectedFeedback.priorEntryDetached',false],['outcome.rejectedFeedback.authenticatedNativeRejection',true],['outcome.rejectedFeedback.nativeCheckpointId',committed.id],['outcome.attempts.0.transportFailure','net::ERR_CONNECTION_RESET']);else mutations.push(['outcome.rejectedFeedback',{variant:'danger'}]);
  for(const [name,value]of mutations){const changed=structuredClone(valid);patch(changed,name,value);assert.throws(()=>run(changed),key+': '+name);checks.push('native-busy-reject-'+key+'-'+visible+'-'+name);}
 }
 return checks;
}

cases.push(...verifyCoreNavigationBusyControls());
console.log(JSON.stringify({ status: "pass", controls: cases.length, cases, runtimeExecuted: false, globalClosed: false }));
