import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { PGlite } from "@electric-sql/pglite";

const migration = readFileSync(
  "sql/migrations/20260807140000_topic_categories_first_publish_date.sql",
  "utf8",
).replace(/^\uFEFF/u, "");
const categoriesColumns = readFileSync(
  "src/app/admin/content/categories/categories-columns.tsx",
  "utf8",
);
const categoriesConfig = readFileSync(
  "src/lib/admin/content/categories-list-config.ts",
  "utf8",
);

const db = await PGlite.create();

function iso(value: Date | string | null) {
  if (value === null) return null;
  return value instanceof Date ? value.toISOString() : new Date(value).toISOString();
}

try {
  await db.exec(`
    create role anon nologin;
    create role authenticated nologin;
    create role service_role nologin;

    create table public.admin_users (
      id bigint primary key
    );

    create table public.topic_categories (
      id bigint generated by default as identity primary key,
      name text not null,
      slug text not null unique,
      description text,
      sort_order integer default 0,
      is_active boolean default false,
      parent_id bigint references public.topic_categories(id),
      status text not null default 'unpublished',
      color_token text not null default 'slate',
      created_at timestamptz,
      updated_at timestamptz
    );

    create table public.topics (
      id bigint generated by default as identity primary key,
      category_id bigint references public.topic_categories(id),
      category text,
      category_slug text,
      deleted_at timestamptz,
      updated_at timestamptz,
      updated_by bigint
    );

    create table public.topic_series (
      id bigint generated by default as identity primary key,
      category_id bigint references public.topic_categories(id)
    );

    insert into public.admin_users(id) values (1);
    insert into public.topic_categories(
      name, slug, is_active, status, created_at, updated_at
    ) values
      ('Legacy published', 'legacy-published', true, 'published',
       '2026-06-11T03:34:54.935323Z', '2026-07-18T13:48:16.201Z'),
      ('Never published', 'never-published', false, 'unpublished',
       '2026-07-01T00:00:00Z', '2026-07-01T00:00:00Z');
  `);

  await db.exec(migration);

  const backfill = await db.query<{
    id: number;
    published_at: Date | null;
  }>("select id, published_at from public.topic_categories order by id");
  assert.equal(
    iso(backfill.rows[0]?.published_at ?? null),
    "2026-06-11T03:34:54.935Z",
    "legacy published rows use the one-time created_at compatibility backfill",
  );
  assert.equal(
    backfill.rows[1]?.published_at,
    null,
    "never-published rows do not receive a fabricated timestamp",
  );

  const firstPublish = await db.query<{ published_at: Date }>(
    "update public.topic_categories set status='published' where id=2 returning published_at",
  );
  const firstPublishedAt = iso(firstPublish.rows[0]?.published_at ?? null);
  assert.ok(firstPublishedAt, "first publish records a timestamp");

  const unpublished = await db.query<{ published_at: Date }>(
    "update public.topic_categories set status='unpublished' where id=2 returning published_at",
  );
  assert.equal(
    iso(unpublished.rows[0]?.published_at ?? null),
    firstPublishedAt,
    "unpublishing preserves the first publish timestamp",
  );

  const republished = await db.query<{ published_at: Date }>(
    `update public.topic_categories
        set is_active=true, published_at='2099-01-01T00:00:00Z'
      where id=2
      returning published_at`,
  );
  assert.equal(
    iso(republished.rows[0]?.published_at ?? null),
    firstPublishedAt,
    "republishing cannot replace the first publish timestamp",
  );

  const tampered = await db.query<{ published_at: Date }>(
    "update public.topic_categories set published_at='2000-01-01T00:00:00Z' where id=2 returning published_at",
  );
  assert.equal(
    iso(tampered.rows[0]?.published_at ?? null),
    firstPublishedAt,
    "direct published_at tampering is ignored by the domain owner",
  );

  const publishedInsert = await db.query<{ published_at: Date }>(
    `insert into public.topic_categories(
       name, slug, is_active, status, published_at, created_at, updated_at
     ) values (
       'Published on create', 'published-on-create', true, 'published',
       '2000-01-01T00:00:00Z', now(), now()
     ) returning published_at`,
  );
  assert.notEqual(
    iso(publishedInsert.rows[0]?.published_at ?? null),
    "2000-01-01T00:00:00.000Z",
    "published inserts use the database-owned first publish instant",
  );

  const unpublishedInsert = await db.query<{ id: number; published_at: Date | null }>(
    `insert into public.topic_categories(
       name, slug, is_active, status, published_at, created_at, updated_at
     ) values (
       'RPC fixture', 'rpc-fixture', false, 'unpublished',
       '2000-01-01T00:00:00Z', now(), now()
     ) returning id, published_at`,
  );
  assert.equal(
    unpublishedInsert.rows[0]?.published_at,
    null,
    "unpublished inserts cannot pre-seed published_at",
  );

  const rpcResult = await db.query<{
    result: { category: { published_at: string; status: string } };
  }>(
    `select public.admin_update_topic_category(
       $1::bigint, 'RPC fixture', null, true, 'slate', 1
     ) as result`,
    [unpublishedInsert.rows[0]?.id],
  );
  assert.equal(rpcResult.rows[0]?.result.category.status, "published");
  assert.ok(
    rpcResult.rows[0]?.result.category.published_at,
    "the canonical category mutation returns published_at",
  );

  const readModel = await db.query<{
    result: { rows: Array<{ id: number; published_at: string | null }> };
  }>(
    "select public.admin_list_categories(1,10,'published_at','asc','','all') as result",
  );
  const readRow = readModel.rows[0]?.result.rows.find((row) => row.id === 2);
  assert.equal(
    iso(readRow?.published_at ?? null),
    firstPublishedAt,
    "the canonical categories read model exposes the stored first publish timestamp",
  );

  assert.match(
    categoriesConfig,
    /CATEGORIES_DEFAULT_COLUMN_KEYS\s*=\s*\[[\s\S]*?"name",\s*"status",\s*"count",\s*"created_at",\s*"actions",/,
    "the default Categories table contains only the agreed visible columns",
  );
  assert.match(
    categoriesColumns,
    /row\.published_at\s*\?\s*formatAdminDateTime\(row\.published_at\)\s*:\s*"—"/,
    "the table renders only published_at with no created_at or updated_at fallback",
  );
  assert.doesNotMatch(
    categoriesColumns,
    /row\.published_at\s*\?[\s\S]*?:\s*(?:row\.)?(?:created_at|updated_at)/,
    "presentation does not introduce a timestamp fallback",
  );

  console.log("verify-topic-category-first-publish passed (Domain transition, republish invariant, RPC, read model, table). ");
} finally {
  await db.close();
}
