import {adminCollectionSearchIncludes} from '../src/lib/admin/entity-list/search-normalization.ts';
import {loadCoreResidualSearchContract,assertCoreResidualSearchReceipt,bindCoreResidualSearchCells} from './fixtures/admin-core-residual-search.mjs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {createJiti} from 'jiti';
import {assertOwnedLocalHandle,type OwnedLocalHandle} from './lib/isolated-supabase.mts';
import {readCoreFixedQaActor} from './verify-admin-core-domain-readback-isolated.mts';
import {assertCoreRenderedAdoptionJoin} from './fixtures/admin-core-rendered-adoption.mjs';
import {FOOTER_SETTING_KEYS} from '../src/lib/footer/types.ts';
import {loadCoreDescendantPresentationPlan,assertCoreDescendantProjection,bindCoreDescendantCells} from './fixtures/admin-core-descendant-presentation-plan.mjs';
type Row=Record<string,unknown>;
type Spec={key:string;scope:string;consumer:string;aliases:string[];route:string;preferenceId:string|null;viewKey:string|null;defaults:string[];rowCount:number;pageSize:number;paginationMode:string;optional:string|null;label:string|null;columns:Array<{key:string;label:string;hideable:boolean}>};
type Fixture={search:string;ids:string[];route:string;tab?:string};
type Proof={id:string;key:string;phase:string;actorId:number;ownedRunId:string;fingerprint:string;ids:string[];preference:Row|null;searchRows:Array<{id:string;text:string}>|null;searchOwnerSha256:string|null;searchOwnerPath:string|null};
type State={scope:'navigation'|'composition';actorId:number;plan:Spec[];fixtures:Record<string,Fixture>;originalPreferences:Map<string,Row|null>;originalFooter:Row[]|null;proofs:Map<string,Proof>;baseline:Map<string,string>;cleaned:boolean};
const states=new WeakMap<OwnedLocalHandle,State>();
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const phases=(spec:Spec)=>spec.preferenceId?['before','hidden','restored','after']:['before','after'];
export function validateCoreDescendantPresentationRequest(input:unknown){assert.ok(input&&typeof input==='object'&&!Array.isArray(input));const row=input as Row;assert.deepEqual(Object.keys(row).sort(),['id','key','kind','phase']);assert.match(String(row.id),/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i);assert.equal(row.kind,'descendant-presentation-state');assert.ok(['menus','items','assignments','footer'].includes(String(row.key)));assert.ok(['before','hidden','restored','after'].includes(String(row.phase)));return row as {id:string;key:string;kind:string;phase:string};}

/** Opt in BEFORE the pre-existing navigation fixture captures its baseline.
 * Cleanup order is existing Navigation cleanup, then this exact outer capture.
 * A composition run uses its own additional unpublished page and no Footer. */
export async function prepareCoreDescendantPresentationFixtures(handle:OwnedLocalHandle,fixtures:Row,scope:'navigation'|'composition'){
 assertOwnedLocalHandle(handle);assert.equal(states.has(handle),false);const plan=await loadCoreDescendantPresentationPlan(scope) as Spec[],namespace='qa-descendant-'+createHash('sha256').update(handle.identity.runId).digest('hex').slice(0,12);
 const current:State={scope,actorId:0,plan,fixtures:{},originalPreferences:new Map(),originalFooter:null,proofs:new Map(),baseline:new Map(),cleaned:false};
 const root=process.cwd(),jiti=createJiti(import.meta.url,{fsCache:false,moduleCache:false,alias:{'server-only':resolve(root,'node_modules/next/dist/compiled/server-only/empty.js')}});
 await handle.withDatabaseConnection(async connection=>{await connection.query('begin');try{
  current.actorId=await readCoreFixedQaActor(connection);const rowCount=plan[0].rowCount;
  if(scope==='navigation'){
   assert.equal((await connection.query('select count(*)::int count from public.menus where slug like $1',[namespace+'%'])).rows[0].count,0);
   const menus=(await connection.query("insert into public.menus(name,slug,location,is_active) select $1||' Name '||lpad(n::text,2,'0'),$1||'-'||n,'custom',n%2=0 from generate_series(1,$2::int)n returning id,name",[namespace+'-menus',rowCount])).rows;assert.equal(menus.length,rowCount);current.fixtures.menus={search:namespace+'-menus',ids:menus.map(row=>String(row.id)).sort((a,b)=>Number(a)-Number(b)),route:'/admin/pages-blocks/menus'};
   const menu=(await connection.query("insert into public.menus(name,slug,location,is_active) values($1,$1,'custom',false) returning id",[namespace+'-items'])).rows[0];const menuId=Number(menu.id);assert.ok(Number.isSafeInteger(menuId)&&menuId>0);
   const items=(await connection.query("insert into public.menu_items(menu_id,parent_id,label,item_type,href,target,style_preset,is_visible,sort_order) select $1,null,$2||' Item '||lpad(n::text,2,'0'),'custom','/qa-descendant-link-'||n,'_self','default',n%2=0,n from generate_series(1,$3::int)n returning id,sort_order",[menuId,namespace+'-items',rowCount])).rows;assert.equal(items.length,rowCount);current.fixtures.items={search:namespace+'-items',ids:items.sort((a,b)=>Number(a.sort_order)-Number(b.sort_order)).map(row=>String(row.id)),route:'/admin/pages-blocks/menus/'+menuId,tab:'items'};
   const original=(await connection.query('select to_jsonb(s) value from public.site_settings s where key=any($1::text[]) order by key',[[...FOOTER_SETTING_KEYS]])).rows;current.originalFooter=original.map(row=>row.value as Row);
   const {createFreshFooterSettings}=await jiti.import<typeof import('../src/lib/footer/defaults.ts')>(resolve(root,'src/lib/footer/defaults.ts'));
   const {changeSlotType}=await jiti.import<typeof import('../src/app/admin/pages-blocks/footer/footer-builder-utils.ts')>(resolve(root,'src/app/admin/pages-blocks/footer/footer-builder-utils.ts'));
   const {evaluateFooterReadiness}=await jiti.import<typeof import('../src/lib/footer/footer-settings-readiness.ts')>(resolve(root,'src/lib/footer/footer-settings-readiness.ts'));
   const fresh=createFreshFooterSettings();let slots=fresh.slots.slots;for(const slot of slots)slots=changeSlotType(slots,slot.index,slot.index===1?'custom_links':'text');
   const links=Array.from({length:rowCount},(_,index)=>({label:namespace+' Footer '+String(index+1).padStart(2,'0'),href:'https://example.invalid/qa-descendant/'+index,target:'_self' as const,visible:true,sortOrder:index}));slots[0]={...slots[0],enabled:true,heading:'QA descendant manual links',config:{links}};
   const values=[{key:'footer.slots',value:{version:1,slots}},{key:'footer.contact_items',value:[]},{key:'footer.social_links',value:[{platform:'facebook',label:'QA isolated',href:'https://example.invalid/qa-descendant/social'}]},{key:'footer.legal',value:{copyright:'QA isolated',tagline:'QA isolated'}}];
   assert.deepEqual(values.map(row=>row.key).sort(),[...FOOTER_SETTING_KEYS].sort());const value=(key:string)=>values.find(row=>row.key===key)?.value;assert.equal(evaluateFooterReadiness({slots:value('footer.slots'),contactItems:value('footer.contact_items'),socialLinks:value('footer.social_links'),legal:value('footer.legal')}).systemValid,true);
   const actor=(await connection.query('select username from public.admin_users where id=$1',[current.actorId])).rows[0];await connection.query("select public.save_footer_settings($1::jsonb,$2,$3,'qa.descendant.presentation.prepare','{}'::jsonb)",[JSON.stringify(values),current.actorId,String(actor.username)]);
   current.fixtures.footer={search:namespace,ids:links.map((row,index)=>index+':'+row.label),route:'/admin/pages-blocks/footer',tab:'column-1'};
  }else{
   const pages=fixtures.pages as {pageId:number;templates:Array<{kind:string;id:number;assigned:boolean}>};assert.ok(Number.isSafeInteger(pages?.pageId)&&pages.pageId>0);const source=pages.templates.find(row=>row.kind==='content'&&!row.assigned);assert.ok(source);
   const page=(await connection.query("insert into public.pages(title,slug,path,page_type,status,seo_title,seo_description,focus_keyword) values($1,$1,'/'||$1,'static','unpublished',$1,'QA owned descendant pagination metadata','QA') returning id",[namespace+'-composition'])).rows[0];const pageId=Number(page.id);
   const templates=(await connection.query("insert into public.content_block_templates(name,slug,status,config,variant,sort_order) select $2||' Template '||lpad(n::text,2,'0'),$2||'-'||n,'published',source.config,source.variant,n from public.content_block_templates source cross join generate_series(1,$3::int)n where source.id=$1 returning id,sort_order",[source.id,namespace+'-assignments',rowCount])).rows;assert.equal(templates.length,rowCount);
   for(const template of templates)await connection.query("select public.mutate_page_composition($1,'save_assignment',$2::jsonb,null,$3)",[pageId,JSON.stringify({kind:'content',template_id:Number(template.id),slot:'main',sort_order:Number(template.sort_order),is_visible:true}),'system:'+namespace]);
   const assignments=(await connection.query("select id from public.page_composition_assignments where page_id=$1 and kind='content' order by sort_order,id",[pageId])).rows;assert.equal(assignments.length,rowCount);current.fixtures.assignments={search:namespace+'-assignments',ids:assignments.map(row=>'content:'+row.id),route:'/admin/pages-blocks/pages/'+pageId,tab:'modules'};
  }
  for(const spec of plan)if(spec.viewKey){const rows:Row[]=(await connection.query('select to_jsonb(p) value from public.admin_user_preferences p where admin_user_id=$1 and view_key=$2',[current.actorId,spec.viewKey])).rows;assert.ok(rows.length<=1);current.originalPreferences.set(spec.key,(rows[0]?.value??null)as Row|null);await connection.query('insert into public.admin_user_preferences(admin_user_id,view_key,preferences) values($1,$2,$3::jsonb) on conflict(admin_user_id,view_key) do update set preferences=excluded.preferences',[current.actorId,spec.viewKey,JSON.stringify({visibleColumns:spec.defaults})]);}
  await connection.query('commit');
 }catch(error){await connection.query('rollback');throw error;}});
 states.set(handle,current);return {scope,namespace,contexts:current.fixtures,exactOwnedRestoreRequired:true};
}

export async function readCoreDescendantPresentationCheckpoint(handle:OwnedLocalHandle,input:unknown){
 assertOwnedLocalHandle(handle);const request=validateCoreDescendantPresentationRequest(input),current=states.get(handle);assert.ok(current&&!current.cleaned);assert.equal(current.proofs.has(request.id),false);const spec=current.plan.find(row=>row.key===request.key);assert.ok(spec);const searchContract=spec.key==='footer'?null:await loadCoreResidualSearchContract(spec.key);const fixture=current.fixtures[spec.key],done=[...current.proofs.values()].filter(row=>row.key===spec.key);assert.equal(request.phase,phases(spec)[done.length]);
 return handle.withDatabaseConnection(async connection=>{await connection.query('begin isolation level repeatable read read only');try{
  const actorId=await readCoreFixedQaActor(connection);assert.equal(actorId,current.actorId);let ids:string[];
  if(spec.key==='menus')ids=(await connection.query('select id from public.menus where name like $1 order by id',['%'+fixture.search+'%'])).rows.map(row=>String(row.id));
  else if(spec.key==='items')ids=(await connection.query('select id from public.menu_items where menu_id=$1 and label like $2 order by sort_order,id',[Number(fixture.route.split('/').at(-1)),'%'+fixture.search+'%'])).rows.map(row=>String(row.id));
  else if(spec.key==='assignments')ids=(await connection.query("select a.id from public.page_composition_assignments a join public.content_block_templates t on t.id=a.template_id where a.page_id=$1 and a.kind='content' and t.name like $2 order by a.sort_order,a.id",[Number(fixture.route.split('/').at(-1)),'%'+fixture.search+'%'])).rows.map(row=>'content:'+row.id);
  else{const row=(await connection.query("select value from public.site_settings where key='footer.slots'")).rows[0].value as {slots:Array<{index:number;config:{links:Array<{label:string;sortOrder:number}>}}>};const links=row.slots.find(slot=>slot.index===1)?.config.links;assert.ok(links&&links.length===spec.rowCount);ids=[...links].sort((a,b)=>a.sortOrder-b.sortOrder).map((link,index)=>index+':'+link.label);}

  let searchRows:Array<{id:string;text:string}>|null=null;
  if(searchContract){
   let rows:Row[]=[];let regions:Record<string,string>={};
   if(spec.key==='menus')rows=(await connection.query('select id,name,slug,location from public.menus order by id')).rows;
   else if(spec.key==='items'){
    const raw=(await connection.query('select to_jsonb(i) item from public.menu_items i where menu_id=$1 order by sort_order,id',[Number(fixture.route.split('/').at(-1))])).rows;
    // This pre-existing disposable fixture is exactly23 root items; tree topology is separately covered by Navigation.
    assert.equal(raw.length,spec.rowCount);assert.ok(raw.every(row=>(row.item as Row).parent_id===null));rows=raw.map(row=>({item:row.item,parentLabel:null}));
   }else{
    const pageId=Number(fixture.route.split('/').at(-1));rows=(await connection.query("select a.id,'content'::text module_kind,t.name template_name,t.slug template_slug,t.variant template_variant,a.slot from public.page_composition_assignments a join public.content_block_templates t on t.id=a.template_id where a.page_id=$1 and a.kind='content' order by a.sort_order,a.id",[pageId])).rows;
    assert.equal(rows.length,spec.rowCount);const declared=(await connection.query('select r.key,r.admin_label from public.pages p join public.page_composition_regions r on r.layout_id=p.layout_id where p.id=$1',[pageId])).rows;assert.ok(declared.length>0);regions=Object.fromEntries(declared.map(row=>[String(row.key),String(row.admin_label)]));
   }
   assert.ok(rows.length>=spec.rowCount&&rows.length<=512,'Complete bounded scope must fit this controlled verification, never truncate.');
   searchRows=rows.map(row=>({id:spec.key==='items'?String((row.item as Row).id):spec.key==='assignments'?'content:'+row.id:String(row.id),text:searchContract.textFor(row,regions)}));
  }

  assert.deepEqual(ids,fixture.ids);const fingerprints:Row[]=[];
  for(const table of ['menus','menu_items','pages','content_block_templates','page_content_block_assignments','admin_audit_logs'])fingerprints.push({table,...(await connection.query(`select md5(coalesce(jsonb_agg(to_jsonb(t) order by id)::text,'[]')) value from public.${table} t`)).rows[0]});
  const footer=(await connection.query('select to_jsonb(s) value from public.site_settings s where key=any($1::text[]) order by key',[[...FOOTER_SETTING_KEYS]])).rows;fingerprints.push({footer});const fingerprint=hash(fingerprints);if(current.baseline.has(spec.key))assert.equal(fingerprint,current.baseline.get(spec.key),'Presentation and optional preferences cannot change domain rows or audit.');
  let preference:Row|null=null;if(spec.viewKey){const rows=(await connection.query('select preferences from public.admin_user_preferences where admin_user_id=$1 and view_key=$2',[actorId,spec.viewKey])).rows;assert.equal(rows.length,1);preference=rows[0].preferences as Row;assert.deepEqual(Object.keys(preference),['visibleColumns']);assert.deepEqual([...(preference.visibleColumns as string[])].sort(),spec.defaults.filter(key=>request.phase!=='hidden'||key!==spec.optional).sort());}
  await connection.query('commit');const proof={id:request.id,key:spec.key,phase:request.phase,actorId,ownedRunId:handle.identity.runId,fingerprint,ids,preference,searchRows,searchOwnerSha256:searchContract?.sourceSha256??null,searchOwnerPath:searchContract?.path??null};current.proofs.set(request.id,proof);current.baseline.set(spec.key,fingerprint);return {...request,status:'pass',actorId,ownedRunId:handle.identity.runId,fingerprint,ids,preference,searchRows,searchOwnerSha256:searchContract?.sourceSha256??null,searchOwnerPath:searchContract?.path??null};
 }catch(error){await connection.query('rollback');throw error;}});
}

/** Restore only captured QA preferences and the four captured Footer keys.
 * No synthetic content delete is needed: the owned database is disposable. */
export async function cleanupCoreDescendantPresentationFixtures(handle:OwnedLocalHandle){
 assertOwnedLocalHandle(handle);const current=states.get(handle);assert.ok(current&&!current.cleaned);await handle.withDatabaseConnection(async connection=>{await connection.query('begin');try{
  for(const spec of current.plan)if(spec.viewKey){const original=current.originalPreferences.get(spec.key);assert.notEqual(original,undefined);await connection.query('delete from public.admin_user_preferences where admin_user_id=$1 and view_key=$2',[current.actorId,spec.viewKey]);if(original)await connection.query('insert into public.admin_user_preferences select * from jsonb_populate_record(null::public.admin_user_preferences,$1::jsonb)',[JSON.stringify(original)]);const rows:Row[]=(await connection.query('select to_jsonb(p) value from public.admin_user_preferences p where admin_user_id=$1 and view_key=$2',[current.actorId,spec.viewKey])).rows;assert.deepEqual(rows.map(row=>row.value),original?[original]:[]);}
  if(current.originalFooter){for(const row of current.originalFooter)assert.ok((FOOTER_SETTING_KEYS as readonly string[]).includes(String(row.key)));await connection.query('delete from public.site_settings where key=any($1::text[])',[[...FOOTER_SETTING_KEYS]]);for(const row of current.originalFooter)await connection.query('insert into public.site_settings select * from jsonb_populate_record(null::public.site_settings,$1::jsonb)',[JSON.stringify(row)]);const rows=(await connection.query('select to_jsonb(s) value from public.site_settings s where key=any($1::text[]) order by key',[[...FOOTER_SETTING_KEYS]])).rows;assert.deepEqual(rows.map(row=>row.value),current.originalFooter);}
  await connection.query('commit');current.cleaned=true;
 }catch(error){await connection.query('rollback');throw error;}});return {status:'pass',scope:current.scope,exactPreferencesRestored:current.originalPreferences.size,exactFooterRestored:current.originalFooter!==null,ownedRunId:handle.identity.runId};
}
/** Remove only the exact completed prefix produced by this owner; every later record remains subject to its original cohort join. */
export function partitionCoreDescendantNativeCheckpoints(handle:OwnedLocalHandle,input:unknown){
 assertOwnedLocalHandle(handle);const current=states.get(handle);assert.ok(current&&current.cleaned);const native=input as Row;assert.equal(native.status,'pass');assert.equal(native.ownedRunId,handle.identity.runId);assert.ok(Array.isArray(native.records));const expected=[...current.proofs.values()].map(proof=>({kind:'descendant-presentation-state',status:'pass',...proof}));assert.equal(expected.length,current.plan.reduce((sum,spec)=>sum+phases(spec).length,0));assert.deepEqual(native.records.slice(0,expected.length),expected,'Every exact owned descendant checkpoint must be the complete ordered pre-mutation prefix.');const remainder=native.records.slice(expected.length) as Row[];assert.equal(remainder.some(row=>row.kind==='descendant-presentation-state'||current.proofs.has(String(row.id))),false,'No duplicate, foreign or orphan descendant checkpoint can be removed from another join.');return {...native,records:remainder};
}
export function verifyCoreDescendantPresentationCompletion(handle:OwnedLocalHandle,input:unknown,nativeInput:unknown){
 partitionCoreDescendantNativeCheckpoints(handle,nativeInput);
 assertOwnedLocalHandle(handle);const current=states.get(handle);assert.ok(current&&current.cleaned);const browser=input as Row;assert.equal(browser.status,'pass');assert.equal(browser.driverCompleted,true);assert.equal(browser.inventoryOnly,false);assert.deepEqual(browser.errors,[]);assert.equal(browser.cohort,current.scope==='navigation'?'navigation-settings':'page-composition');assert.ok(Array.isArray(browser.evidence));
 const evidence=(browser.evidence as Row[]).filter(row=>String(row.id).startsWith('core-descendant-presentation-'));assert.deepEqual(evidence.map(row=>row.key).sort(),current.plan.map(row=>row.key).sort());const used:string[]=[],joined:Row[]=[];
 for(const spec of current.plan){const outcome=evidence.find(row=>row.key===spec.key)!;assert.equal(outcome.status,'pass');assert.equal(outcome.id,'core-descendant-presentation-'+spec.key);assert.equal(outcome.consumer,spec.consumer);assert.equal(outcome.route,current.fixtures[spec.key].route);const expectedBindings=bindCoreDescendantCells(spec,browser.requiredCases);assert.deepEqual(outcome.namedCellBindings,expectedBindings);assertCoreDescendantProjection(spec,current.fixtures[spec.key].ids,outcome);assert.ok(Array.isArray(outcome.nativeCheckpointIds));const ids=outcome.nativeCheckpointIds as string[];const proofs:Proof[]=ids.map((id):Proof=>{const proof:Proof|undefined=current.proofs.get(id);assert.ok(proof);assert.equal(proof.key,spec.key);assert.equal(proof.actorId,current.actorId);assert.equal(proof.ownedRunId,handle.identity.runId);assert.equal(outcome.nativeActorId,proof.actorId);return proof;});assert.deepEqual(proofs.map(row=>row.phase),phases(spec));assert.ok(proofs.every(row=>row.fingerprint===proofs[0].fingerprint));if(spec.key!=='footer'){const searchReceipt=outcome.searchFragments as {projectionSha256:string;ownerSha256:string;ownerPath:string;status:string;observations:unknown[]};assert.ok(searchReceipt);assert.ok(proofs[0].searchRows);for(const proof of proofs)assert.deepEqual(proof.searchRows,proofs[0].searchRows);assert.deepEqual(searchReceipt.projectionSha256,hash(proofs[0].searchRows));assert.equal(searchReceipt.ownerSha256,proofs[0].searchOwnerSha256);assert.deepEqual(outcome.searchNativeCheckpointIds,[proofs[0].id,proofs.at(-1)!.id]);assert.equal(outcome.searchWrites,0);assert.equal(searchReceipt.status,'search-fragments-observed');assertCoreResidualSearchReceipt({path:proofs[0].searchOwnerPath,sourceSha256:proofs[0].searchOwnerSha256,includes:adminCollectionSearchIncludes},proofs[0].searchRows,current.fixtures[spec.key].search,searchReceipt);assert.deepEqual(outcome.searchNamedCellBindings,bindCoreResidualSearchCells({consumers:[spec.consumer,...spec.aliases]},browser.requiredCases));}used.push(...ids);joined.push({physicalConsumer:spec.consumer,aliases:spec.aliases,bindings:expectedBindings,nativeCheckpoints:ids,route:outcome.route});}
 assert.equal(new Set(used).size,used.length);assert.deepEqual([...used].sort(),[...current.proofs.keys()].sort());const renderedExpected=current.plan.flatMap(spec=>{const route=current.fixtures[spec.key].route;const bindings=[spec.consumer,...spec.aliases].filter(consumer=>(browser.requiredCases as Row[]).some(row=>row.boundary==='collection'&&row.consumer===consumer&&row.axis==='scrollbar'&&row.scenario==='complete_applicable_capability_behavior')).map(consumer=>({boundary:'collection',consumer,surface:route}));return bindings.length?[{journeyId:'core-descendant-presentation-'+spec.key,observationId:'descendant-'+spec.key+'-scrollbar',axis:'scrollbar',bindings,routePathname:route}]:[];});assert.equal(renderedExpected.length,current.plan.length);const renderedAdoption=assertCoreRenderedAdoptionJoin({browser,sourceSha256:browser.sourceSha256,expected:renderedExpected});return {status:'pass',scope:current.scope,renderedAdoption,joined,nativeCheckpoints:used.length,exactPreferencesAndFooterRestored:true,automaticCoverage:[],globalClosed:false,boundary:'Only the actual mounted child pagination/column observations and explicit same-route descendant bindings. No structural-slot pagination or complete-axis inference.'};
}
