import {assertPresentationAcceptedDiscardReceipts,partitionPresentationDiscardNativeRecords} from './fixtures/admin-core-presentation-controls-contract.mjs';
import {assertCoreRenderedAdoptionJoin} from './fixtures/admin-core-rendered-adoption.mjs';
import {join} from 'node:path';
import {partitionContentScrollNativeRecords} from './fixtures/admin-core-presentation-controls-contract.mjs';
import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {createRequire} from "node:module";
import {createJiti} from "jiti";
import ts from "typescript";
import * as React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {assertContentScrollFingerprints,assertContentScrollReceipt,validateContentScrollFixture,PRESENTATION_CONTROL_KINDS,PRESENTATION_CONTROL_PHASES,PRESENTATION_CONTROL_ASSETS,buildCorePresentationControlsPlan,validatePresentationControlsRequest,presentationControlForm,loadPresentationControlBuilders,assertPresentationControlsConfig,assertPresentationControlsRow} from "./fixtures/admin-core-presentation-controls-contract.mjs";
const root=resolve(import.meta.dirname,".."),jiti=createJiti(import.meta.url,{fsCache:false,moduleCache:false,alias:{"server-only":resolve(root,"node_modules/next/dist/compiled/server-only/empty.js")}});
const{ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST:manifest}=await jiti.import<typeof import("../src/lib/admin/form-system/adoption-manifest.ts")>(resolve(root,"src/lib/admin/form-system/adoption-manifest.ts"));
const fixtures={templates:PRESENTATION_CONTROL_KINDS.map((kind,index)=>({kind,id:index+1,name:"QA "+kind,slug:"qa-admin-page-interaction-"+kind+"-8",editPath:"/admin/pages-blocks/blocks/"+kind+"/"+(index+1)})),assets:PRESENTATION_CONTROL_ASSETS.map(objectKey=>({objectKey,publicUrl:"/"+objectKey}))};
const cases:string[]=[],test=(name:string,run:()=>unknown)=>{run();cases.push(name);};const builders=await loadPresentationControlBuilders();
test("Actual current Form manifest resolves only two concrete edit surfaces without axis promotion",()=>{const plan=buildCorePresentationControlsPlan({manifest,fixtures});assert.equal(plan.recipes.length,2);assert.ok(plan.recipes.every((row:{coverage:unknown[]})=>row.coverage.length===0));assert.deepEqual(plan.automaticAxisCoverage,[]);assert.equal(plan.globalClosed,false);assert.equal(plan.nonCapabilities.length,3);});
test("Missing current Hero adopter rejects",()=>assert.throws(()=>buildCorePresentationControlsPlan({manifest:manifest.filter(row=>!("registryModuleKind" in row)||row.registryModuleKind!=="hero"),fixtures})));
for(const delta of[{templates:fixtures.templates.slice(1)},{templates:[...fixtures.templates,fixtures.templates[0]]},{templates:fixtures.templates.map((row,index)=>index?row:{...row,slug:"real-template"})},{templates:fixtures.templates.map((row,index)=>index?row:{...row,id:0})},{templates:fixtures.templates.map((row,index)=>index?row:{...row,editPath:"/admin"})},{assets:fixtures.assets.map((row,index)=>index?row:{...row,publicUrl:"https://foreign.invalid"})}])test("Reject unowned fixture "+cases.length,()=>assert.throws(()=>buildCorePresentationControlsPlan({manifest,fixtures:{...fixtures,...delta}})));
const request={id:randomUUID(),kind:"presentation-controls-state",recipe:"hero",phase:"baseline"};test("Fixed twelve native phase requests",()=>{for(const recipe of PRESENTATION_CONTROL_KINDS)for(const phase of PRESENTATION_CONTROL_PHASES)validatePresentationControlsRequest({...request,recipe,phase});});
for(const delta of[{sql:"select 1"},{expected:{}},{table:"hero_templates"},{recipe:"__proto__"},{recipe:"constructor"},{phase:"skip"},{id:"bad"}])test("Reject arbitrary checkpoint "+JSON.stringify(delta),()=>assert.throws(()=>validatePresentationControlsRequest({...request,...delta})));
for(const kind of PRESENTATION_CONTROL_KINDS){
 const form=presentationControlForm(kind,fixtures),config=builders.build(kind,form);
 test("Actual private pure config builder round trip: "+kind,()=>assertPresentationControlsConfig(kind,config,fixtures));
 for(const key of["title","showTitle","titleBold","titleAlignment",...(kind==="hero"?["images","mobileImages","primaryCtaLink","secondaryCtaLink","imageComposition"]:["body"])])test("Native projection rejects missing authored "+kind+":"+key,()=>{const broken=structuredClone(config);delete broken[key];assert.throws(()=>assertPresentationControlsConfig(kind,broken,fixtures));});
 const original={id:kind==="hero"?1:2,name:"QA "+kind,slug:"qa-admin-page-interaction-"+kind+"-8",status:"published",variant:kind==="hero"?"internal-page":null,style_preset:null,description:null,created_at:"2026-01-01",updated_at:"2026-01-01",config:{title:"original"},...(kind==="hero"?{source_type:"manual",source_id:null,source_slug:null,limit_count:1,is_visible:true}:{}),other_identity:"retained"};
 const saved={...original,config,updated_at:"2026-01-02",variant:original.variant||"default",style_preset:kind==="hero"?"cinematic-gold":"premium-dark"};
 test("Exact current Action default normalization, identity preserved: "+kind,()=>assertPresentationControlsRow(kind,saved,original,config));
 for(const key of["id","slug","name","status","created_at","other_identity","config"])test("Native full row comparison rejects unrelated drift "+kind+":"+key,()=>assert.throws(()=>assertPresentationControlsRow(kind,{...saved,[key]:"changed"},original,config)));
}
test("Actual Hero builder stores cleared secondary CTA as null rather than a fabricated none object",()=>{const config=builders.build("hero",presentationControlForm("hero",fixtures));assert.equal(config.secondaryCtaLink,null);});
test("Current internal Hero forces canonical order; this journey does not claim editable element order",()=>{const form=presentationControlForm("hero",fixtures);form.set("hero_element_order","cta,title");assert.deepEqual(builders.build("hero",form).heroElementOrder,["eyebrow","title","highlight","subtitle","description","cta"]);});
const utils=await jiti.import<typeof import("../src/lib/page-blocks/admin-utils.ts")>(resolve(root,"src/lib/page-blocks/admin-utils.ts"));
for(const[kind,name]of [["hero","updateHeroTemplateDetails"],["content","updateContentBlock"]]){
 const file=resolve(root,"src/app/admin/pages-blocks/blocks",kind,"actions.ts"),source=readFileSync(file,"utf8"),tree=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true);const fn=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name);assert.ok(fn&&ts.isFunctionDeclaration(fn)&&fn.body);
 const firstGuard=fn.body.statements.findIndex(node=>ts.isIfStatement(node));assert.ok(firstGuard>0);const prefix=fn.body.statements.slice(0,firstGuard+1).map(node=>node.getText(tree)).join("\n");assert.doesNotMatch(prefix,/getSupabaseAdmin|mutatePageComposition|coordinateMedia/u);
 const code=ts.transpileModule("async function guard(formData:FormData){"+prefix+"}",{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 const guard=new Function("requireAdminSession","parseNumber","cleanText","slugify",code+";return guard;")(async()=>({id:99}),utils.parseNumber,utils.cleanText,utils.slugify) as (form:FormData)=>Promise<void>;
 const form=new FormData();form.set("id","1");form.set("slug","qa-valid");form.set("name","");await assert.rejects(guard(form));cases.push("Actual Action prewrite missing-name guard: "+kind);
 form.set("name","QA valid");await guard(form);cases.push("Actual Action prewrite guard permits canonical retry: "+kind);
}
// Render the actual shared formatting owner with actual leaf controls. Only CSS is stubbed.
const ownerFile=resolve(root,"src/components/admin/page-blocks/ModuleEditorPresentation.tsx"),ownerSource=readFileSync(ownerFile,"utf8"),tree=ts.createSourceFile(ownerFile,ownerSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const owner=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==="ModuleEditorVisibilityAlignRow");assert.ok(owner);const ownerCode=ts.transpileModule(owner.getText(tree).replace(/^export /,""),{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
const leaf=(name:string)=>{const filename=resolve(root,"src/components/admin/ui",name+".tsx"),compiled=ts.transpileModule(readFileSync(filename,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const loaded={exports:{}};new Function("require","module","exports",compiled)(createRequire(import.meta.url),loaded,loaded.exports);return (loaded.exports as {default:React.ComponentType}).default;};
const Switch=leaf("AdminFormSwitch"),Format=leaf("AdminTextFormatControls");
const Row=new Function("React","useState","Children","AdminFormSwitch","AdminTextFormatControls","MODULE_EDITOR_CONTROL_CARD_CLASS_NAME",ownerCode+";return ModuleEditorVisibilityAlignRow;")(React,React.useState,React.Children,Switch,Format,"") as React.ComponentType<Record<string,unknown>>;
for(const mirrored of[false,true])test("Actual rendered "+(mirrored?"two mirrored CTA":"single text")+" toolbars retain one submitted format tuple",()=>{const html=renderToStaticMarkup(React.createElement(Row,{label:"QA",alignmentName:"cta_alignment",showName:"show_cta",boldName:"cta_bold",alignmentDefault:"center",showDefault:false,boldDefault:true,controlsPlacement:mirrored?"cards":"header"},React.createElement("div",{key:"a"},"A"),...(mirrored?[React.createElement("div",{key:"b"},"B")]:[])));for(const name of["show_cta","cta_alignment","cta_bold"])assert.equal(html.split('name="'+name+'"').length-1,1);assert.equal(html.split('role="switch"').length-1,mirrored?2:1);assert.equal(html.split('data-admin-text-format-bold=""').length-1,mirrored?2:1);assert.match(html,/name="show_cta" value="false"/u);assert.match(html,/name="cta_alignment" value="center"/u);});
const browser=readFileSync(resolve(root,"scripts/fixtures/admin-core-presentation-controls-journeys.mjs"),"utf8");test("No alternate interception, direct HTTP, hidden mutations, forced clicks or capability promotion",()=>{assert.doesNotMatch(browser,/page\.(route|unroute|request)|force:\s*true|\.selectOption\(|dispatchEvent\(/u);assert.match(browser,/nativeFinalityRequired:true/u);assert.match(browser,/fieldset\[data-admin-form-fields\]/u);assert.doesNotMatch(browser,/data-admin-form-pending-fields/u);assert.match(browser,/actualStatementCancelled:cancel/u);});
const scrollFixture={id:11,name:'QA Core Content Scroll Variant',slug:'qa-core-content-scroll-about-intro-single-image',variant:'about-intro-single-image',status:'unpublished',editPath:'/admin/pages-blocks/blocks/content/11',unassigned:true,configSha256:'a'.repeat(64)};
const fingerprint={id:randomUUID(),kind:'form-permission-fingerprint',correlationId:randomUUID(),phase:'before',status:'pass',ownedRunId:'owned-verification-run',adminAuditIncluded:true,adminUsersIncluded:true,publicTableCount:64,publicTableInventorySha256:'b'.repeat(64),publicDataSha256:'c'.repeat(64)};
const afterFingerprint={...fingerprint,id:randomUUID(),phase:'after'},scrollSource='d'.repeat(64),scrollReceipt={fixture:scrollFixture,sourceSha256:scrollSource,routePathname:scrollFixture.editPath,readOnly:true,saveNotInvoked:true,reloadVariantRetained:true,pickerCancelled:true,exactTriggerFocusRestored:true,nativeIds:[fingerprint.id,afterFingerprint.id],ownedRunId:fingerprint.ownedRunId,automaticCoverage:[],globalClosed:false};
const scrollBrowser={status:'pass',driverCompleted:true,inventoryOnly:false,sourceSha256:scrollSource,evidence:[{id:'existing-auth-login',status:'pass',authenticated:true},{id:'core-presentation-content-variant-scroll',status:'pass',contentScroll:scrollReceipt,renderedAdoption:[{id:'presentation-content-single-image-media-scroll'}]}],errors:[],presentationControls:{contentScroll:scrollReceipt}};
const proof={browser:scrollBrowser,nativeRecords:[fingerprint,afterFingerprint],fixture:scrollFixture,ownedRunId:fingerprint.ownedRunId},copy=()=>JSON.parse(JSON.stringify(proof));
test('Separate actual Content fixture + broker fingerprints qualify only readonly partial observation',()=>{validateContentScrollFixture(scrollFixture);assertContentScrollFingerprints(fingerprint,afterFingerprint);const result=assertContentScrollReceipt(proof);assert.equal(result.status,'partial-not-global-pass');assert.equal(result.renderedAdoptionJoinStillRequired,true);assert.deepEqual(result.automaticCoverage,[]);});
const corruptions:Array<[string,(x:ReturnType<typeof copy>)=>void]>=[
 ['fixture variant',x=>x.fixture.variant='default'],['assigned template',x=>x.fixture.unassigned=false],['foreign fixture route',x=>x.fixture.editPath='/admin'],['failed journey',x=>x.browser.evidence[1].status='fail'],['recorded failed journey',x=>x.browser.errors.push({id:'core-presentation-content-variant-scroll'})],['duplicate journey',x=>x.browser.evidence.push({...x.browser.evidence[1]})],['missing authentication',x=>x.browser.evidence.shift()],['foreign source',x=>x.browser.sourceSha256='e'.repeat(64)],['false save promise',x=>{x.browser.presentationControls.contentScroll.saveNotInvoked=false;x.browser.evidence[1].contentScroll.saveNotInvoked=false;}],['missing fingerprint',x=>x.nativeRecords.pop()],['duplicate native record',x=>x.nativeRecords.push({...x.nativeRecords[0]})],['foreign owned run',x=>x.nativeRecords[1].ownedRunId='foreign'],['data mutation',x=>x.nativeRecords[1].publicDataSha256='f'.repeat(64)],['audit excluded',x=>x.nativeRecords[1].adminAuditIncluded=false],['identity excluded',x=>x.nativeRecords[1].adminUsersIncluded=false],['inventory changed',x=>x.nativeRecords[1].publicTableCount++],['foreign correlation',x=>x.nativeRecords[1].correlationId=randomUUID()],['wrong phase order',x=>x.nativeRecords[1].phase='before'],['missing actual rendered observation',x=>x.browser.evidence[1].renderedAdoption=[]],['different collector summary',x=>x.browser.presentationControls.contentScroll.routePathname='/admin/elsewhere'],
];for(const[name,change]of corruptions)test('Content scroll strict native join rejects '+name,()=>{const value=copy();change(value);assert.throws(()=>assertContentScrollReceipt(value));});
const nativeFile=resolve(root,'scripts/verify-admin-core-presentation-controls-isolated.mts'),nativeSource=readFileSync(nativeFile,'utf8'),nativeAst=ts.createSourceFile(nativeFile,nativeSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),seedNode=nativeAst.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='prepareContentScrollFixture');assert.ok(seedNode);const seedCode=ts.transpileModule(seedNode.getText(nativeAst).replaceAll('import.meta.url','moduleUrl'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const realConfig=await jiti.import<typeof import('../src/lib/page-blocks/configs.ts')>(resolve(root,'src/lib/page-blocks/configs.ts')),realRegistry=await jiti.import<typeof import('../src/lib/page-blocks/module-edit-registry.ts')>(resolve(root,'src/lib/page-blocks/module-edit-registry.ts'));
async function seedPort(mode:string){const calls:Array<{sql:string;args?:unknown[]}>=[];const handle={owned:true,withDatabaseConnection:async(callback:(client:{query:(sql:string,args?:unknown[])=>Promise<{rows:Record<string,unknown>[]}>})=>unknown)=>callback({query:async(sql,args)=>{calls.push({sql,args});if(sql==='begin'||sql==='rollback')return{rows:[]};if(sql==='commit'){if(mode==='commit-error')throw Error('COMMIT_FAIL');return{rows:[]};}if(sql.startsWith('select id from public.content_block_templates'))return{rows:mode==='duplicate'?[{id:99}]:[]};if(sql.startsWith('insert into public.content_block_templates')){if(mode==='insert-error')throw Error('INSERT_FAIL');assert.equal(args?.[1],scrollFixture.slug);assert.equal(args?.[2],scrollFixture.variant);assert.equal(typeof args?.[3],'string');const config=JSON.parse(String(args?.[3]));return{rows:[{id:11,name:scrollFixture.name,slug:scrollFixture.slug,variant:scrollFixture.variant,status:'unpublished',config}]};}if(sql.startsWith('select id from public.page_composition_assignments'))return{rows:mode==='assigned'?[{id:2}]:[]};throw Error('UNEXPECTED_SQL');}})};const seed=new Function('moduleUrl','assert','assertOwnedLocalHandle','createJiti','PRESENTATION_CONTROL_ASSETS','hash','validateContentScrollFixture',seedCode+';return prepareContentScrollFixture;')(import.meta.url,assert,(target:typeof handle)=>assert.equal(target.owned,true),()=>({import:(specifier:string)=>Promise.resolve(specifier.includes('module-edit-registry')?realRegistry:realConfig)}),PRESENTATION_CONTROL_ASSETS,()=> 'a'.repeat(64),validateContentScrollFixture) as (handle:unknown)=>Promise<unknown>;return{calls,run:()=>seed(handle)};}
for(const mode of ['okay','duplicate','assigned','insert-error','commit-error']){const port=await seedPort(mode);if(mode==='okay'){const result=await port.run();validateContentScrollFixture(result);assert.equal(port.calls.at(-1)?.sql,'commit');assert.equal(port.calls.filter(row=>row.sql==='rollback').length,0);}else{await assert.rejects(port.run());assert.equal(port.calls.at(-1)?.sql,'rollback');}cases.push('Actual fixed native seed transaction '+mode);}
const primaryLoop=ts.createSourceFile('journey.mjs',browser,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);test('Extra Content observation uses existing fingerprint protocol and no save/POST transport',()=>{assert.match(browser,/kind:'form-permission-fingerprint'/u);assert.match(browser,/assertContentScrollFingerprints\(before,after\)/u);assert.match(browser,/actionRequests,0/u);assert.match(browser,/picker\.getByRole\('button',\{name:'إلغاء'/u);assert.match(browser,/planned:2,completed:outcomes.length/u);assert.ok(primaryLoop.statements.some(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='observeContentScrollVariant'));});


const coreNativeRows=[{id:randomUUID(),kind:'presentation-controls-state',status:'pass'},{id:randomUUID(),kind:'domain-write-fault-arm',status:'pass'},fingerprint,afterFingerprint];const qualifiedScroll=assertContentScrollReceipt(proof);
test('Qualified Content fingerprints partition exactly, preserving every original state and fault',()=>assert.deepEqual(partitionContentScrollNativeRecords(coreNativeRows,qualifiedScroll),coreNativeRows.slice(0,2)));
for(const mode of ['missing','duplicate','foreign','wrong-kind','failed','reordered','forged-qualification'])test('Strict Content partition refuses '+mode,()=>{const records=JSON.parse(JSON.stringify(coreNativeRows)),qualified=JSON.parse(JSON.stringify(qualifiedScroll));if(mode==='missing')records.pop();else if(mode==='duplicate')records.push({...records[2]});else if(mode==='foreign')records.push({...records[2],id:randomUUID()});else if(mode==='wrong-kind')records[2].kind='other';else if(mode==='failed')records[2].status='fail';else if(mode==='reordered')[records[2],records[3]]=[records[3],records[2]];else qualified.unusedVariantUnchanged=false;assert.throws(()=>partitionContentScrollNativeRecords(records,qualified));});

const collectorPath=resolve(root,'scripts/verify-admin-adoption-readback-isolated.mts'),collectorSource=readFileSync(collectorPath,'utf8'),collectorAst=ts.createSourceFile(collectorPath,collectorSource,ts.ScriptTarget.Latest,true),sourceAnchorStatements=new Map<string,string>();
function findContentSourceAnchor(node:ts.Node){if(ts.isVariableStatement(node))for(const declaration of node.declarationList.declarations){if(ts.isIdentifier(declaration.name)&&['contentScrollSource','contentScrollRendered'].includes(declaration.name.text)){assert.equal(sourceAnchorStatements.has(declaration.name.text),false);sourceAnchorStatements.set(declaration.name.text,node.getText(collectorAst));}}ts.forEachChild(node,findContentSourceAnchor);}findContentSourceAnchor(collectorAst);assert.equal(sourceAnchorStatements.size,2);
const runContentSourceAnchor=new Function('readFileSync','join','artifactDir','browser','contentScroll','assertCoreRenderedAdoptionJoin',ts.transpileModule([...sourceAnchorStatements.values()].join('\n')+'\nreturn contentScrollRendered;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText);
function anchorBrowser(sourceSha256:string){const value=JSON.parse(JSON.stringify(scrollBrowser)),binding={boundary:'form',consumer:'block-template-content-editor',surface:'content:template-edit'};value.sourceSha256=sourceSha256;value.presentationControls.contentScroll.sourceSha256=sourceSha256;value.evidence[1].contentScroll.sourceSha256=sourceSha256;value.requiredCases=[{key:'form:block-template-content-editor:capability:scrollbar',boundary:'form',consumer:binding.consumer,axis:'scrollbar',scenario:'complete_applicable_capability_behavior',declaration:'adopted'},{boundary:'form',consumer:binding.consumer,surface:binding.surface}];value.evidence[1].renderedAdoption=[{id:'presentation-content-single-image-media-scroll',receiptId:randomUUID(),status:'rendered-fragments-observed',sourceSha256,axis:'scrollbar',routePathname:scrollFixture.editPath,bindings:[{key:value.requiredCases[0].key,...binding}],containment:'modal-lock',observations:[{viewport:'desktop',width:1280,height:900},{viewport:'narrow',width:390,height:760}].map(view=>({...view,state:'overflow-observed',targetReachable:true,targetHitTestPassed:true,computedCanonicalThin:true,extent:900,client:400,actualWheelMoved:true,farBoundaryReached:true,backgroundPositionRetained:true})),automaticCoverage:[],globalClosed:false}];return value;}
function anchorPort(browser:ReturnType<typeof anchorBrowser>,manifestSource:string|null){const calls:string[]=[];const value=()=>runContentSourceAnchor((path:string,encoding:string)=>{calls.push(path);assert.equal(path,join(root,'owned-review-artifacts','public-source-manifest.json'));assert.equal(encoding,'utf8');if(manifestSource===null)throw Error('MISSING_OWNED_SOURCE_MANIFEST');return JSON.stringify({sourceSha256:manifestSource});},join,join(root,'owned-review-artifacts'),browser,{fixtureId:scrollFixture.id},assertCoreRenderedAdoptionJoin);return{calls,value};}
test('Actual collector anchors Content rendered join to independent frozen source manifest',()=>{const port=anchorPort(anchorBrowser(scrollSource),scrollSource);assert.equal(port.value().sourceSha256,scrollSource);assert.equal(port.calls.length,1);});
test('Actual collector rejects coherently foreign source across Browser summary and Content rendered receipt',()=>{const browser=anchorBrowser('e'.repeat(64));assert.equal(assertContentScrollReceipt({...proof,browser}).status,'partial-not-global-pass');const port=anchorPort(browser,scrollSource);assert.throws(port.value);assert.equal(port.calls.length,1);});
test('Actual collector rejects missing frozen source manifest',()=>assert.throws(anchorPort(anchorBrowser(scrollSource),null).value));
test('Actual collector rejects malformed independent frozen source hash',()=>assert.throws(anchorPort(anchorBrowser(scrollSource),'not-a-source-hash').value));

const discardPlan=buildCorePresentationControlsPlan({manifest,fixtures});
function discardFrame(){const nativeRecords:Record<string,unknown>[]=[],outcomes=discardPlan.recipes.map((recipe:{kind:string;consumer:string;surface:string;editPath:string})=>{const correlation=randomUUID(),reopenCorrelation=randomUUID(),pair=[{...fingerprint,id:randomUUID(),correlationId:correlation,phase:'before'},{...fingerprint,id:randomUUID(),correlationId:correlation,phase:'after'}],reopened=[{...fingerprint,id:randomUUID(),correlationId:reopenCorrelation,phase:'before'},{...fingerprint,id:randomUUID(),correlationId:reopenCorrelation,phase:'after'}];for(const phase of PRESENTATION_CONTROL_PHASES){nativeRecords.push({id:randomUUID(),kind:'presentation-controls-state',status:'pass',actorBound:true,assignmentGraphUnchanged:true,catalogUnchanged:true,recipe:recipe.kind,phase});if(phase==='serverRejected')nativeRecords.push(...pair,...reopened);}return{kind:recipe.kind,consumer:recipe.consumer,surface:recipe.surface,postRejectionDirtyNavigationCancelled:true,acceptedDiscard:{status:'discard-accepted-before-reauthor',kind:'navigated',fromPathname:recipe.editPath,toPathname:'/admin/pages-blocks/blocks/'+recipe.kind,nativeBefore:pair[0].id,nativeAfter:pair[1].id,nativeCorrelationId:correlation,actionRequests:0,nativePublicStateUnchanged:true,adminAuditIncluded:true,guardAccepted:true,observedDestination:true,acceptedBeforeReauthor:true,reopen:{nativeBefore:reopened[0].id,nativeAfter:reopened[1].id,nativeCorrelationId:reopenCorrelation,actionRequests:0,nativePublicStateUnchanged:true,draftReauthored:true,originalRouteRestored:true}}};});return JSON.parse(JSON.stringify({browser:{status:'pass',cohort:'presentation-controls',driverCompleted:true,sourceSha256:scrollSource,errors:[],presentationControls:{planned:2,completed:2,outcomes},evidence:outcomes.map((r:{kind:string})=>({...r,id:'core-presentation-controls-'+r.kind,status:'pass'}))},nativeRecords,ownedRunId:fingerprint.ownedRunId,sourceSha256:scrollSource,plan:discardPlan}));}
test('Exact Hero/Content accepted discard and reopen pair join preserves original twelve state receipts',()=>{const value=discardFrame(),joined=assertPresentationAcceptedDiscardReceipts(value);assert.equal(joined.qualified.length,2);assert.equal(joined.nativeCheckpointIds.length,8);const remaining=partitionPresentationDiscardNativeRecords(value.nativeRecords,joined);assert.equal(remaining.length,12);assert.ok(remaining.every((r:{kind:string})=>r.kind==='presentation-controls-state'));});
const discardMutants:Record<string,(x:ReturnType<typeof discardFrame>)=>void>={foreignActorBinding:x=>x.nativeRecords[3].actorBound=false,missingActorBinding:x=>delete x.nativeRecords[3].actorBound,missingEditor:x=>x.browser.presentationControls.outcomes.pop(),missingEvidence:x=>x.browser.evidence.pop(),foreignSource:x=>x.sourceSha256='f'.repeat(64),wrongFixtureId:x=>{x.browser.evidence[0].acceptedDiscard.fromPathname='/admin/pages-blocks/blocks/hero/999';x.browser.presentationControls.outcomes[0].acceptedDiscard.fromPathname='/admin/pages-blocks/blocks/hero/999';},foreignConsumer:x=>x.browser.presentationControls.outcomes[0].consumer='block-template-cards-editor',wrongSurface:x=>x.browser.presentationControls.outcomes[0].surface='hero:template-command',missingCancel:x=>x.browser.evidence[0].postRejectionDirtyNavigationCancelled=false,missingAcceptance:x=>{x.browser.evidence[0].acceptedDiscard.guardAccepted=false;x.browser.presentationControls.outcomes[0].acceptedDiscard.guardAccepted=false;},missingPair:x=>x.nativeRecords.splice(5,1),duplicateNative:x=>x.nativeRecords.push({...x.nativeRecords[4]}),foreignRun:x=>x.nativeRecords[4].ownedRunId='foreign',changedData:x=>x.nativeRecords[5].publicDataSha256='e'.repeat(64),auditOmitted:x=>x.nativeRecords[4].adminAuditIncluded=false,usersOmitted:x=>x.nativeRecords[4].adminUsersIncluded=false,missingReopen:x=>{delete x.browser.evidence[0].acceptedDiscard.reopen;delete x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen;},reopenWrites:x=>{x.browser.evidence[0].acceptedDiscard.reopen.actionRequests=1;x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen.actionRequests=1;},changedReopen:x=>x.nativeRecords[7].publicDataSha256='e'.repeat(64),borrowedReopen:x=>{x.browser.evidence[0].acceptedDiscard.reopen.nativeCorrelationId=x.browser.evidence[0].acceptedDiscard.nativeCorrelationId;x.browser.presentationControls.outcomes[0].acceptedDiscard.reopen.nativeCorrelationId=x.browser.evidence[0].acceptedDiscard.nativeCorrelationId;},reordered:x=>[x.nativeRecords[4],x.nativeRecords[5]]=[x.nativeRecords[5],x.nativeRecords[4]],failedBrowser:x=>x.browser.status='failed',recordedError:x=>x.browser.errors.push({id:x.browser.evidence[0].id}),nativeAfterSave:x=>{const pairs=x.nativeRecords.splice(4,4);x.nativeRecords.push(...pairs);}};
for(const[name,change]of Object.entries(discardMutants))test('Accepted discard exact scheduled join rejects '+name,()=>{const value=discardFrame();change(value);assert.throws(()=>assertPresentationAcceptedDiscardReceipts(value));});
test('A foreign fingerprint survives discard partition and fails existing strict Content partition',()=>{const value=discardFrame(),joined=assertPresentationAcceptedDiscardReceipts(value);value.nativeRecords.push({...fingerprint,id:randomUUID()});const rest=partitionPresentationDiscardNativeRecords(value.nativeRecords,joined);assert.throws(()=>partitionContentScrollNativeRecords([...rest,fingerprint,afterFingerprint],qualifiedScroll));});

console.log(JSON.stringify({status:"pass",controls:cases.length,cases,runtimeExecuted:false,globalClosed:false}));
