import assert from "node:assert/strict";
import ts from "typescript";
import { isDeepStrictEqual } from "node:util";
import { randomUUID, createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { createJiti } from "jiti";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const jiti = createJiti(import.meta.url, { fsCache: false, moduleCache: false, alias: { "server-only": resolve(root, "node_modules/next/dist/compiled/server-only/empty.js") } });
const { buildCoreSpecializedSettingsPlan, fillCorePrivateField, assertCoreSpecializedClosureReceipt, coreSpecializedClosureJourneyIds, CORE_SPECIALIZED_CLOSURE_IDS, CORE_SPECIALIZED_CLOSURE_SELECTION } = await import("./fixtures/admin-core-specialized-settings-journeys.mjs");
const { validateCoreSpecializedSettingsRequest, validateCoreClosureWizardRequest } = await jiti.import<typeof import("./verify-admin-core-specialized-settings-isolated.mts")>(resolve(root, "scripts/verify-admin-core-specialized-settings-isolated.mts"));
const { ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST } = await jiti.import<typeof import("../src/lib/admin/form-system/adoption-manifest.ts")>(resolve(root, "src/lib/admin/form-system/adoption-manifest.ts"));
const { INTEGRATION_APP_CONFIGURATION_DEFINITIONS, INTEGRATION_APP_CONFIGURATION_SURFACES } = await jiti.import<typeof import("../src/lib/admin/integrations/server-configuration-contract.ts")>(resolve(root, "src/lib/admin/integrations/server-configuration-contract.ts"));
const args = { manifest: ADMIN_FORM_SYSTEM_ADOPTION_MANIFEST, definitions: INTEGRATION_APP_CONFIGURATION_DEFINITIONS, surfaces: INTEGRATION_APP_CONFIGURATION_SURFACES,
  fixtures: { securityActor: { id: 27, username: "qa_core_security_settings" }, providers: INTEGRATION_APP_CONFIGURATION_DEFINITIONS.map(row => row.key) } };
const cases: string[] = [];
const test = async (name: string, execute: () => unknown | Promise<unknown>) => { await execute(); cases.push(name); };
await test("Plan derives the three canonical specialized exceptions and all provider owners", () => {
  const plan = buildCoreSpecializedSettingsPlan(args);
  assert.equal(plan.consumers.length, 3); assert.equal(plan.providers.length, INTEGRATION_APP_CONFIGURATION_DEFINITIONS.length);
  assert.equal(plan.globalClosed, false); assert.deepEqual(plan.automaticCoverage, []);
  assert.equal(plan.remaining.length, 1); assert.match(plan.remaining[0].reason, /unexecuted/u);
});
await test("Unknown manifest family cannot silently pass", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, manifest: args.manifest.filter(row => row.id !== "security-settings") })));
await test("Duplicate consumer identity rejects", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, manifest: [...args.manifest, args.manifest.find(row => row.id === "security-settings")] })));
await test("Generic classification is not promoted through specialized proof", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, manifest: args.manifest.map(row => row.id === "security-settings" ? { ...row, classification: "shared" } : row) })));
await test("New unreviewed security surface rejects", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, manifest: args.manifest.map(row => row.id === "security-settings" ? { ...row, surfaces: [...row.surfaces, "policy-editor"] } : row) })));
await test("Fixture provider omissions reject", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, fixtures: { ...args.fixtures, providers: [] } })));
await test("Provider with an integration that needs no absent secret rejects before Test", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, definitions: args.definitions.map((row, index) => index === 0 ? { ...row, integrations: [...row.integrations, "unfenced-provider"] } : row) })));
await test("New independent configuration surface rejects instead of duplicating Meta", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, surfaces: [...args.surfaces, "unreviewed"] })));
await test("Wrong disposable account identity rejects", () => assert.throws(() => buildCoreSpecializedSettingsPlan({ ...args, fixtures: { ...args.fixtures, securityActor: { id: 27, username: "primary-admin" } } })));
await test("Private fill passes the value only to its memory-local receiver", async () => {
  let observed = false; await fillCorePrivateField({ fill: async (value: string) => { observed = value === "synthetic-private-control"; } }, "synthetic-private-control"); assert.equal(observed, true);
});
await test("Private fill rejects without exposing Playwright's value-bearing diagnostic", async () => {
  await assert.rejects(fillCorePrivateField({ fill: async () => { throw new Error("fill synthetic-private-control timed out"); } }, "synthetic-private-control"), (error: unknown) => error instanceof Error && !error.message.includes("synthetic-private-control") && !error.stack?.includes("synthetic-private-control") && !error.cause);
});
const security = { id: randomUUID(), kind: "specialized-settings-state", entity: "security", phase: "baseline" };
await test("Fixed security checkpoint accepts no browser expectation or selector", () => assert.deepEqual(validateCoreSpecializedSettingsRequest(security), security));
await test("Maintenance checkpoint exact contract accepted", () => validateCoreSpecializedSettingsRequest({ ...security, entity: "maintenance", phase: "restored" }));
await test("Canonical provider checkpoint exact contract accepted", () => validateCoreSpecializedSettingsRequest({ ...security, entity: "integration", phase: "stale-rejected", provider: args.definitions[0].key }));
for (const [name, changed] of [
  ["Unknown checkpoint kind", { kind: "run-sql" }], ["Unknown entity", { entity: "production" }], ["Malformed UUID", { id: "------------------------------------" }],
  ["Arbitrary SQL", { sql: "select private_value" }], ["Arbitrary IDs", { actorId: 1 }], ["Browser expected secret", { expected: "private" }],
  ["Provider on security", { provider: "google" }], ["Unknown phase", { phase: "force-success" }],
] as const) await test(name + " rejects", () => assert.throws(() => validateCoreSpecializedSettingsRequest({ ...security, ...changed })));
await test("Unknown integration provider rejects", () => assert.throws(() => validateCoreSpecializedSettingsRequest({ ...security, entity: "integration", provider: "unreviewed" })));
await test("Missing integration provider rejects", () => assert.throws(() => validateCoreSpecializedSettingsRequest({ ...security, entity: "integration" })));
await test("Security cancellation requires a distinct fixed readback", () => validateCoreSpecializedSettingsRequest({ ...security, phase: "sessions-cancelled" }));
const browser = readFileSync(resolve(root, "scripts/fixtures/admin-core-specialized-settings-journeys.mjs"), "utf8");
const native = readFileSync(resolve(root, "scripts/verify-admin-core-specialized-settings-isolated.mts"), "utf8");
await test("No generic coverage, environment import, manual fetch, retained-cookie artifact or provider wizard", () => {
  assert.equal(browser.includes("process.env"), false); assert.equal(/\.request\.|fetch\(|writeFile|import_environment|Connection Wizard/u.test(browser), false);
  assert.equal(browser.includes("automaticCoverage: []"), true); assert.equal(browser.includes('context.route("**/*", ownedNetworkOnly)'), true);
});
await test("Test control follows native incomplete proof and precedes secret save", () => {
  const proof = browser.indexOf('checkpoint("integration", "incomplete", provider)');
  const testCall = browser.indexOf('mutate(page, "test"'); const secretSave = browser.indexOf('integration:${provider}:${field.key}:a');
  assert.ok(proof >= 0 && testCall > proof && secretSave > testCall);
  const resolver = readFileSync(resolve(root, "src/lib/admin/integrations/server-configuration-resolver.ts"), "utf8");
  const service = readFileSync(resolve(root, "src/lib/admin/integrations/server-configuration-service.ts"), "utf8");
  assert.ok(resolver.indexOf("if (group)") < resolver.indexOf("const values: Partial", resolver.indexOf("if (group)")));
  assert.match(service, /if \(before\.missing\.length\)[\s\S]*?continue;[\s\S]*?claimApplicationConfigurationTest/u);
});
await test("Native verifier exports fixed booleans, compares secrets in SQL and protects primary hash diagnostics", () => {
  assert.match(native, /decrypted_secret=\$2\) matches/u); assert.match(native, /isDeepStrictEqual\(main, state\.mainBefore\)/u);
  assert.equal(/return[^\n]*(?:password_hash|vault_secret_id|state\.password|decrypted_secret)/u.test(native), false);
  assert.match(native, /Never replace an existing security actor/u); assert.match(native, /integration_connections/u);
});
await test("Maintenance proof respects the existing explicit five-second proxy policy", () => {
  const owner = readFileSync(resolve(root, "src/lib/maintenance/read-maintenance-mode.ts"), "utf8");
  assert.match(owner, /const CACHE_TTL_MS = 5_000;/u); assert.match(browser, /specialized-maintenance-policy-ttl/u);
  assert.match(native, /parseMaintenanceModeValue\(row\?\.value\)/u);
});
await test("Disposable login uses the actual existing form submit label", () => {
  const login = readFileSync(resolve(root, "src/app/admin/(auth)/login/AdminLoginForm.tsx"), "utf8");
  assert.ok(login.includes("دخول لوحة التحكم")); assert.ok(browser.includes('name: "دخول لوحة التحكم", exact: true'));
});
const closureRequired=[{key:'form:settings-pages:capability:listbox',boundary:'form',consumer:'settings-pages',axis:'listbox',scenario:'complete_applicable_capability_behavior',status:'open',evidence:null}];
const closureReceipt=()=>{
 const before={id:randomUUID(),phase:'before',correlationId:randomUUID(),ownedRunId:'owned-run',publicTableCount:116,publicTableInventorySha256:'a'.repeat(64),publicDataSha256:'b'.repeat(64),adminAuditIncluded:true},after={...before,id:randomUUID(),phase:'after'};
 const checkpoints=['baseline','selection-draft','disconnect-cancelled','disconnected','reloaded'].map((phase,index)=>({id:randomUUID(),phase,kind:'specialized-settings-state',entity:'closure-wizard',status:'pass',ownedRunId:'owned-run',actorId:7,connectionId:'owned-connection',ownedStateSha256:(index<3?'c':'d').repeat(64),actorBoundAuditCount:index<3?0:1,connectionRevoked:index>=3}));
 const maintenance={id:CORE_SPECIALIZED_CLOSURE_IDS[0],status:'pass',consumer:'maintenance-immediate-setting',blockedBeforeDelivery:1,acceptedMutationCount:0,feedbackChannel:'settings-general-maintenance',feedbackVariant:'danger',nativeWrites:0,nativeCheckpointIds:[before.id,after.id],nativeBefore:before,nativeAfter:after,automaticCoverage:[] as string[],globalClosed:false};
 const wizard={id:CORE_SPECIALIZED_CLOSURE_IDS[1],status:'pass',consumer:'settings-pages',surface:'integration-wizard',selectionTransitions:['business:selected','ad_account:selected','business:cleared','business:selected','ad_account:cleared','ad_account:selected'],readyStates:[false,false,true,false,true,false,true],cancelReturnedFocus:true,disconnectPosts:1,externalOperations:0,externalReadinessProven:false,syntheticPreconditionsUncredited:true,checkpoints,nativeCheckpointIds:checkpoints.map(r=>r.id),automaticCoverage:[] as string[],globalClosed:false};
 return {journeySelection:CORE_SPECIALIZED_CLOSURE_SELECTION,cohort:'specialized-settings',scope:'core-closure',inventoryOnly:false,driverCompleted:true,status:'pass',errors:[],wholeCohortExecuted:false,globalClosed:false,selectedJourneyIds:[...CORE_SPECIALIZED_CLOSURE_IDS],executedJourneyIds:[...CORE_SPECIALIZED_CLOSURE_IDS],evidence:[{id:'existing-auth-login',status:'pass'},maintenance,wizard],requiredCases:structuredClone(closureRequired),databaseReadback:[],readOnlyReadback:[],specializedSettings:{status:'pass',externalReadinessProven:false},maintenance,wizard};
};
await test('Closure receipt proves only local missing controls, preserving uncredited synthetic provider state',()=>{const r=assertCoreSpecializedClosureReceipt(closureReceipt(),closureRequired);assert.equal(r.wholeCohortExecuted,false);assert.deepEqual(r.automaticCoverage,[]);});
const closureMutations:Array<[string,(r:ReturnType<typeof closureReceipt>)=>void]>=[
 ['wrong selection',r=>{r.journeySelection='other';}],['whole lifecycle promotion',r=>{r.wholeCohortExecuted=true;}],['failed original',r=>{r.status='fail';}],['missing journey',r=>{r.executedJourneyIds.pop();}],['missing canonical cell',r=>{r.requiredCases=[];}],['cell promoted',r=>{r.requiredCases[0].status='pass';}],['rejected POST delivered',r=>{r.maintenance.blockedBeforeDelivery=0;}],['accepted maintenance replay',r=>{r.maintenance.acceptedMutationCount=1;}],['wrong Feedback channel',r=>{r.maintenance.feedbackChannel='other';}],['wrong Feedback variant',r=>{r.maintenance.feedbackVariant='success';}],['maintenance write',r=>{r.maintenance.nativeWrites=1;}],['native data changed',r=>{r.maintenance.nativeAfter.publicDataSha256='e'.repeat(64);}],['audit excluded',r=>{r.maintenance.nativeAfter.adminAuditIncluded=false;}],['wrong correlation',r=>{r.maintenance.nativeAfter.correlationId=randomUUID();}],['missing selection clear',r=>{r.wizard.selectionTransitions.splice(2,1);}],['false required readiness',r=>{r.wizard.readyStates[1]=true;}],['lost cancel focus',r=>{r.wizard.cancelReturnedFocus=false;}],['duplicate disconnect',r=>{r.wizard.disconnectPosts=2;}],['external operation',r=>{r.wizard.externalOperations=1;}],['external readiness promotion',r=>{r.wizard.externalReadinessProven=true;}],['credited fixture',r=>{r.wizard.syntheticPreconditionsUncredited=false;}],['missing phase',r=>{r.wizard.checkpoints.pop();}],['wrong phase order',r=>{r.wizard.checkpoints.reverse();}],['wrong checkpoint kind',r=>{r.wizard.checkpoints[0].kind='other';}],['native ID substitution',r=>{r.wizard.nativeCheckpointIds[0]=randomUUID();}],['selection wrote',r=>{r.wizard.checkpoints[1].ownedStateSha256='e'.repeat(64);}],['cancel wrote',r=>{r.wizard.checkpoints[2].ownedStateSha256='e'.repeat(64);}],['reload differs',r=>{r.wizard.checkpoints[4].ownedStateSha256='e'.repeat(64);}],['missing actor audit',r=>{r.wizard.checkpoints[3].actorBoundAuditCount=0;}],['not revoked',r=>{r.wizard.checkpoints[4].connectionRevoked=false;}],['automatic credit',r=>{r.wizard.automaticCoverage=['all'];}],['global closure',r=>{r.globalClosed=true;}],
];
for(const[name,mutate]of closureMutations)await test('Closure rejects '+name,()=>{const bad=closureReceipt();mutate(bad);assert.throws(()=>assertCoreSpecializedClosureReceipt(bad,closureRequired));});
const closureRequest={id:randomUUID(),kind:'specialized-settings-state',entity:'closure-wizard',phase:'baseline'};
await test('Closure Wizard validator accepts only fixed phases and fields',()=>{for(const phase of ['baseline','selection-draft','disconnect-cancelled','disconnected','reloaded'])validateCoreClosureWizardRequest({...closureRequest,phase});});
for(const [name,delta]of [['kind',{kind:'sql'}],['entity',{entity:'integration'}],['phase',{phase:'accepted'}],['UUID',{id:'------------------------------------'}],['caller expectation',{expected:true}],['caller connection',{connectionId:randomUUID()}],['provider',{provider:'meta_business'}]] as const)await test('Closure Wizard rejects '+name,()=>assert.throws(()=>validateCoreClosureWizardRequest({...closureRequest,...delta})));
// Execute the actual native phase guard with memory-only query ports. No database or provider is contacted.
const nativeAst=ts.createSourceFile('specialized.mts',native,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const nativeNames=['validateCoreClosureWizardRequest','readCoreClosureWizardCheckpoint','assertCoreSpecializedClosureCompleted'];
const nativeFunctions=nativeNames.map(name=>{const found=nativeAst.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.equal(found.length,1);return found[0].getText(nativeAst);});
const phaseDeclaration=nativeAst.statements.filter(n=>ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>ts.isIdentifier(d.name)&&d.name.text==='closureWizardPhases'));assert.equal(phaseDeclaration.length,1);
const auditStartDeclaration=nativeAst.statements.filter(n=>ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>ts.isIdentifier(d.name)&&d.name.text==='auditStart'));assert.equal(auditStartDeclaration.length,1);
const nativeCode=ts.transpileModule([...nativeFunctions,phaseDeclaration[0].getText(nativeAst),auditStartDeclaration[0].getText(nativeAst)].join('\n'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const nativeSnapshot=()=>({connection:[{id:'owned-connection',status:'pending_selection',version:1,revoked_at:null as string|null,updated_by_admin_user_id:7}],credentials:[{connection_id:'owned-connection',credential_strategy:'meta_user',access_secret_id:'private-reference',refresh_secret_id:null}],assets:[{id:'asset-a',selected:false},{id:'asset-b',selected:false}],readModels:[{id:'model-a'}],app:[{g:{id:'group-a'},entries:[{id:'entry-a'}],validations:[{status:'ready_to_connect'}]}],vault:{connection_present:true,app_present:true},audit:[] as Array<{id:number;actor_admin_user_id:number;action:string;entity_type:string;metadata:Record<string,unknown>}>});
function nativeHarness(code=nativeCode){
 let snapshot=nativeSnapshot();const statements:string[]=[];
 const handle={identity:{runId:'owned-run'},query:async(sql:string,params:readonly unknown[]=[])=>{statements.push(sql);assert.match(sql,/^select /u);const rows=sql.startsWith('select coalesce(max(id),0)')?[{id:Math.max(0,...snapshot.audit.map(row=>row.id))}]:sql.includes('from public.integration_connections')?snapshot.connection:sql.includes('from public.integration_credentials')?snapshot.credentials:sql.includes('from public.integration_connection_assets')?snapshot.assets:sql.includes('from public.analytics_provider_read_models')?snapshot.readModels:sql.includes('from public.integration_app_configuration_groups')?snapshot.app:sql.includes('from public.admin_audit_logs')?snapshot.audit.filter(row=>row.id>Number(params[0])):sql.includes('vault.secrets')?[snapshot.vault]:null;assert.ok(rows,'Unexpected native SQL port');return{rows:structuredClone(rows)};}};
 const state={mainId:7,connectionId:'owned-connection',secretId:'private-reference',appSecretId:'private-app-reference',groupId:'group-a',assetIds:['asset-a','asset-b'],readModelId:'model-a',phase:0,auditStart:0};
 const byHandle=new WeakMap([[handle,state]]),fullState=new WeakMap();
 const owner=new Function('exports','assert','createHash','isDeepStrictEqual','assertOwnedLocalHandle','closureWizardByHandle','stateByHandle',code+';return {read:readCoreClosureWizardCheckpoint,complete:assertCoreSpecializedClosureCompleted};')({},assert,createHash,isDeepStrictEqual,(candidate:unknown)=>assert.equal(candidate,handle),byHandle,fullState) as {read:(h:unknown,r:unknown)=>Promise<Record<string,unknown>>;complete:(h:unknown,selection?:string)=>Record<string,unknown>};
 return{handle,state,fullState,statements,read:(phase:string)=>owner.read(handle,{...closureRequest,id:randomUUID(),phase}),complete:(selection?:string)=>owner.complete(handle,selection),snapshot:()=>snapshot,set:(value:ReturnType<typeof nativeSnapshot>)=>{snapshot=structuredClone(value);},disconnect:()=>{snapshot.connection[0]={...snapshot.connection[0],status:'revoked',version:2,revoked_at:'2026-01-02T00:00:00Z'};snapshot.credentials=[];snapshot.readModels=[];snapshot.vault.connection_present=false;snapshot.audit=[{id:1,actor_admin_user_id:7,action:'integration.disconnected',entity_type:'integration_connection',metadata:{integration:'meta_business',connectionId:'owned-connection',providerRevoked:false,providerRevocationDisposition:'external_manual_action'}}];}};
}
await test('Actual native Wizard guard consumes five ordered phases and exactly one local revocation audit',async()=>{const h=nativeHarness();for(const phase of ['baseline','selection-draft','disconnect-cancelled'])await h.read(phase);h.disconnect();const revoked=await h.read('disconnected');assert.equal(revoked.connectionCredentialsPresent,false);assert.equal(revoked.secretsExported,false);assert.equal(revoked.externalReadinessProven,false);const reloaded=await h.read('reloaded');assert.equal(reloaded.ownedStateSha256,revoked.ownedStateSha256);assert.equal(h.complete().wizardCheckpoints,5);assert.equal(JSON.stringify(revoked).includes('private-reference'),false);await assert.rejects(h.read('reloaded'));});
await test('Actual native Wizard rejects phase skip and premature completion',async()=>{const h=nativeHarness();await assert.rejects(h.read('selection-draft'));assert.equal(h.statements.length,0);assert.throws(h.complete);});
for(const phase of ['selection-draft','disconnect-cancelled'])for(const key of ['credentials','assets','readModels','app','audit'] as const)await test('Actual native Wizard '+phase+' rejects changed '+key,async()=>{const h=nativeHarness();await h.read('baseline');if(phase==='disconnect-cancelled')await h.read('selection-draft');const s=h.snapshot();if(key==='audit')s.audit=[{id:1,actor_admin_user_id:7,action:'integration.disconnected',entity_type:'integration_connection',metadata:{integration:'meta_business',connectionId:'owned-connection',providerRevoked:false,providerRevocationDisposition:'external_manual_action'}}];else s[key]=[];await assert.rejects(h.read(phase));});
const disconnectMutations:Array<[string,(s:ReturnType<typeof nativeSnapshot>)=>void]>=[['connection remains active',s=>{s.connection[0].status='pending_selection';}],['wrong version',s=>{s.connection[0].version=3;}],['missing revocation',s=>{s.connection[0].revoked_at=null;}],['wrong connection actor',s=>{s.connection[0].updated_by_admin_user_id=8;}],['credential retained',s=>{s.credentials=nativeSnapshot().credentials;}],['private Vault value retained',s=>{s.vault.connection_present=true;}],['App Vault removed',s=>{s.vault.app_present=false;}],['read model retained',s=>{s.readModels=nativeSnapshot().readModels;}],['assets selected',s=>{s.assets[0].selected=true;}],['assets changed',s=>{s.assets[0].id='foreign';}],['App configuration changed',s=>{s.app[0].g.id='foreign';}],['missing audit',s=>{s.audit=[];}],['duplicate audit',s=>{s.audit.push(s.audit[0]);}],['wrong audit actor',s=>{s.audit[0].actor_admin_user_id=8;}],['wrong audit action',s=>{s.audit[0].action='integration.tested';}],['wrong audit connection',s=>{s.audit[0].metadata.connectionId='foreign';}],['false provider revocation',s=>{s.audit[0].metadata.providerRevoked=true;}],['wrong revocation disposition',s=>{s.audit[0].metadata.providerRevocationDisposition='revoked';}]];
for(const[name,mutate]of disconnectMutations)await test('Actual native Wizard rejects '+name,async()=>{const h=nativeHarness();for(const phase of ['baseline','selection-draft','disconnect-cancelled'])await h.read(phase);h.disconnect();mutate(h.snapshot());await assert.rejects(h.read('disconnected'));});
await test('Actual native completion rejects replay of the already-qualified full settings lifecycle',async()=>{const h=nativeHarness();for(const phase of ['baseline','selection-draft','disconnect-cancelled'])await h.read(phase);h.disconnect();await h.read('disconnected');await h.read('reloaded');h.fullState.set(h.handle,{});assert.throws(h.complete);});

const wizardLoginAudit=()=>({id:10,actor_admin_user_id:7,action:'auth.login.success',entity_type:'admin_user',metadata:{rememberMe:false}});
const auditBoundaryStatement='if(state.phase===0)state.auditStart=await auditStart(handle);';
assert.equal(nativeFunctions.join('\n').split(auditBoundaryStatement).length,2);
const priorNativeFunctions=nativeFunctions.map(text=>text.replace(auditBoundaryStatement,''));
assert.notDeepEqual(priorNativeFunctions,nativeFunctions);
const priorNativeCode=ts.transpileModule([...priorNativeFunctions,phaseDeclaration[0].getText(nativeAst),auditStartDeclaration[0].getText(nativeAst)].join('\n'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
await test('Actual pre-correction Wizard baseline rejects canonical login audit alone',async()=>{const h=nativeHarness(priorNativeCode);h.snapshot().audit.push(wizardLoginAudit());await assert.rejects(h.read('baseline'),error=>{assert.ok(error instanceof assert.AssertionError);assert.equal(error.actual,1);assert.equal(error.expected,0);return true;});assert.equal(h.state.phase,0);});
await test('Wizard captures its audit boundary only at first real baseline after login',async()=>{const h=nativeHarness();h.snapshot().audit.push(wizardLoginAudit());const baseline=await h.read('baseline');assert.equal(h.state.auditStart,10);assert.equal(baseline.actorBoundAuditCount,0);assert.equal(h.snapshot().audit.length,1);await h.read('selection-draft');await h.read('disconnect-cancelled');assert.equal(h.statements.filter(sql=>sql.startsWith('select coalesce(max(id),0)')).length,1);await assert.rejects(h.read('baseline'));assert.equal(h.state.auditStart,10);});
for(const action of ['auth.login.success','integration.disconnected','unrelated.unexpected'])await test('Wizard retains all post-baseline audit drift: '+action,async()=>{const h=nativeHarness();h.snapshot().audit.push(wizardLoginAudit());await h.read('baseline');h.snapshot().audit.push({...wizardLoginAudit(),id:11,action});await assert.rejects(h.read('selection-draft'));assert.equal(h.state.auditStart,10);assert.equal(h.state.phase,1);assert.equal(h.statements.filter(sql=>sql.startsWith('select coalesce(max(id),0)')).length,1);});
for(const selection of ['specialized-closure-followup','specialized-controls-followup'] as const)await test('Wizard after-login boundary preserves exact disconnect audit and five phases '+selection,async()=>{const h=nativeHarness();h.snapshot().audit.push(wizardLoginAudit());for(const phase of ['baseline','selection-draft','disconnect-cancelled'])await h.read(phase);h.disconnect();h.snapshot().audit[0].id=11;h.snapshot().audit.unshift(wizardLoginAudit());const disconnected=await h.read('disconnected');assert.equal(disconnected.actorBoundAuditCount,1);await h.read('reloaded');assert.equal(h.complete(selection).wizardCheckpoints,5);assert.equal(h.complete(selection).journeySelection,selection);assert.equal(h.state.auditStart,10);});
await test('Wizard completed native owner still refuses a foreign selector',async()=>{const h=nativeHarness();for(const phase of ['baseline','selection-draft','disconnect-cancelled'])await h.read(phase);h.disconnect();await h.read('disconnected');await h.read('reloaded');assert.throws(()=>h.complete('foreign'));});


// Failure diagnostics retain the exact native count criterion and never export raw audit values.
const auditDiagnosticPrefix='CORE_CLOSURE_WIZARD_AUDIT_COUNT ';
async function wizardAuditDiagnostic(rows:(snapshot:ReturnType<typeof nativeSnapshot>)=>void){const h=nativeHarness();for(const phase of ['baseline','selection-draft','disconnect-cancelled'])await h.read(phase);h.disconnect();rows(h.snapshot());let message='';await assert.rejects(h.read('disconnected'),error=>{assert.ok(error instanceof assert.AssertionError);assert.equal(error.expected,1);message=error.message;return message.startsWith(auditDiagnosticPrefix);});assert.equal(h.state.phase,3);return{message,projection:JSON.parse(message.slice(auditDiagnosticPrefix.length).split('\n')[0]) as {phase:string;expectedCount:number;actualCount:number;rows:Array<{action:string;entityType:string;actorMatchesOwned:boolean;metadataFields:string[]}>;truncated:boolean}};}
await test('Wizard diagnostic retains duplicate audit rejection with safe fixed identities',async()=>{const r=await wizardAuditDiagnostic(s=>s.audit.push({...s.audit[0],id:2}));assert.equal(r.projection.actualCount,2);assert.equal(r.projection.expectedCount,1);assert.equal(r.projection.phase,'disconnected');assert.deepEqual(r.projection.rows.map(row=>row.action),['integration.disconnected','integration.disconnected']);assert.ok(r.projection.rows.every(row=>row.actorMatchesOwned));assert.equal(r.message.includes('owned-connection'),false);});
await test('Wizard diagnostic recognizes canonical auth action without exporting metadata values',async()=>{const r=await wizardAuditDiagnostic(s=>s.audit.push({...wizardLoginAudit(),id:2}));assert.equal(r.projection.rows[1].action,'auth.login.success');assert.equal(r.projection.rows[1].entityType,'admin_user');assert.deepEqual(r.projection.rows[1].metadataFields,['rememberMe']);});
await test('Wizard diagnostic masks untrusted action entity actor and metadata payloads',async()=>{const secret='PRIVATE_DIAGNOSTIC_SENTINEL';const r=await wizardAuditDiagnostic(s=>s.audit.push({id:2,actor_admin_user_id:90000007,action:secret,entity_type:secret,metadata:{[secret]:secret,connectionId:secret,password:secret,token:secret}}));assert.equal(r.message.includes(secret),false);assert.equal(r.message.includes('90000007'),false);assert.deepEqual(r.projection.rows[1],{action:'other',entityType:'other',actorMatchesOwned:false,metadataFields:['connectionId']});});
await test('Wizard diagnostic is bounded to eight safe audit projections while retaining total count',async()=>{const r=await wizardAuditDiagnostic(s=>{for(let id=2;id<=12;id++)s.audit.push({...s.audit[0],id});});assert.equal(r.projection.actualCount,12);assert.equal(r.projection.rows.length,8);assert.equal(r.projection.truncated,true);assert.ok(r.message.length<2300);});
await test('Wizard diagnostic preserves missing audit rejection',async()=>{const r=await wizardAuditDiagnostic(s=>{s.audit=[];});assert.equal(r.projection.actualCount,0);assert.deepEqual(r.projection.rows,[]);assert.equal(r.projection.truncated,false);});
await test('Wizard diagnostic does not weaken the downstream exact single audit contract',async()=>{const h=nativeHarness();for(const phase of ['baseline','selection-draft','disconnect-cancelled'])await h.read(phase);h.disconnect();h.snapshot().audit[0].action='auth.login.success';await assert.rejects(h.read('disconnected'));assert.equal(h.state.phase,3);});

async function verifyRemainingSpecializedSelection() {
 const selected='specialized-controls-followup';
 const wizardReceipt=()=>{const value=closureReceipt();return{...value,journeySelection:selected,selectedJourneyIds:[CORE_SPECIALIZED_CLOSURE_IDS[1]],executedJourneyIds:[CORE_SPECIALIZED_CLOSURE_IDS[1]],evidence:[value.evidence[0],value.wizard]};};
 await test('Wizard-only selector derives exactly the original remaining ID',()=>{assert.deepEqual(coreSpecializedClosureJourneyIds(selected),[CORE_SPECIALIZED_CLOSURE_IDS[1]]);assert.deepEqual(coreSpecializedClosureJourneyIds(CORE_SPECIALIZED_CLOSURE_SELECTION),CORE_SPECIALIZED_CLOSURE_IDS);for(const value of [null,'foreign','specialized-settings-followup'])assert.throws(()=>coreSpecializedClosureJourneyIds(value));});
 await test('Wizard-only receipt retains every existing Wizard criterion and five native IDs',()=>{const value=wizardReceipt(),receipt=assertCoreSpecializedClosureReceipt(value,closureRequired);assert.equal(receipt.selection,selected);assert.deepEqual(receipt.selectedJourneyIds,[value.wizard.id]);assert.equal(value.wizard.nativeCheckpointIds.length,5);});
 const maintenanceOnly=new Set(['rejected POST delivered','accepted maintenance replay','wrong Feedback channel','wrong Feedback variant','maintenance write','native data changed','audit excluded','wrong correlation']);
 for(const [name,mutate]of closureMutations.filter(([name])=>!maintenanceOnly.has(name)))await test('Wizard-only still rejects '+name,()=>{const value=wizardReceipt();mutate(value);assert.throws(()=>assertCoreSpecializedClosureReceipt(value,closureRequired));});
 await test('Wizard-only rejects carried-forward Maintenance evidence',()=>{const value=wizardReceipt();value.evidence.splice(1,0,value.maintenance);assert.throws(()=>assertCoreSpecializedClosureReceipt(value,closureRequired));});
 const tree=ts.createSourceFile('journeys.mjs',browser,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),fn=tree.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='runCoreSpecializedClosureJourneys');assert.ok(fn);
 const dispatch=new Function('assert','coreSpecializedClosureJourneyIds','CORE_SPECIALIZED_CLOSURE_IDS',fn.getText(tree).replace(/^export /u,'')+';return runCoreSpecializedClosureJourneys;')(assert,coreSpecializedClosureJourneyIds,CORE_SPECIALIZED_CLOSURE_IDS) as (ctx:unknown)=>Promise<unknown>;
 const context=(selection:string)=>{const calls:string[]=[];return{calls,journeySelection:selection,origin:'http://127.0.0.1:3000',fixtures:{specializedSettings:{selection,uncreditedSyntheticPreconditions:true,externalReadinessProven:false,provider:'meta_business',assets:[{type:'business'},{type:'ad_account'}]}},run:async(id:string)=>{calls.push(id);}};};
 await test('Actual Wizard-only dispatcher invokes no Maintenance callback',async()=>{const value=context(selected);await dispatch(value);assert.deepEqual(value.calls,[CORE_SPECIALIZED_CLOSURE_IDS[1]]);});
 await test('Actual original dispatcher still invokes both original callbacks in order',async()=>{const value=context(CORE_SPECIALIZED_CLOSURE_SELECTION);await dispatch(value);assert.deepEqual(value.calls,CORE_SPECIALIZED_CLOSURE_IDS);});
 for(const [name,mutate]of [['foreign selection',(v:ReturnType<typeof context>)=>{v.journeySelection='foreign';}],['wrong fixture selection',(v:ReturnType<typeof context>)=>{v.fixtures.specializedSettings.selection=CORE_SPECIALIZED_CLOSURE_SELECTION;}],['missing asset',(v:ReturnType<typeof context>)=>{v.fixtures.specializedSettings.assets.pop();}],['external readiness credit',(v:ReturnType<typeof context>)=>{v.fixtures.specializedSettings.externalReadinessProven=true;}]] as const)await test('Actual Wizard-only dispatcher rejects '+name+' before any journey',async()=>{const value=context(selected);mutate(value);await assert.rejects(()=>dispatch(value));assert.deepEqual(value.calls,[]);});
 const collector=readFileSync(resolve(root,'scripts/verify-admin-adoption-readback-isolated.mts'),'utf8'),collectorTree=ts.createSourceFile('collector.mts',collector,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);let branch:ts.IfStatement|undefined;
 function find(node:ts.Node){if(ts.isIfStatement(node)&&node.expression.getText(collectorTree)==='selection==="specialized-closure-followup"||selection==="specialized-controls-followup"')branch=node;ts.forEachChild(node,find);}find(collectorTree);assert.ok(branch&&ts.isBlock(branch.thenStatement));
 const body=branch.thenStatement.statements.filter(node=>!(ts.isVariableStatement(node)&&node.declarationList.declarations.some(d=>d.initializer&&ts.isAwaitExpression(d.initializer)&&ts.isCallExpression(d.initializer.expression)&&d.initializer.expression.expression.kind===ts.SyntaxKind.ImportKeyword))).map(node=>node.getText(collectorTree)).join('\n');
 const js=ts.transpileModule('async function collect(selection,browser,native,fixtures,ownedRunId,actorId,canonicalRequiredCases,handle){let completion;'+body+';return completion;}',{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
 const calls:string[]=[];const collect=new Function('assert','assertCoreSpecializedClosureReceipt','assertCoreSpecializedClosureCompleted','assertCoreAtomicCancellationNative',js+';return collect;')(assert,assertCoreSpecializedClosureReceipt,(_handle:unknown,selection:string)=>{calls.push(selection);return{status:'pass',journeySelection:selection,wizardCheckpoints:5};},()=>calls.push('maintenance-fingerprints')) as (...args:unknown[])=>Promise<unknown>;
 const invoke=(value:ReturnType<typeof wizardReceipt>,records=structuredClone(value.wizard.checkpoints),actor=7,run='owned-run')=>collect(selected,value,{records},{specializedSettings:{connectionId:'owned-connection'}},run,actor,closureRequired,{});
 await test('Actual Wizard-only collector consumes exactly five records and actual selector',async()=>{calls.length=0;const value=wizardReceipt();await invoke(value);assert.deepEqual(calls,[selected]);});
 for(const [name,mutate]of [['extra fingerprint',(rows:ReturnType<typeof wizardReceipt>['wizard']['checkpoints'])=>{rows.push({...rows[0],id:randomUUID()});}],['missing native',(rows:ReturnType<typeof wizardReceipt>['wizard']['checkpoints'])=>{rows.pop();}],['reordered native',(rows:ReturnType<typeof wizardReceipt>['wizard']['checkpoints'])=>{rows.reverse();}]] as const)await test('Actual Wizard-only collector rejects '+name,async()=>{const value=wizardReceipt(),rows=structuredClone(value.wizard.checkpoints);mutate(rows);await assert.rejects(()=>invoke(value,rows));});
 await test('Actual Wizard-only collector rejects wrong actor and run',async()=>{const value=wizardReceipt();await assert.rejects(()=>invoke(value,structuredClone(value.wizard.checkpoints),8));await assert.rejects(()=>invoke(value,structuredClone(value.wizard.checkpoints),7,'foreign'));});
 await test('Actual original collector retains both Maintenance fingerprints',async()=>{calls.length=0;const value=closureReceipt();await collect(CORE_SPECIALIZED_CLOSURE_SELECTION,value,{records:[value.maintenance.nativeBefore,value.maintenance.nativeAfter,...value.wizard.checkpoints]},{specializedSettings:{connectionId:'owned-connection'}},'owned-run',7,closureRequired,{});assert.deepEqual(calls,['maintenance-fingerprints',CORE_SPECIALIZED_CLOSURE_SELECTION]);});
}
await verifyRemainingSpecializedSelection();


async function verifyIntegrationAuthorizationNavigation(){
 const source=readFileSync(resolve(root,'src/components/admin/integrations/IntegrationConnectionWizard.tsx'),'utf8');
 function assertExplicitAuthorizationNavigation(text:string){const ast=ts.createSourceFile('wizard.tsx',text,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),links:ts.JsxElement[]=[];function visit(node:ts.Node){if(ts.isJsxElement(node)&&node.openingElement.attributes.properties.some(a=>ts.isJsxAttribute(a)&&a.name.getText(ast)==='href'&&a.initializer?.getText(ast).includes('/api/admin/integrations/')))links.push(node);ts.forEachChild(node,visit);}visit(ast);assert.equal(links.length,1);const link=links[0],attrs=link.openingElement.attributes.properties;assert.equal(link.openingElement.tagName.getText(ast),'a');assert.equal(link.closingElement.tagName.getText(ast),'a');assert.deepEqual(attrs.map(a=>ts.isJsxAttribute(a)?a.name.getText(ast):'spread').sort(),['className','href']);const href=attrs.find(a=>ts.isJsxAttribute(a)&&a.name.getText(ast)==='href') as ts.JsxAttribute;assert.ok(href.initializer&&ts.isJsxExpression(href.initializer)&&href.initializer.expression&&ts.isTemplateExpression(href.initializer.expression));const target=href.initializer.expression;assert.equal(target.head.text,'/api/admin/integrations/');assert.equal(target.templateSpans.length,1);assert.equal(target.templateSpans[0].expression.getText(ast),'item.key');assert.equal(target.templateSpans[0].literal.text,'/authorize');assert.ok(link.children.some(n=>ts.isJsxExpression(n)&&n.expression&&ts.isConditionalExpression(n.expression)&&n.expression.condition.getText(ast)==='item.connectionId'));return{start:link.getStart(ast),end:link.end,text:link.getText(ast)};}
 await test('OAuth authorization uses only explicit native navigation preserving endpoint and labels',()=>{assertExplicitAuthorizationNavigation(source);});
 const target=assertExplicitAuthorizationNavigation(source);const mutant=(text:string)=>source.slice(0,target.start)+text+source.slice(target.end);
 for(const[name,change]of [['automatic Next Link',(text:string)=>text.replace(/^<a/u,'<Link').replace(/<\/a>$/u,'</Link>')],['Next Link with prefetch false still intercepts API navigation',(text:string)=>text.replace(/^<a/u,'<Link prefetch={false}').replace(/<\/a>$/u,'</Link>')],['programmatic handler',(text:string)=>text.replace(/^<a/u,'<a onMouseEnter={()=>undefined}')],['unreviewed spread',(text:string)=>text.replace(/^<a/u,'<a {...externalProps}')],['wrong endpoint',(text:string)=>text.replace('/authorize','/action')],['wrong provider identity',(text:string)=>text.replace('item.key','item.connectionId')]] as const)await test('Authorization navigation rejects '+name,()=>assert.throws(()=>assertExplicitAuthorizationNavigation(mutant(change(target.text)))));
}
await verifyIntegrationAuthorizationNavigation();

console.log(JSON.stringify({ status: "pass", boundary: "Offline plan/negative/privacy controls only; native and Browser behavior remain pending.", cases: cases.length, evidence: cases }, null, 2));
